cozy/cozy-drive

.gitignore, README.md, config/webpack.base.config.js, config/webpack.hash.config.js, mobile/README.md, mobile/config.xml, mobile/src/main.jsx, mobile/test/test.spec.js, package.json, src/components/AppRoute.jsx, src/main.jsx
=> Add cozy mobile build :tada:

src/components/FilenameInput.jsx
KeyboardEvent.key is not supported on safari: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key
=> Fix enter key on safari :bug:

src/components/File.jsx
Filesize use base 2 by default. Added option to use base 10.
=> [fix] Use base 10 for file size computing

mobile/src/actions/index.js, mobile/src/containers/OnBoarding.jsx, mobile/src/main.jsx, mobile/src/reducers/mobile.js, mobile/test/__snapshots__/onboarding.spec.js.snap, package.json, yarn.lock
This PR aims to let the user register his device and share authorization.  
A form is shown and on submit it validates the user's passphrase.
A `Authorize application` screen is displayed, use must accept.
Then user is redirected to the app and can browse cozy files.
**TODO**
=> Register your device within an in-app browser

src/actions/index.js, src/containers/Breadcrumb.jsx
In the current breadcrumb, when you click on the root Files, the path doesn't change to the correct path means '/files'.
This PR fixes it.
=> Fix breadcrump router behaviour

mobile/config.xml
We can choose 'io.cozy.mobile.files' or 'io.cozy.files.mobiles'.
But I think 'io.cozy.mobile.sync' is not correct.
=> Change cordova app ID

mobile/src/actions/index.js, package.json, src/components/Nav.jsx
jest do not use variables defined in webpack
so we have to add them in jest configuration
thanks @m4dz for pointing my little noise to this http://facebook.github.io/jest/docs/configuration.html#globals-object
=> fix tests with globals __ALLOW_HTTP__ and __TARGET__

mobile/src/actions/index.js
I use to keep the HTTP error received by cozy-client-js
but for user it may be clearer to have only one error:
"The address doesn't seem to match a Cozy."
=> Change error displayed when url is wrong

src/styles/filenameinput.styl
This input needs to be smaller than the usual ones defined in cozy-ui.
=> [fix] added specific styles for the input

src/components/File.jsx, src/components/FilenameInput.jsx, src/reducers/ui.js
When a user aborts a folder creation with escape, no notification should be shown.
=> [fix] FIL-16 : Prevent notifications when the aborting folder creation on purpose

.babelrc, mobile/src/reducers/index.js, package.json, yarn.lock
We added the spread operator to import and combine the browser's reducers inside our mobile reducer.
=> fix: spread op for reducers and beyond

src/styles/nav.styl
Wrong indentations caused the mobile nav to break on icons position
=> [Fix] Mobile nav's icons

src/actions/index.js, src/reducers/folder.js, src/reducers/index.js
The way files were seemed to work but was actually flawed.
A trashed file was kept in the `files` collection in the state, but with their `dir_id` set to the trash folder. Then, all files who's `dir_id` were the trash folder were hidden via another reducer.
This leads to the `files` collection in the state to sometimes contain files that are *not* inside the currently displayed folder (this caused at least one bug). It also makes it impossible to display files inside the trash folder.
The new approach is a lot more straightforward: a trashed file is removed from the `files` state, period.
=> [fix] Better file trashing

mobile/test/actions/settings.spec.js
I don't know why a `return` was added here, unnecessary.
=> fix: tests doesn't return anything

mobile/src/actions/settings.js, mobile/src/main.jsx, mobile/src/reducers/settings.js, mobile/test/actions/settings.spec.js, mobile/test/reducers/settings.spec.js
It will be useful to get `clientID`, `registrationAccesToken` or `accessToken` to use `cozy.auth.getClient()` or `cozy.auth.unregisterClient()`. And so on...
=> SET_CLIENT to store cozy-client-js's client object in state

config/webpack.target.mobile.js, mobile/src/actions/settings.js, mobile/src/main.jsx, package.json, yarn.lock
This new feature gives access to sentry online logger.
JavaScript uses Raven to connect to sentry.cozycloud.cc.
Sentry's Dashboard looks like that:
In another development, we will add an option (activable via settings) to trigger or not the error's capture.
As Sentry takes data from customer (private data such as IP address, and less sensible data), we have to check twice if the user is ok to send data, and what data the application sends. And we need to make a declaration for the purpose of our collect.
=> feature: add sentry to watch errors

config/webpack.config.base.js, config/webpack.config.dev.js, config/webpack.config.prod.js, config/webpack.target.browser.js, config/webpack.target.mobile.js, package.json, src/index.ejs, src/main.jsx, webpack.config.js, yarn.lock
:warning: This PR relies on https://github.com/cozy/cozy-bar/pull/12 and https://github.com/cozy/cozy-client-js/pull/74, merge them before pliz
This PR allow devs to use local version of stack assets rather than the ones delivered by the stack in development condition.
Stack assets like `cozy-client-js` and `cozy-bar` are injected into the DOM as legacy-scripts by the stack when it serves the app to the browser. Sometimes, we need to overrides them with local versions when a developper needs to works on them and tests them in a real app environment.
When lanching the app in _watch mode_ (e.g. `yarn run watch`), then local versions (downloaded from the npm registry into the `node_modules` directory) are used by the app instead of the stack's ones (they are implicitely detected and bundled …
=> Simplify dev process on stack assets

config/webpack.config.base.js, package.json, postcss.config.js, yarn.lock
Add missing dep for `imports-loader`, needed for stack assets dev mode (https://github.com/m4dz/cozy-files-v3/blob/update/deps/config/webpack.config.dev.js#L11) and update stack assets deps.
=> Update missing deps

mobile/src/actions/settings.js, mobile/src/lib/crash-reporter.js, mobile/src/main.jsx, package.json, yarn.lock
It appears to be a good tips to add the current state if a dispatch throws an exception.
Cf. https://blog.sentry.io/2016/08/24/redux-middleware-error-logging.html
So these commits introduce two concepts:
- an automatic redux dispatch exception logger
- a helper `logException` to let developer add exception in Sentry
=> update sentry integration

package.json, src/lib/withGestures.jsx, yarn.lock
Post-mortem, for anyone curious:
When viewing the file action menu, you're supposed to be able to tap the background or do a swipe down gesture to dismiss the menu. This worked fine during our tests, but not in production, not on the iphone simulator, etc.
One of our dependencies was injecting a polyfill for PointerEvents. This caused `hammer` to rely on them to detect gestures. However, the polyfill in question requires that elements for which you want PointerEvents be marked with a special attribute, which we didn't use, and so no PointerEvents were fired, and Hammer wasn't doing anything.
We didn't see the problem in dev because we were either using browsers that natively support PointerEvents, or because the polyfill was being blocked for CSP reasons.
Anyway, tested in Firefox, Chrome …
=> Fix gesture problems

mobile/config.xml, mobile/src/actions/mediaBackup.js, mobile/src/lib/media.js
To valide: On settings clic on 'Launch Backup' you can see an Android popup with authorization.
=> Upgrade cordova plugin image & fix permission :bug: on Android

mobile/src/actions/authorization.js, mobile/src/actions/settings.js, mobile/src/containers/RevokableWrapper.jsx, mobile/src/lib/cozy-helper.js, mobile/src/main.jsx, mobile/src/reducers/authorization.js, mobile/src/reducers/index.js, mobile/test/reducers/authorization.spec.js, package.json, src/locales/en.json, yarn.lock
To unregister a device, you need to retrieve the `device id` then `DELETE` this device:
```
OAUTH_TOKEN=$(./cozy-stack instances token-oauth cozy.local:8080 \
$(./cozy-stack instances client-oauth cozy.local:8080 \
http://localhost curl curl) 'io.cozy.oauth.clients')
http http://cozy.local:8080/settings/clients \
--auth user:$OAUTH_TOKEN
http DELETE http://cozy.local:8080/settings/clients/17d49c2fef1f1b951635881e3bc0d1b12 \
--auth user:$OAUTH_TOKEN
```
Here is the scenario:
1. open the android app
1. go through the onboarding
1. your device is registered
1. make above commands to unregister the client
1. restart the android app
1. you should see the onboarding screen
I don't know yet how to manage revocation during app usage.
*hints:*
- `cozy-client-js` throws an error with a specific …
=> feat: manage device revocation

src/containers/FileActionMenu.jsx
After a tap, a click event is *also* fired not long after -- the infamous GhostClick. See the last tip here: http://hammerjs.github.io/tips/
We could prevent the click as wildly suggested elsewhere, but that requires a bit of code and doesn't integrate very well with our current set-up.
Instead, I'm slighty delaying the hiding of the backdrop, so the ghost click happens on the backdrop and has no side effects.
=> [fix] Prevent ghostclicks after taps

mobile/src/actions/mediaBackup.js, mobile/src/components/Settings.jsx, mobile/src/containers/Settings.jsx, mobile/src/lib/media.js, src/locales/en.json
With this PR, media are not backed up in the root folder, but
in the Media Backup Folder, customizable in `en.json` file with `mobile.settings.media_backup.media_folder` key.
Some changes:
-    feat: The Media Backup Folder is i18nizable
-    refactor: move loading behavior inside the container
-    fix: Promise must be always returned
-    fix: Check Cordova context before using a plugin
-    feat: backup Media in /Camera folder
-    refactor: dirID as a variable
=> Feat: The Media Backup Folder is customizable

mobile/src/actions/settings.js, mobile/src/lib/cozy-helper.js, mobile/src/main.jsx
When a replication is complete AND when there is some new document(s), then
we refresh the current folder's file list by dispatching an action creator.
And on startup, we don't get localfile first as in that case we have to need the end of the replication to display files.
Instead we load remote files and start a repeated replication. When the first replication is going to start, it creates a local database.
It is related to https://github.com/cozy/cozy-client-js/pull/109
I think it's better, what do **you** think?
=> feat: enhance offline behavior

mobile/src/containers/RevokableWrapper.jsx
In https://github.com/cozy/cozy-ui/pull/78 we had a new props to control the cross in the modal.
This PR aims to use it to not display cross in our revocation modal.
=> feat: revocation Modal has no cross

mobile/config.xml, mobile/src/actions/mediaBackup.js, mobile/src/actions/network.js, mobile/src/actions/settings.js, mobile/src/components/Settings.jsx, mobile/src/containers/Settings.jsx, mobile/src/lib/network.js, mobile/src/main.jsx, mobile/src/reducers/index.js, mobile/src/reducers/mediaBackup.js, mobile/src/reducers/network.js, mobile/src/reducers/settings.js, mobile/test/actions/settings.spec.js, mobile/test/reducers/settings.spec.js
We need to:
That is more or less what this PR aims to do.
=> feat: add option to allow backup media only on wifi

src/containers/FileActionMenu.jsx, src/lib/withGestures.jsx, src/styles/actionmenu.styl
The whole FileActionMenu can now be swipped, and the menu follows the gesture.
=> Swipe to dismiss the FAM

src/containers/FileActionMenu.jsx
Handles the case where the gesture ends when the menu is already past the bottom of the screen, and no `transitionend` event is fired.
=> [fix] Dismiss menu when already down

mobile/src/components/Settings.jsx, mobile/src/containers/RevokableWrapper.jsx, src/containers/DeleteConfirmation.jsx
As `cancel...` and `validate...` are deprecated.
@y-lohse or @CPatchane could you validate the code change as it impacts `src/containers/DeleteConfirmation.jsx`?
Only one approval is needed 😉
=> fix: update cozy-ui's modal usage

mobile/src/actions/mediaBackup.js, mobile/src/components/UploadProgression.jsx, mobile/src/containers/UploadProgression.jsx, mobile/src/reducers/mediaBackup.js, mobile/src/styles/uploadprogression.styl, mobile/test/__snapshots__/onboarding.spec.js.snap, mobile/test/actions/mediaBackup.spec.js, mobile/test/reducers/mediaBackup.spec.js, src/containers/Folder.jsx, src/locales/en.json
We could use `Alerter` from [cozy-ui](https://github.com/cozy/cozy-ui) but it seems not correct for this kind of progression message (see @goldoraf and @gregorylegarec for more information).
So the `UploadProgression` component is the very same UI than an Alerter, but it did not have the same behavior, it is very simpler: if a message is display, it is shown, otherwise it is not.
Hope it fits the needs.
=> feat: add a progression view for media backup

mobile/src/components/Settings.jsx, mobile/src/containers/DebugTools.jsx
This PR is a proposal to add a debug tool in settings page.
It is displayed only in `dev mode`  activable by webpack configuration manipulation.
=> feat: add debug tool in settings page :microscope:

mobile/src/actions/mediaBackup.js, mobile/test/components/OnBoarding.spec.js, mobile/test/onboarding.spec.js, src/actions/index.js, src/components/File.jsx, src/lib/confirm.js, src/reducers/ui.js, src/reducers/view.js
A tiny refactoring pass to let `let` be `const` when variable are not redefined.
All changes do not have test coverage... We need to cover code as soon as possible.
=> refactor: const is better :hammer:

mobile/src/actions/settings.js
It may be a smell to let the `reporter` depends on the *redux state*.
See https://github.com/cozy/cozy-files-v3/blob/master/mobile/src/lib/reporter.js#L10
So in that particular case, the message was sent to sentry before the global state was set. So the message was not sent. Nice 🎉 !
=> fix: shouldSendCallback uses the state :interrobang:

package.json
It's clearer to use parenthesis if you need to launch a command in
a subdirectory.
Replace:
```bash
cd mobile ; cordova run android ; cd ..
```
By:
```bash
(cd mobile && cordova run android)
```
=> chore: parenthesis to set bash context :crocodile:

mobile/src/actions/settings.js, mobile/src/actions/timestamp.js, mobile/src/containers/onboarding/Analytics.jsx, mobile/src/main.jsx, mobile/src/reducers/timestamp.js
- logInfo is launched when user change the backup image settings.
Now we know if he set the value in the onboarding or later in
the settings page.
- pingOnceADay was not triggered on fist launch as we initialized
the timestamp state with the current date before checking if
the timestamp is today or not.
=> Kill two :bird: with one stone

mobile/src/actions/index.js, mobile/src/actions/settings.js, mobile/src/actions/unlink.js, mobile/src/containers/DebugTools.jsx, mobile/src/containers/Settings.jsx, mobile/src/lib/cozy-helper.js, mobile/src/lib/replication.js, mobile/src/lib/store.js, mobile/src/main.jsx, mobile/src/reducers/authorization.js, mobile/src/reducers/mediaBackup.js, mobile/src/reducers/settings.js, mobile/src/reducers/ui.js, mobile/test/actions/settings.spec.js, mobile/test/actions/unlink.spec.js, mobile/test/reducers/mediaBackup.spec.js, mobile/test/reducers/settings.spec.js, mobile/test/reducers/ui.spec.js, src/actions/index.js, src/actions/settings.js, src/reducers/index.js, src/reducers/settings.js
Now after an user is registered, he can browse directly in its folders
This feature adds 2 flags:
- offline : on browser is false, on mobile is true after client is defined
- firstReplication : after client is registered, a replication is launched. At the end of this replication `firstReplication` is set to true. Now we can display offline folder.
=> feat: Add online view after subscribe 🏃

src/components/FolderView.jsx, src/ducks/trash/Container.jsx, src/ducks/trash/Toolbar.jsx, src/ducks/trash/components/DestroyConfirm.jsx, src/locales/en.json
=> Better confirmation modal when destroying a selection of files

src/containers/Breadcrumb.jsx
The breadcrumb uses a state called `deployed` to display the hierarchical menu and to add a backdrop as an overlay.
This state is toggled when actioning the menu items.
First, I refactored the duplicate code.
Second, I added a `toggleDeploy()` call in the asynchronous call.
*Note: I don't like the animation flow when clicking on the back button. But it is not related to the FIL-24 bug statement.*
=> fix: incorrect flow in breadcrumb state management

src/containers/Breadcrumb.jsx
We have two behaviors within the breadcrumb:
1. on breadcrumb deploy: animate the dropdown menu
1. on back button: no animation
*Animation includes a deployed menu, an overlay and a collapsed menu.*
=> feat: breadcrumb animation :moneybag:

mobile/src/components/MobileAppRoute.jsx, mobile/src/lib/init.js, mobile/src/main.jsx
[react-router](https://github.com/ReactTraining/react-router/blob/v3/docs/API.md#onenternextstate-replace-callback) let us register a function called each time a route is going to enter.
That is the way we drive user to the onboarding or to the application main page.
This is not a way to *initialize* the application.
So I moved the initialization into a function called once the JS file is loaded and evaluated.
And I renamed the `requireSetup` function with a more explicit name.
I would like to initialized the [cozy-bar](https://github.com/cozy/cozy-bar) at two places:
- when the application is opened in classical condition (user already onboarded)
- when the onboarding is finished
Because we don't want to initialized the cozy-bar each time the *normal route* is called (`#/files`).
*Note: …
=> fix: handle setup :fries:

mobile/src/lib/cozy-helper.js
Even if it looked a good idea to remove https://github.com/cozy/cozy-drive/pull/157/files#diff-f96699990a60f265f8d3b7bd25d3e9a6L26 earlier.
It is mandatory while https://github.com/cozy/cozy-client-js/blob/master/src/index.js#L177 is not refactored.
Without that, the mobile application does not start when the phone is on plane mode.
=> fix: unable to start on plane mode

manifest.webapp, mobile/src/lib/cozy-helper.js, src/index.ejs, src/main.jsx
Adding Editor's name to the manifest so the stack can use it and make sure this data is shared so the cozy-bar can use it.
tl;dr: It displays the "Cozy" before the "Drive" in the Cozy-bar
Related PR: https://github.com/cozy/cozy-bar/pull/37
=> feat: Add Support for editor's name

package.json, src/components/FolderView.jsx, src/components/SelectionBar.jsx, src/locales/en.json, src/styles/selectionbar.styl, yarn.lock
As asked in [this card](https://trello.com/c/oppcRVha/217-3-fil-21-cosmetique-selection-bar), here are some cosmetic changes:
See the bad screenshot below
=> fix: Selection Bar UI

src/components/File.jsx
This feature add 3 gestures on file list:
It's disable on [label](https://github.com/cozy/cozy-drive/pull/250/files#diff-7e3f754a65a763e426e5b54107d0702aR94) checkbox and [button](https://github.com/cozy/cozy-drive/pull/250/files#diff-7e3f754a65a763e426e5b54107d0702aR113) action.
=> feat: Add press action on file list :point_up_2:

src/locales/en.json
As asked in https://trello.com/c/VPVNgirg/287-fil-dans-l-app-mobile-changer-le-placeholder-pour-montrer-une-adresse-web-et-pas-email
=> fix: change placeholder's wording

src/actions/index.js
This bug was [introduced here](https://github.com/cozy/cozy-drive/commit/f03593ff3c6f561f00ddbac6bc4df058964254c4#diff-4e3037116dbc2bc69a473b7ace3d02abL229), it was just a logic inversion.
=> fix: Download directories and single files

mobile/src/containers/RevokableWrapper.jsx, src/actions/index.js, src/main.jsx, src/middlewares/piwik.js
I've created a new redux middleware that can be used as a hook to track certain actions in piwik. The upside is that we'll be able to track most actions quite easily; the downside is that sometimes (as is the case here), we're going to need new actions / modify existing one solely for the middleware, not for the store.
Tell me what you think about this approach, and once we've found a good one I'll deploy the same thing to photos.
=> feat: Add piwik events

mobile/src/actions/unlink.js, mobile/src/reducers/index.js, mobile/src/reducers/mediaBackup.js, mobile/src/reducers/settings.js, mobile/src/reducers/ui.js, mobile/test/actions/unlink.spec.js, src/actions/settings.js, src/reducers/settings.js
This feature reset all state with a rootReducer to unlink a user.
I find this solution [here](https://stackoverflow.com/questions/35622588/how-to-reset-the-state-of-a-redux-store/35641992#35641992) by Dan Abramov.
=> refactor: Reset all state with a rootReducer :hammer:

src/index.ejs, src/lib/tracker.js, src/main.jsx, src/middlewares/EventTracker.js
This is a proposal for a module dedicated to Piwik, which could be externalized to cozy-ui or a separate library.
The module exposes 2 things:
- access to a unique Piwik instance object; this is important because otherwise every instance has to be configured with the user id, the app name, etc.
- a redux middleware (see comments in code for more on that)
The module's function pull default values from our usual setup (global variables and the root element's dataset), so they need little configuration. However all these defaults can be overriden, so the module should work in any setup and all parts are optional. The only dependency is [piwik-react-router](https://github.com/joernroeder/piwik-react-router) and, of course, Piwik.
=> refactor: Piwik wrapper

mobile/src/actions/settings.js, mobile/src/lib/cozy-helper.js, mobile/src/lib/store.js, mobile/src/lib/tracker.js, mobile/src/main.jsx, src/lib/tracker.js
As discussed, I've updated the tracker lib so that it can be used to inject the piwik script instead of relying on it to be already there.
On the mobile side of things, i've added a file in lib that can active and deactivate the tracking, and I've added the middlewares. the activate function is called once on start up, and when the setting is changed.
=> feat: enable piwik tracking on mobile

src/styles/buttonclient.styl
Download app button for mobile was misplaced on tablet viewport (between 480px and 1024px).
It surely seems like an odd job. 
I could have done it prettier (but with much more lines) but it would have been too much complex fix for just an ad that is never gonna stay for long anyway. I think this is the most pragmatic way.
=> fix: Download app button position on tablet view

src/components/IntentHandler.jsx
1. Rename class to have the same name as the file
2. Only sends the `message` part of the error through the inter-window channel
=> Keep class name coherent with file name

src/components/FolderView.jsx
**bug**
On the first file selection, the view scrolled up to the top.
It was due to the `<SelectionBar />` addition in the DOM.
**fix**
We always have the `<SelectionBar />` in the DOM, but when no files are selected, the wrapping `<div />` HTMLElement is `display: none`. As soone as the first file is selected, we don't mutate the DOM but displaying the wrapping `<div />` HTMLElement.
=> fix: select the first file scrolled up the page

src/services.jsx
The intent service did not work anymore since it does not have i18n. This breaks espacially the cozy-edf application
=> fix: add i18n to the intent service

src/styles/actionmenu.styl
The mime type classe names I altered the other day were also used in a different module so that one broke. As far as I can tell these are the only two places they were used.
=> fix: file action menu icon

package.json, src/actions/index.js, yarn.lock
see https://github.com/cozy/cozy-client-js/commit/3e8b4c63590468ffc35e6f81d22e685a5b81aed7\#diff-ecdbeb0b77447177e8165fbaf62b5a09L274
and https://trello.com/c/trQ3Mi16/416-forum-4753-fil-le-t%C3%A9l%C3%A9chargement-dune-s%C3%A9lection-de-fichier-ne-fonctionne-plus
=> fix: cozy-client-js changes but not projects

src/actions/index.js, src/components/File.jsx, src/components/Preview.jsx, src/styles/table.styl
So, I don't replace the mime type icon per say, I just add a new div with the preview image as background on top of that type icon.
Easier way to deal with it than replacing and in that case, when an error occurs, no preview is displayed and the icon type remains visible. Same thing for long loading time.
Although, it would be nice to have even smaller preview image from the stack. Even the small image is still way too big for what we're showing which means way too much bits are loaded, unused and unnecessary bits.
=> feat: add jpeg preview on filelist

src/components/ShareButton.jsx
`<ShareButton className='coz-desktop' />` make sense as `className` props in React/Preact paradigm is a `String`.
But destructuring a `String` with the spread operator is not very useful inside the `<ShareButton />` component.
So I remove the destructuring operation, and now, if you want to add more than one css class for the component, you need to set the value to be a `String` or use something like [classnames](https://github.com/JedWatson/classnames) to build a `String`.
Sorry for that.
=> fix: destructuring is not ok for strings

src/actions/index.js
This fixes the issues with the selection right after an upload, because without the function call `_id` wasn't converted to `id`.
=> fix: extract file attributes after upload

src/ducks/files/Container.jsx
Temporarily disabled folder renaming to prevent the bug on cozy-desktop. 
I'm merging this PR right away, just looping everybody in FYI.
=> fix: disable folder renaming

src/ducks/files/files.js
Since the constant wasn't exported, the deletion from albums wasn't happening.
=> fix: export albums doctype

src/components/ButtonClient.jsx, src/components/LightFolderView.jsx, src/components/PublicLayout.jsx, src/containers/Breadcrumb.jsx, src/reducers/view.js, src/styles/table.styl
This PR aims to fix two things for public view:
1. [sidebar and layout](#)
1. [breadcrumb](#)
I remove the sidebar because it was added only to remove a glitch in the layout.
The glitch was coming from a CSS rule `max-width 'calc(100vw - %s)' % em(220px)` (stylus syntax).
According to @GoOz2 this rule stand for a safari bug.
I did test my commit in safari with browsertstack 10.1 on Sierra, below a screenshot:
A long discourse or an illustration? Or both! (click to enlarge)
Hope it is good for you
=> fix: public view

mobile/src/containers/onboarding/SelectServer.jsx, package.json, src/locales/en.json, yarn.lock
AFAIK, it was either `dangerouslySetInnerHTML`, or installing `react-markdown` which seemed like a lot of hassle just for a link. All error messages are generated from the translations so this should be safe.
=> fix: add link in error message

src/components/LightFolderView.jsx, src/styles/toolbar.styl
A previous commit (see PR https://github.com/cozy/cozy-drive/pull/340) was hiding the menu more in desktop view (large screen).
Here is the fix.
=> fix: toolbar display

README.md, src/ducks/sharing/README.md
Adding some doc about sharing in a development workflow.
We may add some documentation to create two local instances to test master-master share.
=> doc: help developers with sharing email

src/targets/mobile/containers/RatingModal.jsx, src/targets/mobile/lib/constants.js, src/targets/mobile/lib/cozy-helper.js, src/targets/mobile/lib/tracker.js
- the rating modal was importing constants from `cozy-helper`
- this caused `cozy-helper` and it's dependencies to get included in the build files, even the browser-build
- one of these dependencies is the sentry `reporter.js`, which was missing a global variable at runtime and that's how I noticed the problem
So I'm proposing to move the constants to a separate file where they can be imported from without side-effects.
=> fix: removed cozy-helper import

src/targets/public/main.jsx
Looks like Safari doesn't like the `_SELF` parameter for `window.open`.
(Tagging in @enguerran just for information)
=> fix: window.open bug in safari

src/drive/styles/actionmenu.styl
I revert a previous commit saying that it removes *unused css* rules that were used...
see https://github.com/cozy/cozy-drive/commit/31d3440fc7406bcefd22cd51ff82f53bf39c684f
=> I don't know anything like Jon Snow

src/photos/components/Viewer.jsx, src/photos/components/ViewerToolbar.jsx, src/photos/styles/viewer.styl, src/photos/styles/viewerToolbar.styl
Toolbar and next/prev buttons also appears on click just like on mobile.
Also renamed some vars to be more clear.
See video here: 
~~https://www.dropbox.com/s/2xlt7fbv7j14c7u/viewer2.0.mp4?dl=0~~
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿https://www.dropbox.com/s/pwj7wbolgsyey8k/viewer2.1.mp4?dl=0
=> feat: Viewer on desktop is now fullscreen

src/sharing/README.md
After creating the document at `src/ducks/sharing/README.md`, here what happened:
```
git log --stat -- src/ducks/sharing/README.md
```
So to continue looking for file history, let use the new path:
```
git log -1 --stat -- src/drive/ducks/sharing/README.md
```
And we finally find that 9e7a717e8fac00c6bb63ca84c04eb1800e49985d deleted the file.
See it on github https://github.com/cozy/cozy-drive/commit/9e7a717e8fac00c6bb63ca84c04eb1800e49985d#diff-abe2ff96c3eb1bf133e479cf58dd38ee
=> chore: readd lost documentation

src/drive/actions/index.js, src/drive/components/AppRoute.jsx, src/drive/components/FolderView.jsx, src/drive/containers/Breadcrumb.jsx, src/drive/containers/FileExplorer.jsx, src/drive/containers/Nav.jsx, src/drive/ducks/files/Container.jsx, src/drive/ducks/files/Toolbar.jsx, src/drive/ducks/files/index.jsx, src/drive/reducers/view.js
The [main Container for files](https://github.com/cozy/cozy-drive/blob/master/src/drive/ducks/files/Container.jsx) is almost exactly what we needed for the recent files view, minus a few options. I made a small change [here](https://github.com/cozy/cozy-drive/pull/385/files#diff-791ebcf61511f68da1d94d3b8f95ff19R46) that allows it to be configured at [init time](https://github.com/cozy/cozy-drive/pull/385/files#diff-aaf0824cb9f25c2ee0edbac1cc65054bR1).
I made a few changes to the breadcrumb and the toolbar, and I [created a new function](https://github.com/cozy/cozy-drive/pull/385/files#diff-a171b9a4b7e114f23187cf310589afd9R103) to fetch the most recent files and hooked it into redux.
Note: as it is, the code generates a harmless error because of …
=> feat: recent files view

src/photos/components/Viewer.jsx, src/photos/styles/viewer.styl
I removed the wrapping div `pho-viewer-content` as it was not really useful and tweaked a little the CSS so it won't deform images in Chrome anymore.
I don't think it will interfere with the zoom feature but still, if you could take a look @y-lohse that would be appreciated.
=> fix: image ratio on chrome in Viewer

src/sharing/components/ShareAutocomplete.jsx, src/sharing/components/autosuggest.styl
Today I wanted to share a photo album on my phone, and it was annoying to type the email address without the dedicated keyboard.
=> fix: use email input type

src/photos/components/Viewer.jsx
iOS Safari was catching tap events that was meant to the toolbar, so I transfered all the gesture logic to the Photo wrapper instead of the Viewer wrapper.
=> fix: Viewer on iOS couldn't be closed

src/drive/ducks/trash/Toolbar.jsx
Just added a class to hide this button on mobile. Dunno why it wasn't here before.
=> fix: empty trash button no longer visible on mobile

package.json, src/drive/mobile/actions/mediaBackup.js, src/drive/mobile/lib/replication.js, yarn.lock
I did some refactoring in 1b04b6bcacd77923c410a4b5b82cbdc70a86929a first — stopping the success / error callbacks to go all the way down the function chain. They probably shouldn't even be  in the replication lib at all, but that will be for another day.
The 2 other commits are just calling the new route.
=> Update the client's last sync date on the server

targets/drive/mobile/config.xml
Updates the plugin to version 1.0.3, which re-allows HTTP requests and fixes a possible crash when uploads error.
=> chore: update list library items plugin

targets/drive/mobile/config.xml
The latest versions of iOS require a new icon to be generated, the latest ios engine version takes care of that.
=> chore: update ios to latest engine

src/drive/components/AppRoute.jsx, src/drive/containers/Nav.jsx, src/drive/ducks/files/FileOpener.js, src/drive/ducks/files/index.jsx, src/drive/ducks/files/styles.styl, src/drive/ducks/services/components/SuggestionProvider.jsx, src/drive/locales/en.json, src/drive/reducers/view.js
Adds a new route `/show/:fileId` that shows a modal with the given file in an iframe. It is useful for the bank mobile application since the mobile intents do not work yet.
* When the user closes the modal, the displayed folder is the parent folder of the file.
* Some mobiles do not display the PDF in an iframe and instead try to download the file. Since we cannot know whether the iframe is displaying or downloading the file, a fallback message is shown 2s after the modal is shown "You can close this if you have downloaded the file".
On a mobile whose modal is not displaying the file : 
On a mobile displaying the file
This PR is a first step, we should have later on a proper viewer (maybe PDF.js) to display PDFs on all mobiles.
=> feat: new route to display files

src/drive/components/AppRoute.jsx
I think we missed something while reviewing #423.
Putting the [`file/fileid` route](https://github.com/cozy/cozy-drive/pull/423/files#diff-c1bd35ae3774ffe22abae27a6577346eR21) inside the [`FileExplorer`](https://github.com/cozy/cozy-drive/pull/423/files#diff-c1bd35ae3774ffe22abae27a6577346eR16), it [triggers a redux dispatch](https://github.com/cozy/cozy-drive/blob/master/src/drive/containers/FileExplorer.jsx#L53) with faulty parameters — when it shouldn't dispatch at all.
I also think the line `<Redirect from="/" to="files" />` is obsolete, there's no view named `files`. `<Redirect from="*" to="folder" />` is a newer version of that, but we can merge them together, I believe?
=> fix: app routes

src/drive/components/AppRoute.jsx
For applications that use Drive ability to open folder (Collect when you want to open the drive where your bills are stored), it is necessary to have backward compatibility.
=> fix: add redirect to conserve backward compatibility

src/drive/mobile/actions/mediaBackup.js, targets/drive/mobile/config.xml
There's a problem in our upload code for android and I can't find a proper fix for it, so instead I'm fixing it here.
Essentially, uploading a file that already exists will produce an error in Android, but that particular error (`Broken pipe`) could also happen for other reasons. 
My proposal is to check if a file exists before trying to upload it. It's a lot of overhead during the first run, but it's the best I have.
=> fix: uploads on android

src/drive/mobile/lib/device.js, targets/drive/mobile/config.xml
Swapped out the plugin to provide the device name
=> fix: return actual device name

src/drive/components/FileActionMenu.jsx
Addressing [this](https://sentry.cozycloud.cc/sentry/cozy-drive-v3/issues/388/) error in sentry.
The [MenuItem](https://github.com/cozy/cozy-drive/blob/master/src/drive/components/FileActionMenu.jsx#L26) component just assumes that `onClick` is going to return a promise, but there was no guarantee for that. For example, [showing the sharing modal](https://github.com/cozy/cozy-drive/blob/master/src/drive/ducks/files/Container.jsx#L89) doesn't.
Now whatever the click handler returns, it gets wrapped in a promise.
=> fix: always return promise in menu click handler

src/drive/actions/index.js, src/drive/components/File.jsx, src/drive/components/FileList.jsx, src/drive/ducks/files/Container.jsx, src/drive/ducks/files/index.jsx, src/drive/reducers/view.js, src/drive/styles/table.styl
We fetch the recent files with a mango index (to sort them by `updated_at`), but this API doesn't return the file's path as those are not stored in CouchDB. 
I've added a call to the server to fetch the parent folders of all recent files, as *they* have a `path` attribute. @GoOz has updated the `File` component to allow displaying a file's path next to it's name.
=> feat: add path to recent files 

package.json, src/drive/components/File.jsx, src/drive/locales/en.json, yarn.lock
Changes the date format according to the vewport's size. 
1200+ pixels wide means a full written month, otherwise it's an abbreviated one.
=> feat: add responsive date format

config/webpack.target.browser.js, src/drive/ducks/services/components/SuggestionProvider.jsx, src/lib/cozy-client/CozyClient.js, src/lib/cozy-client/DataAccessFacade.js, src/lib/cozy-client/adapters/PouchdbAdapter.js, targets/drive/web/main.jsx, targets/drive/web/services.jsx
So the search now uses Cozy Client. I've made the following changes to the client:
- Make sure the cozy url has a protocol.
- Since the doctype `io.cozy.files` can't be written *to*, we only want to replicate *from* the cozy instance. I've added methods that allow to do one way syncs.
=> Fast search

package.json, yarn.lock
Two advantages:
1. fix what is the used version
1. do not use global install
=> chore: add cordova to dev dependencies

targets/drive/web/services.jsx
On the service page too, we need a URL with protocol in order for pouch to work.
=> fix: cozy url with protocol for services

package.json, yarn.lock
Gets you the latest cozy-bar and cozy-client-js, which is useful in dev and doesn't hurt for the mobile apps.
=> chore: update cozy-bar and cozy-client-js

package.json, src/components/Error/Empty-drive.jsx, src/components/Error/Empty-photos.jsx, src/components/Error/ErrorComponent.jsx, src/components/Error/ErrorShare-drive.jsx, src/components/Error/ErrorShare-photos.jsx, src/components/Error/Oops.jsx, src/components/Error/empty-drive.styl, src/components/Error/empty-photos.styl, src/components/Error/oops.styl, src/drive/components/FolderContent.jsx, src/drive/components/LightFolderView.jsx, src/drive/styles/oops.styl, src/photos/components/AlbumsList.jsx, src/photos/components/Empty.jsx, src/photos/components/PhotoBoard.jsx, src/photos/components/SelectAlbumsForm.jsx, src/photos/containers/AlbumsView.jsx, targets/drive/web/public/main.jsx, targets/photos/web/public/App.jsx
As I would like to fix a [label bug](https://trello.com/c/IzDE90L5/550-pho-%F0%9F%90%9B-libell%C3%A9s-non-traduits-sur-l%C3%A9cran-de-partage-public-dalbums), I discover duplication.
For now, I moved all related files into one global folder.
But I hope we could refactor components' and style's code into more simple one.
=> fix: remove unused errorType

src/drive/mobile/styles/uploadprogression.styl
=> fix: thumbnail in progression status

src/components/Error/Empty-photos.jsx, src/photos/components/AlbumsList.jsx, src/photos/components/SelectAlbumsForm.jsx, src/photos/locales/en.json, targets/photos/web/public/App.jsx
I misread the information when I worked on https://github.com/cozy/cozy-drive/pull/482
Here is a revert and a fix for empty shared album:
- revert: use `photosContext`
- fix: add 2 i18n keys for this specific case
- remove: the HOC was too noisy for this component, I removed it
_Note: I think one should rethink the abstraction of the _Empty_ component (The _Error_ one is similarly affected). What is an `<Empty />` component responsible for? It displays one big picture, one h2 title and one paragraph with details. As for now, it receives a single prop called `emptyType`, that means this component is responsible for steering the rendering towards the correct _«type»_ (what is a type? that is too mysterious), but he does not steer anything toward anywhere. We should change that._
=> fix: misuse of empty labels

src/lib/cozy-client/CozyClient.js, src/lib/cozy-client/__tests__/store.spec.js, src/lib/cozy-client/__tests__/utils.spec.js, src/lib/cozy-client/adapters/CozyStackAdapter.js, src/lib/cozy-client/adapters/PouchdbAdapter.js, src/lib/cozy-client/helpers.js, src/lib/cozy-client/index.js, src/lib/cozy-client/reducer.js, src/lib/cozy-client/utils.js
Adding support for `_bulk_docs` method from couchdb.
- The stack directly proxies to couchdb via `/data/`.
- Added pouchdb adapter
- Added stack adapter
- Reducer support
Example code : 
```js
await dispatch(
updateDocuments(
'io.cozy.bank.groups',
{
selector: { _id: { $gt: null } }
},
group => removeAccountFromGroup(group, account),
{
updateCollections: ['groups']
}
)
)
await dispatch(deleteDocuments('io.cozy.bank.operations', {
selector: { account: account.id }
}, {
updateCollections: ['transactions']
}))
```
=> Support for bulk update/delete

src/drive/locales/en.json, src/drive/mobile/containers/UploadProgression.jsx, src/drive/mobile/ducks/mediaBackup/index.js, src/drive/mobile/lib/network.js, src/drive/mobile/styles/uploadprogression.styl
Every time we skip a round of backup, I add a flag in redux so we can inform the user.
I am not very happy with this, but I don't see a way to do this properly *and* in a reasonable time-frame. I think ideally, we should completely reshape this part of the state: include informations such as "list f photos that need to be saved", avoid having properties that are sometimes present and sometimes not, and probably more. But I'm open to suggestions!
=> feat: indicator for paused file sync

src/drive/mobile/containers/MediaBackupProgression.jsx
Because we faced some _lags_ in loading Android files.
See https://trello.com/c/7uFiqx4D/526-3-dri-%F0%9F%93%B1-am%C3%A9liorer-le-retour-visuel-lors-de-la-sauvegarde-de-photo
=> fix: remove img in media backup progress

src/sharing/ShareModal.jsx
- Only shows the share by email tab if the URL contains the magic `sharingiscaring` word
- Make the link sharing the default tab
=> fix: hide cozy to cozy sharing behind a flag

config/webpack.config.pictures.js, package.json, src/drive/ducks/services/components/SuggestionProvider.jsx, yarn.lock
I changed the procedure:
1. load every `icon-type` file with [file-loader](https://github.com/webpack-contrib/file-loader)
1. build a mapping object : `name => icon-file-name`
1. map the mime-type to an icon file
1. warn in the console no mapping found
1. build an url
1. pass the url to the searchBar's `renderSuggestion` function
```js
const iconsContext = require.context(
'../../../assets/icons/',
false,
/icon-type-.*.svg$/
)
```
```js
const icons = iconsContext.keys().reduce(
(acc, item) => ({
...acc,
[item.replace(/\.\/icon-type-(.*)\.svg/, '$1')]: iconsContext(item)
}),
{}
)
```
```js
const mapMimeIcon = {
'image/jpeg': 'image',
'image/png': 'image',
'application/pdf': 'pdf'
}
```
_and add a default icon_
```js
const keyIcon =
mapMimeIcon[mimetype] ||
console.warn(
`No icon found, you …
```
=> feat: display an icon in the search bar results

src/drive/mobile/containers/FirstUploadModal.jsx
In https://github.com/cozy/cozy-drive/pull/455 we renamed variables without modifying this call. Maybe we could use selectors here. But for now, let's fix the bug.
- https://github.com/cozy/cozy-drive/pull/455/files#diff-d173561dcc55260e5a4050bb22efe48eL32
- https://github.com/cozy/cozy-drive/pull/455/files#diff-d173561dcc55260e5a4050bb22efe48eL33
=> fix: FirstUploadModal not displayed

targets/photos/manifest.webapp
The slug is incorrect, maybe that is the reason why I cannot publish to the registry.
See https://trello.com/c/Tu30nQwT/557-3-mettre-les-applications-drive-et-photos-dans-lapps-registry#comment-5a16d924189f25e82a2c3af9
=> fix: photos slug in manifest.webapp

src/drive/mobile/containers/FirstUploadModal.jsx
This fixes the issue, but it's not very clean, I've tried to avoid the render if the state has not been restored in the withPersistentState HOC, but I couldn't make it work strangely...
=> Avoid flashing of the first upload modal when navigating

src/drive/containers/File.jsx
Display `fil-file-file` if no mapping found (+ a message in the console)
=> fix: manage undefined mapping icons

src/authentication/steps/SelectServer.jsx
- changes the input type so the browser doesn't require a protocol
- fix an inversion in error messages
- use an internal `fetching` state because some async checks happen internally and were introducing a visible delay
=> fix: server selection improvements

src/lib/cozy-client/slices/sharings.js, targets/drive/web/public/main.jsx
This PR may cause problems for our next release. The commit we're merging into prod here is already on master so theoretically it's all ok but I'm not super confident.
=> fix: decide on download type at runtime

config/webpack.target.mobile.js
Sinon pour un build de prod sur mobile on a le build de la cozy-bar en mode non production et du coup on a un warning comme ceci :
=> chore: Use the production build of cozy libs

package.json, src/components/Button/index.styl, src/drive/mobile/styles/uploadstatus.styl, src/drive/styles/nav.styl, src/drive/styles/table.styl, src/drive/styles/toolbar.styl, src/photos/components/UploadButton.jsx, src/photos/styles/createAlbumForm.styl, src/photos/styles/nav.styl, src/photos/styles/newAlbum.styl, src/photos/styles/sidebar.styl, src/photos/styles/toolbar.styl, src/sharing/components/button.styl, src/sharing/components/recipient.styl, targets/photos/web/public/index.styl
I used the new version (not yet released) with no more output classes. (`.c-btn`, `.nav`, etc) for performance purpose.
So I had to manually recall every missing part, mostly buttons. It could better, it should be better but I think that for most cases we should use the `<Button />` component at some point.
=> chore: update UI version

src/components/Image/ImageLoader.jsx, src/drive/components/FilesViewer.jsx, src/drive/components/FolderView.jsx, src/drive/locales/en.json, src/photos/locales/en.json, src/viewer/AudioViewer.jsx, src/viewer/ImageViewer.jsx, src/viewer/NoNetwork.jsx, src/viewer/NoViewer.jsx, src/viewer/VideoViewer.jsx, src/viewer/withFileUrl.jsx
- All viewers now have a loading timeout and show the "no-good-network" screen. To do this, I implemented a `withFileUrl` [HOC](https://github.com/cozy/cozy-drive/pull/563/files#diff-75dfe39feb623ef6c3433f43d0e06fc3) that simplify a lot the audio & video viewers ;
- If there is no network (instead of a slow one), we now display the "no-good-network" screen without waiting for the timeout ;
- the `<ImageLoader />` no longer downloads the raw image when not necessary (it was a bug) ;
=> [WIP] Viewer enhancements

src/authentication/styles.styl, src/drive/mobile/styles/onboarding.styl, src/sharing/share.styl
Buttons in sharing modal & mobile onboarding were left unstyled from previous PR https://github.com/cozy/cozy-drive/pull/558
=> fix sharing modal & onboarding buttons

src/drive/components/FileList.jsx, src/drive/components/FilesViewer.jsx, src/drive/components/LoadMore.jsx, src/drive/containers/File.jsx, src/drive/locales/en.json, src/drive/styles/table.styl, yarn.lock
we removed react-virtualized as it caused problems with the layout and some glitches when browsing the app.
=> feat: lazy load files list

package.json, src/lib/cozy-client/collections/SharingsCollection.js, src/lib/cozy-client/package.json, src/lib/cozy-client/slices/sharings.js
with minified source it is r.byMe is undefined.
This is cause by fetching inconsistent data between
- `/permissions/doctype/:doctype/:sharingtype`
- `/sharings/:id`
=> fix: perms.byMe is undefined

src/drive/components/FilesViewer.jsx, src/drive/components/FolderView.jsx, src/drive/components/LightFolderView.jsx, src/drive/containers/FileExplorer.jsx, src/photos/ducks/timeline/components/Toolbar.jsx
on `root_dir`, `params.folderId` is `undefined` this is handled by `getFolderIdFromRoute`
=> refactor: use getFolderIdFromRoute

package.json, targets/drive/mobile/config.xml
There have been a few bugfix releases and the version numbers haven't been updated along the way.
=> chore: bump version numbers

src/drive/containers/File.jsx
Opening files from the trash was broken. For now, we'll use the same behavior on the recent and trash views — open files in new tabs.
=> fix: unify file opening in recent and trash views

src/viewer/assets/spinner.svg, src/viewer/styles.styl, yarn.lock
- Our toolbar overlaps the pdf viewer's native toolbar, making it unusable. I disabled pointer events on the wrapper element, but re-enabled them on the actual buttons.
- Especially in firefox, loading large pdf's introduces a notable lag and the screen stays dark for a while. There is no cross-browser compatible way to detect when the `object` is loaded, but we can put a waiting background underneath it.
=> pdf viewer fixes

src/drive/ducks/files/Container.jsx
Essentially a revert of 7b9ff889d7e0ad9460c29464b3a02dfee513a7d8 , done in #325 .
=> feat: enable folder renaming

src/drive/locales/en.json, src/drive/mobile/lib/filesystem.js, src/viewer/NativePdfViewer.jsx, src/viewer/README.md, src/viewer/Viewer.jsx, targets/drive/mobile/config.xml
We try to open pdf files with [this plugin](https://github.com/sitewaerts/cordova-plugin-document-viewer) — it requires local so we download the file first if it's not available offline already.
If the plugin can't open the pdf, we fallback to the system's default pdf viewer.
While the PDF is being viewed, the app shows a screen with an icon and a button to open the file again — but if everything goes well, no one will ever see it.
After the PDF is closed, we close the whole viewer.
=> feat: open pdf with cordova plugin

package.json, src/drive/components/FileList.jsx, yarn.lock
Pretty straightforward : i'm using the [InterSectionObserver](https://developer.mozilla.org/fr/docs/Web/API/IntersectionObserver) to detect when the "More" button comes into view, and then I fetch more files.
The only "complexity" comes from observing the button in case it gets re-rendered.
=> feat: load more files on scroll

targets/drive/mobile/config.xml
J'ai mis à jour cordova... mais pas les plugins, je vous laisse regarder ;)
On peut voir que même si "la communauté est morte", il y a des mises à jour, ça vaut le coup de les faire. Je pense qu'il faut jeter un œil tous les sprints sur https://cordova.apache.org/blog/
Sinon le 2eme commit correspond à l'ajout d'une url reconnu par l'application grâce au plugin [Custom-URL-scheme](https://github.com/EddyVerbruggen/Custom-URL-scheme). C'est à dire que l'on va pouvoir avoir des liens `cozydrive://blabla` qui redirigerons directement vers l'application. On s'en sert coté Bank pour rediriger vers l'application lorsque l'on veut voir une facture. Pour l'instant on arrive directement sur la home mais le but final sera évidemment d'ouvrir sur le bon fichier (J'imagine que l'on fera ça dans le …
=> Add custom url scheme

src/drive/components/FilesViewer.jsx
Quand on ouvre le viewer alors qu'il y a moins de 5 fichiers, fetchMoreFiles est appelé en boucle.
=> fix: fetch is called too often

src/drive/containers/File.jsx, src/drive/ducks/services/components/SuggestionProvider.jsx, src/drive/lib/getFileTypeFromMime.js
- We had an error on our `services` page, the one used for intents. `Cannot read property BarCenter of undefined`.
- `BarCenter` is a component exposed by the cozy bar, and there is no cozy bar on the `services` page because we don't need it. So why is `BarCenter` called at all?
- When we provide suggestions for the search bar, we also provide icons. To get the correct icon, we import a function that was defined in the `File` component.
- The `File` component itself imports half of our code base, including things that eventually call `BarCenter`
So
- I put the function in a standalone file that doesn't import anything else.
- No calling `BarCenter` anymore.
- The `services.js` file is 2x smaller now.
What I still don't like : the `Services` duck relies on a `lib` file that is not part of …
=> fix: make mimetype to file type function standalone

src/components/Button/MoreButton.jsx, src/drive/ducks/files/Toolbar.jsx, src/drive/ducks/trash/Toolbar.jsx, src/drive/locales/en.json, src/drive/mobile/lib/filesystem.js, src/photos/ducks/albums/components/AlbumToolbar.jsx, src/photos/ducks/albums/components/AlbumsToolbar.jsx, src/photos/ducks/timeline/components/Toolbar.jsx, src/viewer/ImageViewer.jsx, src/viewer/NoNetworkViewer.jsx, src/viewer/NoViewer.jsx, src/viewer/styles.styl, src/viewer/withFileUrl.jsx, targets/photos/web/public/App.jsx
I would like to enhance the viewer behavior when we're on mobile as requested in https://trello.com/c/t7lvpy6G
In `NoViewer` I added a `Spinner` when fetching/saving remote file. I guess we could refactor the different `Button` that are used in `NoViewer`.
I also added a `Alerter` error when there is no app or if something happens.
=> work on the mobile viewer

package.json
The second part of the command was missing a `npm run`.
=> fix: signed build script

src/authentication/Authentication.jsx, src/authentication/steps/SelectServer.jsx, src/drive/mobile/actions/settings.js, src/drive/mobile/containers/settings/Support.jsx, src/drive/mobile/lib/background.js, src/drive/mobile/lib/reporter.js, targets/drive/mobile/main.jsx
In the first commit, I removed the flag that allowed to disable Sentry, because we want to be able to report exceptions in all cases.
In the second commit, I added exception logging to the various errors that can occur when the user is entering its server url.
=> Sentry exception reporting during the onboarding

src/drive/mobile/containers/settings/About.jsx
It was due to a jsx error, it's been there for a while apparently.
=> fix: cozy link in settings

targets/drive/mobile/config.xml
I found a strange bug on iOS - some file types like `pptx` or `docx` would not open. They were downloaded, but when we tried to open them we received an error `File does not exist`.
Not knowing where to look, I upgraded [the plugin](https://github.com/pwlin/cordova-plugin-file-opener2) — there's no changelog, but it fixed the problem and everything else works as before, as far as I can tell.
=> chore: upgrade file opener plugin

src/authentication/steps/SelectServer.jsx
I revamp URL check instructions to explicit the codebase and to describe the intent.
We still have an anti-pattern in `componentWillReceiveProps`:
```js
componentWillReceiveProps(nextProps) {
this.setState(state => ({
...state,
error: nextProps.externalError ? ERR_WRONG_ADDRESS : null,
fetching: nextProps.fetching
}))
}
```
Putting a props in the internal state is an anti-pattern.
I added `propTypes` and `defaultProps`.
=> fix: manage url input

src/drive/mobile/styles/main.styl
We're hiding the button that shows the list of apps on the mobile app, until we've made a few changes to this menu.
=> feat: temp hide cozy bar apps button

src/drive/mobile/lib/cozy-helper.js
When we are offline, we can't get a token to pass to the cozy-bar. But we still want to init the bar! Even without a token.
To test this, you can start the app in `standalone` mode, and then block all queries to `cozy.tools:8080` with the devtools. Without this PR, the cozy bar doesn't show up at all. With this PR, it appears as usual.
=> fix: init bar when offline

config/webpack.config.preact.js
With #612, react-router will need a new alias to stay preact-compatible. See [this issue](https://github.com/developit/preact/issues/739#issuecomment-316684628).
=> chore: alias create-react-class with preact

src/viewer/NoViewer.jsx
I think this was a mistake ? [`logException`](https://github.com/cozy/cozy-drive/blob/df16620b204a36a85bcf6ac9a4ff222d4fbd62d0/src/drive/mobile/lib/reporter.js#L28) only accepts one argument.
=> fix: exception log on file error

src/lib/cozy-client/connect.jsx
Since we test with React, we must be compatible with React.
EDIT : More context : 
For React to pass context properties down to children components, contextTypes must be defined with the properties that are passed. In preact, access to the context is not restricted like this. 
https://reactjs.org/docs/context.html
> If contextTypes is not defined, then context will be an empty object.
EDIT: Removed :
=> Compatibility with React

src/lib/cozy-client/CozyClient.js, src/lib/cozy-client/DataAccessFacade.js, src/lib/cozy-client/adapters/PouchdbAdapter.js
I ported [`destroyAllDatabase`](https://github.com/cozy/cozy-client-js/blob/master/src/offline.js#L87-L91) function (+ added mechanism to stop synchronization) from cozy-client-js to cozy-client.
=> [cozy-client] feat: add destroyAllDatabases method

src/authentication/steps/SelectServer.jsx
A while ago, we started using the URL API to parse the server URL.
We noticed afterwards that this API tends to add an extra `/` at the end, eg. `https://my.cozy.cloud` becomes `https://my.cozy.cloud/`, and then some of our calls end up having double slashes (eg. `https://mYcozy.cloud//status`).
We fixed it, but fixed badly, using the unparsed URL. This PR fixes things properly, I hope.
It should now work when entering a URL with or without protocol, and there should never be an extra slash at the end.
=> fix: add protocol to server url

src/drive/containers/File.jsx
On touch devices, taping the "more" button on the right of a file would sometimes not work, depending on what element exactly was the `target`. When it didn't work, the file was opened in the viewer instead.
This fixes the problem, so tapping the "more" button should always bring up the FileActionMenu now.
=> fix: taps on more button

.travis.yml
waiting for the resolution of a known bug
https://github.com/transifex/transifex-client/issues/207
=> chore: freeze travis version

src/authentication/Standalone.jsx, src/authentication/package.json
Fallback to English if locale is not available.
`<I18n />` already does that for us but we have to use the callback dictRequire to load the locale data.
=> Auth component npm

src/lib/cozy-client/__fixtures__/sharings.js, src/lib/cozy-client/__mocks__/cozy-client-js.js, src/lib/cozy-client/__mocks__/pouchdb.js, src/lib/cozy-client/__tests__/sharings.spec.js, src/lib/cozy-client/index.js, src/lib/cozy-client/slices/sharings.js
Cette PR ajoute des tests autour du partage. Pour l'instant, seules la création d'un partage et d'un lien de partage sont couverts. La stratégie employée est de mocker la réponse JSON de la stack, afin de documenter cette réponse attendue d'une part, et de vérifier le bon fonctionnement du store et des différents sélecteurs.
J'en ai profité pour faire un petit refacto des reducers des permissions afin de régler le pb des erreurs de type `byMe is undefined` : https://github.com/cozy/cozy-drive/pull/681/files#diff-9adf7fd271915ca7d36b207126236acb
=> Sharing unit tests

targets/drive/web/index.ejs, targets/photos/web/index.ejs
The `fonts.css` asset imported from the main domain is already injected by the stack, with an immutable hash. This PR removes the import made by the application to avoid wasting a network roundtrip.
=> chore: fonts.css asset is already imported by the stack

src/drive/mobile/lib/handleDeepLink.js, targets/drive/mobile/main.jsx
We use the `history` to navigate when we handle an URL `cozydrive://mylink`.
=> feat: navigate when handling cozydrive:// url

config/webpack.target.mobile.js, package.json
=> Webpack tweaks

targets/drive/mobile/config.xml, targets/drive/mobile/translations/app/en.json, targets/drive/mobile/translations/app/fr.json
Adds descriptions for permission requests on iOS.
The file and folder structure is required by the plugin we use, so unfortunately these strings won't be in our translation system.
For languages without translation file, the app falls back on english or french, depending on how iOS is configured.
=> chore: add ios permission descriptions

config/webpack.config.base.js, package.json, src/drive/ducks/files/FileOpener.js, src/drive/mobile/lib/device.js, yarn.lock
From Bank, we need to be able to open Drive on a specific file. We cannot retrieve the parent of the file (we have no permission on io.cozy.files) so we cannot redirect to `/folder/$folderId/file/$fileId` from bank.
I changed FileOpener which had already the role of fetching file information and displaying it to use the Viewer.
The `/file/$fileId` route now fetches the file and redirects (router.replace not to add an entry in the back button history) to `/folder/$fileFolderId/file/$fileId`.
=> Use viewer for file

renovate.json
Following up on #696, activate pinning for regular dependencies too. We'll probably get a couple more PRs from renovate, but we won't have any sneaky `yarn.lock` updates to deal with either.
=> chore: activate version pining for dependencies

src/authentication/package.json, src/authentication/steps/SelectServer.jsx, src/authentication/yarn.lock
- adds a polyfill for super old browsers  that have no support for the `URL` API
- automatically adds the `mycozy.cloud` domain if no domain is entered
- strips out application slugs when URLs are pasted, ie. `yannick-drive.mycozy.cloud` becomes `yannick.mycozy.cloud`
=> fix: safer onboarding

src/components/Error/Empty.jsx, src/drive/actions/index.js, src/drive/components/FileList.jsx, src/drive/components/FolderView.jsx, src/drive/components/Main.jsx, src/drive/containers/File.jsx, src/drive/containers/FileExplorer.jsx, src/drive/containers/Nav.jsx, src/drive/reducers/index.js, src/drive/reducers/view.js, src/drive/styles/main.styl, src/drive/styles/nav.styl, src/drive/styles/table.styl
Actuellement, si la vue générale et la vue de la corbeille récupère les données dont elles ont besoin dans l'instance Pouch locale sur mobile, ce n'est pas le cas de la vue "Récents" qui fetche les données par le réseau, d'où un sentiment de lenteur en cas de réseau de piètre qualité. Le problème peut être exacerbé si l'utilisateur s'impatiente et clique sur d'autres onglets.
Cette PR implémente : 
- la récupération des fichiers récents depuis PouchDB ;
- la désactivation des onglets lorsque l'un d'entre eux vient d'être cliqué et que du contenu est en train de charger ;
- le floutage du contenu sur mobile au chargement : j'ai pour cela ajouté 2 reducers et un [selector](https://github.com/cozy/cozy-drive/pull/690/files#diff-dba5935292b52df2da17bc1ea6222f12R53), selector qui est utilisé …
=> [WIP] Fix tab switching performance problems

config/webpack.target.mobile.js, package.json, src/drive/mobile/lib/reporter.js, yarn.lock
For some reason I still have to investigate, our version or raven-js is not pinned. This resulted in us shipping the app with a new minor version of raven, v3.21 — and that's where the actual problem starts.
From that version on, raven uses `fetch` instead of `XHR` when available. Somehow, when using `fetch` from cordova, the `Origin` header is set to `null` and this [causes the error](https://github.com/getsentry/sentry/issues/4060) we experienced.
One way to work around this is to use the secret DSN, as described [here](https://docs.sentry.io/clients/javascript/config/) in the section about `allowSecretKey`. 
The only alternative I found would be to downgrade `raven-js`.
=> fix: raven errors on mobile

src/drive/mobile/containers/RatingModal.jsx, src/drive/mobile/ducks/mediaBackup/UploadQuotaError.jsx
We've been using different emails for different purposes in the past. We decided to drive all user email interactions to contact@cozycloud.cc. As a result I suggest this change.
=> Change support email to contact

src/drive/mobile/containers/MediaBackupProgression.jsx, src/drive/mobile/ducks/mediaBackup/index.js
- Turns out we'd rather interrupt the upload as soon as we get a quota error, otherwise the user never sees it
- When the upload starts, `mobile.mediaBackup.something.current` is `0` so if we just test `current` instead of `current !== undefined` the uploader doesn't show up.
=> Upload fixups

src/drive/mobile/containers/MediaBackupProgression.jsx, src/drive/mobile/ducks/mediaBackup/UploadAbortedWifi.jsx, src/drive/mobile/ducks/mediaBackup/UploadProgression.jsx, src/drive/mobile/ducks/mediaBackup/UploadQuotaError.jsx, src/drive/mobile/ducks/mediaBackup/UploadUptodate.jsx, src/drive/mobile/ducks/mediaBackup/styles.styl
I've added an infinite progress bar for individual files, like this : https://gfycat.com/InformalImpressionableDuckbillcat
I also remove a `div`-based progress bar with a `progress` element.
=> feat: add infinite progress bar for individual photos

src/drive/mobile/ducks/mediaBackup/UploadProgression.jsx, src/drive/mobile/ducks/mediaBackup/styles.styl
=> fix: super-impose the upload progression on the cozy bar border

src/authentication/steps/SelectServer.jsx
I disabled links in the onboarding so it looks like this again:
I didn't find a simpler way to disable that link — see https://github.com/rexxars/react-markdown/issues/139
=> fix: remove fake link in onboarding

src/drive/actions/index.js, src/drive/actions/settings.js, src/drive/components/AppRoute.jsx, src/drive/components/FileList.jsx, src/drive/components/FilesViewer.jsx, src/drive/containers/File.jsx, src/drive/containers/FileExplorer.jsx, src/drive/locales/en.json, src/drive/mobile/actions/settings.js, src/drive/mobile/lib/replication.js, src/drive/reducers/settings.js, src/drive/reducers/view.js, src/lib/cozy-client/CozyClient.js, src/lib/cozy-client/adapters/CozyStackAdapter.js, src/viewer/ImageViewer.jsx, src/viewer/Viewer.jsx
Dans cette PR j'ai ajouté les routes nécessaires pour que le viewer fonctionne depuis /recent et /trash. De plus, étant donné que sur mobile, les données viennent de PouchDB et que les fichiers n'ont pas de liens vers les vignettes, je me suis efforcé d'isoler ce code de récupération des vignettes ~~dans le wrapper `FilesViewer`~~ dans l'`ImageViewer` au final : c'est moins optimum, car une requête sera faite pour chaque image (mais seulement au moment où on essaie de l'afficher), mais c'est plus simple et plus sûr dans l'immédiat.
Dans un second temps, j'ai résolu un certain nb de pbs liées à l'utilisation de PouchDB : 
- dorénavant, l'appli tape sur la stack tant que la première réplication n'est pas faite (ou les indexes n'ont pas été créés) ;
- on utilise maintenant une query …
=> Added viewer to trash and recent views

targets/drive/web/services.ejs
The cozy-bar was not injected in the services part of cozy-drive, causing errors when components were relying on cozy-bar's `BarLeft`, `BarCenter` or `BarRight` components.
Currently I propose a quick fix that consists in injecting the bar. Maybe there is a better way to fix this problem we can discuss.
=> fix: inject cozy-bar in services

src/drive/actions/index.js, src/drive/components/LightFolderView.jsx, src/drive/containers/File.jsx, src/drive/containers/FileExplorer.jsx, targets/drive/web/public/main.jsx
Please note that for simplicity reasons I decided to not use routing to open/close the viewer, but used a local state instead. I also cleaned up a bit of code now that we don't have to open files in tabs anymore.
=> Viewer in the public shared folder view

src/drive/components/FilesViewer.jsx
=> Fixed viewer that tried to display folders

src/drive/ducks/services/components/SuggestionProvider.jsx, src/drive/lib/getFileTypeFromMime.js
[this is the actual fix](https://github.com/cozy/cozy-drive/pull/730/files#diff-ab8f134c72c2b24476f993fcb9f5c5e2R57) : folders don't have a `trashed` property, and `undefined === false` is falsy so the folders were filtered out.
After fixing *that*, the app crashed because we tried to get an icon based on the folders `mime` property which again, doesn't exist.
[I handled the case of folder icons](https://github.com/cozy/cozy-drive/pull/730/files#diff-ab8f134c72c2b24476f993fcb9f5c5e2R97) separately because `folder` isn't a mime type, technically speaking.
I also made sure that [`getFileTypeFromMime ` won't just crash if called with `undefined`](https://github.com/cozy/cozy-drive/pull/730/files#diff-b60035d97397e5f3b868c2846f4130c4R11).
=> Enable folders in search results

src/drive/mobile/styles/main.styl
Evolution of the previous fix : now the app menu can take all the available height, and nothing iss displayed on tablets.
Note that this stylus file is only used for native builds, so it doesn't affect the web version of Cozy Drive.
=> fix: hide settings on mobile

jest.config.json, src/drive/ducks/services/FuzzyPathSearch.js, src/drive/ducks/services/FuzzyPathSearch.spec.js, src/drive/ducks/services/components/SuggestionProvider.jsx
- I amended the code that filters out trashed files and folders — it now *really* discards anything that's in the trash
- We had the correct results, but not in the correct order. This was due to a combination of several small problems, which I've all corrected
=> Search: result order and trashed dirs

src/drive/mobile/ducks/mediaBackup/index.js
We'd like to find out why the upload sometimes hand, but since the file metadata is only displayed when there is an error at the moment, it's hard to know. This will provide more data to work with.
=> feat: log file metadata when upload hangs

src/drive/ducks/services/components/SuggestionProvider.jsx
- There was a bug with filtering trashed results, again.
- Sometimes, there are orphan files — the files exist, but their parent folder does not. It has not been investigated yet, but in the meantime we need to filter out those files from search results.
=> fix: filter out orphans from search results

src/lib/cozy-client/__tests__/store.spec.js, src/lib/cozy-client/reducer.js
Previously, when no data was updated/deleted, the reducer would throw.
=> fix: reducer throws when updating/deleting no documents

src/lib/cozy-client/helpers.js, src/lib/cozy-client/reducer.js, src/lib/cozy-client/utils.js
`removeObjectProperty` does not take into account if the "object" passed is undefined. There was an edge case in the `reducer` when it happened. I replaced it by "lodash/omit" which does the same thing, has IMHO a better API (supports both array form and single value form), returns `{}` if the object passed is undefined, and is already loaded since `lodash` is loaded.
=> Fix remove obj property

src/lib/cozy-client/DataAccessFacade.js
In banks, we need to use the `StackOnlyStrategy` for the first data fetch, then `PouchFirstStrategy` for subsequent fetches. So we need to be able to import the strategies to dynamically switch it when we need to.
=> feat(cozy-client): export data access strategies

src/sharing/ShareModal.jsx
We recently changed the `SharingModal` so that it renders using a Portal, as provided by cozy-ui. This caused a really weird bug where the Modal was rendered *twice*. And if you close the first modal, the second is still there and you can't change it.
I narrowed down the problem a little bit and found a workaround — if the component returning the Modal isn't connected to cozy-client, the bug doesn't happen. 
I will create an issue in cozy-ui tomorrow with everything I know, and search a bit more. But i already spent several hours on this, and it's very, very strange. I doubt we'll find a better solution soon.
=> fix: modal appears twice in the DOM

src/sharing/components/SharedBadge.jsx, src/sharing/components/badge.styl
Refactoring of SharedBadge component:
- Use of `<Icon />` instead of background image
- proper width/height values instead of playing with padding
🗒️ On a side note, I was not sure what the size should do, I guess there could be some improvement to do here, like a default size and modifiers classes but as this was not the purpose of this refactoring and giving the fact that I don't know this component this well, I'll leave you judge if it's a good thing or not to do.
=> fix: refactoring for sharedBadge Component

package.json, src/components/Button/MoreButton.jsx, src/drive/components/FileListHeader.jsx, src/drive/containers/File.jsx, src/drive/styles/table.styl, yarn.lock
Updated UI to fix some bugs and update some narrow button.
=> Chore/update u iv7.4

src/components/pushClient/Banner.jsx, src/components/pushClient/Button.jsx, src/components/pushClient/index.js, targets/drive/manifest.webapp
Cela m'embête un peu (beaucoup) d'être obligé de faire un fetch pour chaque composant, mais ils sont totalement décorrélés dans le layout et je ne voyais pas trop comment faire mieux sans sortir l'artillerie lourde (redux). En espérant que cela vous convienne malgré tout (et en sachant qu'il faut qu'on en discute avec notre PO étant donné que cela nécessite de demander une perm de plus).
=> Don't show the desktop banner or button if already installed

src/drive/mobile/containers/RatingModal.jsx
1. First commit: we show the rating prompt after 10 boots and a minimum of one week after the first usage
2. Second commit: fix the button styles (I'm working on a PR for cozy-ui to fix the initial problem)
3. Third commit: not essential, but when the cordova plugin can't be found, we want to reject the promise and handle the error
=> Rate prompt delay

package.json, src/components/pushClient/pushClient.styl, yarn.lock
Aligns the banner text to the left, and includes the latests fixes from cozy-ui.
=> fix: banner alignments

targets/drive/mobile/fastlane/metadata/android/fr-FR/full_description.txt
=> Update description to add Cozy description

src/lib/cozy-client/CozyClient.js
I've essentially inverted the logic — instead of treating everything like a revocation *except* offline errors, we know consider every error as "it's fine, we're just offline" *except* the ones that really tell us that the client has been revoked.
=> fix: proper client revokation detection

src/lib/cozy-client/reducer.js
Problem 1
========
Example : Fetching of banking operations, query depends on the account currently shown,
all operations are stored in the same collection.
Observed behavior : the collection is reset for each query, unless the action has a `skip` attribute.
Desired behavior : the collection should not be reset, and any new data should be merged.
Proposal : added the `merge` attribute to the action.
Problem 2
=========
Observed behavior : Now that we have the merge attribute, ids are duplicated if there
are multiple fetches.
Proposal : deduplicate the ids of the collection
=> feat: allow several fetches from several queries to be merged into a single collection

package.json
This will only work for Android, still looking for a solution for iOS.
=> fix: upload sourcemaps on correct path

src/sharing/ShareModal.jsx
Added missing polyfill for `URL.searchParams`, required for MS Edge (and others).
=> fix: polyfill search params

src/lib/cozy-client/reducer.js
I think a small bug slipped [here](https://github.com/cozy/cozy-drive/commit/696bc3b6d3b9700d60e00e7dfdb984056993854d) : after that change, in order to combine the results instead of replacing them, the action would need to have both `skip` and `merge` to `true`, but I'm pretty sure any one of them is enough.
=> fix: merge-skip bug

src/drive/actions/index.js, src/photos/ducks/albums/components/AlbumToolbar.jsx
Revokes sharings when an album, a file or a folder is deleted.
=> fix: revoke sharing links on delete

src/drive/components/LightFolderView.jsx
There are other types of errors where we want to display the "revoked" screen — for example 404, or expired tokens.
=> fix: show revoked error for all types of errors

src/authentication/steps/Welcome.jsx, src/components/Button/CozyHomeLink.jsx, src/drive/components/LightFolderView.jsx, targets/photos/web/public/App.jsx
We changed the webpage's URL where users are redirected if they want to create a cozy.
Related to https://github.com/cozy/cozy-banks/pull/19 (see https://trello.com/c/TMNxeLZO/917-1-changer-les-urls-pour-la-cr%C3%A9ation-de-cozy)
=> fix: create cozy url

src/authentication/Revoked.jsx, src/authentication/package.json
This very simple PR adds the ability to give an `url` prop to `Revoked` so that `cozy-client-js` is not needed for this.
=> Fix Revoked component for Banks

targets/.travis.yml
We use `cozy-app-publish` to publish our apps to the registry, and it uses the value of `TRAVIS_TAG` to decide what branch the app should be published on. `TRAVIS_TAG` is simply the current git tag, if any.
Since git tags are unique per repo, we can't tag the builds fro drive and photos with the same tag, which means we can't actually publish them.
So instead, we are going to tag the build branches with `drive-1.0.0` and `photos-1.0.0`. And then in the travis script, we remove the prefix from the `TRAVIS_TAG` variable so the script can run as usual.
Hopefully this workaround won't stick around for too long, because it's a bit fragile.
=> Publish to registry — change TRAVIS_TAG variable

src/drive/ducks/services/components/SuggestionProvider.jsx
When selecting a file as a search result, direct to the viewer instead of the parent folder.
=> feat: open files in the viewer from the search results

src/drive/components/FileListPlaceholder.jsx, src/drive/components/FolderContent.jsx, src/drive/components/FolderView.jsx, src/drive/components/LightFolderView.jsx, src/drive/styles/foldercontent.styl, src/drive/styles/table.styl
Here's the preview:
When the content of a folder is loading, we display a set of placeholders instead of a giant spinner, or nothing.
The code for the animation is complicated but I really don't see a better way to do it :/
=> feat: file list placeholder

README.md
It fixes a typo in the main README.md with the previous location of the sharing documentation
~~- [ ] Faithful integration of the mockups at all screen sizes~~
~~- [ ] Tested on supported browsers, including responsive mode (IE11 and Edge, Chrome >= 42, 2 latest versions of Firefox and Safari)~~
~~- [ ] Localized in english and french~~
~~- [ ] All changes have test coverage~~
=> Fix link to sharing in main readme

targets/drive/mobile/config.xml, targets/drive/mobile/main.jsx
because cordova.plugin.file is a funny kid that changed window.File by its own object
=> fix: handle edge cases

src/drive/ducks/files/FileOpenerExternal.jsx, src/viewer/ViewerControls.jsx
I choosed to not show the cross when the `onClose` prop isn't provided. That's a simpler solution than what we thought about.
=> Don't show the viewer cross when displayed in an intent modal

src/drive/components/FilesViewer.jsx
Because it breaks the search! This PR implements a contingency measure by loading the file attributes directly. It allows us to show the file in the viewer, but without the nav arrows.
=> Don't close the viewer when trying to view a file lost in a big folder

src/drive/actions/async.js, src/drive/actions/index.js, src/drive/components/FileList.jsx, src/drive/reducers/index.js, src/drive/reducers/view.js, src/drive/styles/table.styl
Sorting by name didn't work correctly on large folders because folders and files got mixed when fetching more. Because Couch and Pouch can't sort on 2 fields but different orders (it'd allow us to sort by type AND name and be done), I had to resort to fetch folders and files separately.
=> Sorting fixes

src/drive/styles/table.styl
Better use of space on mobile, especially when "offline" icon is on.
=> fix: longer file name length on mobile

package.json, targets/drive/manifest.webapp, targets/drive/mobile/config.xml, targets/drive/mobile/fastlane/metadata/android/en-US/changelogs/140.txt, targets/drive/mobile/fastlane/metadata/android/en-US/changelogs/141.txt, targets/drive/mobile/fastlane/metadata/android/fr-FR/changelogs/140.txt, targets/drive/mobile/fastlane/metadata/android/fr-FR/changelogs/141.txt, targets/photos/manifest.webapp
In release `1.4.0` we forgot to disable the "share to Cozy Drive" feature on Android.
Here is a fix for the previous release, `master` will be tagged `1.4.1`.
=> release 1.4.1 with intent disabled

src/photos/components/Photo.jsx
Thumbnails in a public page need some special permission given by the token and a cookie. The previous client could not send a authenticated request, so I updated the client to use an authenticated client instead.
=> Fixed thumbnails display on public page

src/drive/mobile/lib/intents.js, targets/drive/mobile/config.xml, targets/drive/mobile/main.jsx, targets/drive/mobile/scripts/configure-share-extension.js
These changes allows the user to send a file to Cozy Drive on iOS. it relies on [this plugin](https://github.com/EternallLight/cordova-plugin-openwith-ios).
Further comments coming up 👇
(Looping in the gangsters @kosssi @ptbrowne @drazik in case you're interested, although I'm not sure it's too useful for Cozy Banks.)
=> feat: ios file sharing

package.json, yarn.lock
We have to change versions inside:
- the config.xml files
- the drive manifest
- the photos manifest
- the package.json
Not sure if package.json should refer to Drive or Photos, but still.
With these new tasks, we can change the version in package.json, and then run `yarn version:drive` or `yarn version:photos` to change the other files.
=> chore: change all versions at once

.gitignore, src/drive/ducks/files/Toolbar.jsx, src/drive/ducks/upload/index.js, src/drive/mobile/lib/intents.js
We need to call [this function](https://github.com/cozy/cozy-drive/blob/master/src/drive/actions/index.jsx#L231) to update the redux state after uploading a file, so that the file actually appears.
This function is used 3 times, but with 3 different forms. Only one of them actually worked. This PR fixes the two others.
=> fix: reload after upload

src/drive/ducks/files/FileOpenerExternal.jsx, src/drive/ducks/services/components/SuggestionProvider.jsx, targets/drive/web/services.jsx
The icons were missing because we sent wrong URLs. With that fix, we now send [data URIs](https://github.com/cozy/cozy-drive/compare/master...goldoraf:fix-search-icons?expand=1#diff-ab8f134c72c2b24476f993fcb9f5c5e2R129).
I also reverted back to using cozy-client-js for the file list fetching and the file opener intent because we want to get rid of the old cozy-client, but the PouchDB integration in the new cozy-client is not dry enough.
=> Fixed missing icons in the search suggestions

src/drive/actions/index.jsx, src/drive/components/FolderView.jsx, src/drive/ducks/files/Container.jsx, src/drive/ducks/files/FileOpenerExternal.jsx, src/drive/ducks/files/rename.js, src/drive/ducks/trash/actions.js, src/drive/mobile/components/Settings.jsx, src/drive/mobile/containers/RatingModal.jsx, src/drive/mobile/containers/settings/Support.jsx, src/drive/reducers/view.js
With the recent migration to the `cozy-ui` `Alerter`, we failed to fix some alerts, essentially the alerts that are included in redux actions and that were handled by the previous redux alerter.
=> Fixed Drive alerts

src/drive/ducks/files/FileOpenerExternal.jsx
- tells cozy-client-js to not rely on offline data to fetch the file
- formats the data as expected by the viewer
=> fix: fetching file with cozy client js

src/drive/actions/index.jsx, src/drive/containers/FileExplorer.jsx, src/drive/ducks/files/Toolbar.jsx, src/drive/ducks/upload/UploadQueue.jsx, src/drive/ducks/upload/index.js, src/drive/ducks/upload/styles.styl, src/drive/locales/en.json, src/drive/mobile/lib/intents.js
- Detects network errors
- Shows a specific message when they happen
- Regular, unspecified errors are now grey instead of bright red
=> fix: specific message when upload fails because of the network

src/drive/mobile/lib/cozy-helper.js
Forgot this during the recent cozy-client migration.
=> fix: init cozy-client-js offline databases

package.json, src/drive/components/Dropzone.jsx, src/drive/ducks/upload/UploadQueue.jsx, src/drive/ducks/upload/index.js, src/drive/store/configureStore.js, yarn.lock
Folder upload by Dn'd didn't work correctly: first, it simply didn't work at all on FF because of mimetypes (fixed with the new CC version), and second, it uploaded a flat list of files instead of creating dirs and sub-dirs. That's why I moved the folder handling code [in the upload module](https://github.com/cozy/cozy-drive/compare/master...goldoraf:folder-dnd-ff?expand=1#diff-a8db4e1272c43f0485054c5491a45fc0R104).
I also needed to have access to a CC instance in the upload thunks, so I used the [withExtraArgument method of redux-thunk](https://github.com/cozy/cozy-drive/compare/master...goldoraf:folder-dnd-ff?expand=1#diff-967a91470826706845a91e50ee1316c2R18).
=> Added folder upload by DnD

src/drive/components/FileActionMenu.jsx, src/drive/styles/actionmenu.styl
We have some UI fixes to implement on the ActionMenu (swipe RTL instead of top-down, ...), but as we'd like Banks to benefit from that fixes too, it's better to implement them in cozy-ui. So this PR makes Drive use the cozy-ui ActionMenu.
=> Replaced Drive ActionMenu by the cozy-ui one

src/components/Image/ImageLoader.jsx
Firefox ESR, probably among others, doesn't yet support `Promise().finally`.
=> fix: replace finally call for unsupported browsers

src/drive/mobile/containers/RatingModal.jsx, src/drive/mobile/lib/constants.js
The plugin now needs the app store id number rather than the string?
=> fix: ios app id for ratting

package.json, src/drive/components/FolderView.jsx, src/drive/components/Layout.jsx, src/drive/ducks/files/Container.jsx, src/sharing/SharingDetailsModal.jsx, src/sharing/__tests__/state.spec.js, src/sharing/components/Recipient.jsx, src/sharing/index.js, src/sharing/state.js
This PR fixes a few things:
- when a sharing is revoked, if the corresponding `byId` entry is "empty" (no more sharings or perms), it is deleted ;
- we filter out self-revoked sharings and sharings with all revoked recipients ;
- UI fixes.
=> Sharing fixes

src/photos/components/PhotoList.jsx
We need to take into account EXIF orientation tags (present on some images) to dispaly the correct image ration in all cases.
=> Use photos orientation metadatum to correct image ratios

package.json, src/drive/containers/File.jsx, src/drive/ducks/services/components/SuggestionProvider.jsx, src/drive/lib/getFileMimetype.js, targets/drive/manifest.webapp, targets/drive/mobile/config.xml, targets/photos/manifest.webapp, yarn.lock
I used a different lib for mimetype lookup because the one used by cozy-client seems problematic. I've made the change in cozy-client too.
=> Better handling of mimetype icons by guessing the type from the extension

src/drive/actions/async.js, src/drive/mobile/lib/replication.js
Renaming the index was unnecessary and caused the index to be recreated, leading to potential errors.
=> fix: renamed index

src/drive/actions/index.jsx, src/drive/ducks/files/Container.jsx, src/drive/locales/en.json, targets/drive/mobile/config.xml
Using [this plugin](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin#8-whitelisting-on-ios-9), i've replaced the (broken) file download feature on mobile by one that exports files to other apps.
=> feat: Export files on mobile

package.json, src/components/Button/CozyHomeLink.jsx, src/components/Button/index.styl, src/viewer/Viewer.jsx, src/viewer/ViewerControls.jsx, src/viewer/styles.styl, targets/drive/web/public/main.jsx, yarn.lock
Previously, when sharing a single file by link, we redirected to a download URL. We now want to open it in a light version of the viewer, with a white background and with a special version of the cozy-bar on top. I had to add a few props to `Viewer` to enable that.
=> [WIP] Open files shared by link in the viewer

package.json, src/drive/mobile/ducks/mediaBackup/styles.styl, yarn.lock
I introduced a regression a few days ago by moving the border of a table-row from the bottom to the top. But I forgot a usecase, so I added a bottom border to the last row of a table (fix in UI update) and because the border is now at the top we had a disgraceful double border on the mobile app with the `.coz-upload-status` element.
This PR  fixes that by removing this element's border.
=> fix: table's last row bottom border

targets/drive/mobile/main.jsx
There were é issues when starting the app offline:
- at least on iOS, the error we received was interpreted as meaning we had been disconnected. I inverted the logic — now we only consider ourselves revoked when we encounter specific error codes, in all other cases, we consider ourselves offline
- cozy-client-js was not restored at the application start, so PouchDB databases were unavailable
=> Fix offline boot

package.json, src/drive/locales/en.json, src/sharing/ShareModal.jsx, src/sharing/__tests__/state.spec.js, src/sharing/components/Recipient.jsx, src/sharing/components/ShareByEmail.jsx, src/sharing/components/WhoHasAccess.jsx, src/sharing/components/recipient.styl, src/sharing/index.jsx, src/sharing/share.styl, src/sharing/state.js
Like described in the Trello card, we have to forbid sharing of a folder/file whose parent is shared or who have a shared child. We therefore need to get the paths of all shared folders/files. This is straightforward for folders, because they have a `path` property, but for files, we need to fetch their parent dir to get the path and append the file name.
I also fine-tuned some CSS.
=> Forbid some sharings

src/drive/ducks/files/Container.jsx
Until now, the action menu was closed when sharing due to a bug in cozy-ui. This also had some very strange side effect: the sharing modal would sometimes get `translateY` instead of the menu (presumably a bug in preact?).
This change closes it in a better way while also avoiding the translate bug.
=> fix: Properly close action menu

targets/drive/mobile/main.jsx
If you revoke the client, kill the app and restart it, the cozy bar would be initialized. This PR fixes it.
=> fix: Only init bar if there's a server url

src/drive/mobile/containers/DriveMobileRouter.jsx, src/drive/mobile/lib/cozy-helper.js, src/drive/mobile/lib/replication.js, targets/drive/mobile/main.jsx
There were a few issues when a token expired — the cozy-bar and cozy-client-js were keeping their old tokens, and their requests would fail.
=> Improve revocation and expired token handling

targets/drive/mobile/config.xml
The file-opener plugin is out of date. Sadly there's no new official release, so in the meantime I've switched us to `master`. I've also opened an issue : https://github.com/pwlin/cordova-plugin-file-opener2/issues/219
=> chore: Update file-opener plugin

src/drive/containers/Breadcrumb.jsx, src/drive/ducks/files/SharingsContainer.jsx, src/drive/reducers/view.js
The sorting fix is pretty straightforward.
For the breadcrumbs, when on the sharings view, we need to know if the folders are shared or not — because if they are, we don't want to show their (not shared) parent in the breadcrumb.
=> Sharings view fixes

src/components/Menu/index.jsx, src/drive/ducks/files/Container.jsx, src/drive/ducks/files/Toolbar.jsx, src/drive/styles/actionmenu.styl, src/drive/styles/toolbar.styl, src/sharing/components/Recipient.jsx, src/sharing/index.jsx
As the more menu on mobile is injected into the cozy-bar, it doesn't have access to the sharing context. That's why I had to use `RecipientsAvatars` [here](https://github.com/cozy/cozy-drive/pull/1074/files#diff-12918a0e2886ac9526cde1534cc4ca9fR78) instead of `SharedRecipients` and pass the recipients to the Toolbar.
=> Added sharing recipients to the more menu

package.json, src/drive/locales/en.json, src/drive/mobile/actions/authorization.js, src/drive/mobile/reducers/index.js, src/drive/reducers/index.js, src/drive/store/configureStore.js, src/sharing/ShareModal.jsx, src/sharing/components/ShareAutosuggest.jsx, src/sharing/components/ShareByEmail.jsx, src/sharing/index.jsx, src/sharing/share.styl, yarn.lock
Some users that have installed the application a long time ago didn't ask for contacts' perm when they authorized the app (it wasn't in the OAuth scope yet). This PR detects 403s on contacts fetch and displays a popin for the user to renew authorization with the good scope.
=> Added a 'permissions required' popin to the sharing modal

src/sharing/ShareModal.jsx, src/sharing/components/recipient.styl, src/sharing/share.styl
The menu to revoke a sharing participant is a pain in the ass. It was not positioned quite right and had some issues on tablet, this PR fixes these problems.
=> Share modal access

package.json, src/photos/components/Topbar.jsx, src/photos/components/UploadButton.jsx, src/photos/ducks/albums/components/AlbumPhotos.jsx, src/photos/ducks/albums/components/AlbumToolbar.jsx, src/photos/ducks/albums/components/AlbumsToolbar.jsx, src/photos/ducks/albums/components/AlbumsView.jsx, src/photos/ducks/albums/index.js, src/photos/ducks/timeline/components/Timeline.jsx, src/photos/ducks/timeline/components/Toolbar.jsx, src/photos/reducers/index.js, src/photos/styles/toolbar.styl, src/photos/styles/topbar.styl, yarn.lock
Don't merge until we have https://github.com/cozy/cozy-client/pull/116 and a new version of cozy-client!
- I moved the title of the pages to the cozy-bar on mobile view, that was relatively easy.
- I also moved all the menus toolbar there
- The toolbar menus now use cozy-ui menu's
- Once renderer inside the cozy-bar, the components get the cozy-bar contact, so any HOC that relies on context won't work. To workaround this, I had to pass the Toolbars instance of `t`, `router`, and move some sharing code around
=> Photos: title and menus in the cozy bar

package.json, src/sharing/__tests__/state.spec.js, src/sharing/components/Recipient.jsx, src/sharing/index.jsx, src/sharing/state.js, yarn.lock
With this PR, we now rely on the recipient index (from the stack) to revoke a recipient. A cozy-client new version is needed.
=> Fixed recipient revocation

src/drive/styles/filelist.styl
Force background-image's size so devices with some different screen DPI don't enlarge the icon.
Fixes #1147
=> fix(FileList): leaking default image image preview

src/drive/web/modules/drive/Toolbar.jsx, src/lib/react-cozy-helpers/BarContextProvider.jsx, src/lib/react-cozy-helpers/index.js
This fixes our problem of components not showing up in the cozy-bar — more context can be found here : https://github.com/cozy/cozy-bar/issues/144#issuecomment-425138507
=> fix: Provide full context to bar components

package.json, targets/drive/mobile/main.jsx, targets/drive/web/main.jsx, targets/drive/web/public/main.jsx, targets/drive/web/services.jsx, yarn.lock
fix the issue when fetch was not defined. It's the case at least on iOS 9. 
I don't know why we didn't encountered it before, we certainly had one dependency installing it, and since an update it's not the case anymore.
=> fix: add whatwg-fetch

src/authentication/src/steps/SelectServer.jsx
And in this case, cozy-client throws an error, we have to catch it and treat it as not an error ;)
=> fix: We can now cancel the OAuth registration process. 

src/drive/styles/filelist.styl
Tagging @GoOz just in case it's of interest to you: in firefox, the file list in a modal was taking up all it's height instead of being scrollable. This change fixes the problem, and I haven't seen any other consequences on desktop or mobile, in Chrome, Firefox or Safari.
=> fix(ModalFileList): Firefox overflow bug in modal

src/components/Error/Oops.jsx, src/components/Error/oops.styl, src/drive/lib/upgradePouchDatabase.js, src/drive/mobile/lib/cozy-helper.js, src/drive/mobile/lib/replication.js, src/drive/mobile/modules/replication/sagas.js, targets/drive/mobile/main.jsx
When we're telling PouchDB to use the `sqlite` adapter on iOS, it starts using it right away. The documents are eventually replicated, but the indexes are missing and that's why we're seeing an error.
We now check for missing indexes, and recreate them if they are missing. The good news is it fixes the problem in all cases, even people having only done a partial migration. the problem is that the app will still show an error message the first time it is loaded, and will need a view change or restart to get the new indexes. But I don't see a better way to handle the situation :/
=> Websql migration corrections

src/components/Button/CozyHomeLink.jsx, src/drive/web/modules/public/PublicToolbar.jsx
The button is rendered in the cozy bar, so it still doesn't have the right context.
See https://github.com/cozy/cozy-bar/issues/144 for discussions on a long term solution.
=> fix(PublicLink): Translate button label

src/drive/mobile/modules/mediaBackup/duck/index.js, src/drive/mobile/modules/settings/components/MediaBackup.jsx
When switching to `False`, we `cancelMediaBackup` and force settings to be set to `false` by adding a new param to the function. 
This is because of https://github.com/cozy/cozy-drive/blob/master/src/drive/mobile/modules/mediaBackup/duck/index.js#L266
=> fix: Stop synchro params

src/photos/styles/topbar.styl, targets/photos/web/public/App.jsx
On mobile, on this view, we display a custom header, but it was broken.
=> Public album view on mobile

src/drive/web/modules/navigation/breadcrumb.styl
The z-index was conflicting with the cozy-bar, but we only need such a high z-index when the breadcrumb menu is open — and when it's open, the cozy-bar is hidden.
=> fix(Breadcrumb): z-index position

targets/drive/web/public/main.jsx
It works on some views because the bar automatically goes into public mode when the URL contains `/public`… but not on all the views.
=> fix: Force bar to be in public mode

targets/drive/web/services.ejs
The intents will try to get the bar with the host application React, error prone and unecessarry since we don't use the cozy-bar for the intents.
=> Remove unecessary and error prone bar from intents

src/viewer/styles.styl
Some cleaning in preparation for a future [release of Cozy-UI](https://github.com/cozy/cozy-ui/pull/641) with color variables as CSS custom properties.
~I couldn't test it because I could make Photos works.~ It works fine :)
~⚠️ Meanwhile if your Photos apps works well, you should consider testing it locally before merging.~
=>  fix: Don't use color var in stylus func

src/photos/ducks/clustering/consts.js, src/photos/ducks/clustering/metrics.js, src/photos/ducks/clustering/service.js, src/photos/ducks/clustering/service.spec.js, targets/photos/services/onPhotoUpload.js
The reachabilities are the distance between 2 photos temporally adjacent. This will be useful later to determine how to clusterize the photos.
=> Compute reachabilities between photos

targets/drive/web/services.jsx
Offline for services was originally enabled for offline-search. However the search doesn't use the offline database anymore. We have no immediate plans to migrate back to it, and in the meantime the offline part is problematic on safari mobile browser where it tends to fail.
=> fix: Disable offline for services

src/photos/ducks/albums/index.js
Filter the albums on the `auto` fields to anticipate the ones created as clusters.
The `indexFields` is useful to avoid the `auto` field to be automatically indexed, which would prevent the albums without this field to enter the index.
=> feat: Do not query auto albums

src/drive/targets/mobile/config.xml
When reseting our iOS App, we have some encoding issues (cf https://github.com/kelvinhokk/cordova-plugin-localization-strings/issues/34) 
So we use our fork with the fix
=> fix(drive/Mobile): IOS utf8 issue

src/photos/ducks/clustering/albums.js, src/photos/ducks/clustering/settings.js, src/photos/targets/services/onPhotoUpload.js
This updates the setting after a clustering, i.e. the period on which the parameters are used, the sequence number to keep track of the _changes, and a counter to trigger the computing of new params (this will come later).
=>  feat: update setting 

src/photos/ducks/clustering/consts.js, src/photos/ducks/clustering/knn.js, src/photos/ducks/clustering/service.js, src/photos/ducks/clustering/service.spec.js, src/photos/ducks/clustering/utils.js, src/photos/targets/services/onPhotoUpload.js
Some large dataset performed badly for the parameters estimation because of noise data (in this context, 2 photos taken in distant dates). 
We fix that by adding a `MAX_DISTANCE` constant, beyond which a distance is not used for the computation.
=> feat: use a MAX_DISTANCE for outliers

src/drive/styles/filelist.styl
I use `+small-screen()` selector, it seems to match mobile resolutions
=> fix(Sharings): Remove underline on path on hover

src/drive/targets/browser/index.jsx, src/lib/initHelper.js
This is just a POC to have access to the React Dev Tools panel. 
But I want to discuss about a more global subject.
We've several entry points with Drive / Photos and we need to do the same thing several times. 
How can we have some kind pf mutualisation here? Should we create a DriveWrapper to wrap IconSprite / devtools and so on?
PS : If you want to crash your browser, do not hesitate to enable React dev tools highlights :D
=> feat(Drive): Require DevTools during DEV

src/drive/web/modules/public/LightFolderView.jsx, src/drive/web/modules/public/PublicToolbar.jsx
We were using the react router to open URLs on the public page, but:
- [we don't always have a router in the public page](https://github.com/y-lohse/cozy-drive/blob/share-redirect/src/drive/targets/public/index.jsx#L93)
- `router.push` is meant for routes that are part of the app, but here we redirect to completely different pages, so `window.location` is more appropriate
=> fix: Redirect on public pages

.travis.yml, package.json, scripts/downcloud.js, yarn.lock
This PR uploads the app as it is in a pull request to downcloud. Later we'll be able to use the URL of the archive to install the app on a cozy and run tests on it.
It's very similar to what we do in a regular `deploy` step, except we're not creating a release.
=> Upload PR code to artefact server

.travis.yml
no need to 'install' firefox, just adding it in option was enough before (and that's what the [testcafe-travis tutorial](https://devexpress.github.io/testcafe/documentation/continuous-integration/travis.html) recommend)
=> chore(travis) : Add firefox for testing photos

package.json, yarn.lock
This commit is exactly what we wanted : https://github.com/souporserious/react-measure/pull/118/files ;) 
We should be able to run our photos tests on chrome now
=> fix: Upgrade react-mesure to fix resizeObserver loop

src/viewer/Viewer.jsx, src/viewer/Viewer.spec.js
The `class` attribute will report `text` even for complex text formats like docx etc. I added mime type detection to narrow the file formats we display using the viewer, even though it can probably handle more than that.
=> fix: Make the textviewer handle less files

src/photos/components/UploadButton.jsx, testcafe/tests/drive_sharing.js, testcafe/tests/pages/drive-model.js
- fix(testcafe): remove line break in breadcrumbEnd
When running the original test, breadbrumb was `Drive > folder....` on my computer, but `Drive\n > folder...` on thomas's. So I remove all line break from breadcrumb before using it. => This is a temporary fix, I'll need to check with Thomas to understand where the `\n`is coming from.
Also add more robust waitForLoading, so breadcrumbs don't break
- fix(drive): change Selector (seems I forgot to publish the uploadbutton fix before)
- fix(testcafe) : Add wait(3000) for download 
This fix is need for tests to pass. It will be removed after https://trello.com/c/IZfev6F1/1658-drive-public-share-impossible-de-t%C3%A9l%C3%A9charger-le-fichier is fixed
=> fix(testcafe): breadcrumb and downloads

testcafe/tests/pages/drive-model.js
When deleting current folder, I can't use the getBreadcrumb methods, so I need to remove line break when using `partialBreacrumbStart`
=> fix(testcafe): breadcrumb in 'delete folder'

package.json
As `cordova` prefers our package.json instead of our config.xml, we need to remove it during the clean
=> fix: Prepare should also rm package files

.travis.yml
It will skip builds when pushing to other branches as they are building the same things that the pull requests, and slow down the other builds.
=> chore: Build on travis for PRs and push on master

src/drive/web/modules/navigation/Breadcrumb.jsx
When clicking on a folder, we want to navigate to the folder, but we also need to stop event progation to avoid "opening" the breadcrumb and thus capturing the next click to close it.
=> fix: Stop event propagation on breadcrumb

jest.config.json, src/photos/ducks/albums/__snapshots__/index.spec.js.snap, src/photos/ducks/albums/index.jsx, src/photos/ducks/albums/index.spec.js
When the request album is not found (because it has been deleted, or the id is wrong, or some other reason), we don't want to render it.
=> fix: Don't crash when album is not found

src/photos/ducks/albums/index.jsx, src/photos/ducks/albums/index.spec.js
I previously [removed a spreaded `props`](https://github.com/cozy/cozy-drive/pull/1466/commits/c799b9cb0c817ed9a2d3c90fcdfa6d42cc978097#diff-b99860e2348055cdd5e05388380200ddL149) — most of it is react-router stuff that is unnecessary, but the `children` prop is important as it is used to render the photo viewer / photo picker.
=> fix: Show album photos

src/authentication/MobileRouter.jsx, src/authentication/MobileRouter.spec.jsx, src/authentication/__snapshots__/MobileRouter.spec.jsx.snap
I think we could improve these tests, especially the ones that check mismatching secrets and states, by returning something testable from the function in MobileRouter. Maybe the error ?
=> tests: Automatic login in MobileRouter

.travis.yml
=> chore: Match tag branches starting with a "v"

src/drive/mobile/lib/filesystem.js, src/drive/targets/mobile/config.xml
It should fix the problem with have on iOS with our offline files. 
We don't need to `encodeURIComponent` anymore. 
See https://github.com/pwlin/cordova-plugin-file-opener2/issues/14
=> fix(OfflineFile): Upgrade fileOpener2 and remove encodeURIComponent

src/photos/targets/public/App.jsx, src/photos/targets/public/App.spec.jsx, src/photos/targets/public/__snapshots__/App.spec.jsx.snap
Any idea for relevant tests? Shallow-rendering snapshot gives:
```
<div>
<Main
className="u-pt-1-half"
>
<Selection />
<IconSprite />
</Main>
</div>
```
…which is pretty useless. And I don't think deep-rendered snapshot are very useful to catch regressions.
=> fix: Viewer on public album

src/photos/ducks/clustering/albums.js, src/photos/ducks/clustering/utils.js, src/photos/targets/services/onPhotoUpload.js
If new photos impact existing clusters, we need to be able to re-compute them efficiently. 
This PR deals with files having a referenced cluster (auto-album) and the building of a Map to associate clusters with existing and new photos.
=> Use existing photos in clustering

src/authentication/MobileRouter.spec.jsx, src/authentication/__snapshots__/MobileRouter.spec.jsx.snap, src/authentication/src/utils/onboarding.js
I'm not sure why, but in some cases the redux store does not have the default `onboardingInformations` set, and when that happens the auth module crashed.
=> fix: Safer way to check if auth should start

src/components/Button/CozyHomeLink.jsx
Changed the link to create a Cozy from the public sharing page to a button style (but it's still a link).
I hope I didn't miss any other link but according to the code it seems like this is it.
That was a very hard task to do for a morning task 😫 *`</sarcasm>`*
=> fix: Public page link as a button

.travis.yml, src/drive/targets/mobile/README.md
Only upload an APK when a `[APK]` tag is present in the last commit message.
=> chore: Only build APK when requested

src/components/Button/CozyHomeLink.jsx, src/components/Button/getHomeLinkHref.jsx, src/components/Button/getHomeLinkHref.spec.js, src/drive/web/modules/public/PublicToolbar.jsx, src/photos/targets/public/App.jsx, src/photos/targets/public/__snapshots__/App.spec.jsx.snap, src/photos/targets/public/index.styl
I should have seen it… That was too easy.
Here, now the button is hidden on mobile and a new `MenuItem` with the same action is added on Album sharing and the button is properly displayed when in cozy-bar on Drive as well.
NB: `getHomeLinkHref` function has been extracted to be properly called in any other context.
=> fix: move creation button to menu on mobile

package.json, testcafe/runner-photos.js, testcafe/tests/helpers/comment-on-github.js, testcafe/tests/helpers/utils.js, testcafe/tests/helpers/visualreview-utils.js, testcafe/tests/photos/photos_end_delete_all_data.js, testcafe/tests/photos/photos_start_upload_photos.js, yarn.lock
For each fixture in testcafe : I create a new VisualReview Object, so https://visualreview.cozycloud.cc/#/ will have 2 projects (Photos and Drive), and one suite for each fixture.
Each time we launch the test, a new run will be created in the suite.
I only check each run once, when all screenshots are uploaded.
----
Also, I'm using the fixture/tests name quite a lot : 
- to declare the fixture/test
- in console.log to provide infos
- to create the visual review object
- to name my screenshots
testcafe doesn't have a prop like test.name , so I think I'll use const like
`const FIXTURE_UPLOAD= 'Uploads Photos'`
`const TEST_UP_1 = 'Uploads 1 Photos'`
etc... and use those const to name my fixtures/test/screenshots/etc....
What do you think is best : 
declare each const in the scenario file …
=> Visual Review : Upload screenshots, and get testcafe to fail if not accepted

src/photos/ducks/timeline-clusters/dates.js, src/photos/ducks/timeline-clusters/index.jsx
**Context**: the stack stores photos' datetime with its own timezone, UTC+00 for our infra.
However, this creates an offset if the user's locale is not the same. Typically with a UTC+02 timezone, 2 hours will be "added" to all photos on the front side when we create the date with `new Date(date)`.
This is particularly obvious when there are several cluster for the same day, as we show the hour. 
This PR fixes this behavior by using the constructor `new dates(year, month ...)`, as the arguments are interpreted as the local time, as stated [here](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Date#Param%C3%A8tres)
=> fix: Dates timezone

src/authentication/src/LinkManager.jsx, src/authentication/src/Revoked.jsx, src/authentication/src/steps/SelectServer.jsx, src/components/Image/ImageLoader.jsx, src/drive/lib/reporter.js, src/drive/lib/upgradePouchDatabase.js, src/drive/mobile/lib/background.js, src/drive/mobile/lib/intents.js, src/drive/mobile/lib/media.js, src/drive/mobile/lib/replication.js, src/drive/mobile/modules/mediaBackup/duck/checkCorruptedFiles.js, src/drive/mobile/modules/mediaBackup/duck/index.js, src/drive/mobile/modules/offline/duck.js, src/drive/mobile/modules/replication/sagas.js, src/drive/mobile/modules/settings/duck/reducers.js, src/drive/store/persistedState.js, src/drive/targets/public/index.jsx, src/drive/web/modules/drive/rename.js, src/drive/web/modules/move/MoveModal.jsx, src/drive/web/modules/navigation/RealtimeFiles.jsx, src/drive/web/modules/navigation/duck/actions.jsx, src/drive/web/modules/navigation/duck/async.js, src/drive/web/modules/public/PublicToolbar.jsx, src/drive/web/modules/upload/index.js, src/drive/web/modules/viewer/FilesViewer.jsx, src/photos/ducks/albums/index.jsx, src/photos/ducks/upload/index.js, src/sharing/components/ShareByEmail.jsx, src/sharing/components/ShareByLink.jsx, src/viewer/TextViewer.jsx
I'm tired of seeing so much warnings when linting ;).
I removed some, for others I just disable the check since I think they can be useful on Sentry.
What do you think?
=> chore: Remove eslint warning by removing console or disable-next-line

scripts/downcloud.js
add TRAVIS_BUILD_ID to version number to help our friend in infra to know why the stack failed to deploy ou zip sometimes
=> fix: add TRAVIS_BUILD_ID to version number

src/sharing/components/Avatar.jsx
We're not using this avatar at the moment, and it relies on importing `Tooltip` from cozy-ui but that component [doesn't exist yet either](https://github.com/cozy/cozy-ui/pull/648).
=> chore: Removed unused code

src/components/pushClient/Banner.jsx, src/components/pushClient/Button.jsx, src/viewer/NoViewer/CallToAction.jsx
To be able to override a file from webpack, we need to use a relative path from `src` folder. We already have an alias for that : `drive`.
=> fix: Use relative path from src

src/drive/web/modules/drive/FileOpenerExternal.jsx, src/drive/web/modules/drive/FileOpenerExternal.spec.jsx
- Component is not unmounted when switching back to other app 
- it's better to use `routeParams` than `router.params` since it's an abstraction and is up to date even if something went wrong 
- react-router v3 doesn't expose render props, right? I wanted to have only props.fileId but... 
- Is there a way to mock   `await cozy.client.files.statById(id, false)` in a test?
=> fix: Fetch file when props have changed

package.json, testcafe/runner-drive.js, testcafe/runner-photos.js, testcafe/tests/helpers/utils.js, testcafe/tests/pages/drive/drive-model-private.js, testcafe/tests/pages/drive/drive-model.js, yarn.lock
=> Fix: testcafe running with new cozy-bar

src/viewer/ImageViewer.jsx, src/viewer/PdfJsViewer.jsx, src/viewer/PdfJsViewer.spec.jsx
Most notably on iOS, it was not possible to pan inside a zoomed pdf. This is because somehow, the swipe and pan handlers defined on the ViewerControls kept intercepting regular touch events even though they shouldn't.
The fix I propose is to disable these event handlers when we are zoomed into the pdf.
=> Panning the pdf viewer

testcafe/tests/drive/public-viewer-feature.js, testcafe/tests/helpers/visualreview-utils.js, testcafe/tests/pages/drive/drive-model-private.js, testcafe/tests/pages/drive/drive-model.js, testcafe/tests/pages/photos-album/album-model.js, testcafe/tests/pages/photos-albums/albums-model.js, testcafe/tests/pages/photos/photos-timeline-model.js, testcafe/tests/pages/viewer/viewer-model.js, testcafe/tests/photos/photos_start_upload_photos.js
With this PR the screenshots will be a bit different from before so CI will failed until they are set as new baseline, and we have to wait to merge to do that, other wise, other PR will fail because of screenshots! 
New screenshots : 
- When uploading files, now, we wait 10s, then reload to avoid thumbnail problem : https://visualreview.cozycloud.cc/api/image/21707
- Because of this reload, the "upload div" can't be seen, So I added a screenshot on this component only : https://visualreview.cozycloud.cc/api/image/21704
=> fix: change screenshots when uploading files (thumb problems)

src/viewer/controls.styl
This fixes a regression that I introduced while refactoring the viewer's css. Most viewers were using a flex direction of `row` so I kept it like that, but I missed the fact that the `ImageViewer` used `column` to make sure the image inside doesn't overflow.
With the new layout, it doesn't actually matter for the other viewers whether the direction is `row` or `column` since there's only one child element anyway. So we can now use `column` everywhere 🏛
=> fix: Photo scales in viewer

testcafe/tests/pages/photos-album/album-model.js, testcafe/tests/pages/photos-albums/albums-model.js, testcafe/tests/pages/photos/photos-timeline-model.js, testcafe/tests/pages/viewer/viewer-model.js
fix error : 
```
ClientFunction execution was interrupted by page unload. This
problem may appear if you trigger page navigation from
ClientFunction code.
```
=> fix: fix error 'ClientFunction execution was interrupted by page unload'

package.json, yarn.lock
I don't know why, but with the latest version of the bar, the current app on a public page is well displayed 
Found out: https://github.com/cozy/cozy-bar/commit/e44d8d314623fabac9eca17e0d513ab67612fa97#diff-65077881c2a917dcc5fe0fcbbf8a3658
Also fix cursor item on the current app
=> fix: Upgrade cozy-bar

src/viewer/TextViewer.jsx
After the viewer refactor, the text viewer was a bit too low on the page.
=> fix: Reduce text viewer padding

package.json, yarn.lock
Should solve the blank page on Settings.
In fact sometimes realtime can go to onSocketClose and we have no event to detect that. The fix was to be more defensive on realtime side. See https://github.com/cozy/cozy-libs/pull/378
=> fix: Upgrade realtime

scripts/create-deploy-test.sh, scripts/delete-instance.sh, scripts/rundeck.sh
Add a check on `instance already exists` in error log. 
If that case : delete instance, and re-create it.
This should stabilize our build process
=> chore: delete and retry if instance already exists

src/drive/mobile/lib/__mocks__/cozy-helper.js, src/drive/mobile/lib/cozy-helper.js, src/drive/mobile/modules/authorization/DriveMobileRouter.jsx, src/drive/mobile/modules/authorization/sagas.js, src/drive/targets/mobile/InitAppMobile.jsx
- Since cozy-client is injected, we do not need to refresh token from the bar 
- /settings/disk-usage doesn't check the expired token...
=> fix: Do not cozy bar refreshToken. Use route expired token

src/drive/web/modules/navigation/RealtimeFiles.jsx, src/drive/web/modules/navigation/RealtimeFiles.spec.jsx
If the context has a change, we unsuscribe the socket and registrer it again with the new information
=> fix: Update RealTime when context token change

testcafe/runner-drive.js, testcafe/runner-photos.js
`ClientFunction execution was interrupted by page unload. This
problem may appear if you trigger page navigation from
ClientFunction code.` 
This issue seems to be relative to temporary path, and memory on the CI
https://github.com/DevExpress/testcafe-react-selectors/issues/109
Some seems to have solve this issue by using ` --disable-dev-shm-usage` on chrome (https://github.com/DevExpress/testcafe/issues/3608), so let's try it out
=> fix: add --disable-dev-shm-usage option to chrome

src/photos/styles/toolbar.styl
Delete album action should be red, importing the palette in `toolbar.styl` does the trick
Same as in https://github.com/cozy/cozy-drive/pull/1572
=> Fix delete album action color

src/drive/mobile/modules/settings/components/About.jsx, src/drive/web/modules/filelist/File.jsx
There is an underlying bug, but this is a quick fix. 
React was bugged at some point, but it seems that was fixed long time ago (https://github.com/facebook/react/issues/5719)
=> fix: Defensive Code

src/drive/styles/filelist.styl, src/drive/web/modules/filelist/FileListBody.jsx
Since our rewrite of the FileRow component, we had an issue affecting our Android build. 
It seems that the content of the FileRow is too big for the space. I didn't find why for the moment, but an overflow hidden, hide the problem. 
This fix is not done via CSS because `fil-content-body` class is also used in the `MoveModal` and it works perfectly there.
=> fix: FileList 'border' on Android

testcafe/tests/pages/viewer/viewer-model.js
For now, there a no specific hover when navigating in the viewer.
Now, it happens like this : 
- choosing a starting file/photos
- open the viewer, and check there is a next file
- navigate to next file
- hover the **previous** button (which brings us back to the file we opened)
- take screenshots
Same thing when navigating to previous image, we will hover the **next** button.
So 1st screenshots will fail as for now, there were no arrow
=> fix: add hover on arrow in viewer navigation

src/drive/styles/filelist.styl, src/drive/web/modules/filelist/FileListBody.jsx
from @GoOz : "sinon le SVG est inline est donc il a une "marge" correspondante à une hauteur de ligne et ça augmente sa taille, et donc ça pousse de 1px les ligne sans que ça se voit."
=> fix: Android scroll bar issue

app.config.js, src/components/Button/index.styl, src/drive/targets/browser/index.jsx, src/drive/targets/mobile/index.jsx, src/drive/targets/public/index.jsx, src/photos/targets/browser/index.jsx, src/photos/targets/public/index.jsx
There are some differences in css orders when we build the app for production, but using the transpiled version of cozy-ui solves the problem.
See https://github.com/cozy/cozy-ui/issues/335 for the original issue.
=> fix: Use transpiled version of cozy-ui

src/drive/targets/mobile/InitAppMobile.jsx, src/drive/targets/mobile/index.jsx
The styles are already imported in the other file, and the `__DEVELOPMENT__ ` wasn't used anymore.
=> fix: Remove duplicated lines

testcafe/runner-drive.js, testcafe/runner-photos.js
Fix error : 
`The file at
"/home/travis/build/cozy/cozy-drive/reports/2019-04-16_15-06-05/test-2-1
Check viewer for zip file-errors/1.png" already exists. It has just been
rewritten with a recent screenshot. This situation can possibly cause
issues. To avoid them, make sure that each screenshot has a unique path. If
a test runs in multiple browsers, consider including the user agent in the
screenshot path or generate a unique identifier in another way.`
=> fix: change error screenshots path

testcafe/runner-drive.js, testcafe/runner-photos.js, testcafe/tests/drive/classification_scenario.js, testcafe/tests/drive/public-viewer-feature.js, testcafe/tests/pages/commons.js
Screenshots are not commented.
Now, I check the toast exists, and then that it doesn't exist anymore, and then take the screenshots.
The **ClassicationScenario/3-5 Empty Trash** is a bit different:
Because there are 2 toast when emptying the trash : `Your trash is being emptied. This might take a few moments.'` and `The trash has been emptied.`. Those toast sometimes shows up at the same time, one on top of the other. Sometimes the 1st one appears, then disappear, then the 2nd one appears. So we don't have a fix order of appearance/disappearance.
So I just wait for the 2 toasts to show up, then wait 5s to be sure they both disappear, then take the screenshot.
=> fix: remove toast from screenshots

testcafe/runner-drive.js, testcafe/runner-photos.js, testcafe/tests/drive/classification_scenario.js, testcafe/tests/drive/file_sharing_scenario.js, testcafe/tests/drive/folder_sharing_scenario.js, testcafe/tests/drive/navigation.js, testcafe/tests/drive/public-viewer-feature.js, testcafe/tests/drive/viewer-feature.js, testcafe/tests/pages/photos/photos-timeline-model.js, testcafe/tests/photos/album_sharing_scenario.js, testcafe/tests/photos/create_empty_album_scenario.js, testcafe/tests/photos/create_full_album_scenario.js, testcafe/tests/photos/photos_crud.js, testcafe/tests/photos/photos_end_delete_all_data.js, testcafe/tests/photos/photos_start_upload_photos.js
Photos crud scenario was already split into 3 scenario : Upload photos, photos crud, and Delete Photos.
For each one:
- Add const for test names and logs
- change `initVR` to `ctx.vr.start()`
- change name for existing screenshots
- add new screenshots
- move `checkAllImagesExists` to avoid error when reloading page
- change test `open random photos, not 1st nor last` to `open 2nd photo` , beaucse we need to open the same photos each time when taking screenshots
=> feature: Add screenshots to photos crud scenario

src/drive/web/modules/drive/FileOpenerExternal.jsx
The `FileOpenerExternal` isn't wrapper in a `Router` component when used as an interapp service.
=> Embeded viewer without router

src/drive/styles/main.styl
Since we use `cozy-bar` >= 6, we don't need this anymore
=> fix: Remove unnecessary style

src/components/Menu/index.jsx, src/components/Menu/index.styl
This reverts commit da6707c8000e31c7e6c03adf591c493aff2efdaa.
We need to keep the menu in the DOM so the upload event can fire.
=> Revert "refactor: Don't display items if menu is not opened"

package.json
I think we do not need this dep anymore since eslint-config-cozy-app has the dep https://github.com/cozy/cozy-libs/blob/master/packages/eslint-config-cozy-app/package.json
=> chore: Remove eslint-config-prettier

testcafe/tests/photos/photos_crud.js
I need to validate the screenshot for `photos : PhotosCrud 1- Photos Navigation` as it will be the good picture this time
=> fix: open 2nd photo, not random

testcafe/tests/drive/public-viewer-feature.js
I  forgot to add the mask the correct way.
I'll delete the baseline for `drive : PublicViewerFeature 3- Cleanup Data` in order to get the new mask
=> fix: add missing mask

src/sharing/components/EditableSharingModal.jsx
Takes only contacts that don't have `trashed` attribute or for which `trashed` is `false`
=> fix: Don't allow user to share to a trashed contact

src/viewer/PdfJsViewer.jsx
We were passing the wrong prop to the fallback component.
=> fix: Properly display pdf fallback

src/sharing/components/ShareRecipientsInput.jsx, src/sharing/components/ShareRecipientsInput.spec.jsx, src/sharing/components/__snapshots__/ShareRecipientsInput.spec.jsx.snap
We need contacts to be able to display groups correctly and to be able to get the contacts from the group on click.
=> Don't display groups in recipients until all contacts are loaded

package.json
We need `cozy-doctypes==1.44.1` to have the latest Contact/Group models and proptypes
=> chore: Upgrade cozy-doctypes to 1.44.1

src/sharing/SharingDetailsModal.jsx
We removed `getDisplayName` function from `sharing/index.jsx` so now, we need to use `Contact.getDisplayName` for this.
=> fix: Use Contact.getDisplayName

app.config.js, jest.config.json, jestHelpers/mocks/pdfjsWorkerMock.js, package.json, src/viewer/PdfJsViewer.jsx, src/viewer/PdfJsViewer.spec.jsx, yarn.lock
The first commit is self-explanatory i think.
For the second one: when importing from `react-pdf/dist/entry.webpack`, react-pdf loads a webworker that it creates through a webpack configuration. This worker is created at the root of the webpack output, and because this file is already transpiled, we can't change that (or at least I didn't manage to).
So the solution is to load the worker through *our* webpack configuration, so we can change the output directory.
=> Public viewer fix

jest.config.json, src/drive/appMetadata.js, src/drive/lib/doctypes.js, src/drive/lib/reporter.js, src/drive/mobile/lib/cozy-helper.js, src/drive/mobile/modules/settings/components/FeedbackForm.jsx, src/drive/targets/browser/index.jsx, src/drive/targets/intents/index.jsx, src/drive/targets/public/index.jsx, src/photos/appMetadata.js, src/photos/targets/browser/index.jsx, src/photos/targets/public/index.jsx, test/jestLib/json-transformer.js
So that `CozyClient` can use those infos to add `cozyMetadata` on contacts it creates.
There are several `CozyClient` instantiations in cozy-drive (mobile, photos, public, ...), we probably need to add those infos everywhere?
=> Add appMetadata and contacts doctype version to CozyClient

src/sharing/components/ShareAutosuggest.jsx, src/sharing/components/ShareByEmail.jsx, src/sharing/suggestionMatchers.js, src/sharing/suggestionMatchers.spec.js
We can use the cozy url to share documents to users with a cozy but without email, The stack will find the email to send the notification. It also handles contacts that have a cozy in groups.
=> Share with cozy url

src/models/Contact.js, src/models/Contact.spec.js
When Bob shares a document to Alice and Alice look at this document's sharings in her cozy's, Alice's cozy may only have the recipient's emails to display the avatar of the recipients. This PR fixes this use case.
=> fix: Use email if public_name and name are not available

package.json, testcafe/tests/helpers/logger.js, yarn.lock
Using log-prefix to add timestamp to testcafé log. 
I choose to use `toTimeString` to display the date-time in format ` [14:23:45 GMT+0200 (CEST)]`
This can be [change to any date format ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Conversion_getter)
Maybe `toISOString` is better because more precise (`[2019-05-09T08:58:50.487Z]`), but I think it's less readable
=> Testcafe : add timestamp in log

src/sharing/components/ShareByEmail.jsx, src/sharing/components/ShareByEmail.spec.jsx
If recipient has no email (sharing by cozy url for example), use cozy url. If it has no email and no cozy, use the generic success message.
Refactoring: added a `getSuccessMessage` method and tests.
=> fix: Use cozy in success message if contact has no email

src/sharing/components/ShareByEmail.jsx, src/sharing/components/ShareByEmail.spec.jsx, src/sharing/components/ShareModal.jsx
Compare new recipients email/cozy to the current recipients email/cozy to display the number of new recipients in the toast
=> feat: Display real new recipients count in toast

src/drive/locales/en.json, src/models/Contact.js, src/models/Contact.spec.js, src/sharing/components/Recipient.jsx
- if sharing has been done by url, we may only have the member's `public_name`
- also add a default values for initials and display name if name, public_name or email are not available (for sharing members for whom sharing has been done by url and that have not yet accepted the sharing)
=> Fix getDisplayName and getInitials

src/sharing/components/ShareByEmail.jsx, src/sharing/components/ShareByEmail.spec.jsx
Since https://github.com/cozy/cozy-drive/pull/1652 has been merged, we can't use `this.props.currentRecipients` in `getSuccessMessage` because in this case, it uses the updated prop to count the new recipients. Thus, we "save" the currentRecipients before the promises are resolved and it's all good.
=> fix: Don't take currentRecipients from props in getSuccessMessage

testcafe/runner-photos.js, testcafe/tests/helpers/data.js, testcafe/tests/pages/photos-album/album-model.js, testcafe/tests/pages/photos-albums/albums-model.js, testcafe/tests/pages/photos/photos-timeline-model.js, testcafe/tests/photos/album_sharing_scenario.js, testcafe/tests/photos/create_empty_album_scenario.js, testcafe/tests/photos/create_full_album_scenario.js, testcafe/tests/photos/photos_end_delete_all_data.js
Ready for review (but I close this PR during my holidays)
There are new screenshots (which don't have a baseline yet) in this scenario, you can check VR : photos : **CreateFullAlbumScenario 1- Create Full Album** : https://visualreview.cozycloud.cc/#/8/72/1117
Also, 2 new screens for **photos : PhotosDelete 1- Delete Photos** : https://visualreview.cozycloud.cc/#/8/65/1119
~~Screenshots in **photos : AlbumSharingScenario 2- Go to public link and download files :** https://visualreview.cozycloud.cc/#/8/51/1118 changed because I now remove, then re-upload some photos in the **CreateFullAlbumScenario**, but I can avoid thoses changes by changing the order tests run.~~ Tests order changes to avoid screenshots changes
=> Testcafé Album full : New steps and screenshots

src/photos/targets/public/index.jsx
As we're on a public page, we should init the bar in public mode
=> fix: Init bar isPublic on public page

src/drive/lib/doctypes.js, src/drive/lib/extraDoctypes.js
To be able to customize the client's schema without overriding the `doctypes.js` file, we introduce an empty `extraDoctypes` object. It will allow us to override doctypes in the schema without having to change the customizations schema each time we change something in Drive
=> feat: Add extraDoctypes to ease customization

src/drive/styles/coz-bar-size.styl, src/drive/web/modules/navigation/breadcrumb.styl, src/drive/web/modules/upload/styles.styl, src/drive/web/modules/viewer/barviewer.styl
I deleted a variable that seemed unused, but the file was `required` elsewhere, and stylus doesn't complain about undefined variables.
=> Breadcrumb fix

src/drive/mobile/lib/__mocks__/cozy-helper.js, src/drive/mobile/lib/cozy-helper.js, src/drive/targets/manifest.webapp, src/drive/targets/mobile/InitAppMobile.jsx
The mobile app uses the same permissions as the web app, so we need email permissions for both.
Arguably, we don't need the mobile specific code anymore..? Should we remove [this](https://github.com/cozy/cozy-drive/blob/master/src/drive/mobile/lib/cozy-helper.js#L26) and everything that goes with it, or leave it as a backup?
=> fix: Request email permissions for the webapp

package.json, src/authentication/src/steps/ButtonLinkRegistration.jsx, src/drive/locales/en.json, src/drive/web/modules/drive/Toolbar/components/UploadItem.jsx, src/drive/web/modules/drive/Toolbar/toolbar.jsx, src/drive/web/modules/layout/Layout.jsx, src/drive/web/modules/navigation/duck/actions.jsx, src/drive/web/modules/upload/Dropzone.jsx, src/drive/web/modules/upload/UploadButton.jsx, src/drive/web/modules/upload/UploadQueue.jsx, src/drive/web/modules/upload/index.js, src/drive/web/modules/upload/index.spec.js, src/lib/flags.js, src/sharing/hoc/withSharingState.jsx, src/sharing/state.js, src/sharing/state.spec.js, yarn.lock
Handle conflicts when we upload a file via :
- Import files button in toolbar
- Import files action in action menu
- dropzone
Uses `handle-conflicts` flag to activate the feature.
Note that we need `sharingState` to be able to know if a file is shared (if a file is shared, user can't update it). To do this, we use a `withSharingState` HOC and pass the `sharingState` directly to the `uploadFiles` action creator. We could use the same `mapDispatchToProps` in `UploadButton` and in `Dropzone` or even the whole `compose(...)` function to avoid duplication, WDYT?
=> Upload conflict

testcafe/tests/drive/viewer-feature.js, testcafe/tests/pages/drive-viewer/drive-viewer-model.js
Change private viewer scenario in order to check one file for each viewer type (instead of checking all of the 25 files uploaded) in order to reduce CI time.
Now time to build drive and run tests is around ~21min while before this PR and #1679 it need around ~30min
=> refacto: viewer private & public scenario

src/components/pushClient/Banner.jsx
`<p>` HTML tag cannot contain block elements like `<figure>`, it triggers a DOM warning in some browsers console, hence the `<div>` replacement.
See #991 
This PR is not about using UI component plz ;)
=> chore: Replace p by a div since we now have figure child

src/components/pushClient/Banner.jsx
We don't want to use `setState` on an unmounted component.
=> fix: Don't use setState if unmounting

testcafe/tests/drive/classification_scenario.js, testcafe/tests/drive/clean-data.js, testcafe/tests/drive/file_sharing_scenario.js, testcafe/tests/drive/folder_sharing_scenario.js, testcafe/tests/drive/init-data.js, testcafe/tests/drive/navigation.js, testcafe/tests/drive/public-viewer-feature.js, testcafe/tests/drive/search.js, testcafe/tests/drive/viewer-feature.js, testcafe/tests/pages/drive-viewer/drive-viewer-model-public.js, testcafe/tests/photos/album_sharing_scenario.js, testcafe/tests/photos/create_empty_album_scenario.js, testcafe/tests/photos/create_full_album_scenario.js, testcafe/tests/photos/photos_crud.js, testcafe/tests/photos/photos_end_delete_all_data.js, testcafe/tests/photos/photos_start_upload_photos.js
Now, all resize operations are done at the begining of a test (or in `beforeEach`), so if a mobile view test fail, the risize will still happend
=> fix: Put t.maximizeWindow() at the begining of test

testcafe/tests/drive/file_sharing_scenario.js, testcafe/tests/drive/folder_sharing_scenario.js, testcafe/tests/pages/drive/drive-model-public.js, testcafe/tests/pages/photos/photos-model-public.js, testcafe/tests/photos/album_sharing_scenario.js
We have troubles with the `more` menu not opening, or not closing when expected.
Instead of
- opening the menu
- checking all selectors for both buttons
- clicking on 1st button
- re-open more menu without selector checks
- clicking on the 2nd button
I change the script to : 
- open the menu 
- checking selector for 1st button
- clicking on 1st button
- checking the menu is closed
- open the menu 
- checking selector for 2nd button
- clicking on 2nd button
As we cannot reproduce manually the open/close issue, I reduce the 'click speed' while clicking on the more button (https://devexpress.github.io/testcafe/documentation/test-api/actions/action-options.html#click-action-options) to emulate a more 'human' way of clicking.
while running tests locally it really improve stability on theses …
=> Fix: Create cozy button not working

testcafe/runner-drive.js, testcafe/runner-photos.js, testcafe/runner.js
Vérifier si les résultats de tests sur travis sont plus stables et cohérants en lancant un runner par scenario au lieu d'un seul runner jouant tous les scénarios
=> fix: Launch each tests in a different runner

testcafe/tests/drive/file_sharing_scenario.js, testcafe/tests/drive/folder_sharing_scenario.js, testcafe/tests/drive/public-viewer-feature.js, testcafe/tests/drive/viewer-feature.js, testcafe/tests/helpers/data.js, testcafe/tests/helpers/utils.js, testcafe/tests/photos/album_sharing_scenario.js
- Remove delay before checking for downloads.
- Add a loop to check for file every 10ms. Error will be throw if the file still not exist after `DOWNLOAD_DELAY`
- increase `DOWNLOAD_DELAY` to avoid false error as we don't have to wait the whole delay anymore
=> fix: Remove wait(DOWNLOAD_DELAY) from checkLocalFile

testcafe/tests/drive/search.js
searching for `a` or `tes` made the screenshots in the tests scenario unstable, as they return more than 10 results, with the same "score", which cause them to show up in a random order. 
So I change the search request : 
We know search for : 
- `at`, then add `i`
- `cozy`, then add ` pho`
- `tes im`
- `qwerty`
I'll run this PR twice on CI to get the new screenshots, and validate them (the screenshots are named based on the search request, so they won't conflict with the ones already on master)
=> fix: Change searched words in search scenario

src/drive/web/modules/upload/UploadButton.jsx, src/photos/components/UploadButton.jsx
We have to empty the value of the input[type=file] so that the user can upload the same file twice. If the input is uncontrolled, it leads to a strange behavior because nothing happens
=> fix: Empty input[type=file] so that the user can upload the same file

src/photos/targets/manifest.webapp
The photos app needs the permission on io.cozy.files for the PATCH verb to allow moving photos to the trash.
=> Update photos permissions

src/components/Image/ImageLoader.jsx
Do not try to load remote asset when we know we are not online. It results on an infinite loop and freezing the app
=> fix: Don't try to load remote asset if offline

src/drive/styles/toolbar.styl
We had a condition to display or not the upload item if we are in a shared menu (ie we already have a primary action button) or not. But with this condition, if we are in a shared menu, we didn't have the upload item anymore. 
The current fix is to display the upload button anytime in the more menu.
=> fix: Always display upload item

package.json, src/photos/ducks/selection/index.jsx, src/sharing/context.js, yarn.lock
I think create-react-context was there for historical reason. Since we use React now, we can use it from React directly
=> refactor: Use createContext API from react, not from third packages

package.json, src/photos/ducks/clustering/consts.js, src/photos/ducks/clustering/files.js, src/photos/ducks/clustering/settings.js, src/photos/ducks/clustering/utils.js, src/photos/ducks/timeline-clusters/dates.js, src/photos/targets/services/README.md, src/photos/targets/services/onPhotoUpload.js, yarn.lock
This improves the overall performances of the clustering, by: 
1. Requesting new files with an index instead of the changes
2. Use cursor-based pagination for albums
3. Use a bigger files batch limit, as allowed by the 2 previous improvements (1000 vs 200)
On tests performed on my local machine, the clustering performed 6x faster on a large dataset (+5k photos).
=> Improve clustering performances

src/photos/ducks/timeline-clusters/dates.js, src/photos/ducks/timeline-clusters/index.jsx
This fixes situations where non-clustered photos wouldn't be displayed in the timeline because the date section (which are days for non-clustered-yet photos) was not properly managed.
=> fix: Handle section dates

jest.config.json, package.json, src/photos/ducks/clustering/albums.js, src/photos/ducks/clustering/files.js, src/photos/ducks/clustering/reclusterize.js, src/photos/ducks/clustering/reclusterize.spec.js, src/photos/ducks/clustering/settings.js, src/photos/ducks/clustering/utils.js, src/photos/targets/services/onPhotoUpload.js, yarn.lock
This removes all references of cozy-client-js to use only cozy-client in the clustering service.
A positive side-effect  is the removal of the heavy cozy-konnector-libs dependency.
=> Use cozy-client for clustering

src/photos/ducks/timeline-clusters/index.jsx
The `⠂` character (U+2802) wasn't correctly displayed on Chrome in MacOs. It is therefore replaced by `·` (U+00B7 )
=> fix: Median dot display

src/photos/ducks/timeline-clusters/index.jsx
This allows to execute the clustering service when one goes to the `/clusters` route from Photos. This will be used for testing only and will be eventually removed.
=> feat: Run clustering from client

src/drive/web/modules/move/MoveModal.jsx
indexing by dir_is first since we're looking for files in a specific dir_id. The order of the indexes are very important 
See: https://docs.cozy.io/en/cozy-stack/pouchdb-quirks/#indexing-more-than-one-field
> Furthermore, the order in which fields are indexed on a multi-index is significant, most notably when it comes to sorting.
=> feat: Use a better index

src/photos/ducks/clustering/consts.js, src/photos/ducks/clustering/setting.spec.js, src/photos/ducks/clustering/settings.js, src/photos/targets/services/onPhotoUpload.js
We used to store the period of the photos concerned by a set of parameters, to be able to know which photos' period were clustered with which set of parameters, to retrieve the correct parameters for new photos (e.g. the photo with the datetime 2019-02-01 will be clustered with the params having a `period` between 2019-01-01 and 2019-03-01).
Additionally, we kept track of how many new photos were clustered since the last re-evaluation of params, to start a new params recomputing when  `evaluationCount > EVALUATION_THRESHOLD`.
However, this was not efficient, because `evaluationCount` was incremented for each new photo, even though the datetime was not necessary newer than the last params period, while a new params recomputing will only be on photos newer than the last params period, …
=> feat: Improve parameters recomputing

src/photos/ducks/clustering/consts.js, src/photos/ducks/clustering/utils.js, src/photos/ducks/clustering/utils.spec.js, src/photos/targets/manifest.webapp, src/photos/targets/services/onPhotoUpload.js, src/photos/targets/services/onPhotoUpload.spec.js
There is currently a rate limit for the thumbnails jobs creation, set to [5000 per hour](https://github.com/cozy/cozy-stack/blob/master/pkg/limits/rate_limiting.go#L102-L107). This limit will be reached if one runs the clustering service with more than 5000 photos, as the writes on io.cozy.files triggers the thumbnails jobs.
Therefore, we use `@in` triggers to postpone the next service execution and save the last execution date to avoid running anything by this time (in case there are new uploaded photos ).
=> feat: Use @in triggers to postpone next service

src/drive/web/modules/public/LightFolderView.jsx
We forgot to pass `onFolderOpen` on the public view. 
This resolves the bug when, being on a public page, we can not navigate through folders from the breadcrumb
=> fix: Pass onFolderOpen props to breadcrumb

src/photos/ducks/clustering/consts.js, src/photos/ducks/clustering/utils.js, src/photos/ducks/clustering/utils.spec.js, src/photos/targets/manifest.webapp, src/photos/targets/services/onPhotoUpload.js, src/photos/targets/services/onPhotoUpload.spec.js
This activates the clustering service, by using the real trigger condition, i.e. when a new photo is uploaded. However, we only run it for a fixed 5% of instances, in order to make a progressive deployment ; we plan to increase this % progressively.
=> feat: Activate service for % of instances

src/photos/ducks/clustering/consts.js
No problem has been noticed with the current 5% of instances having the clustering service ; therefore we increase to 25%.
=> feat: Increase percent of instances having clustering

src/sharing/state.js
We have some sentry reports telling us that sometimes `sharedPaths` is undefined. It should not occurs since we have a default state. 
I'm suspecting that, if the stack call is failing, we set an undefined stuff in this var. but I'm not sure. 
This is not a real fix, but : 
- I check if the var is undefined, and add a log 
- I try to log when we set something in the state to see if my previous assumption is right 
see: https://trello.com/c/fBZoFLfV/1733-partage-%C3%A9cran-blanc
=> fix: Don't crash if no sharedPaths

src/photos/ducks/clustering/consts.js, src/photos/ducks/clustering/utils.js, src/photos/ducks/clustering/utils.spec.js, src/photos/targets/services/onPhotoUpload.js
This removes the code responsible for a progressive deployment of the clustering service. Therefore, it enables the service for 100% of instances. 
Note that a more generic approach will be implemented in the future on the stack side, to allow progressive/targeted deployment of features.
=> feat: Allow service execution for all instances

src/photos/styles/addToAlbum.styl
Ça devrait résoudre le souci de build de Photo depuis une upgrade de cozy-ui (https://travis-ci.org/cozy/cozy-drive/jobs/595608157#L395) 
Par contre, ça veut dire que : 
- avant quand on faisait @require cozy-ui ça importait tout, dont $modal. 
- certainement u'on devrait retirer l'import de ui
=> fix: Build issue

src/drive/web/modules/filelist/File.jsx
We should not be able to open / view a file when we're in `selection mode`. 
- Before the prop was read during the didmount() and not during the callback 
- Also, we had a proptypes for `selectionModeActive` but this props was never passed... So added the HOC
=> fix: Don't open file/folder when selection isActive

src/drive/web/modules/upload/index.js, src/drive/web/modules/upload/index.spec.js
We're only defining `error` if `conflict` resulting of having our `if error` not being executed. 
Added a test to cover this case
=> fix: Quota on upload

src/photos/components/Layout.jsx, src/photos/ducks/albums/components/AlbumPhotos.jsx, src/photos/ducks/timeline/index.jsx, src/photos/ducks/upload/index.jsx, src/photos/locales/en.json
- Dispatch a quotaAlert when needed 
- Add <ModalManager at the root of the layout since it can be called from every where 
- Should use `QuotaAlert` from UI (see https://github.com/cozy/cozy-ui/pull/1218 but let's do that in an other PR when merged) 
- Disk usage should be in cozy-client (see https://github.com/cozy/cozy-client/issues/553)
=> feat: Display QuotaAlert when needed

src/drive/web/modules/filelist/FileListRows.jsx
We added recently this div to be able to scrollToTop when we change between forlder and we play with the size of the thumbnails. 
But it appaers that we have a small overflow on this div causing a bug when the user try to scroll on the FileList since this div was catching first the scroll then scrolled for a few pixels... Having an overflow hidden seems to fix the issue.
As I can't reproduce on my smartphone, let's wait to see if it fix the bug on eric/ben's phone
edit: confirmed by ben, it works ;)
=> fix: Scroll issue on chrome / android

src/drive/web/modules/drive/Container.jsx
To fix the native shared menu, I used the `url` attribute of
cordova social plugin. It works great but only with one file, so
instead of having an error, let's hide this functionnality if we
select more than one file
=> fix: iOS shared action

src/drive/targets/browser/index.jsx
I was trying to use cozy-client in the bar by making a query. But since I was instancing cozy-bar before making client.setStore in Drive, I had this error and I didn't know what to do.
thanks to @ptbrowne, I now know that, when you call a query before setting a store, cozy-client creates by itself its store. So calling setStore later throws an exception.
https://github.com/cozy/cozy-client/pull/568
=> fix: Calls order between cozyClient setStore and cozy-bar init

src/components/pushClient/supportUs.styl
add bottom margin, specially needed if we don't hav e the "Desktop pushClient button" since this one give us margin...
=> fix: Add margin-bottom to SupportUS button

src/drive/targets/mobile/config.xml
The used keyboard plugin brings us a few issues mainly this one:
when we open the keyboard and then close it, we couldn't scroll
anymore.
At the begining we use this keyboard for the auth page in order
to shrink the view and let a few buttons on top of the keyboard
on iOS. We created a PageLayout for that, and we need to use it
for cozy-auth (https://github.com/cozy/cozy-libs/issues/872)
By removing this keyboard, we can scroll anytime :)
=> fix: Remove keyboard plugin

src/drive/mobile/modules/upload/index.jsx
We need to use history.replace() instead of history.push() since we can go back on Android with the back button. And in that case, we go back to the ImportModal. This is not what we want.
Thanks @Gara64 for the bug report ;)
=> fix: Replace for back button on Android

src/drive/web/modules/drive/files.js, src/drive/web/modules/drive/files.spec.jsx, src/drive/web/modules/navigation/FileExplorer.jsx, src/drive/web/modules/navigation/FileExplorer.spec.jsx
Since Notes app doesn't handle sharing at the moment, we don't want top open the note in Notes if the file is note created on my cozy (aka the file is shared with me). If the file is shared, then we display the markdown in the viewer.
=> feat: Don't open Note on Notes if not mine

src/drive/targets/browser/index.jsx, src/drive/targets/intents/index.jsx, src/drive/targets/mobile/InitAppMobile.jsx, src/drive/targets/public/index.jsx, src/drive/web/modules/drive/StyledApp.jsx, src/drive/web/modules/navigation/AppRoute.jsx, src/photos/components/AppRoute.jsx, src/photos/components/StyledApp.jsx, src/photos/targets/browser/index.jsx, src/photos/targets/public/index.jsx
In a previous commit, I was importing CSS in `AppRoute` component. But this component is not loaded when we are in a public context. I created a `StyledApp` which only import styles / css
=> fix: Create StyledApp component to inject CSS and style

src/drive/targets/mobile/config.xml
Since we need to have access to Crypto API on the browser, we have to drop iOS 10 support. See https://github.com/cozy/cozy-stack/pull/2310
=> feat: Drop iOS 10 support

package.json
Was used by the SharingModal (https://github.com/cozy/cozy-drive/pull/816) but since sharing was moved in its own lib let's remove this ref. 
(also since we don't target edge 16 anymore, we don't need this polyfill at all)
=> refactor: Remove url-polyfill dep

src/drive/locales/en.json, src/drive/targets/mobile/InitAppMobile.jsx, src/drive/web/modules/drive/Toolbar/share/ShareItem.jsx
was part of 1.20 release and forgot to backport 
close https://github.com/cozy/cozy-drive/pull/1958
=> Cherry pick

src/drive/web/modules/filelist/fileopener.styl
Using flex comes with a few drawback and we only want them on Edge 18, not on all the browsers. 
I know this fix is not optimal since we have a small alignment issue on Edge 18, but I don't see how I can fix it without editing the all table. @y-lohse any idea is welcomed!
=> fix: Use display contents when supported. Use flex when not

src/drive/web/modules/upload/IconDropZone.jsx
Icon was renamed to cloud a long time ago
=> fix: Dropzone used a no longer existent icon

src/drive/web/modules/upload/index.js, src/drive/web/modules/upload/index.spec.js
I made a mistake and merged while the PR was still in the red. After
introduction of the "progress" property in the upload redux slice,
some tests needed an update.
=> tests: Fix upload redux slice tests after "progress" introduction

src/drive/web/modules/upload/index.js
uploadFile's options need to be defaulted
In case of directory upload, uploadFile is called without the
onUploadProgress callback
=> fix: Error while uploading directory

src/drive/web/modules/upload/index.js, src/drive/web/modules/upload/index.spec.js
We added this check before having the file's revisions. Now that the file's history is now live for a few months now, we can remove this check and let the stack handling the update.
=> feat: Since we now have revisions, let's remove this check

package.json, yarn.lock
Through cozy-ui update
This should fix the problem below:
=> fix: Upload queue misalignment

src/drive/web/modules/drive/Container.jsx
We don't want to display "Move" or "Qualify" if we don't have write access on the folder / file.
=> fix: Don't display those new actions if no write access

src/drive/web/modules/layout/FolderView.jsx
One more forgotten item. 
We're working on writing down the functional behavior for each case (combinaison between view (ie recent / shared/.. and "item" (folder, file, url) and "context" (writeAccess etc)). In the meantime, when working again on our Cozy-Client migration we need to take into account this issue.
=> fix: Don't allow drag and drop if no write access

jest.config.json, package.json, src/drive/mobile/modules/settings/components/__snapshots__/Unlink.spec.jsx.snap, src/drive/web/modules/drive/Toolbar/components/ShortcutCreationModal.jsx, src/drive/web/modules/drive/Toolbar/components/ShortcutCreationModal.spec.jsx, src/drive/web/modules/public/Actions.jsx, src/drive/web/modules/public/LightFileList.jsx, src/photos/targets/public/__snapshots__/App.spec.jsx.snap, yarn.lock
Rebasing #2017 was not straightforward and it appears I did loose a few changes in the process.
See individual commit messages for details.
=> Public view fixes

src/drive/web/modules/public/PublicToolbar.jsx
This PR temporarily disables the notes creation from the public page. After the note is created, we need to redirect to the public page of the note (with a sharecode in the URL), but this requires some more work and we would like to publish a new version of drive before handling this.
=> feat: Disable public note creation

src/drive/web/modules/public/PublicLayout.jsx, src/drive/web/modules/public/PublicLayout.spec.jsx
The `Alerter` component on the public page did not receive a `t` function, which means that all calls to `Alert.xxx` had to be done with a translated string, eg. `Alert.info(t('error'))` and not `Alert.info('error')`.
We still have several calls to `Alert.xxx` that are in redux dispatch calls where getting an instance of `t` is not so easy. This PR makes sure we pass a valid `t` function to `Alerter`.
=> fix: Translate all public alerts

src/drive/targets/public/index.jsx, src/drive/web/modules/public/LightFolderView.jsx, src/drive/web/modules/public/LightFolderView.spec.jsx
The navigation on the public view uses `/files/:folderId` format, whereas the private app uses `/folder/:folderId`. This trips up some internal functions like [getFolderUrl](https://github.com/cozy/cozy-drive/blob/master/src/drive/web/modules/public/LightFolderView.jsx#L102).
This PR makes both public and private app use the same format. This solves 2 problems:
1. Navigating on the public view changes the URL, meaning you can use the browsers back button etc
2. Reloading the content of the view actually reloads the currently displayed folder, and not the first opened folder
=> Public navigation fixes

src/drive/lib/RouterContext.jsx, src/drive/web/modules/navigation/AppRoute.jsx, src/drive/web/modules/views/Drive/index.jsx, src/drive/web/modules/views/Drive/useActions.jsx
The last action that needed to be fixed with the migration to cozy-client was the "File History" one. It doesn't use cozy-client, but the format of the action definition has changed.
It used to be a `mapDispatchToProps`, and the history action was using `ownProps.router` to push a change of route. This wasn't necessarily a good thing because:
a) Accessing `ownProps` in `mapDispatchToProps` is discouraged
b) The component that needs the actions needs to have access to the router props, but it's not obvious by looking at the component. This is even truer now where [this component](https://github.com/cozy/cozy-drive/blob/master/src/drive/web/modules/views/Drive/FileWithActions.jsx) would need a `withRouter` call just to use `useActions`
To avoid injecting and passing around the router props, …
=> [cozy-client-migration] History action

jest.config.json, src/drive/mobile/lib/background.js, src/drive/mobile/modules/mediaBackup/duck/fixBackupFolderNamesBug.js, src/drive/store/configureStore.js, src/drive/store/connectedRouter.js, src/drive/store/connectedRouter.spec.js, src/drive/store/rootReducer.js, src/drive/targets/browser/index.jsx, src/drive/targets/mobile/InitAppMobile.jsx, src/drive/targets/public/index.jsx, src/drive/web/modules/actionmenu/MobileActionMenu.jsx, src/drive/web/modules/navigation/AppRoute.jsx, src/drive/web/modules/navigation/duck/actions.jsx, src/drive/web/modules/navigation/duck/hooks.js, src/drive/web/modules/navigation/duck/index.js, src/drive/web/modules/navigation/duck/reducer.js, src/drive/web/modules/queries.js, src/drive/web/modules/routeUtils.js, src/drive/web/modules/selectors.js, src/drive/web/modules/services/components/Picker/withReduxStore.jsx, src/drive/web/modules/viewer/FilesViewer2.spec.jsx, src/drive/web/modules/viewer/FilesViewerV2.jsx, src/drive/web/modules/views/Drive/index.jsx
- Uses cozy-client query for data
- Uses redux for folderId and fileId
~~Still~~ Not anymore in draft ~~since I want to fix~~, since I've addest tests for: 
I will put the sort config inside Redux I think).
I think it's already readable and I'd like some feedback on the initial changes, mainly the router state inside redux. Are we ok to continue this way ?
=> FilesViewer2

src/drive/web/modules/actions/useActions.jsx, src/drive/web/modules/actions/useActions.spec.jsx
When porting actions, we left out the tracking of the versioning view. This PR adds it back in.
=> feat: Track versioning event

src/drive/web/modules/views/Drive/RealTimeQueries.jsx, src/drive/web/modules/views/Drive/RealTimeQueries.spec.jsx, src/drive/web/modules/views/Drive/index.jsx
This PR allows to keep query results up to date by relying on the realtime connection. Ultimately I want to integrate this in cozy-client and will post there shortly with a few questions and an API proposal, but in the meantime this is a quick way to make it work in cozy-drive.
TODO:
=> feat: Update client queries in real time

src/drive/web/modules/actions/utils.js, src/drive/web/modules/actions/utils.spec.js
Downloading a single file was broken because `client.getDownloadLinkById` returns a full URL, whereas the cozy-client-js version returned the path only, without the domain name.
=> fix: Download a single file

src/drive/web/modules/drive/Toolbar/components/NotRootFolder.jsx, src/drive/web/modules/drive/Toolbar/toolbar.jsx
Here, we change the notRootfolder boolean to be positive and only assume that we are in the root folder if we have the displayedFolder.
=> fix: Assume we're in the root folder if there's no displayedFolder

src/drive/store/connectedRouter.js, src/drive/store/connectedRouter.spec.js
So far, we extracted the first router params we found into the redux store. But several routes could be matching, with different sets of params, and only the first in the list would be extracted, not necessarily matching the correct route.
With this PR, we check for the most probable route and extract those params.
=> fix: Only params from matching route  are extracted to redux

src/drive/web/modules/drive/Toolbar/toolbar.jsx
Follow up on #2046 — the `insideRootFolder` condition is better, but sadly it breaks the non-migrated version of drive. This PR is a quick fix for the legacy drive version while we finish the migration.
(From what I can see, the legacy `displayedFolder ` is not set on the first render, even in the root folder, which breaks the first render and never gives the redux store a chance to actually set `displayedFolder`.)
=> fix: Legacy toolbar display condition

src/drive/web/modules/navigation/Breadcrumb/MobileAwareBreadcrumb.jsx, src/drive/web/modules/navigation/Breadcrumb/MobileAwareBreadcrumb.spec.jsx
The back button on mobile had no `onClick` prop bound to it, so it wasn't working.
=> fix: Back button in breadcrumb

src/drive/web/modules/actions/useActions.jsx, src/drive/web/modules/actions/useActions.spec.jsx
Automatically closes the selection bar after actions are activated. In the previous version [we used to dispatch a meta field in the redux action with most actions](https://github.com/cozy/cozy-drive/blob/master/src/drive/web/modules/navigation/duck/actions.jsx#L433). I think it was a bit of a hack and wasn't very explicit. And for some actions we forgot and the bar wasn't closing.
Instead all actions are "enhanced" with the desired behavior. Alternatively, we could add the dispatch call in each action, for example if we wanted some actions *not* to close the bar.
=> fix: Close selection bar after all actions

src/drive/web/modules/trash/Toolbar.jsx, src/drive/web/modules/trash/Toolbar.spec.jsx, src/drive/web/modules/trash/components/EmptyTrashConfirm.jsx
On the migrated version, we were deleting the trash straight away instead of showing a confirmation modal.
~Still needs unit tests~
=> fix: Show confirm modal before emptying the trash

src/drive/web/modules/queries.js
Pouch needs all fields in the selector, like the other queries.
=> fix: Trash query for pouch

src/drive/targets/mobile/README.md
iOS-deploy is needed in order to make cordova run iOS command work
=> docs: added iOS deploy install command

src/drive/store/configureStore.js, src/drive/targets/mobile/InitAppMobile.jsx
Before, we were subscribing to all the store changes. resulting in a lot of localStorage write...
Now we only saveState when the app goes in background.
=> fix: Don't subscribe to Store change, but save it before closing the app

src/drive/mobile/modules/mediaBackup/duck/index.js, src/drive/mobile/modules/mediaBackup/duck/index.spec.js
We missed the "r" in "synchronized"…
=> fix: Typo in route name

package.json, yarn.lock
Avoids a throw when trying to split the root folder name.
=> fix: Upgrade cozy-client

src/drive/web/modules/filelist/File.jsx, src/drive/web/modules/selection/duck.js, src/drive/web/modules/selection/duck.spec.jsx, src/drive/web/modules/views/Recent/index.jsx, src/drive/web/modules/views/Sharings/index.jsx
The selection on the public page was slightly broken, because we used to store only file ids and get the full file object by searching in the cozy-client redux store. However due to limitations on the public page, we don't use a query and so the documents are not in the store.
Instead the selection now stores the full object instead  of just the id.
I also enabled the trash and rename actions on the Recent and Sharings view… because we can.
=> Fix selection

src/drive/targets/public/index.jsx, src/drive/web/modules/navigation/AppRoute.jsx, src/drive/web/modules/views/Public/index.jsx, src/drive/web/modules/views/Public/index.spec.jsx, src/drive/web/modules/views/Recent/index.jsx, src/drive/web/modules/views/Recent/index.spec.jsx, src/drive/web/modules/views/Sharings/SharingsFolderView.jsx, src/drive/web/modules/views/Sharings/index.jsx, src/drive/web/modules/views/Sharings/index.spec.jsx
The file versions views on Recent and Sharings were still broken, because we were accidentally passing the global `location` object to our actions instead of the `location` object provided by react-router, which includes the pathname of the current view etc.
I also had to tweak the sharing route configuration a little so that all components are in the right hierarchy — they all need to be children of `/sharing` in order for the nav  to stay active, but once inside a shared folder we want a different main route.
=> Fix versions view

src/drive/web/modules/drive/Toolbar/components/MoreMenu.jsx, src/drive/web/modules/drive/Toolbar/components/MoreMenu.spec.jsx, src/drive/web/modules/drive/Toolbar/components/ScanWrapper.jsx, src/drive/web/modules/drive/Toolbar/components/StartScanner.jsx, test/setup.jsx
We currently have a problem where the more menu in the top corner stays open after we start the cozy-scanner. This was introduced as a workaround [here](https://github.com/cozy/cozy-drive/pull/2017/files#r423532174) — the `Scanner` component needs to be rendered in order to run the scanner, but the ActionMenu closes itself after an action is selected, which unmounts `Scanner`.
So i moved `Scanner` outside of the `ActionMenu` so that it can stay in the render tree independently from the menu. However the scanner also exposes a `startScan` function that needs to be called from inside the menu. To make this function accessible, the `ScanWrapper` now renders a context provider, and the corresponding menu item is a consumer of that context. This way the scanner and the menu still work …
=> fix: Close the menu after the scanner is called

src/drive/web/modules/drive/RenameInput.jsx, src/drive/web/modules/drive/RenameInput.spec.jsx, src/drive/web/modules/filelist/FilenameInput.jsx
Files that have just been uploaded don't have a `meta.rev` field, but they do have a plain `_rev` field. Trying to read `meta.rev` was causing an error when renaming a file just after it had been uploaded.
=> fix: Rename files after upload

src/drive/web/modules/views/Sharings/index.jsx
There's a problem when deleting files on the trash view, so we want to disable this feature at the moment.
=> fix: Disable trash actions on sharings

src/photos/ducks/timeline/index.jsx
Since we upgraded Cozyclient, we forgot to update our sortBy instruction. We now need to pass an array instead
=> fix: Sort wants an array now

src/drive/web/modules/views/Drive/index.jsx
We forgot to add our DropZone component in the Drive view. Our users were not able to drag and drop a file... It fixes the issue
=> fix: Add DropZone to DriveView

src/drive/web/modules/trash/Toolbar.jsx
u-hide--mob hides all the elements less than "desktop" size (< 1024px). isMobile refers to max-width: 768px... 
see https://github.com/cozy/cozy-ui/issues/1528
=> fix: Display Empty Trash button even on "tablet"

src/drive/web/modules/queries.js
Thumbnails links have a validity of 10 minutes. So
we need to have a cache lesser than the one from
the stack. Like that, we make a new request to get
new links before the end of the previous ones.
(https://github.com/cozy/cozy-doctypes/pull/134)
=> fix: Reduce query's cache

src/drive/web/modules/drive/Toolbar/components/MoreMenu.jsx
We don't allow to download a folder on the mobile app. Let's hide this action also in the toolbar
=> fix: Don't display the download item in the toolbar on mobile

src/drive/mobile/modules/settings/Settings.jsx
The photo backup can be started from the settings view, which creates files and folders. It's useful to have the realtime listener activated on this view as well so that cozy-client stays informed of changes going on during the backup.
=> fix: Add Realtime to settings view

src/drive/mobile/modules/settings/components/SettingCategory.jsx, src/drive/web/modules/drive/MakeAvailableOfflineMenuItem.jsx
toggle is deprecated since a lot of time now. time to remove its use in Drive.
=> refactor: Remove deprecated use to Toggle and use Switch

package.json, src/components/App/App.jsx, src/drive/targets/manifest.webapp, src/drive/web/modules/filelist/File.jsx, src/drive/web/modules/filelist/FileIcon.jsx, src/drive/web/modules/filelist/FileIconMime.jsx, src/drive/web/modules/filelist/FileIconShortcut.jsx, src/drive/web/modules/filelist/FileThumbnail.jsx, src/drive/web/modules/filelist/SharingShortcutBadge.jsx, test/components/AppLike.jsx, yarn.lock
~~Draft PR, waiting on https://github.com/cozy/cozy-libs/pull/1090 and https://github.com/cozy/cozy-ui/pull/1542.~~
Updates the file thumbnails so that sharing previews are distinguishable from other types of files. The file logic has changed a bit:
- FileThumbnail is responsible for rendering FileIcon and decorating it with the appropriate badge
- FileIcon renders the correct icon depending on the file (image thumbnails, shortcut favicons or mime-type icon)
=> Sharing urls

src/drive/web/modules/drive/Toolbar/components/MoreMenu.jsx
We have a `disable` state in the toolbar that isn't honored by the more menu. The toolbar is notably disabled when the selection mode is active.
=> feat: Disable more menu in toolbar

src/drive/web/modules/views/Recent/useFilesQueryWithPath.jsx, src/drive/web/modules/views/Recent/useFilesQueryWithPath.spec.jsx
We don't want to display shared file that are in the trash in the "Sharing View"
=> fix: Don't display trashed file or folder in Sharing View

src/components/Image/ImageLoader.jsx
Since we can have new versions of a file now, we should not unsubscribe 
since we can receive several messages even after the first one
=> fix: Don't unsubscribe the realtime event

src/drive/web/modules/filelist/File.jsx
SharedStatus props can change, so memo is useless here
=> fix: Remove memo on Status

src/drive/targets/manifest.webapp
This permission should had been added in a PR but this was lost during the departure of Y.
=> fix: Add sharing permission

src/components/sharing/PublicBanner.jsx, src/drive/web/modules/views/Drive/index.jsx, src/drive/web/modules/views/Drive/useTrashRedirect.jsx
Previously, if you manually go to /folder/trashedFolder, it would
display the Drive view with all actions on the folder / files. But we
don't want that. So we redirect to the TrashView.
Also, some apps (like Notes) are redirecting to the note's folder in
Drive without checking if the note is trashed or not.
This is a Drive's responsibility to redirect at the right place.
=> feat: Redirect to trash if the folder is trashed

package.json, src/components/sharing/PublicBanner.jsx, src/drive/mobile/modules/authorization/UserActionRequired.jsx, src/drive/web/modules/views/Drive/index.jsx, src/drive/web/modules/views/Drive/useTrashRedirect.jsx, yarn.lock
Remove the use of react-markdown. Let's use snarkdown instead. It's much lighter. Also React-markdown adds a wrapper (p) we don't want in some case. 
https://bundlephobia.com/result?p=snarkdown@2.0.0 vs https://bundlephobia.com/result?p=react-markdown@5.0.2
=> fix: Use snarkdown instead of react-markdown

package.json, src/drive/lib/doctypes.js, src/drive/lib/migration/qualification.js, src/drive/lib/migration/qualification.spec.js, src/drive/targets/manifest.webapp, src/drive/targets/services/qualificationMigration.js, yarn.lock
We used to qualify files by manually setting specific attributes in the metadata, either in some konnectors, either through cozy-scanner.
We recently introduced a new API [here](https://github.com/cozy/cozy-client/pull/820) by using a qualification model that enforce new qualification rules.
This service migrates files qualified in the old way with the new qualification model.
Keep in my mind that:
* This PR needs this [fix](https://github.com/cozy/cozy-stack/pull/2743) for the permissions
* Eventually we want cozy-scanner and konnectors to use the new qualification API
* Some developer documentation should be added
=> Qualification migration service

src/drive/targets/manifest.webapp
Wildcard on io.cozy.files has been fixed recently, but
we still have issue when requesting /sharing/doctype routes
So let's add the both option, and remove the first one
when the stack is fixed
see https://trello.com/c/B7zOlZJx/876-stack-wildcard-iocozyfiles-et-sharings-doctype-iocozyfiles
=> fix: Perm issue

src/drive/web/modules/actionmenu/ActionMenuWithHeader.jsx
Since we can have folder with only a few files, the
filelist can be pretty small in height. Resulting not
having enought space to display the ActionMenu.
In order to not depend on the FileList height, we
tell the ActionMenu to be displayed in a Fixed Position
=> fix: Add Position fixed to the ActionMenu on the file list

src/drive/styles/actionmenu.styl, src/drive/web/modules/actionmenu/ActionMenuWithHeader.jsx, src/drive/web/modules/actionmenu/ActionsItems.jsx
Fix padding in header + sharing avatar position (avatar size is little bit different because of https://github.com/cozy/cozy-libs/pull/1159 not merged on "before" branch)
**Before**
**After**
=> Fix sharing avatars in mobile action menu

package.json, src/drive/targets/services/qualificationMigration.js, yarn.lock
This upgrades cozy-client in order to use [this fix](https://github.com/cozy/cozy-client/pull/832). The qualification migration service was broken because of it.
=> chore: Upgrade cozy-client

src/drive/styles/filelist.styl, src/drive/web/modules/filelist/File.jsx, src/drive/web/modules/filelist/File.spec.jsx, src/drive/web/modules/filelist/FileThumbnail.jsx, src/drive/web/modules/move/FileList.jsx, test/data.js
Dans le cadre de la synchronisation, on souhaite afficher un spinner dans certains cas (non définit ici). Pour l'instant on passe par un flag afin d'afficher ou non les lignes dans un état "en cours de synchronisation".
---
=> Add spinner for folder/file still in sync

src/photos/ducks/timeline/index.jsx
This is meant to improve the Photos' timeline query by : 
* Explicitly index `class` and `metadata.datetime` in this order, as `metadata.datetime` is an interval query and should therefore be at the end, as explained [here](https://docs.cozy.io/en/tutorials/data/advanced/#indexes-performances-and-design)
* Sort `metadata.datetime` after `class: 'image'` for the same reason
* Use a partial index to filter trashed photos, so the index will be smaller and more efficient if many photos are trashed.
=> feat: Optimize timeline query

src/drive/web/modules/filelist/FileThumbnail.jsx, src/drive/web/modules/filelist/SharingShortcutBadge.jsx, src/drive/web/modules/navigation/Index.jsx, src/drive/web/modules/navigation/Index.spec.js, src/drive/web/modules/views/Folder/FolderViewBody.jsx
refactor after cozy-client update
=> refactor: Use isSharingShortcut instead of deprecated isSharingShorcut

src/drive/lib/migration/qualification.js
The `queryAll` function will try to fetch all the documents available for
this query. Here, we want
to query a fixed number of documents, through the `limit`
parameter, hence we use the `query` function.
=> fix: Use query to limit fetched documents

src/drive/web/modules/filelist/File.jsx, src/drive/web/modules/views/Folder/FolderViewBody.jsx, src/drive/web/modules/views/Folder/syncHelpers.js, src/drive/web/modules/views/Folder/syncHelpers.spec.js
**Context** : Après une redirection suite à l'acceptation d'un partage, s'il y a de la latence, on affiche un spinner à la place du shortcut, avant que le fichier partagé arrive chez les destinataires.
**Préalablement**, pour faire ça, on vérifiait simplement s'il y avait un partage dans le context de partage, pour remplacer les shortcut par des spinner. Or on faisait ça quelque soit l'id du partage. Donc tous les shortcuts étaient remplacés par des spinner, même ceux qui n'était pas en relation avec le partage actuel.
**Maintenant** on ne remplace que le shortcut relatif au partage actuel en vérifiant pour chaque fichier, s'ils sont référencés par un partage qui est bien présent dans le contexte de partage.
=> fix: Only the right shortcut should turn into a spinner

src/drive/targets/services/qualificationMigration.js
The returned object is not the same between .query and .queryAll: there is a data object for the former but not for the later. Maybe we should change that to avoid future mistakes like this one?
=> fix: Query returns docs in data object

package.json, yarn.lock
This upgrade allows to support a new qualification case, and avoids a crash when a qualification case is not found when trying to categorize a file.
=> feat: Upgrade cozy-scanner to support new qualification

src/photos/ducks/timeline/index.jsx
We have an issue in CozyClient with this new query when using client.destroy() on this query. I don't know if it's related to partialIndex or indexFields or the selector. 
I'll create the issue on the CozyClient's side
=> fix: Revert optim query since there is a bug in CozyClient

src/drive/web/modules/certifications/CertificationTooltip.jsx
Certification icon has width 0 on firefox. The span is needed to make the tooltip working.
=> Fix certification icon width on firefox

package.json, src/photos/ducks/timeline/index.jsx, yarn.lock
This query optimization was previously [reverted](https://github.com/cozy/cozy-drive/pull/2200) because of a bug in cozy-client, which is now fixed and tested.
For more details, see the [issue](cozy/cozy-client#845)
=> feat: Re-enable partial index based query optimization 

src/photos/ducks/clustering/albums.js, src/photos/ducks/clustering/albums.spec.js, src/photos/ducks/clustering/files.js, src/photos/ducks/clustering/settings.js, src/photos/targets/services/onPhotoUpload.js
The clustering service is currently broken since a cozy-client upgrade with breaking change in the HasManyFiles relationships: 
* `insertDocuments` becomes `addReferences`
* `removeDocuments` becomes `removeReferences`
This PR:
* Fix the API change
* Add somes tests to avoid such situation in the future
* Improve the error handling to avoid hiding errors and be alerted when the service actually fails
* Fix existing queries
=> Fix clustering

src/drive/web/modules/filelist/cells/FileName.jsx
Instead of carbonCopy icon, if the file is not electronicSafe
=> fix: Show connector icon for carbonCopy certification on mobile

src/drive/styles/filelist.styl, src/drive/web/modules/filelist/cells/FileName.jsx
Les icones de certifications doivent apparaître sur mobile à côté du filepath ou de la description du fichier (date et poids)
=> Add certification icons after filepath on mobile

src/drive/targets/browser/index.jsx, src/drive/targets/intents/index.jsx, src/drive/targets/public/index.jsx, src/drive/web/modules/drive/StyledApp.jsx, src/photos/components/StyledApp.jsx, src/photos/targets/browser/index.jsx, src/photos/targets/public/index.jsx
Problème : l'utilisation de variable css cozy-ui se fait avant le chargement de la feuille de style de cozy-ui, ce qui génère une erreur et plante l'application. 
Solution : Charger la feuille de style plus tôt.
Je n'ai pas réussi à corriger le problème simplement en déplaçant les appels à `styleApp` (qui mutualise tous les chargement de feuille de style) plus tôt dans l'app. J'ai donc sorti l'appel à la feuille de style cozy-ui de `styleApp` pour le mettre plus tôt, dans tous les endroits qui faisait appel à `styleApp`.
=> fix: Inject cozy-ui css earlier in code to prevent invalid var call

src/drive/mobile/lib/media.js
**Description**
This PR is related to [this PR](https://github.com/cozy/cordova-plugin-list-library-items/pull/31).
This change sends back to the java code the asset's creation date.
**How does it work ?**
This line of code `createdDate: file['creationDate'],`, adds the asset's creation date. With this, the java code use this date to format it and send it to the stack through the headers.
For more information about this, please check out [this PR](https://github.com/cozy/cordova-plugin-list-library-items/pull/31).
=> fix: Added exif creation date of asset sent back to java

src/photos/ducks/clustering/consts.js, src/photos/ducks/clustering/files.js, src/photos/ducks/clustering/settings.js, src/photos/ducks/clustering/utils.js, src/photos/ducks/clustering/utils.spec.js, src/photos/targets/services/onPhotoUpload.js, src/photos/targets/services/onPhotoUpload.spec.js
This fixes 2 behaviors with the photos clustering service:
* The query to get the new photos to clusterize was based on `file.created_at`, which is the date from exif data (or the upload date if it does not exist): the photos with a `file.created_at` older than the last execution date were not clusterized. We now use `file.cozyMetadata.createdAt`, to always rely on the upload date.
* When the service is running, a lock is set in order to avoid parallel executions of the service. In some cases, the lock was never released, causing the service to be never run again. We add a safeguard to bypass the lock if it has been set for more than 24h.
=> Fixes for clustering service

package.json, src/drive/locales/en.json, src/drive/web/modules/viewer/FilesViewer.jsx, src/drive/web/modules/viewer/Panel/Certifications.jsx, src/drive/web/modules/viewer/Panel/PanelContent.jsx, src/drive/web/modules/viewer/Panel/getPanelBlocks.jsx, src/drive/web/modules/viewer/Panel/getPanelBlocks.spec.jsx, src/drive/web/modules/viewer/helpers.js, yarn.lock
Première étape de l'utilisation du Viewer augmenté dans Drive. On souhaite afficher des informations relatives aux certifications si le fichier visualisé est certifié.
Pour l'instant on ne gère que les certifications sur les fichiers. L'étape suivante consistera à gérer les informations relatives au connecteur.
=> Viewer : add certifications panel

src/drive/targets/mobile/index.jsx
Since https://github.com/cozy/cozy-drive/pull/2216 we've changed
the way we import UI's style. But we forgot to import the CSS
for the mobile build.
I was pretty sure to check carefully #2216 but it seems not... 🤦‍♂️
=> fix: Import UI's style for react component

src/drive/web/modules/filelist/cells/FileName.jsx
Default fetchIcon from AppIcon doesn't work when used in a mobile app context. More detail here https://github.com/cozy/cozy-ui/issues/1723
=> fix: FetchIcon works on mobile

src/photos/ducks/clustering/files.js, src/photos/ducks/clustering/settings.js, src/photos/targets/services/onPhotoUpload.js, src/photos/targets/services/onPhotoUpload.spec.js
We used to store a timestamp of the last execution of the service,
which is useful to know if the service should actually be run, depending on the 'running' and 'postponed' status.
However, this timestamp was not always set, leading to missing
information.
Therefore, we prefer to remove this timestamp and now use the
`cozyMetadata.udpatedAt` field, that we are sure is always set, as the
photo settings are updated at the beggining of the execution.
Note the doctype format should be updated accordingly: https://github.com/cozy/cozy-doctypes/blob/master/docs/io.cozy.photos.md#clustering-settings
=> fix: Missing last execution timestamp

src/photos/ducks/clustering/albums.js
This allows a more efficient query to find auto-albums as it avoids to
query on the `auto` non-indexed field
=> feat: Use partial index for auto albums

src/drive/web/modules/views/Public/index.jsx
If not, we got undefined for currentIndex when opening
the viewer. Let's set the index before opening it.
Tried to add a test on the component, but I can't
handle it since we've a react-test-lib test but
file-opener is done with HammerJS. Click will not
fire the right event... We should test our
hooks call in order to test the component
=> fix: Call the hooks in the right order

src/drive/web/modules/filelist/cells/FileName.jsx, src/drive/web/modules/filelist/cells/FileName.spec.js
Deep dependencies in useCallback seems to be a tricky usage, because it's checked on mount (unreachable prop object will crash JS)
=> fix: Remove deep dependecies in CertificationsIcons useCallback

src/drive/web/modules/queries.js
As recommended
[here](https://docs.cozy.io/en/tutorials/data/advanced/#partial-indexes),
we use partial indexes for negative queries. This is notably better to
have lighter indexes (the _id is not indexed anymore) and thus, more
efficient queries.
=> feat: Use partial index for negative queries

src/drive/web/modules/filelist/cells/FileName.jsx, src/drive/web/modules/filelist/cells/FileName.spec.js
Fix fait sur la branche release/1.32.0 validé et mergé sur la branche, mais non rappatrié sur master.
voir https://github.com/cozy/cozy-drive/commit/66891bd2681e494a3d65f641b7642e84e20a2e5a
=> fix: Remove deep dependecies in CertificationsIcons useCallback 

src/drive/web/modules/public/LightFileViewer.jsx, src/drive/web/modules/public/LightFileViewer.spec.jsx
Remove toolbar in public viewer
=> fix: Viewer in public view doesn't need any toolbar

src/drive/targets/mobile/index.ejs
Les dataset sont habituellement injecté par la stack. Ce qui n'est pas le cas sur mobile et fait que les `data-cozy-*="{{.Xxxxx}}"` reste telque et ne sont pas remplacé comme il devrait.
Et cela fait planter le `JSON.parse()` de https://github.com/cozy/cozy-ui/blob/master/react/helpers/appDataset.js#L37 `return value === undefined ? undefined : value === '' || JSON.parse(value)` car `value` vaut `{{.Xxxxx}}` dans le cas présent.
=> Fix mobile dataset

.gitignore
Un dossier `/ul_web_hooks` avec les fichier `/android/android_web_hook.html` et `/ios/links.mycozy.cloud#apple-app-site-association` sont générés au build mobile
=> chore: Add /ul_web_hooks in mobile gitignore

src/drive/locales/en.json, src/drive/web/modules/actions/index.jsx, src/drive/web/modules/actions/useActions.spec.jsx
On souhaite avoir ce comportement : 
- Le 'ouvrir avec... ' reste 'ouvrir avec...' et 'open with...' pour Android dans le menu d'action (et garde le même comportement). Idéalement c'est "Aperçu apple" pour iOS.
- Le 'send to ...' devient 'transférer vers...' / 'forward to...' dans le menu d'action (avec idéalement une icône en fonction de l'OS: android ou iOS)
- Le bouton 'dans le viewer prend alors le comportement du "send to" renommer 'transférer vers ...'/ 'forward to...' avec comme texte pour ce bouton "Transférer" et "Forward" (pour des raisons de place)
=> feat: Action menu openWith, forwardTo and sendTo label/icon

package.json, src/drive/web/modules/viewer/Footer/BottomSheet.jsx, src/drive/web/modules/viewer/Footer/BottomSheetContent.jsx, src/drive/web/modules/viewer/Footer/FooterContent.jsx, src/drive/web/modules/viewer/Footer/FooterContent.spec.jsx, yarn.lock
Sur mobile, pour les fichiers qui contiennent des informations "augmentée" (certification et konnecteur) on souhaite afficher ces informations dans un bottom sheet
La lib utilisée est https://github.com/mayteio/mui-bottom-sheet qui possède un bug https://github.com/mayteio/mui-bottom-sheet/issues/1 . Nous avons donc forké https://github.com/cozy/mui-bottom-sheet pour corriger, c'est pourquoi nous utilisons notre propre version dans l'app.
=> Add Viewer bottomSheet for mobile

package.json, src/drive/targets/mobile/config.xml
Le numéro de version android n'était plus le bon depuis la dernière version : un `0` a été rajouté à la main entre temps.
=> fix: Adjust Android version number

package.json, yarn.lock
Pour corriger ce souci : https://github.com/cozy/cozy-libs/pull/1284
Sera mergée dès que la CI est verte
=> feat: Update cozy-scanner to 1.1.1

package.json, src/components/sharing/PublicBanner.jsx, src/drive/web/modules/drive/Toolbar/components/UploadButtonItem.jsx, src/drive/web/modules/public/CozyBarRightMobile.jsx, src/drive/web/modules/public/LightFileViewer.jsx, src/drive/web/modules/public/PublicToolbar.jsx, src/drive/web/modules/public/PublicToolbarByLink.jsx, src/drive/web/modules/public/PublicToolbarCozyToCozy.jsx, src/drive/web/modules/public/SharingBanner.jsx, src/drive/web/modules/public/useSharingInfos.jsx, src/drive/web/modules/queries.js, src/drive/web/modules/upload/UploadButton.jsx, src/drive/web/modules/views/Public/index.jsx, yarn.lock
- Sur les pages publiques, on souhaite avoir la toolbar non plus en haut dans la cozybar mais entre le contenu et la banner (comme dans la partie privée)
- La bannière d'info est remaniée au passage, pour récupérer le bouton "créer un cozy" qui était initialement dans la cozybar
- On en profite pour rajouter le bouton "import de fichier" lorsqu'on a les accès écriture
=> Public toolbar and banner

package.json, src/drive/web/modules/public/LightFileViewer.jsx, src/drive/web/modules/public/LightFileViewer.spec.jsx, src/drive/web/modules/public/PublicToolbar.jsx, src/drive/web/modules/public/PublicToolbarByLink.jsx, src/drive/web/modules/public/PublicToolbarCozyToCozy.jsx, yarn.lock
⚠️ **update UI first**
suite à https://github.com/cozy/cozy-ui/pull/1784 on répercute ici les changements pour avoir un page publique avec le même comportement : à savoir une version tablette qui agit comme une version mobile.
A l'exception de la toolbar qui ne se retrouve pas en haut dans la cozy-bar, mais entre la bannière et le contenu comme sur desktop.
De plus, suite à l'ajout d'un div autour de la public toolbar, le style était cassé.
=> feat: Adjust PublicFileViewer on tablet according to the new viewer

src/drive/web/modules/viewer/Footer/FooterContent.spec.jsx, src/drive/web/modules/viewer/Footer/ForwardButton.jsx
Suite à une incompréhension, il y avait l'action "ouvrir avec" sur le bouton "transférer vers" du footer dans le viewer
=> fix: ForwardButton now forward the file instead of opening it

src/components/Error/ErrorShare.jsx, src/drive/targets/public/index.jsx, src/photos/components/__snapshots__/ErrorUnshared.spec.js.snap
Sharing error was not wrapped in `styledapp`. So the style (font & size) wasn't right.
Refactor: useI18n() instead of translate()
=> fix: Wrap Error in StyledApp

package.json, yarn.lock
Pour corriger le problème de traduction dans le bloc konnecteur du viewer augmenté, dû au fait que Drive et Harvest embarquent chacun leur propre version de Ui, et n'utilisent donc pas les mêmes contextes.
=> feat: Update cozy-harvest-lib to 5.3.1

package.json, src/drive/lib/RealTimeQueries.jsx, src/drive/mobile/modules/authorization/DriveMobileRouter.jsx, src/drive/mobile/modules/offline/duck.js, src/drive/targets/mobile/InitAppMobile.jsx, src/drive/targets/mobile/InitAppMobile.spec.jsx, src/drive/targets/mobile/config.xml, src/drive/targets/mobile/migrations/migrationOfflineFiles.js, src/drive/targets/mobile/migrations/migrationOfflineFiles.spec.js, src/drive/web/modules/actions/utils.js, src/drive/web/modules/actions/utils.spec.js, yarn.lock
Avec la sortie de Android 11, l'emplacement des fichiers sauvegardé à changé.
La config du plugin file de Cordova `<preference name="AndroidPersistentFileLocation" value="Compatibility" />` doit être remplacé par `<preference name="AndroidPersistentFileLocation" value="Internal" />`
On souhaite également gérer les fichiers qui étaient déjà pris en charge par le offline. Ces fichiers doivent être re-téléchargés dans le nouvel emplacement afin que la migration soit transparente pour l'utilisateur.
=> Add offline migration

src/drive/web/modules/views/OnlyOffice/Editor.spec.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/FileName.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/index.spec.jsx, test/data.js
see commit message
J'ai créé un nouveau fichier de test spécifique à la Toolbar pour éviter de devoir mocker ou gérer des cas inutiles liés à d'autres éléments du composant OnlyOffice, comme la vue, l'éditeur, l'instanciation du script js de l'éditeur etc.
=> fix: OnlyOffice file should not be renamable if doc is read only

src/drive/web/modules/views/OnlyOffice/View.jsx
We now show the Error view, and we remove the broken script to avoid, the next time the editor is loaded, to detect that it is present in the DOM and use it to instantiate the editor which caused an error
=> feat: Fallback to Error if something goes wrong when loading only office api

src/drive/web/modules/drive/Toolbar/share/ShareButton.jsx, src/drive/web/modules/drive/Toolbar/share/share.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/ReadOnly.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/Sharing.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/index.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/index.spec.jsx
On souhaite avoir accès au partage (bouton de partage + avatars) directement dans la toolbar de l'éditeur only office
=> feat: Add sharing avatars and button in Only Office toolbar

src/drive/web/modules/views/OnlyOffice/Editor.spec.jsx
oublie dans https://github.com/cozy/cozy-drive/pull/2338 je ne sais pas pourquoi la CI était verte pour autant...
=> test: Fix sharingContext in only office editor

src/drive/web/modules/views/OnlyOffice/Editor.jsx, src/drive/web/modules/views/OnlyOffice/Editor.spec.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/FileName.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/index.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/index.spec.jsx, src/drive/web/modules/views/OnlyOffice/View.jsx, src/drive/web/modules/views/OnlyOffice/helpers.js, src/drive/web/modules/views/OnlyOffice/index.jsx, src/drive/web/modules/views/OnlyOffice/useConfig.js, src/drive/web/modules/views/hooks.js
On récupère dans le contexte le fait que l'éditeur a terminé son initialisation. Cela permet de charger certains éléments seulement après.
=> Wait for only office editor initialisation

src/drive/web/modules/views/OnlyOffice/Title.jsx
Onlyoffice Banner display logic when comes from sharing
=> fix: Onlyoffice Banner display logic when sharing

src/drive/web/modules/views/hooks.js
We use here the same way as in useFilesQueryWithPath : while we don't have the folder id, we use Q('io.cozy.files').getByIds([]) query (that didn't trigger any error) instead of Q('io.cozy.files').getById({})
=> fix: GET https://xxx/files/%5Bobject%20Object%5D 404 in useFileWithPath

src/drive/web/modules/views/OnlyOffice/Toolbar/HomeLinker.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/Sharing.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/helpers.js, src/drive/web/modules/views/OnlyOffice/Toolbar/index.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/index.spec.jsx, src/drive/web/modules/views/OnlyOffice/useConfig.js
Lors de l'accès à une page publique, suite à un partage, on était redirigé comme s'il s'agissait d'un partage de cozy à cozy.
De plus, il y avait les boutons et avatars de partage sur les pages publiques, ce qu'on ne souhaite pas faire.
=> Fix redirection and sharing in only office Public view

package.json, src/drive/targets/public/index.jsx, src/drive/web/modules/filelist/File.jsx, src/drive/web/modules/filelist/FileOpener.jsx, src/drive/web/modules/navigation/AppRoute.jsx, src/drive/web/modules/views/Folder/FolderViewBody.jsx, src/drive/web/modules/views/Folder/createFileOpeningHandler.js, src/drive/web/modules/views/OnlyOffice/Title.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/index.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/index.spec.jsx, src/drive/web/modules/views/OnlyOffice/helpers.js, src/drive/web/modules/views/OnlyOffice/helpers.spec.js, src/drive/web/modules/views/OnlyOffice/index.jsx, src/drive/web/modules/views/OnlyOffice/useConfig.js, test/components/AppLike.jsx, yarn.lock
Lors d'un partage de cozy à cozy on reroutait en partie privée de Drive, ce qui posait des problèmes d'authentification lors de l'ouverture du document only office par le receveur d'un partage. Pour rappel, dans ce cas (partage d'un doc only office de Alice à Bob), Bob est renvoyé sur l'instance d'Alice pour ouvrir le doc, et utiliser son serveur only office.
On a également gérer le cas d'un partage d'un dossier contenant un document only office
=> Fix route for sharing only office from cozy to cozy

src/drive/web/modules/views/OnlyOffice/Toolbar/BackButton.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/FileName.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/ReadOnly.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/Sharing.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/index.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/index.spec.jsx
- suppression de l'icone home, de l'avatar et de l'icone fichier
- suppression du chemin du fichier
- nom éditable
- icone de partage à la place des avatars et bouton de partage
- cadenas simple sans texte pour une document readOnly
=> Enhanced Only Office toolbar on mobile

src/drive/web/modules/drive/Fab.jsx, src/drive/web/modules/drive/Toolbar/components/AddButton.jsx
Précédemment on avait `{...isOffline && { onClick: handleOfflineClick }}` qu'on a remplacé par `onClick={isOffline && handleOfflineClick}`.
Sauf qu'en fait avec cette approche, si la condition (ici `isOffline`) et la valeur (ici `handleOfflineClick`) sont des bool (false par exemple) toutes les deux, on se retrouve avec un `onClick={false}`.
Du coup il est préférable d'utiliser `onClick={isOffline ? handleOfflineClick : undefined}`
=> Refactor conditional onClick

src/drive/targets/public/index.jsx, src/drive/web/modules/views/OnlyOffice/Title.jsx, src/drive/web/modules/views/OnlyOffice/helpers.js, src/drive/web/modules/views/OnlyOffice/helpers.spec.js, src/drive/web/modules/views/OnlyOffice/index.jsx
On ne se basait initialement que sur le fait que le document soit public ou synchronisé. Or il est important de savoir si le document partagé est un dossier ou non.
Les tests aident à comprendre les différents cas. J'ai également mis tous ces cas dans un tableau dans le paper du partage.
=> Fix conditions to show the sharing banner on Only Office files

src/drive/web/modules/drive/Fab.jsx, src/drive/web/modules/drive/FabWithMenuContext.jsx, src/drive/web/modules/views/Drive/index.jsx, src/drive/web/modules/views/OnlyOffice/Editor.jsx, src/drive/web/modules/views/OnlyOffice/Editor.spec.jsx, src/drive/web/modules/views/OnlyOffice/ReadOnlyFab.jsx, src/drive/web/modules/views/OnlyOffice/Title.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/FileName.jsx, src/drive/web/modules/views/OnlyOffice/View.jsx, src/drive/web/modules/views/OnlyOffice/config.js, src/drive/web/modules/views/OnlyOffice/helpers.js, src/drive/web/modules/views/OnlyOffice/index.jsx, src/drive/web/modules/views/OnlyOffice/useConfig.js, src/drive/web/modules/views/Public/index.jsx, src/lib/flags.js
Sur mobile on souhaite avoir l'editeur only office en "lecture" par défaut. Dans ce mode, la toolbar de l'éditeur only office est masqué.
On ajoute également un Fab qui permet de passer en mode "écriture", ce qui remplace notre toolbar par celle d'only office.
Ce comportement est également sur desktop si le flag associé est à true.
Enfin, on a ajouté un flag qui permet de définir la hauteur de la toolbar de l'éditeur only office à masquer.
=> feat: Add Fab on mobile to switch between read-only or write mode on only office editor

src/drive/targets/public/index.jsx
Problème initial: En partageant un dossier par lien (avec accès en écriture), la personne ne peut pas uploader un fichier déjà existant dans le dossier (même nom).
Aujourd'hui le processus d'upload, en cas de conflit (409), requière `cozy-doctype`
(cf: https://github.com/cozy/cozy-drive/blob/13ff154da4f2dd71ae765437210e6cb32c40944e/src/drive/web/modules/upload/index.js#L186)
L'index public n'enregistrait pas le client via la méthode `Document.registerClient` de `cozy-doctype` comme il devrait le faire depuis l'ajout/modification du code ci-dessus.
=> fix: Allow overwriting a file from a share link

src/components/Error/Oops.jsx, src/drive/locales/en.json, src/drive/web/modules/views/OnlyOffice/Error.jsx
Si `GET /onlyoffice/fileId` return 404, on souhaite afficher une page d'erreur
=> feat: Add fallback when only office editor returns 404

src/drive/web/modules/views/OnlyOffice/Editor.spec.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/index.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/index.spec.jsx
L'éditeur Only Office est "autonome" à savoir qu'après avoir instancié l'app, le routeur de l'app redirige tout de suite sur l'éditeur. Il n'hérite donc d'aucun wrapper/provider de l'app. C'est pourquoi nous avons besoin d'ajouter le `RealTimeQueries` ici.
Due to the limitations of the public page, real time is only effective for the owner of the document. So if the recipient modifies an information, the owner receives the update. However, this is not true in the other direction.
=> feat: Add realtime on only office toolbar

src/drive/web/modules/views/OnlyOffice/helpers.js, src/drive/web/modules/views/OnlyOffice/helpers.spec.js, src/drive/web/modules/views/OnlyOffice/useConfig.js
in this case, isPublic is true because the recipient use the public access of the host to get the document. So this is not the only param to check, we need `isFromSharing` too.
=> fix: Only office username for cozy to cozy shared document

package.json, src/drive/web/modules/queries.js, src/drive/web/modules/views/Sharings/FilesViewerSharings.jsx, src/drive/web/modules/views/Sharings/index.jsx, src/drive/web/modules/views/Sharings/withSharedDocumentIds.jsx, yarn.lock
:heavy_exclamation_mark: Cette PR est liée à celle-ci sur cozy-sharing: https://github.com/cozy/cozy-libs/pull/1323
Lorsque l'on rafraichissait la page Partages avec au moins 60 fichiers/dossiers, de multiples rendus étaient effectués car le composant n'attendait pas d'avoir tous les fichiers partagés avant de les lister.
La source du problème vient de cozy-sharing qui retourne par 30 au maximum les fichiers/dossiers.
Avec la propriété `allLoaded` ajoutée à cozy-sharing, le composant peut maintenant attendre pour afficher la liste complète.
=> fix: Multiples renderers on sharings view

src/drive/targets/public/index.jsx
Previously we were relying on the "auto init" cozyclient from the bar.
But since we're not using data-cozy-token in our templates but data-cozy
this mechanism didn't work anymore.
So let's be explicit and pass the cozy client instance directly.
=> fix: CozyBar init

src/drive/targets/public/index.jsx
Since our last refacto, we created 2 conditions for the same thing. It
resulted to have wrong kind of children for `<Router />`
=> fix: Public Route declaration

src/drive/appMetadata.js, src/drive/web/modules/selectors.js, src/drive/web/modules/viewer/FilesViewer.jsx, src/drive/web/modules/views/Folder/FolderView.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/index.jsx, src/drive/web/modules/views/hooks.js, src/drive/web/modules/views/useUpdateDocumentTitle.js, src/drive/web/modules/views/useUpdateDocumentTitle.spec.js
On souhaite afficher le `<nom de l'élément> (<chemin de l'élément>) - Cozy Drive` dans le titre de la fenêtre/onglet quand on est dans l'éditeur only office.
Idem pour les vues de Drive, pour les dossiers Drive et Trash ainsi que leurs sous-dossiers.
Il reste toujours le TODO sur le hook useFileWithPath relatif à la nouvelle option 'enabled' des useQuery. Ayant déjà passé trop de temps sur cette feature, je n'ai pas réussi à utiliser cette nouvelle approche rapidement et simplement dans ce cas d'utilisation. J'ai donc repris le trick précédemment utilisée. Je compte me dégager du temps semaine prochaine pour m'en occuper.
Par ailleurs une issue est créée https://github.com/cozy/cozy-client/issues/961 par rapport à l'utilisation que j'en ai eu. Idem j'aimerai prendre le temps semaine …
=> feat: Window title updates with doc name and path

src/drive/targets/browser/setupAppContext.js, src/drive/targets/public/index.jsx, src/photos/targets/browser/index.jsx, src/photos/targets/public/index.jsx
We decided to use data-cozy={{}} to get access to
the variables injected by the cozy-stack.
By removing data-cozy-*, cozy-bar was lost since
the bar will look into cozy-data-appslug to detect
the slug of the app. Since the bar can't do that
anymore, we need to pass all the args during the
init phase.
=> fix: Pass the right arguments to the cozy-bar

src/drive/web/modules/views/OnlyOffice/useCreateFile.js
Assets are available in /onlyOffice/file.ext, not
in /onlyoffice/file.ext
=> fix: OO creation

src/drive/web/modules/filelist/FilenameInput.jsx
Previously we were splitting the filename on the latest do,
to prevent extension change.
It works well for file but not for folder. If it's a folder,
let's select the full filename
=> feat: Select the full filename if we rename a folder

src/drive/web/modules/drive/AddMenu/AddMenu.jsx, src/drive/web/modules/drive/AddMenu/AddMenu.spec.jsx, src/drive/web/modules/drive/AddMenu/AddMenuProvider.jsx, src/drive/web/modules/public/PublicToolbarByLink.jsx, src/drive/web/modules/public/PublicToolbarCozyToCozy.jsx, src/drive/web/modules/views/Public/index.jsx
- We hide the CreateNote button 
- We don't display the MoreMenu if the is no file in the folder (since the only action within the menu is "Select file" and this action is not display when there is no file...) 
- We hide the download button if there is no file to download
=> fix: Few fixes on public page

src/drive/web/modules/filelist/FileOpener.jsx
https://trello.com/c/80mmMpTV/1497-%F0%9F%93%81-drive-mobile-le-clic-long-sur-le-mobile-nenclenche-plus-une-s%C3%A9lection-de-l%C3%A9l%C3%A9ment
The "onpress" event never existed, see: https://hammerjs.github.io/recognizer-press/
It used to work in cozy-drive because "onpress" was a custom event. With the new API, we can simply use the native 'press' event.
=> fix: Update hammerjs API usage

CHANGELOG.md, src/drive/web/modules/filelist/FilenameInput.jsx
Related to https://trello.com/c/W6b1eknd/1505-%F0%9F%93%81-drive-r%C3%A9gression-1-erreur-%C3%A0-la-cr%C3%A9ation-dun-dossier
Issue: creating a directory triggered a "this folder already exists error"
Bug: FilenameInput launches two save() action if a file has no name => directory never has a name when creating one, so it will always be saved twice creating dupe error
Resolution: return the save action if the component has no name
=> fix: Remove double saving when creating directory

CHANGELOG.md, src/drive/web/modules/drive/DeleteConfirm.jsx
Related to https://trello.com/c/Oon3REW1/1500-%F0%9F%93%81-drive-ajouter-un-spinner-dans-la-modale-de-suppression
Bug: no UX feedback when deleting batch of files
Fix: useState in the confirm modal and inject busy state in the button when starting delete process
=> fix: Add busy state to delete confirm button

.prettierrc, CHANGELOG.md, package.json, src/drive/web/modules/filelist/FileOpener.jsx, src/drive/web/modules/views/Recent/index.spec.jsx, yarn.lock
Related to: https://trello.com/c/BdnfOXYA/1510-%F0%9F%93%81-drive-le-lien-sur-le-chemin-du-dossier-ne-fonctionne-pas-bien
Issues:
- note directory opens a note instead of its dir
- other files open the dir, but the preview tool when going back
Bugs:
- conflict with FileName onClick() and Link in Dir Name (link inside a link => double routing)
Resolution:
- add a guard on file opening method
=> fix: Update browser navigation on directory links

src/drive/web/modules/filelist/FileOpener.jsx, src/drive/web/modules/filelist/cells/FileName.jsx
I was wrong, FileOpener can indeed be rendered inside a link in some cases I wasn't aware of (OpenOffice sharing for instance).
To fix that, I changed the guard in FileOpener to not block at every parent link, but only at file-path parent links. It's more fragile because it's linked to the css class of the link.
=> fix: Use a more specific guard in FileOpener

src/drive/web/modules/views/Folder/FolderViewBody.jsx, src/drive/web/modules/views/Folder/createFileOpeningHandler.js, src/drive/web/modules/views/Folder/createFileOpeningHandler.spec.js
- **Issue**: Shared folder with OnlyOffice files. The user doesn't have OnlyOffice installed => Link to download the file in FileViewer is broken.
- **Bug**: missing `isOnlyOfficeEnabled()` check in `createFileOpeningHandler()`
- **Resolution**: add `isOnlyOfficeEnabled()` check as a boolean argument to `createFileOpeningHandler()` function.
=> fix: Allow users without OO to navigate to OO file

src/drive/store/configureStore.js, src/drive/web/modules/filelist/AddFolder.spec.jsx, src/lib/flags.js
redux-logger was enabled by default, even in production. This is useful
to debug, but is also quite verbose. Therefore, we disable it by
default. Note one can still use the redux brower extension to get useful
insights.
=> feat: Do not enable redux-logger by default

src/drive/mobile/modules/offline/duck.js, src/drive/web/modules/actions/utils.js, src/drive/web/modules/actions/utils.spec.js, src/drive/web/modules/upload/index.js, src/drive/web/modules/upload/index.spec.js
From the mobile app, we are now able to upload encrypted files. It is
also now possible to visualize them through the cordova `open`.
Note the direct display through the Viewer is not possible at this
moment because it requires changes in cozy-ui.
This also uses the mobile upload methods moved in cozy-client in https://github.com/cozy/cozy-client/pull/1051 instead of using the one in cozy-scanner.
=> feat: Upload encrypted files and open them, on mobile

package.json, src/components/App/App.jsx, src/drive/lib/DriveProvider.jsx, src/drive/lib/encryption.js, src/drive/mobile/modules/upload/index.jsx, src/drive/mobile/modules/upload/index.spec.js, src/drive/store/configureStore.js, src/drive/targets/browser/index.jsx, src/drive/targets/browser/setupAppContext.js, src/drive/targets/intents/index.jsx, src/drive/targets/mobile/InitAppMobile.jsx, src/drive/targets/public/index.jsx, src/drive/web/modules/drive/Toolbar/components/UploadItem.jsx, src/drive/web/modules/move/FileList.jsx, src/drive/web/modules/move/Topbar.jsx, src/drive/web/modules/navigation/AppRoute.jsx, src/drive/web/modules/navigation/duck/actions.jsx, src/drive/web/modules/upload/index.js, src/drive/web/modules/upload/index.spec.js, src/drive/web/modules/views/Trash/TrashFolderView.spec.jsx, test/components/AppLike.jsx, yarn.lock
We used to init the vault by manually creating a WebVaultClient
instance. However, this requires a URI, which is not set in mobile
context, when the user is not onboarded. This was causing a crash on the
first launch.
We fix this by using the VaultProvider, which is now capable to
automatically set the URI thanks to the given cozy-client instance.
=> fix: Init vault through provider

src/drive/mobile/lib/__mocks__/cozy-keys-lib.js, src/drive/web/modules/filelist/AddFolder.spec.jsx, src/drive/web/modules/navigation/AppRoute.jsx, src/drive/web/modules/navigation/Index.spec.js, src/drive/web/modules/navigation/duck/actions.spec.jsx, test/setup.jsx, yarn.lock
The c3bd4aa commit broke the app
because of cozy-keys-lib wrongly mocked into the AppRoute component.
Instead, we mock it in the revelant files to make the tests run.
=> fix: Wrong cozy-keys-lib mock 

package.json, yarn.lock
3.12.9 (2021-12-31)
Bug Fixes
sharing: ShareButton should not pass I18n props to Cozy-UI Button (587cd2e)
3.12.8 (2021-12-28)
Note: Version bump only for package cozy-sharing
3.12.7 => https://github.com/cozy/cozy-drive/pull/2456
=> fix(share): Remove warnings in the sharing button by upgrading cozy-sharing

src/drive/web/modules/filelist/cells/FileName.jsx
Useful when we've a long filename and not enough space
to display it
.
=> feat: Use title to display the filename

CHANGELOG.md, src/drive/mobile/lib/cozy-helper.js, src/drive/mobile/modules/authorization/DriveMobileRouter.jsx
La migration (introduite ici https://github.com/cozy/cozy-drive/pull/2399 ) entraine des cas qui ont échoué sans qu'on arrive trop à comprendre pourquoi, ce qui donne parfois des comportements étranges sur les requêtes.
Côté Pouch il semble que indexedDB ne soit pas encore prod ready
Afin de publier une version mobile de Drive, on préfère pour l'instant désactiver cette feature.
=> feat: Remove Pouch adapter migration

src/drive/web/modules/upload/Dropzone.jsx, src/drive/web/modules/upload/Dropzone.spec.jsx, src/drive/web/modules/upload/__snapshots__/Dropzone.spec.jsx.snap, test/setup.jsx
Since the changes introduced in #2441, the uploadFiles signature changed
and the DropZone component was not updated accordingly. Hence the drag
and drop feature was broken, which is now fixed.
=> fix: Drag and drop

src/drive/web/modules/upload/Dropzone.jsx, src/drive/web/modules/upload/Dropzone.spec.jsx
When uploading file, we used to have
=> fix(dropzone): invalid prop were shouting errors instead of uploading file

src/drive/web/modules/drive/AddMenu/AddMenuProvider.jsx, src/drive/web/modules/drive/AddMenu/AddMenuProvider.spec.jsx
Plenty of users complains because AddMenu button appears offline, but they are not.
We want to log exception to keep eyes on that bug.
=> feat(add): Log sentry exception on click on add menu when offline

CHANGELOG.md, src/drive/lib/dacc/dacc.js, src/drive/lib/dacc/dacc.spec.js, src/drive/lib/dacc/query.js, src/drive/targets/manifest.webapp, src/drive/targets/services/dacc.js
This service aggregates the file size by grouping them by the app/konnector
that created them.
It then sends all the measures to the DACC, an external service used to
aggregate anonymized measures, which require new remote doctype
permissions.
Note this feature is yet restricted by a flag.
=> feat: Add DACC service, to send anonymized measures.

CHANGELOG.md, src/drive/lib/dacc/dacc.js, src/drive/lib/dacc/dacc.spec.js, src/drive/lib/dacc/query.js
* Use MB instead of MiB for size
* Use `cozyMetadata.uploadedAt` instead of `created_at` for file date
=> Fixes on dacc service

CHANGELOG.md, src/drive/lib/encryption.js, src/drive/lib/encryption.spec.js, src/lib/flags.js
The query is useless if the encryption flag is not set
=> feat: Do not look for encryption when flag is not set

package.json, src/drive/web/modules/drive/Toolbar/index.jsx, src/drive/web/modules/public/LightFileViewer.spec.jsx, src/drive/web/modules/views/Drive/index.jsx, src/drive/web/modules/views/Public/index.spec.jsx, yarn.lock
- Updating cozy-bar for localdev purposes
- Inject webviewIntent into BarContextProvider because ActionMenu doesn't have access to the webviewIntent from the cozy-bar directly
- Still need to update cozy-ui once it's published
=> feat: Upgrade cozy dependencies for App Amirale navigation

CHANGELOG.md, src/photos/components/PhotoBoard.jsx, src/photos/ducks/albums/components/AlbumPhotos.jsx, src/photos/ducks/albums/components/AlbumsView.jsx, src/photos/ducks/albums/index.jsx, src/photos/ducks/timeline/components/Timeline.jsx
We need to check if lastFetch is defined to know
if we're in a fetchMore context or in the first
render.
=> fix: Fix pagination on Photos

src/drive/web/modules/navigation/Index.jsx, src/drive/web/modules/navigation/Index.spec.js
Currently, when going to drive from cozy-homepage,
the user gets stuck in an endless loop if trying to navigate backward.
This is because the app router is instantiated on a single hash,
then push the pathname after it.
An easy way to fix that is to use a router.replace,
so that way the initial hash route is deleted from the stack.
Now the user can navigate backward without any issue.
=> fix: Use replace instead of push on init router

CHANGELOG.md, src/drive/targets/manifest.webapp, src/drive/targets/mobile/README.md, src/photos/targets/manifest.webapp, webpack/drive.config.js
same url for prod/dev env, but environment var already passed
to senty https://github.com/cozy/cozy-drive/blob/master/src/drive/lib/reporter.js#L38
=> feat: Change Sentry url

CHANGELOG.md, src/drive/lib/encryption.js, src/drive/web/modules/actions/index.jsx, src/drive/web/modules/actions/index.spec.js, src/drive/web/modules/actions/utils.js, src/drive/web/modules/drive/AddMenu/AddMenu.jsx, src/drive/web/modules/drive/AddMenu/AddMenu.spec.jsx, src/drive/web/modules/drive/AddMenu/AddMenuProvider.jsx, src/drive/web/modules/drive/AddMenu/AddMenuProvider.spec.jsx, src/drive/web/modules/drive/Toolbar/toolbar.jsx, src/drive/web/modules/filelist/FileIconMime.jsx, src/drive/web/modules/move/FileList.jsx, src/drive/web/modules/selectors.js, src/drive/web/modules/services/components/iconContext.js, src/drive/web/modules/views/Folder/FolderViewBody.jsx
We do not support the following features with client-side encryption:
- Notes
- OnlyOffice
- Shortcuts
- Archive download
- Sharing
Those items are therefore disabled in the UI inside an encrypted folder.
Moreover, the regular folder creation is disabled as well, as we do not
want to allow non-encrypted files inside an encrypted folder.
=> feat: Do not display unsupported menu items inside an encrypted folder

CHANGELOG.md, src/drive/web/modules/upload/index.js
In a shared folder, the upload was broken because one does not have the
rights to GET on the `io.cozy.files.encryption` doctype.
This is a quick fix to solve the issue found in prod
=> fix: Request encryption key only when encryption flag is set

CHANGELOG.md, package.json, yarn.lock
`cozy-client` as been upgraded to to `29.1.1` to retrieve fix about
broken services from cozy/cozy-client#1180
=> fix: Upgrade `cozy-client` to 29.1.1

CHANGELOG.md, package.json, src/drive/web/modules/drive/Toolbar/index.jsx, src/drive/web/modules/public/PublicToolbarByLink.jsx, src/drive/web/modules/public/PublicToolbarCozyToCozy.jsx, src/drive/web/modules/trash/Toolbar.jsx, src/drive/web/modules/views/Drive/index.jsx, yarn.lock
WebviewIntent was not passed correctly in most cases
=> fix: Improve cozy-bar interactions

src/photos/ducks/clustering/albums.js, src/photos/ducks/clustering/files.js, src/photos/lib/onPhotoUpload.js
It appears the datetime or photos object might be undefined, leading to
unexpected errors during the service execution.
We add checks and logs to cope with this.
=> fix: Handle undefined cases

package.json, yarn.lock
This will allow to use better cozy-bar support in dev mode
=> feat: Update cozy-scripts

CHANGELOG.md, src/drive/web/modules/drive/Toolbar/components/CreateNoteItem.jsx
When in a mobile Flagship app we shouldn't rely on editing
`window.location.href` in order to trigger navigation
Instead we should call `openApp` from `cozy-intent` so the navigation
is handled on mobile app's native side
Based on 24af91284645c2eab42355ab402c868385f58326 implementation
=> fix: Call `openApp()` on note creation when in a mobile Flagship app

CHANGELOG.md, src/photos/targets/manifest.webapp
This was probably forgotten when the cozy-to-cozy sharing was removed
from Photos
=> fix: Remove useless permission on contacts

CHANGELOG.md, src/drive/web/modules/views/Folder/createFileOpeningHandler.js
When on flagship app we want to handle shortcuts as navigation instead
of opening them in new tab
By doing so we ease links interception on Flagship app, so it would be
able to decide to navigate between cozy-apps, or to open InAppBrowser
regarding the link content
Note that the previous implementation would trigger the new
`onOpenWindow` event from cozy/react-native-webview#2
But this is not enough as the provided url would be an `#/external/`
link which cannot be analysed easily. With the new implementation we
provide the final URL that can by analysed directly
___
Related PRs:
- cozy/cozy-react-native#391
=> fix: Navigate to shortcuts instead of opening new tab on Flagship app

.bundlemonrc, package.json, src/drive/web/modules/actions/index.jsx, yarn.lock
Current implementation of iOS Flagship app doesn't handle files
download correctly
So we want to temporarily disable Download button on this platform
This commit is meant to be reverted when files download is fixed on iOS
Flagship app
---
Related PRs:
- https://github.com/cozy/cozy-ui/pull/2215
---
TODO:
=> fix: Do not display Download actions on iOS Flagship app

CHANGELOG.md, package.json, src/drive/web/modules/drive/AddMenu/AddMenu.spec.jsx, src/drive/web/modules/drive/Fab.jsx, src/drive/web/modules/drive/MakeAvailableOfflineMenuItem.jsx, src/drive/web/modules/move/MoveModal.jsx, src/drive/web/modules/views/OnlyOffice/ReadOnlyFab.jsx, src/drive/web/modules/views/OnlyOffice/Title.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/FileName.jsx, src/drive/web/modules/views/OnlyOffice/useConfig.js, src/drive/web/modules/views/Public/index.jsx, yarn.lock
I forgot the TODO from cozy/cozy-drive#2672 🤦 
I also added the changelog entry that I should have done in the initial PR
---
`cozy-ui` as been upgraded to to `73.0.1` to retrieve a fix that
disable Viewer's download button from cozy/cozy-ui#2215
This commit fixes the previous commit that wrongly set the version
7c6d187c10b758015b1cbeaeeb6a958159e280c6
Related PR: cozy/cozy-drive#2672
=> fix: Upgrade cozy-ui to 73.0.1

package.json, yarn.lock
On desktop, the user can now select content
from PDF or markdown. see cozy-ui's commit
7efff3d18797c8386b8542a92e499a7fd4ec2469
=> feat(Viewer): User can now select content

.eslintrc.json, CHANGELOG.md, package.json, src/drive/web/modules/services/components/SuggestionProvider.jsx, src/drive/web/modules/services/components/SuggestionProvider.spec.jsx, src/drive/web/modules/services/components/helpers.js, src/drive/web/modules/services/components/helpers.spec.js, test/dummies/dummyFile.js, yarn.lock
By preventing every notes fetching url, loading only once a note is clicked
Last question: should we update isNote in cozy-client? (I think yes, but I will confirm)
after https://github.com/cozy/cozy-drive/pull/2663#issuecomment-1224092333
=> fix(search): Improve speed of search suggestions

CHANGELOG.md, src/drive/web/modules/public/PublicLayout.jsx, src/drive/web/modules/public/PublicLayout.spec.jsx
Currently we don't have any feedback when
uploading files on a public view. Let's
add the UploadQueue in order to give the
feedback needed.
=> feat: Add UploadQueue to the public view

src/drive/web/modules/services/components/SuggestionProvider.jsx
In production build, the number of Suggestions looks duplicated (or worst)
In order to prevent the duplicate called, we should set the fetching
indicator directly when we call indexFiles method
Before:
=> fix(Search): prevent duplicate API called when suggestions are fetched

src/drive/web/modules/services/components/SuggestionProvider.jsx, src/drive/web/modules/services/components/SuggestionProvider.spec.jsx
that commit  24c2d46d was not equivalent to previous version, now it is.
proof:
=> fix(search): Group filter calculation should use && to be equivalent

CHANGELOG.md, package.json, src/drive/web/modules/actions/index.jsx, yarn.lock
This commit is a revert from 268b46e415f90289337aa58f91480331eecc087a
and from b4fb66b184f1ad7f435f9e2c04b2a5ea6844f9f5
In previous commit we removed the Download button on iOS Flagship app
as this platform was not able to handle downloads correctly
Now that we implemented a solution to handle downloads on this platform
we can add this feature back
Related PR: cozy/cozy-drive#2672
Related PR: cozy/cozy-drive#2676
___
TODO:
=> fix: Display Download actions on iOS Flagship app

CHANGELOG.md, src/components/pushClient/index.js
This component makes request at every
render. If the user doesn't hide the
banner, the request is done every time
he/she clicks on a new view.
By adding a name and a fetch policy
we don't always make the request.
=> feat: Add cache to the clients query

src/drive/web/modules/services/components/SuggestionProvider.jsx, src/drive/web/modules/services/components/SuggestionProvider.spec.jsx
Like that, we don't have a dep between the stack
deployed and the drive version.
If the stack handles the Fields attribute then
fetch is optimized, if not, then we still got
the docs.
=> fix: Make Search backward compatible

src/photos/ducks/timeline/index.jsx
After v30.0.0 of cozy-client, select MUST include all the fields expressed in the selector and partialIndex
=> fix(photos): timeline query needs select fields to be completed

src/drive/web/modules/views/Public/index.jsx
The main should be the defilable element, in order to achieve this we need the debording Table to be the direct child of main.
=> fix(styles): Remove double elevator on file list on public pages

src/drive/web/modules/upload/index.js
Fix error: Uncaught TypeError: reduce of empty
array with no initial value
when uploading a new file.
=> fix: Reduce should always have an initial value

src/drive/web/modules/move/MoveModal.jsx
the directory io.cozy.root-dir doesn't have a name. So when we moved a file to that folder, %targetName was displayed to the user. Now, if there is no name to a directory, then we display "Drive".
```
fix: When a user moved a file to the root directory, we displayed "the file was moved to %targetName. Now we display the file was moved to Drive"
```
=> fix: Display Drive when moving to the root of the cozy

src/drive/lib/dacc/dacc.js, src/drive/lib/dacc/dacc.spec.js, src/drive/targets/manifest.webapp
We prefer a work-hours scheduling to monitor its execution
=> feat: Change @monthly DACC trigger for testing

CHANGELOG.md, package.json, src/drive/targets/manifest.webapp, src/drive/targets/mobile/config.xml, src/drive/targets/mobile/package.json, src/photos/targets/manifest.webapp
* Improvements to DACC service
* Remove double elevator on file list on public pages
* Fix issue on file upload
* Fix display when moving element to the root
* Use new DACC API
* Remove verbose mode
* Add all files for bundlemon and make it drastically sensitive
=> chore: Bump to 1.45.0

src/photos/targets/manifest.webapp
Cozy-ui's viewer needs to be able to query
konnectors and triggers in order to display
the konnector block with the status of the
konnector and the icone.
```
fix: Viewer on photo display correctly the information about the konnector if there is some to display. 
```
=> fix: Add permissions to Photos

package.json
Make android build (i.e. `yarn version:drive:androidbuild`) POSIX compliant so it doesn't requires explicitely instructing node to use bash or wrongly assume `sh` shell is `bash`.
=> chore: Make version:drive:androidbuild POSIX compliant

src/drive/web/modules/views/Recent/index.jsx
feat: Add sharing option to the Recent View. 
I just added this option as is since the sharing
modal already does the check to know if the file
is inside an already shared folder (we restrict 
the fact to share a subfolder of an already 
shared folder)
=> feat: Add sharing option to the Recent View

README.md
Disabling CSP is mandatory in dev mode with Hot Module Replacement because assets are served via webpack dev server. Without it, it displays a blank page.
=> docs: Disable CSP in dev mode command

src/drive/web/modules/views/OnlyOffice/useConfig.js
When there was a cozy to cozy sharing from Alice to Bob with a OO file, and Bob share the OO file with a public link, the public link displayed a blank page. The code to open the file on an other instance was bypassed when the file was public.
I did not understand what was the purpose of the `!isPublic` I removed with @Crash-- help, so if you have any idea of the purpose, tell me.
* A public OnlyOffice document from a cozy to cozy share is now displayed correctly
=> fix: Shared OO document displayed a blank page

src/drive/web/modules/views/OnlyOffice/helpers.js, src/drive/web/modules/views/OnlyOffice/helpers.spec.js, src/drive/web/modules/views/OnlyOffice/useConfig.js
The presence of a sharecode was used to determine if the document should be opened on other instance, but it was not sufficient. It only occured now because I updated recently the condition.
```
*
* Shared OO document displayed a blank page due to infinite loop
*
```
=> fix: Shared OO document displayed a blank page due to infinite loop

src/drive/web/modules/views/OnlyOffice/Editor.jsx, src/drive/web/modules/views/OnlyOffice/Title.jsx, src/drive/web/modules/views/OnlyOffice/config.js
The size of the OO header change between iOS and Android, so we need to adapt the size of our header for iOS and Android.
```
*
* OnlyOffice header is correctly displayed on smartphone.
*
```
=> feat: Adapt OO header in responsive for iOS and Android

src/drive/targets/manifest.webapp, src/drive/web/modules/actions/index.jsx, src/drive/web/modules/actions/useActions.spec.jsx, src/drive/web/modules/actions/utils.js, src/drive/web/modules/drive/DeleteConfirm.jsx, src/drive/web/modules/queries.js, src/drive/web/modules/views/Folder/FolderView.jsx
Previously, when you wanted to delete a photo, a delete warning was displayed every time the photo was referenced by an album. Even if the album was a cluster album which does not make sense.
```
*
* Show delete photo from album warning only when necessary
*
```
=> fix: Delete warning only when referenced by manual album

src/drive/web/modules/views/useUpdateDocumentFavicon.jsx
The class attribute of Only Office spreadsheet document is a spreadsheet. The icon type is only named «sheet». To match the two, I had a normalisation function to spread with future exception.
```
* Show the correct favicon for Only Office spreadsheet
```
=> fix(useUpdateDocumentFavicon): Show the correct favicon for Only Office spreadsheet

src/drive/web/modules/services/components/SuggestionProvider.jsx, src/drive/web/modules/services/components/SuggestionProvider.spec.jsx, src/drive/web/modules/services/components/helpers.js
URL sent to cozy-bar is now the direct OO editor URL and not the preview URL
```
* Open directly an OO file from the searchbar
```
=> fix: Open directly an OO file from the searchbar

src/drive/web/modules/views/Trash/TrashFolderView.jsx
Since we started to call useQuery() instead of reading the redux store 162aa9a8611165e094a82f447bddbcd707fdc500
We were able to call useQuery without a defined currentFolderId
Since we can't call getById() with an undefined ID ATM even with enabled to false, we need to handle that in Drive's code.
How currentFolderId can be undefined between the change of trash to recent view? Because we have a lot of re-render before moving from one view to an other. Not relying on redux is part of this effort to remove all this re-render it's a long work.
(no changelog since this is a bug introduced by a previous non released commit)
=> fix: Navigation from Trash to Recent was displaying a blank page

src/drive/web/modules/drive/Toolbar/components/CreateNoteItem.jsx
In 953e2c4e25e0c8461b9813f18599d9aa39d38bd2 we generated `returnUrl` using `generateWebLink` when a cozy-note from a Flagship app
We incorrectly inserted the origin folder's path as we used the pathname attribute instead of the hash, which would break the application on Android as the browser would try to interpret the pathname and try to load an non-existing asset. On iOS the app was loading correctly but did not navigate to the requested path
```
* Set correct returnUrl hash for note creation from Flagship app
```
=> fix: Set correct returnUrl hash for note creation from Flagship app

src/drive/web/modules/navigation/Breadcrumb/Breadcrumb.jsx
On breadcrumb open, an event listener was added. However, the event listener was not correctly removed on breadcrumb close (very likely due to a different handleClickOutside function being created).
New solution use a useEffect always cleaning itself.
```
* Back button was not working immediately after breadcrumb close
```
=> fix: Back button was not working immediately after breadcrumb close

src/drive/web/modules/services/components/SuggestionProvider.jsx
When you run the provideSuggestions function, first it run indexFiles. However, if indexFiles is not finished and you run provideSuggestions again, you can try to make a search even if the fuzzyPathSearch variable is not ready leading to an error.
@Crash-- It is linked to this commit https://github.com/cozy/cozy-drive/commit/acc29f0a116482c4adc8ecd8c7433725486f1ff6 Do you have any ideas of what were the duplication issue solved in the previous commit? Because we tried to create duplicate with this PR fix without success.
However, it is still possible to create duplicate in production (so not linked to this PR) by : 
- taping something like "tre"
- selecting tre with the mouse
- taping "tre" again
Co-authored-by: cballevre <celestin.ballevre@protonmail.com>
```
* Avoid to search …
```
=> fix: Avoid to search suggestions when files not indexed

src/drive/locales/en.json, src/drive/web/modules/actions/index.jsx
```
* Rename action "copy" to "duplicate" and change icon
```
=> feat: Rename action "copy" to "duplicate" and change icon

src/drive/targets/browser/index.ejs, src/drive/targets/public/index.ejs, src/photos/targets/browser/index.ejs, src/photos/targets/public/index.ejs
Before cozy fonts were imported with `{{ .cozyBar }}`  served from the stack. We bundle `cozy-bar` as a vendor now so we have to import fonts into index.ejs
```
* Use cozy fonts again
```
**Related PRs :**
- https://github.com/cozy/cozy-stack/pull/3638
=> fix: Use cozy fonts again

src/drive/web/modules/views/Search/SearchView.jsx
```
* Index files only once in SearchView
```
=> fix: Index files only once in SearchView

src/drive/styles/filelist.styl
It was due to action button taking too much width in mobile file list.
```
* File name took not all width in mobile file list
```
=> fix: File name took not all width in mobile file list

package.json, src/drive/date-fns/add.js, src/drive/date-fns/sub.js, yarn.lock
Since the cozy-client upgrade to 34.7.1 date-fns is a needed dep for a few of its models. But we don't need them in Drive for now and we have a few issues with the tree shaking of cozy-client.
(see https://github.com/cozy/cozy-client/pull/1274)
So the workaround is to force the resolution to date-fns 1 which is required by drive, in order to not duplicate the package.
We should not have issue with that. When we'll upgrade date-fns to v2 in drive & ui, then, we'll be able to remove this line.
=> fix: Dedup of date-fns

package.json
This command wasn't working anymore because of the `--barV7` option that is only accepted by cozy-scripts.
We also remove the unecessary `npm-run-all` as only one command is run.
```
*
*
* Fix `yarn build:photos` command
```
=> chore: Fix `yarn build:photos`

src/photos/ducks/clustering/reclusterize.js, src/photos/ducks/clustering/reclusterize.spec.js
The service is not working anymore because of the mock placed in the source file rather than the test file.
The tests were ok, but not the actual service execution...
```
*
* Photos clustering service that was unable to run
*
```
=> fix: Wrong mock make service crash

package.json, src/drive/targets/manifest.webapp, src/drive/targets/mobile/config.xml, src/drive/targets/mobile/package.json, src/photos/targets/manifest.webapp
The version 1.49.0 is used to deploy the selfhosted version so the tag v1.49.0 is already taken. That's why, I bump the version to 1.50.0 for the next release. 
```
* chore: Bump version from 1.49.0 to 1.50.0
```
=> chore: Bump version from 1.49.0 to 1.50.0

package.json, yarn.lock
The goal of the update is to have the contact page link on settings rather than open a modal
```
* Update cozy-bar from 8.13.1 to 8.14.0
```
=> feat: Update cozy-bar from 8.13.1 to 8.14.0

package.json, src/drive/targets/manifest.webapp, src/drive/targets/mobile/config.xml, src/drive/targets/mobile/package.json, src/photos/targets/manifest.webapp
We skip 1.51.0 because it's already in production to troubleshoot deployment issues
```
*  Bump version from 1.50.0 to 1.52.0
```
=> chore: Bump version from 1.50.0 to 1.52.0

src/drive/web/modules/drive/Fab.jsx, src/drive/web/modules/drive/FabWithMenuContext.jsx, src/drive/web/modules/views/OnlyOffice/ReadOnlyFab.jsx
As an user can zoom into his document, scrollbar appears under OnlyOffice FAB. We added some margin to increase visibility on OnlyOffice FAC on desktop
```
* Add extra margin on desktop for OnlyOffice FAB
```
=> fix: Add extra margin on desktop for OnlyOffice FAB

package.json, yarn.lock
Today, the buton sharedwith me is invisible. Let's upgrade cozy-sharing to use the right colors
https://github.com/cozy/cozy-libs/pull/2041
```
* The button sharedwithme has the right color.
```
=> fix: SharedWith me has the right color now

package.json, yarn.lock
Technical upgrade. Nothing for the user.
The BC is not a real one, it seems that we
have a lerna issue at that moment.
```
* upgrade cozy-realtime 
```
=> feat: Upgrade cozy-realtime

src/drive/web/modules/search/components/SuggestionItemTextSecondary.jsx
We were not passing the right informations. The path was not good.
```
* Search: Link on parent's folder is now working
```
=> fix: Link to the parent folder

.bundlemonrc, package.json, src/drive/targets/public/index.jsx, src/drive/web/modules/drive/AddMenu/AddMenu.jsx, src/drive/web/modules/drive/Toolbar/components/CreateOnlyOfficeItem.jsx, src/drive/web/modules/navigation/AppRoute.jsx, src/drive/web/modules/public/LightFileViewer.jsx, src/drive/web/modules/services/components/Embeder.jsx, src/drive/web/modules/viewer/FileOpenerExternal.jsx, src/drive/web/modules/viewer/FilesViewer.jsx, src/drive/web/modules/views/Folder/FolderViewBody.jsx, src/drive/web/modules/views/Folder/createFileOpeningHandler.js, src/drive/web/modules/views/Folder/createFileOpeningHandler.spec.js, src/drive/web/modules/views/OnlyOffice/Editor.jsx, src/drive/web/modules/views/OnlyOffice/Editor.spec.jsx, src/drive/web/modules/views/OnlyOffice/OnlyOfficePaywallView.jsx, src/drive/web/modules/views/OnlyOffice/ReadOnlyFab.jsx, src/drive/web/modules/views/OnlyOffice/Title.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/FileName.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/index.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/index.spec.jsx, src/drive/web/modules/views/OnlyOffice/View.jsx, src/drive/web/modules/views/OnlyOffice/helpers.js, src/drive/web/modules/views/OnlyOffice/index.jsx, src/drive/web/modules/views/OnlyOffice/useConfig.jsx, src/photos/targets/public/index.jsx, yarn.lock
```
* Add OnlyOffice paywall
```
**Notes :** This PR comes with a new flag calls `drive.office` which replace `drive.onlyoffice.enabled` and extends it's features. You can set a default mode for the onlyoffice editor and give write permission. For example: 
```
{
"enabled": true,
"engine": "onlyOffice",
"write": true,
"onlyOffice": {
"defaultMode": "edit"
}
}
```
* https://github.com/cozy/cozy-ui/pull/2366
* https://github.com/cozy/cozy-libs/pull/2058
=> feat: Add OnlyOffice paywall

src/drive/web/modules/views/OnlyOffice/helpers.js, src/drive/web/modules/views/OnlyOffice/index.jsx
```
* Add backwards compatibility with `drive.onlyoffice.enabled` flag
```
Some bug fix are waiting the work on Only Office to deploy. To unlock the situation, we decide to make backwards compatibility with the flag `drive.onlyoffice.enabled`. 
It's override if the flag `drive.office` exists. Its default mode is view on mobile so in some context we can set its default mode to edit on desktop with `drive.office.defaultMode: edit`
This PR also modifies the `drive.office` flag by grouping all the mobile-specific settings in a single object. 
Old: 
```
drive.office : {
"enabled": true,
"write": false,
"disableMobileEditing": true,
"onlyOffice": {
"defaultMode": "edit",
"mobileDefaultMode": "view"
}
}
```
New: 
```
drive.office : {
"enabled":true,
"write": true,
"defaultMode":"edit", …
```
=> feat: Backwards compatibility with onlyoffice flag

src/drive/web/modules/views/OnlyOffice/helpers.js
New tablet has greater resolution than the tablet breakpoint which is 1023px. For example, the new iPad Pro has an resolution of 2560 X 1600px. That's why now we check also on which device we are with the cozy-device-helper
```
*  Detect touch screen device to enable OnlyOffice
```
=> fix: Detect touch screen device to enable OnlyOffice

src/drive/styles/main.styl, src/drive/targets/public/index.jsx
```
* Spacing on empty share page
```
Before : 
After :
=> fix: Spacing on empty share page

package.json, yarn.lock
This update brings improvements on the selection bar by limiting the number of visible actions depending on the screen size
```
* Update cozy-ui from 82.10.0 to 82.13.0
```
=> feat: Update cozy-ui from 82.10.0 to 82.13.0

src/drive/targets/public/components/AppRouter.jsx, src/drive/targets/public/components/AppRouter.spec.jsx
```
* Redirect to the viewer when accessing OnlyOffice although it is deactivated
```
=> fix: Blank screen when onlyoffice is disabled

src/photos/components/EditableAlbumName.jsx, src/photos/components/MoreMenu.jsx, src/photos/components/Topbar.jsx
```
* Fixed the ability to rename a photo album on desktop
```
The problem stems from a conflict with the MUI Menu. The menu goes into focus when it is opened for accessibility reasons. This causes the input to lose focus and disappear just afterwards because it blurs. I've disabled autoFocus for this specific case until I find a fix in cozy-ui. I find my dirty fix in MUI  issue: https://github.com/mui/material-ui/issues/4387.
During my tests, I converted EditableAlbumName into a functional component. It's not required for the fix but as the work had been done I incorporated it. 
I'll try to find a better solution tomorrow but I'll take it if you have any other ideas
=> Fix: Rename photo album desktop

.bundlemonrc, package.json, yarn.lock
This update gets back the new design of the QuotaAlert modal
```
* Update cozy-ui from 88.5.0 to 88.6.0
```
=> feat: Update cozy-ui from 88.5.0 to 88.6.0

src/drive/web/modules/views/Drive/index.jsx, src/drive/web/modules/views/Folder/hooks/useBreadcrumbPath.jsx, src/drive/web/modules/views/Folder/hooks/useBreadcrumbPath.spec.jsx, src/drive/web/modules/views/Sharings/SharingsFolderView.jsx, src/drive/web/modules/views/Trash/TrashFolderView.jsx
In case of an error (eg. Not found), the breadcrumb displayed the root path (eg. Trash)
```
*  Remove the endless loop when accessing a folder not found
```
=> fix: Breadcrumb endless loop for not found folder

src/drive/web/modules/filelist/File.jsx, src/drive/web/modules/filelist/File.spec.jsx, src/drive/web/modules/move/FileList.jsx, src/drive/web/modules/views/Folder/FolderViewBody.jsx
This commit aims to correct the regression introduced since migration of the selection to a Provider. It was possible to select a file in the dialog to move it even though no checkbox was displayed
```
* Disable file selection into move modal 
```
=> fix(File): Add the ability to disable file selection

package.json, yarn.lock
This update allows to limit the number of recipients per document (default: 100)
```
* Update cozy-sharing from 8.2.0 to 8.3.0
```
=> feat: Update cozy-sharing from 8.2.0 to 8.3.0

package.json, yarn.lock
To benefit from the renamed Notes qualifications
```
* Update cozy-scanner from 5.1.1 to 5.2.0
```
=> feat: Update cozy-scanner from 5.1.1 to 5.2.0

src/drive/locales/en.json, src/drive/web/modules/move/MoveModal.jsx, src/drive/web/modules/move/MoveModal.spec.jsx, src/drive/web/modules/move/MoveSharedFolderInsideAnotherModal.jsx
```
* Check if file are shared also when moving a shared element inside another one
* Display the list of shared entries when moving a shared element within another one
```
=> fix: Improve wording of moving shared element inside another one

src/drive/web/modules/views/Public/index.spec.jsx
The useEffect inside usePublicWritePermissions is leaking only during tests. The problem seems to come from fetchOwn from cozy-client because it use fetch and we don't clean it. We didn’t find a way to fix it so we decide to mock the problematic hook. To solve it would probably need to add an abortController to manage fetch into cozy-client
```
* Remove the act error caused by an useEffect leak
```
=> test(Public): Remove the act error caused by an useEffect leak

src/drive/styles/filelist.styl, src/drive/web/modules/filelist/cells/SharingShortcutBadge.jsx, src/drive/web/modules/navigation/Nav.jsx, src/drive/web/modules/navigation/NavContent.jsx, src/drive/web/modules/navigation/NavItem.jsx, src/drive/web/modules/navigation/NavLink.jsx, src/drive/web/modules/navigation/SharingsNavItem.jsx, src/drive/web/modules/navigation/helpers.js, src/drive/web/modules/queries.js
```
* Show number of new sharing in the sidebar
```
On desktop :
On tablet & mobile :
=> feat: Show number of new sharing in the sidebar

src/drive/locales/en.json, src/drive/web/modules/move/MoveSharedFolderInsideAnotherModal.jsx
```
* Always show shared entries in MoveSharedFolderInsideAnotherModal
```
=> fix: Always show shared entries in MoveSharedFolderInsideAnotherModal

package.json, src/drive/web/modules/public/LightFileViewer.jsx, src/drive/web/modules/viewer/FilesViewer.jsx, src/photos/components/PhotosViewer.jsx, src/photos/targets/public/index.jsx, yarn.lock
```
* Display the file path into non-public viewer
```
**PRs related:**
- https://github.com/cozy/cozy-ui/pull/2488
=> feat(Viewer): Display the file path into non-public viewer

src/drive/web/modules/queries.js
This ensures consistency between the number of shortcuts displayed in recent and their number in the sidebar
```
* Only count new sharing shortcut not trashed into sidebar
```
=> fix(SharingsNavItem): Only count new sharing shortcut not trashed

src/drive/web/modules/move/Footer.jsx, src/drive/web/modules/move/MoveModal.jsx, src/drive/web/modules/move/MoveModal.spec.jsx
When users had a lot of shares, they could move one shared folder to another without being blocked because the shares were not fully loaded. Now, we wait before allowing the user to perform the move action
```
* Wait for shares to load before authorising moves
```
=> fix(MoveModal): Wait for shares to load before authorising moves

src/drive/web/modules/views/OnlyOffice/Editor.spec.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/FileName.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/index.jsx
```
* Hide path in OnlyOffice editor in public
```
=> fix: Hide path in OnlyOffice editor in public

src/drive/web/modules/drive/Toolbar/share/ShareButton.jsx, src/drive/web/modules/drive/Toolbar/share/ShareItem.jsx, src/drive/web/modules/drive/Toolbar/share/SharedRecipients.jsx, src/drive/web/modules/drive/Toolbar/share/helpers.js, src/drive/web/modules/drive/Toolbar/share/helpers.spec.js
```
* Share the displayed folder even from path ending with /
```
=> fix: Share the displayed folder even from path ending with /

src/photos/ducks/backup/components/UpdateAppAlert.jsx, src/photos/ducks/backup/hooks/useBackupActions.jsx, src/photos/ducks/backup/index.jsx, src/photos/locales/en.json
```
* Avoid errors on backup page on old flagship app
```
=> Avoid errors on backup page on old flagship app

src/drive/targets/public/components/AppRouter.jsx, src/drive/web/modules/filelist/FileOpener.jsx, src/drive/web/modules/navigation/AppRoute.jsx, src/drive/web/modules/public/LightFileViewer.jsx, src/drive/web/modules/search/components/helpers.js, src/drive/web/modules/viewer/FileOpenerExternal.jsx, src/drive/web/modules/viewer/FilesViewer.jsx, src/drive/web/modules/views/Folder/FolderViewBody.jsx, src/drive/web/modules/views/Folder/createFileOpeningHandler.js, src/drive/web/modules/views/OnlyOffice/Create.jsx, src/drive/web/modules/views/OnlyOffice/Editor.spec.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/BackButton.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/index.jsx, src/drive/web/modules/views/OnlyOffice/Toolbar/index.spec.jsx, src/drive/web/modules/views/OnlyOffice/helpers.js, src/drive/web/modules/views/OnlyOffice/index.jsx, src/drive/web/modules/views/OnlyOffice/useConfig.jsx
```
* Make working back button for a file at another Cozy
```
**Context:**
Historically, we were going backwards in the browser's history for 3 reasons: 
- We cannot use the relative route because it is not a sub-route of where the user is coming from
- The OnlyOffice shared file opens in the owner's cozy, to return you must reopen the previous cozy 
- The creation process has redirect process that we need to avoid if we don't want to fall into an endless lopp
Why did we decide to use redirectLink instead of jumping to the browser history?
- It doesn't matter how many steps before if you have redirect link you can bring the user back to the starting point
- It's a lot more predictable where the user will end up 
To get around the problem of whether or not the url is shared in the search …
=> fix: Make working back button for a file at another Cozy

package.json, src/drive/targets/manifest.webapp, src/drive/targets/mobile/config.xml, src/drive/targets/mobile/package.json, src/photos/targets/manifest.webapp
```
* Bump to version 1.62.0
```
=> feat: Bump to version 1.62.0

src/drive/web/modules/views/OnlyOffice/index.jsx
In react-router v6, we need an `<outlet />` instead of a children otherwise the subroute like paywall would no longer be displayed
```
* Display the OnlyOffice paywall when there are no editing rights
```
=> fix(OnlyOffice): Regression from migration react-route to v6

src/drive/web/modules/views/Upload/useResumeFromFlagship.ts
*  Removed the purgeUpload, as it's not clear if it would really be useful
in case of an unknown error
*  Explicitely handle post-me not implemented error
In this case doing nothing is what's needed
=> fix: do not dispatch in resume hook catch block

src/declarations.d.ts, src/drive/locales/en.json, src/drive/web/modules/move/Header.jsx, src/drive/web/modules/views/Upload/UploadTypes.ts, src/drive/web/modules/views/Upload/UploaderComponent.styles.ts, src/drive/web/modules/views/Upload/UploaderComponent.tsx, src/drive/web/modules/views/Upload/useResumeFromFlagship.ts
- file icon
- no back arrow
- fix paddings
- fix breadcrumb overlay
=> fix: Harmonize flagship upload view

.travis.yml
The service execution production environment will be migrated to node 20 instead of node 16. To prepare for this change, we're running tests in node 20
```
* Add test in node 20
```
=> chore: Add test in node 20

src/photos/ducks/albums/index.jsx
Using a `$exists: false` in the selector is not efficient as it will full scan the index.
Rather, we use a partial index, which is way more efficient in this case: only the non-auto albums will be indexed
```
* More efficient album querying
*
*
```
=> feat: Use partial index for album query

src/drive/hooks/useRedirectLink.jsx, src/drive/hooks/useRedirectLink.spec.jsx, src/drive/targets/public/components/AppRouter.jsx, src/drive/web/modules/views/Folder/FolderViewBody.jsx, src/drive/web/modules/views/Folder/createFileOpeningHandler.js, src/drive/web/modules/views/OnlyOffice/Create.jsx, src/drive/web/modules/views/OnlyOffice/helpers.js, src/drive/web/modules/views/Public/index.jsx
The redirection of the back button requires adaptation when opening an onlyoffice file from a folder shared by a link or the preview of a shared folder. You need to stay on the same cozy and share the pathname and sharecode to remain authenticated during browsing. 
However, this behaviour must be different for public files accessed directly, where you must return to the instance from which you came. 
This PR allows to take in account the first behaviour without breaking the second.
```
* OnlyOffice back button redirect when coming from public folder
```
=> fix: OnlyOffice back button redirect when coming from public folder

src/photos/ducks/backup/components/BackupDescription.jsx, src/photos/ducks/backup/components/BackupInfo.jsx, src/photos/locales/en.json
```
* Hide first part of backup description if a backup is running or has already been made
```
I also added a small fix for this PR https://github.com/cozy/cozy-drive/pull/3016 which has been merged but not released yet.
=> fix: Hide first part of backup description if a backup is running or has already been made

src/drive/web/modules/views/Sharings/SharingsFolderView.jsx
We didn't pass the currentFolderId to the FolderViewBody. So we had currentFolderId undefined and then when we create a folder in a shared folder, then we make a request to POST `/files/undefined`
=> fix: Can create folder in a shared folder

src/drive/web/modules/views/Trash/FilesViewerTrash.jsx
@zatteo regression due to react-router v6 migration
```
* Correct navigation from trash viewer
```
=> fix: Navigation into trash viewer

.travis.yml, .tx/config
We are split Drive & App into there separated repository. In this process, we stop publishing Photos from this repository. After, we will take the time to remove Photos base code from this repository.
You can find photos codebase here now : https://github.com/cozy/cozy-photos
```
* Remove build photos
```
=> chore: Remove build photos

src/drive/web/modules/filelist/FilenameInput.jsx
```
* Don't throw an error when a user starts the creation of a folder / file. 
```
=> fix: Don't send errors if not needed

.bundlemonrc, src/drive/targets/manifest.webapp, src/drive/web/modules/queries.js, src/drive/web/modules/views/Drive/HarvestBanner.jsx, src/drive/web/modules/views/Drive/index.jsx, src/drive/web/modules/views/Drive/index.spec.jsx
Display the HarvestBanner in order to be able to run the associated konnector when displaying a folder.
Behind the flag `drive.show.harvest-banner`
```
* Display the Harvest Banner if the flag `drive.show.harvest-banner` is activated. No design ATM. Just to check if it works.
```
=> [VIO-14] feat: Add HarvestBanner

src/drive/web/modules/views/Folder/FolderViewBody.jsx
```
* Remove the blicking before the not found message is displayed
```
=> [VO-144] fix: Remove the blicking before the not found message is displayed

src/components/Bar.jsx
* App will not crash in flagship anymore because AddMenuProvider doesn't seem
able to find the appwide AlertProvider
=> fix: Add AlertProvider to AddMenuProvider

src/drive/web/modules/drive/Toolbar/components/Scanner/Scanner.spec.tsx, src/drive/web/modules/drive/Toolbar/components/Scanner/useScannerService.ts
First argument shape wasn't correct after refactor.
It has been updated to be the File object directly
=> fix: update file upload structure in scanner (VO-115)

src/drive/web/modules/views/Upload/useResumeFromFlagship.spec.tsx, src/drive/web/modules/views/Upload/useResumeFromFlagship.ts
This hook conflicted with more declarative uses of the uploadqueue,
for instance in the file scanner.
This produced instances where the success toaster showed twice.
Handling this by just removing it, will have to rely on the automatic
toast to show up instead.
=> fix: remove manual uploadQueue success hook (VO-115)

package.json, yarn.lock
This dependency was only necessary for Cordova
```
* Remove cozy-authentification
```
=> feat: Remove cozy-authentification

src/components/FilesRealTimeQueries.jsx, src/modules/views/Folder/FolderView.jsx, src/modules/views/OnlyOffice/Toolbar/index.jsx
After duplicating a file, it has no path. This makes it impossible to know if it is shared. For a move, we check some conditions around the sharing so we make sure that the moved file always has a path.
```
* Make sure that the files to be moved have a path
```
=> fix: Make sure that the files to be moved have a path

src/modules/views/Upload/UploaderComponent.tsx
* The MoveTopbar API changed in terms of props.
Due to that, UploaderComponent which was using the old props names crashed the app. To fix that critical issue we update UploaderComponent to use the updated prop names for Topbar
=> fix: Update TopBar API in uploader.component (VO-362)

src/modules/views/Modal/ShareFileView.jsx
* Fix a bug when infinite loader could show up when removing self from a sharing
=> fix: Refactor ShareFileView component (VO-370)

src/modules/upload/index.js
* Files too large on upload will be correctly detected in Firefox
=> fix: Handle error format in file too large error (VO-417

src/modules/drive/Toolbar/index.jsx
As Drive has the latest version of the cozy-bar, there is no longer any need to wrap custom bar content to access the provide 🙂
=> feat: Remove SharingProvider inside BarRight

src/modules/views/Folder/createFileOpeningHandler.js, src/modules/views/Folder/generateShortcutUrl.js
We had a bug that caused an issue where if we wanted to open a shortcut from the preview page, it wouldn't work.
Indeed, since we were only testing the public case and forgetting the preview case, it couldn't work.
So now, we rely on the props to be able to know if we are public or not instead of just checking the url.
```
*
* We had a bug that caused an issue where if we wanted to open a shortcut from the preview page, it wouldn't work.
*
```
=> fix: Can open shortcut even on preview page

src/modules/upload/index.js
* Removed an issue where uploading a file above quota would trigger max file size error wrongly
=> fix: Update err max file size handling (VO-637)

src/modules/views/Modal/QualifyFileView.jsx
In the case where we remove the qualification it's necessary to define the attribute to `null` and not `undefined`, with `undefined` the stack does not return the attribute and today the Redux store is not updated for a missing attribute.
As a result, the UI is not updated and continues to display the qualification on the document, even though it has been deleted in CouchDB.
```
* Remove document qualification should refresh UI
```
=> fix: Remove document qualification should refresh UI

src/modules/filelist/AddFolderRow.jsx, src/styles/filelist.styl
* Using LastUpdate component with undefined date,
this will keep homogeneity with other rows
* Also adjust CSS so that input folder name and other existing
folder names keep the same width
and stay aligned
=> fix: Disable update time for addFolder row (VO-391)

src/modules/search/components/BarSearchAutosuggest.jsx, src/modules/search/components/SuggestionItem.jsx
Not using `splitFileName()` because
we don't have access to the full file here.
Using a more low level approach but still safe.
=> fix: Hide ".url" in suggestionItem (VO-647)

src/components/Button/BackButton.jsx, src/components/FolderPicker/FolderPicker.jsx, src/components/FolderPicker/FolderPickerBody.jsx, src/components/FolderPicker/FolderPickerFooter.jsx, src/components/FolderPicker/FolderPickerHeader.jsx, src/components/FolderPicker/FolderPickerHeader.spec.js, src/components/FolderPicker/FolderPickerHeaderIllustration.jsx, src/components/FolderPicker/FolderPickerTopbar.jsx, src/modules/move/MoveModal.jsx, src/modules/move/Topbar.jsx, src/modules/navigation/Breadcrumb/components/MobileBreadcrumb/MobileBreadcrumb.jsx, src/modules/views/Search/SearchView.jsx, src/modules/views/Upload/UploadTypes.ts, src/modules/views/Upload/UploadUtils.ts, src/modules/views/Upload/UploaderComponent.tsx, src/modules/views/Upload/useUploadFromFlagship.ts
This first technical step will make it easier to add shared drives. The component has a single function: to pick a folder. And those who use it no longer have to worry about implementation. So I could change the way it moves to match the design requirements for opening a Nextcloud folder
=> [VO-759] refactor: Extract to modal to pick folder into a component calle FolderPicker

src/targets/browser/index.ejs, src/targets/intents/index.ejs, src/targets/public/index.ejs
Our custom theme CSS was not taken into account because cozy-ui CSS was inserted after the custom theme CSS.
I did not understand why it was working in <= 1.60.0 (if you want to check https://github.com/cozy/cozy-drive/compare/v1.60.0...v1.61.0).
```
* Custom theme colors were not taken into account
```
**Before**
**After**
=> fix: Move custom theme CSS at end of <head>

src/modules/navigation/Nav.jsx
```
* Hide favorites into navigation without the flag
```
=> fix: Hide favorites into navigation without the flag

src/modules/filelist/FileOpener.jsx, src/modules/filelist/FileOpener.spec.jsx, src/modules/views/Folder/createFileOpeningHandler.js, src/modules/views/OnlyOffice/helpers.js
OnlyOffice files can be opened with ctrl + right click for quick access. This didn't work in public because we hadn't kept the sharecode in the generated urls.
```
* Open in new tab OnlyOffice file in public
```
=> [VO-910] fix: Open in new tab OnlyOffice file in public

src/components/Error/Empty.jsx
The `u-mh-2` class corrected a margin problem that was later corrected in cozy-ui (https://github.com/cozy/cozy-ui/commit/8c036602cf88cbce7dc8e7c00aaec62445e89784). The combination of the two caused a horizontal scroll bar to appear in mobile. I've removed the Drive fix in favour of the cozy-ui fix.
```
* Remove scrollbar in empty state on mobile
```
=> [VO-912] fix(Empty): Remove scrollbar on mobile

package.json, yarn.lock
```
* On move conflicting, trash the file already existing instead the destination folder 
* Update cozy-client from 48.11.1 to 48.11.2
```
=> feat: Update cozy-client from 48.11.1 to 48.11.2

src/components/Bar.jsx, src/modules/public/LightFileViewer.jsx, src/modules/public/PublicToolbarByLink.jsx
The fix #3159 had two side effect when there was only one file inside a share folder : 
- in desktop, we showed the filename inside the toolbar
- in mobile, we showed the filename inside the cozy-bar instead of the folder name
This commit aims to correct these problems
```
* Show filename only in public viewer instead of folder view
```
=> fix(Public): Show filename only in viewer

src/components/FolderPicker/FolderPickerListItem.tsx, src/lib/flags.js, src/modules/actions/components/addToFavorites.tsx, src/modules/actions/components/removeFromFavorites.tsx, src/modules/filelist/cells/FileName.jsx, src/modules/filelist/helpers.ts, src/modules/navigation/AppRoute.jsx, src/modules/navigation/Nav.jsx, src/modules/navigation/hooks/helpers.spec.js, src/modules/nextcloud/components/actions/deleteNextcloudFile.tsx, src/modules/nextcloud/components/actions/moveNextcloud.jsx, src/modules/nextcloud/components/actions/shareNextcloudFile.jsx, src/modules/nextcloud/helpers.ts, src/modules/views/Folder/FolderDuplicateView.tsx, src/modules/views/Modal/MoveFilesView.jsx, src/modules/views/Nextcloud/NextcloudFolderView.jsx
```
* Revert `drive.show-nextcloud-dev` to `drive.hide-nextcloud-dev` so the feature is activated by default
* Remove `drive.show-favorites-dev`
```
=> [VO-1167] feat: Remove some development flags

src/modules/views/Drive/FilesViewerDrive.jsx, src/modules/views/Recent/FilesViewerRecent.jsx, src/modules/views/Sharings/FilesViewerSharings.jsx, src/modules/views/Trash/FilesViewerTrash.jsx
ça ne posait pas de souci avec un usage classique de l'app : chargement de la home, puis navigation dans les dossier/fichier. Car la requête de récupération des fichiers est exécuté au lancement de l'app, et donc la navigation se fait sur le cache. Usequery dans les composants retourne alors toujours un tableau et non un null. On ne passe donc jamais dans le FilesViewerLoading.
Sauf qu'avec un refresh sur la visualisation d'un fichier, la query est réinitialisée, donc on passe par un null, donc l'app plantait car l'import n'était pas bon.
=> fix: FilesViewerLoading was imported from a file that did not export it

src/declarations.d.ts, src/locales/en.json, src/locales/fr.json, src/modules/layout/DummyLayout.tsx, src/modules/navigation/AppRoute.jsx, src/modules/navigation/ExternalRedirect.jsx, src/modules/navigation/PublicNoteRedirect.tsx, src/modules/navigation/hooks/helpers.spec.js, src/modules/navigation/hooks/helpers.ts, src/modules/navigation/hooks/useFileLink.tsx, src/modules/views/Public/PublicNoteRedirectView.tsx, src/targets/public/components/AppRouter.jsx
```
* Opening note inside public repository
```
=> [VO-1187] fix: Opening note inside public repository

src/modules/public/LightFileViewer.jsx
In the Public view, no return is possible, as there is none.
=> fix: Hide back icon in public viewer

src/modules/actions/index.jsx, src/modules/public/PublicToolbarByLink.jsx, src/modules/views/Public/PublicFolderView.jsx
We no longer wish to highlight this action, but it remains in the 3-point menu.
=> feat: Hide sharing banner for the synchronize action 

src/modules/drive/FabWithMenuContext.jsx, src/modules/views/Drive/DriveFolderView.jsx, src/modules/views/Public/PublicFolderView.jsx
This reverts commit 66291048339cd2cb2206e2ee44e684289d7240d2.
Accidental commit on master
=> fix: Revert "refactor: Rename FabWithMenuContext"

src/modules/actions/openExternalLink.jsx, src/modules/public/OpenExternalLinkButton.jsx, src/modules/public/PublicToolbarMoreMenu.jsx, src/modules/views/OnlyOffice/Title.jsx, src/modules/views/OnlyOffice/Toolbar/index.jsx, src/modules/views/OnlyOffice/Toolbar/index.spec.jsx, src/modules/views/Public/PublicFolderView.jsx
An change shared banner display conditions.
=> feat(OO): Change actions of the toolbar

src/modules/views/Public/PublicFolderView.jsx
When sharing with Cozy and already Added, the share banner should never appear.
Before this fix, it could blink on loading.
=> fix: Sharing banner blinks

package.json, src/lib/dacc/dacc-run.js, src/lib/dacc/dacc-run.spec.js, yarn.lock
This update has revealed a mistake in the [aggregateFilesSize](https://github.com/cozy/cozy-drive/blob/1b67de296094c118a09add39d6df56f29e143858/src/lib/dacc/dacc.js#L90-L91) function.
We could end up comparing a Date type with a String type.
=> feat: Upgrade date-fns to 2.30.0

package.json, yarn.lock
=> feat: Bump dataproxy

package.json, src/components/App/App.jsx, src/lib/doctypes.js, yarn.lock
When searching through the dataproxy, the default doctype search order is apps, contacts, files, mainly because of their respective volume. It is assumed to have very few apps, and less contacts than files. Therefore, since there is a limit to displayed results, we prefer to display files in last.
This works in the Home search contexte, but not so much in Drive, where it makes sense to have the files displayed first.
=> feat: Files doctype should appear first in search

src/locales/en.json, src/locales/fr.json, src/modules/views/OnlyOffice/Editor.spec.jsx, src/modules/views/OnlyOffice/Toolbar/EditButton.jsx, src/modules/views/OnlyOffice/Toolbar/index.jsx, src/modules/views/OnlyOffice/View.jsx, src/queries/index.ts
And no longer display the FabButton in Desktop mode.
You can either hide the tooltip permanently or temporarily.
=> feat(OO): Add an edit button to the toolbar in place of the FabButton

package.json, yarn.lock
During migration to rsbuild, we removed cozy-scripts. But cozy-app-publish was present only because it was present in cozy-scripts. So let's add it directly.
=> feat: Add cozy-app-publish to allow publishing in registry

rsbuild.config.mjs
Since the rslib migration, the mui-bottom-sheet component would not work anymore due to `.willAdvance is not a function` error
This is due to library's side effects that are erased by the tree shaking mechanism
To prevent that we change the rsbuild configuration to handle those side effects
More info: pmndrs/react-spring#1078
=> fix: Enable rslib sideEffects on react-spring

src/locales/en.json, src/locales/fr.json, src/modules/filelist/cells/FileName.jsx, src/modules/filelist/icons/FileThumbnail.tsx, src/modules/shareddrives/components/AddSharedDriveButton.tsx, src/modules/shareddrives/components/AddSharedDriveFab.tsx, src/modules/shareddrives/helpers.ts, src/modules/views/Drive/SharedDrivesFolderView.tsx, src/styles/filelist.styl
Shared drive are being added in cozy-stack in https://github.com/cozy/cozy-stack/pull/4511. Here we display them in "Drives" section and we add buttons to create them.
It is behind a flag `drive.enable-shared-drive` so it can be safely merged and send to production.
See : https://github.com/cozy/cozy-drive/pull/3323
=> Display shared drives in "Drives" section

package.json, tsconfig.json, yarn.lock
To allow back "editor wide feature" by vscode. It was not working because it was trying to watch too many files.
Also removed "jsx": "react" which is already part of cozy-tsconfig.
=> feat: Exclude build from tsconfig

src/modules/views/OnlyOffice/Toolbar/HomeIcon.jsx
In 617fadf1888a4fb7376a40fc5bcd9a2f6d7edcac I removed icon fetched from stack to an icon from cozy-ui. It was a mistake due to a misconfiguration on my local environment. We must keep it like this to be able to customize home icon.
=> fix: Home icon takes again customization into account

src/modules/filelist/virtualized/cells/FileName.jsx, src/modules/filelist/virtualized/cells/FileNamePath.jsx
Passing a comp returning null as props is not the same than passing
directly undefined, because if we test the prop inside the comp,
first way will return true, second way will return false
=> feat(FileName): Don't load path component if not necessary

src/modules/viewer/FilesViewer.jsx, src/modules/viewer/FilesViewer.spec.jsx, src/modules/views/Public/PublicFileViewer.jsx
issue: https://www.notion.so/linagora/Browsing-files-through-viewer-is-limited-to-displayed-files-22462718bad1802d9d6df2847f1210d7
fixes:
- Public file viewer not loading more than the currently loaded files ( 30 files limit )
- File viewer is not loading more than the currently loaded files (100 files limit )
=> fix(file viewer): not loading more items when reaching the end of current query result 🐛

package.json, src/components/FilesRealTimeQueries.jsx, src/modules/views/Trash/TrashDestroyView.tsx, yarn.lock
When receiving a batch of realtime events, we used to treat them
sequentially and do the following:
- Query the parent folder if it's a file to compute the path
- Dispatch the mutation
This was highly inefficient, because the dispatch is a costful
operation, especially if the store is filled with documents and queries.
Indeed, each dispatch will trigger the full reevaluation of the existing
queries against the documents in the store.
So, to improve this behaviour we now introduce a debounce mechanism for
relatime events: we wait a fixed amount of time before processing the
events all at once.
To do this, each new realtime event is temporarily stored in a buffer,
and removed once treated.
This impact all treatments involving multiple realtime events, such as
trash, restore, or deletion …
=> Improve performances of mutliple updates

package.json, src/components/App/App.jsx, src/components/pushClient/index.js, src/components/pushClient/index.spec.js, src/lib/DriveProvider.jsx, src/lib/encryption.js, src/modules/move/helpers.spec.js, src/targets/browser/setupAppContext.js, yarn.lock
We now support offline navigation thanks to the `DataProxyLink`.  By
default, all request go through the `StackLink`, but it now detects if
the user is offline, and then forward data queries to the DataProxy,
which will run them on PouchDB.
Note this only work for read queries that rely on `io.cozy.files`: we
typically do not support offline download, or write operations such as
renaming yet.
=> feat: Add support for offline navigation in web

package.json, yarn.lock
The new version of `cozy-sharing` resolves the bug in creating shared drive
=> chore: Upgrade cozy sharing to 25.7.2 :arrow_up:

src/modules/views/Folder/FolderViewBody.jsx, src/modules/views/Folder/virtualized/GridWrapper.jsx
fixes scroll on mobile for both grid and list view.
root issue:
`overflow: hidden` was added when on mobile to the folder body, which clips the content, disables scrolling, touch dragging, etc
https://github.com/user-attachments/assets/56f3a095-658f-49ba-90ed-2f12a49c2dc0
=> fix: not being able to scroll on mobile 🐛

src/components/Storage/StorageProgress.jsx
New pull. 
Ref : https://github.com/cozy/cozy-drive/pull/3447
Before : 
After : 
Ticket : https://www.notion.so/linagora/the-available-space-in-the-quota-is-not-displayed-correctly-23262718bad180388c6bd17b7932f5ec
=> fix: available space in the quota is not displayed correctly

src/locales/en.json, src/locales/fr.json, src/modules/drive/Toolbar/components/LeaveSharedDriveButtonItem.jsx, src/modules/drive/Toolbar/components/MoreMenu.jsx, src/modules/drive/Toolbar/index.jsx, src/modules/shareddrives/helpers.ts, src/modules/views/SharedDrive/SharedDriveFolderView.jsx
When a user displays a shared drive, the menu is now available with the "Leave shared drive" command which revokes the current user from the selected shared drive.
When done, a success message is displayed and the user is redirected to the list of sharings
- **feat: Add header to shared folder view**
- **feat: Add "leave shared drive" to toolbar**
- **feat: Hide shared recipients and share buttons**
=> feat: Shared drive recipients can leave a shared drive

src/modules/filelist/File.jsx, src/modules/filelist/icons/FileThumbnail.tsx, src/modules/navigation/hooks/helpers.ts, src/modules/navigation/hooks/useFileLink.tsx, src/modules/views/Sharings/index.jsx
Shared drives in the Sharing section only appear as shortcuts and don’t include a root folder id, making them unusable. Since `io.cozy.sharings` provides the needed driveId and root folder id but in an incompatible format, we transform them into directory-like objects with the correct structure. This allows them to be displayed properly in the UI and opened via `shareddrive/:driveId/:rootFolderId`.
https://github.com/user-attachments/assets/0f2a7e2f-ea57-447d-96ae-542092aaf731
https://github.com/user-attachments/assets/6406e962-909c-44b6-b975-9279cb2ca5bf
~~- In recipient's sharing section, the shared drive ID is not correct as shared drive list in sidebar, maybe there was an error from `/files/_all_docs?include_docs=true` endpoint~~
=> feat: Open shared drive from sharing section :sparkles:

src/modules/views/Drive/DriveFolderView.jsx
Remove `Drives` folder from root directory.
<table>
<tr>
<th> Before </th>
<th> After </th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> feat: Remove Drives folder from root directory :coffin:

src/modules/views/Sharings/index.jsx
In 0746c41fd3b5986619850b56469adf0fca991a86, I used file.driveId instead of file.attributes.driveId but forgot to update it in the transformedSharedDrives used in Sharing view.
=> fix: Blank screen in sharing because of shared drive

package.json, src/modules/navigation/hooks/helpers.spec.js, src/modules/navigation/hooks/helpers.ts, src/modules/navigation/hooks/useSharedDriveLink.tsx, src/modules/shareddrives/helpers.ts, src/modules/views/Sharings/index.jsx, yarn.lock
Set the correct path to open shared drive by user's role.
https://github.com/user-attachments/assets/ff9ae41a-7059-4449-bf02-b524059a5ab1
https://github.com/user-attachments/assets/bbc73a90-86f5-460f-9b39-d61e5088de30
[cozy/cozy-viewer#2818](https://github.com/cozy/cozy-libs/pull/2818)
=> fix: Open correct shared drive view by user :bug:

package.json, src/declarations.d.ts, src/modules/shareddrives/hooks/useSharedDriveFolder.tsx, yarn.lock
This is a naive implementation of realtime for shared drives files.
A better approach is expected later using the storage of cozy-client
But for this we need to fix
https://github.com/cozy/cozy-client/issues/1620 first.
=> feat: Add realtime to shared drives files

package.json, src/modules/navigation/duck/hooks.ts, src/modules/views/Folder/virtualized/FolderViewBody.jsx, src/modules/views/Folder/virtualized/Table.jsx, src/modules/views/Trash/TrashFolderView.jsx, src/modules/views/Trash/TrashFolderView.spec.jsx, yarn.lock
Ticket : https://www.notion.so/linagora/Display-files-in-the-trash-by-deletion-date-1c062718bad1803d8aa6c3f51d515d4c?source=copy_link
The trash folder is now sorted by last update desc by default but an issue persist.
When you delete a file/folder, it's not concidered as an update. So currently it's not sorted by the last item deleted but really by the last time the item is modified. 
As discussed with Khaled, apparently it's a back-end problem. 
- use updated_at default sort order in trash folder view
=> feat: Sort trash by updated_at by default

src/modules/views/Folder/virtualized/Table.jsx
not used in the comp, only passed to the DOM as is
=> refactor(Table): Remove useless `handleShiftArrow` prop

src/hooks/useOnLongPress.js
On mobile, when we scroll on the folder view, it was selecting the item where we start the scroll because it was detected as a long press.
=> fix: Stop long press detection when scrolling

src/modules/views/Folder/virtualized/FolderViewBody.jsx
Fix adding folder view is incorrect in an empty folder
=> fix: Resolve wrong view when adding new folder in empty folder :bug:

src/components/Error/Empty.jsx, src/modules/layout/Layout.jsx, src/modules/views/Drive/DriveFolderView.jsx
- Properly propagate writing permission to child components; previously, it was true by default
- Disable the new upload button on the emptyWrapper component
- Disable the create menu & upload button on the layout when the shared drive is read-only
=> fix(shared drives): upload button and create menu was not disabled when in read-only 🐛
