.tx/config
src/components/location.jsx
src/components/nav.jsx
src/components/table.jsx
src/components/toolbar.jsx
src/locales/en.json

Thi PR enables Transifex on the project. It uses a nested dictionnaries, relevant to each component (a dict name is the related JSX component).

Enable transifex

---

manifest.webapp
package.json

This PR introduces a Cozy v3 (cozy-stack v2) manifest for cozy-files

Cozy manifest

---

.transifexrc.tpl
.travis.yml

This PR enables the travis automation:
- build the source code
- test the source code
- deploy the build the the dedicated branch when the merge occurs on the `master` branch

Add travis config

---

.gitignore
__mocks__/fileMock.js
config/webpack.base.config.js
config/webpack.preact.config.js
package.json
src/components/Toolbar.jsx
src/plugins/preact-polyglot.js
test/toolbar.spec.js
yarn.lock

This PR enables Jest tests and add a basic example on the Toolbar component

Enable Jest tests

---

package.json
src/main.jsx

It was a requirement for the navigation feature card currently in validation.

Add ‘Coming soon’ temporary text to all views except the first one

---

src/actions/index.js
src/components/Alerter.jsx
src/components/App.jsx
src/locales/en.json
src/reducers/ui.js
src/styles/alerter.styl

This PR :
Needs this branch of Cozy UI : https://github.com/gregorylegarec/cozy-ui/tree/feat/improve-alerts
* Connects App to redux
* Add Alerter component, which show alerts. Based on `Notifier.jsx` in `MyAccounts` app, but the behaviour is a little bit different (Overlay, reloading, button, etc.)
* At this time, the alerter mechanism only show critical errors.
* To trigger CSS transition, I used a `setTimeout` in `componentDidMount` method. I clearly not a big fan and I'd love to replace it by a better solution.

[feat] Add error alerts for file fetching

---

.gitignore
mobile/src/actions/index.js
mobile/src/containers/OnBoarding.jsx
mobile/src/main.jsx
mobile/src/reducers/index.js
mobile/src/reducers/mobile.js
mobile/src/styles/onboarding.styl
mobile/test/__snapshots__/onboarding.spec.js.snap
mobile/test/onboarding.spec.js
package.json
src/locales/en.json
yarn.lock

I could split this onto 4 commits, but it's kinda one thing. So I push it as it.
Featuring:

[mobile] Add a wizard to configure app

---

mobile/src/components/Wizard.jsx
mobile/src/containers/OnBoarding.jsx
mobile/src/styles/onboarding.styl
mobile/test/__snapshots__/onboarding.spec.js.snap
mobile/test/onboarding.spec.js
src/locales/en.json
test/components/__snapshots__/File.spec.js.snap

Now it's a wizard with steps.
No react-router involved, everything in a single one component.
A Logo is involved and is stored inside the `mobile/src/assets` folder, don't know if it is its best place.
Could you review this?

Now it's a wizard 🎅

---

package.json

You can see https://github.com/webpack/webpack/issues/708

Stop webpack when failed fix travis green build :bug:

---

mobile/src/reducers/mobile.js

Oups, we may add test on reducer to avoid this kind of bugs.

fix: SET_URL

---

mobile/src/actions/index.js
mobile/src/main.jsx
mobile/src/reducers/mobile.js
package.json
yarn.lock

waiting for #40 to be merged, then could merge this one.

Mobile.inappbrowser.remember

---

package.json
yarn.lock

Updated react-bosonic to a new version that uses click instead of Pointer Events

---

src/components/File.jsx

Also use a temporary constant for the stack URL in the File component.

Handle file or folder opening by double clicking

---

mobile/config.xml

A Security issue was discovered in cordova-android. Apache Cordova Android 6.1.2 Released: https://cordova.apache.org/announcements/2017/01/27/android-612.html

Upgrade cordova :rocket:

---

mobile/src/actions/index.js
mobile/src/containers/OnBoarding.jsx
mobile/src/main.jsx
mobile/src/reducers/mobile.js
mobile/test/__snapshots__/onboarding.spec.js.snap
mobile/test/actions.spec.js
mobile/test/onboarding.spec.js
src/locales/en.json

If a user write a non `https://` url, an error is displayed.
If a user write only his domain name, `https://` is added.
What do you think ?
PS : I refactor i18n keys for homogeneity.

Handle errors on url

---

mobile/src/actions/index.js
mobile/src/main.jsx

[mobile] Fix some bugs

---

mobile/src/containers/Settings.jsx
mobile/src/styles/settings.styl
mobile/test/settings.spec.js

clean component style :bathtub:

---

mobile/config.xml
mobile/src/lib/filesystem.js
mobile/src/main.jsx
mobile/test/lib/filesystem.spec.js
src/actions/index.js

- Create on Android `sdcard/Cozy/Cozy Files`
- Add download file on folder

[mobile] Donwload files

---

mobile/config.xml
mobile/src/actions/index.js
mobile/src/lib/filesystem.js
src/actions/index.js
src/components/App.jsx
src/components/Toast.jsx
src/containers/FileActionMenu.jsx
src/containers/Toast.jsx
src/locales/en.json
src/reducers/ui.js
src/styles/actionmenu.styl
src/styles/toast.styl

On mobile device, you can *"Open With..."* a file stored in your cozy.
It downloads the file to a temporary folder then let user opens the file in another application.

feature: open with in cordova app :busstop:

---

mobile/src/actions/index.js
mobile/src/lib/cozy-helper.js
mobile/src/lib/cozy_init.js
mobile/src/main.jsx
mobile/test/actions.spec.js
package.json
yarn.lock

I don't know how to update #79.
And I fix as well #77 in this PR.
So @aenario and @kosssi, are we cool?

Refactoring cozy init :dizzy:

---

package.json
src/actions/index.js
src/components/App.jsx
src/containers/DeleteConfirmation.jsx
src/locales/en.json
src/reducers/ui.js
src/styles/table.styl
yarn.lock

Fixes some minor issues:
- modal close button and mobile view
- a visual regression affecting checkboxes
- simplified translations
- better notifications

[fix] Fil 16 fixes

---

config/webpack.browser.target.js
config/webpack.copyfiles.config.js
manifest.webapp
src/index.ejs
src/main.jsx

I've rebased #58 and updated yarn.lock

Jinroh handle permissions

---

mobile/src/actions/index.js
mobile/src/containers/Settings.jsx
mobile/src/reducers/index.js
mobile/src/reducers/mobile.js
mobile/src/styles/settings.styl
mobile/test/settings.spec.js
src/locales/en.json

We can view a 'backup images' settings in the settings page.
Maybe we need to persist this value somewhere, we might add a 'redux' persistence in the whole mobile app.

[mobile] PHO-2 :camera:

---

mobile/src/actions/index.js
mobile/src/containers/OnBoarding.jsx
mobile/src/containers/Settings.jsx
mobile/src/lib/localStorage.js
mobile/src/main.jsx
mobile/src/reducers/mobile.js
mobile/test/actions.spec.js

We use localforage to store settings in IndexedDB within redux thanks to really good redux API.
See https://egghead.io/lessons/javascript-redux-persisting-the-state-to-the-local-storage

refactor: mobile settings are persisted :vhs:

---

src/locales/en.json

`Lorem ipsum` seems to not be clear enough 😜

i18n: change description

---

mobile/src/components/Wizard.jsx
mobile/src/containers/BackupPhotosVideos.jsx
mobile/src/containers/OnBoarding.jsx
mobile/src/containers/onboarding/BackupPhotosVideos.jsx
mobile/src/containers/onboarding/SelectServer.jsx
mobile/src/containers/onboarding/Welcome.jsx
mobile/src/styles/onboarding.styl
mobile/test/__snapshots__/onboarding.spec.js.snap
mobile/test/actions.spec.js
mobile/test/onboarding.spec.js
src/locales/en.json

[PHO-1] feature: add a page to backup Medias on onboarding

---

mobile/src/containers/onboarding/SelectServer.jsx

It was not easy to find this one. Sorry

[fix] input value was not connected to the state

---

package.json

I cannot anymore type the same command, again and again.

add a script to deploy on cordova

---

package.json
src/containers/FileActionMenu.jsx
src/lib/withGestures.jsx
yarn.lock

⚠️ **I wasn't able to test the swipe (I don't know, it seems like my fingers just don't work) so I'm not 100% sure it's all working.**
For testing, just open the file's action menu by taping on the tree dots button and then:
- Tap on the transparent background to close the menu;
- Swipe down on the menu to close it;
Although, if anyone sees some kind of optimisation to be made, just tell me.

Add HammerJS for swiping and taping on mobile

---

mobile/src/actions/unlink.js
mobile/src/components/Settings.jsx
mobile/src/containers/Settings.jsx
mobile/src/lib/cozy-helper.js

Add unregisterClient when unlink :punch:

---

src/styles/table.styl

That's only a part of the fix.

[fix] Fix thead on Safari (requires updated UI & Bar)

---

mobile/src/actions/index.js
mobile/src/containers/onboarding/BackupPhotosVideos.jsx
package.json
src/actions/index.js
src/containers/Folder.jsx
src/reducers/index.js
src/reducers/ui.js
yarn.lock

This PR is paired with https://github.com/cozy/cozy-ui/pull/73

Fix alerts & alerts' redux stuff move to cozy-ui

---

src/containers/FileActionMenu.jsx

See screenshots to understand what was going on...
[before fix](https://cloud.githubusercontent.com/assets/701648/23755908/32058532-04e2-11e7-98e0-5db4cb310b53.png)
[after fix](https://cloud.githubusercontent.com/assets/701648/23755917/36f7787a-04e2-11e7-93f9-1d60b9c7e2da.png)

fix: wrong flag to display loader

---

src/styles/table.styl

That was a odd behaviour… Still don't know why it's doing what it's doing but at least i got a fix that works.

[fix] Fix long name folder's bug on Firefox

---

src/containers/FileActionMenu.jsx
src/lib/withGestures.jsx

Following up on #166, a hopefully more robust fix.

[fix] Prevent ghost clicks, attempt #2

---

mobile/src/components/MobileAppRoute.jsx
mobile/src/lib/cozy-helper.js
mobile/src/main.jsx

I found that `main.jsx` was too heavy.
So.
- I create `MobileAppRoute.jsx` in regard to the original `AppRoute.jsx`.
- I move some code inside the `main.jsx` file

[mobile] refactor main.jsx

---

src/containers/FilesSelectionBar.jsx
src/containers/TrashSelectionBar.jsx
src/styles/table.styl

Mobile selection great again

---

mobile/src/lib/registration.js

I remove default options:
- location=yes
- hidden=no
I add clear cache parameter.
You can see the documentation [here](https://github.com/apache/cordova-plugin-inappbrowser).

Remove inappbrowser cache :punch:

---

mobile/src/reducers/settings.js
src/locales/en.json

I added the english and french translation.
And set the default value to `true` for `on wifi only` option.

feat: some adds for the `on wifi only` option

---

src/locales/en.json

When a typo is added, the world may explode.
\#oops!

fix: i18n key for wifi backup option

---

mobile/src/lib/cozy-helper.js
package.json
src/main.jsx
src/styles/actionmenu.styl
src/styles/breadcrumb.styl
yarn.lock

This PR is related to https://github.com/cozy/cozy-bar/pull/28 as it uses its new mechanism to disable title in cozy-bar and allow custom component replacement. It also adjust some alignments.

Improve component replacement in Bar

---

mobile/config.xml
mobile/src/styles/onboarding.styl
src/locales/en.json

https://trello.com/c/Jii1ONDB/198-2-fil-11-cosmetique-onboarding

Cosmetics onboarding

---

config/webpack.target.mobile.js
mobile/config.xml
mobile/scripts/update-config-version.sh
mobile/src/lib/cozy-helper.js
package.json

feat: Add more information about oauth client ✨

---

mobile/src/lib/cozy-helper.js
mobile/src/main.jsx

The message between the automatic pouchDB replication
was not handled well by the application.

fix: revoke not handled with replication :beetle:

---

package.json
src/containers/FileActionMenu.jsx
yarn.lock

I update cozy-bar to fix https://github.com/cozy/cozy-bar/pull/29
I remove OpenWith in ActionMenu on browser

Fix some :bug:

---

.tx/config
CONTRIBUTING.md
README.md
manifest.webapp
mobile/README.md
mobile/config.xml
mobile/fastlane/Appfile
mobile/fastlane/Deliverfile
mobile/fastlane/Fastfile
mobile/fastlane/Supplyfile
mobile/fastlane/metadata/android/en-US/full_description.txt
mobile/fastlane/metadata/android/en-US/short_description.txt
mobile/fastlane/metadata/android/en-US/title.txt
mobile/fastlane/metadata/android/fr-FR/full_description.txt
mobile/fastlane/metadata/ios/en-US/description.txt
mobile/fastlane/metadata/ios/en-US/name.txt
mobile/fastlane/metadata/ios/en-US/release_notes.txt
mobile/fastlane/metadata/ios/en-US/support_url.txt
mobile/fastlane/metadata/ios/fr-FR/description.txt
mobile/src/lib/cozy-helper.js
mobile/src/lib/filesystem.js
package.json
src/containers/Breadcrumb.jsx
src/containers/Nav.jsx
src/locales/en.json

On this repository:
Update service:

Rename Cozy Files to Cozy Drive

---

mobile/config.xml
mobile/fastlane/Appfile
package.json

chore: Update ios publication :rocket:

---

src/index.ejs

Message is 'Failed to load resource: net::ERR_FILE_NOT_FOUND'.
maybe report it on cozy-template?

refactor: Remove warning message on mobile :hammer:

---

README.md
package.json

I always read the readme to launch docker server. So I think it's a good idea to add it on package.json config.
Once merged, I will add it in the template repository ;)

chore: Add server command to launch docker :whale:

---

config/webpack.config.dev.js
src/main.jsx

Enable React Developer tools and Redux developer tools in Chrome.
[Redux dev tools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd)
[React dev tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi)

[feat] add developer tools

---

mobile/fastlane/metadata/ios/en-US/description.txt
mobile/fastlane/metadata/ios/en-US/keywords.txt

Small additions to description and keywords

---

src/components/SelectionBar.jsx

Sometimes bugs are real bugs...

fix: boolean bug in condition :candy:

---

config/webpack.config.dev.js
config/webpack.config.prod.js
package.json
src/index.ejs
src/main.jsx
yarn.lock

I don't know how to configure webpack the best way to:
Please help! 🆘
**[EDIT]**
I find something better, see below.

chore: add piwik tracking

---

CONTRIBUTING.md
README.md

chore: update README about docker and cozy.tools :notebook:

---

mobile/src/actions/settings.js
mobile/src/components/SettingCategory.jsx
mobile/src/components/Settings.jsx
mobile/src/containers/settings/MediaBackup.jsx
mobile/src/containers/settings/Support.jsx
mobile/src/containers/settings/Unlink.jsx
mobile/src/lib/init.js
mobile/src/lib/network.js
mobile/src/lib/reporter.js
mobile/src/lib/store.js
mobile/src/styles/settings.styl
package.json
src/locales/en.json
yarn.lock

It's possible to display a log button (and send log) after 3 taps on version number.
If this PR relies on changes in one of our internal libraries (cozy-ui), please also do the following things:

feat: Send log to help debug 🎉

---

package.json
src/components/ButtonClient.jsx
src/components/Sidebar.jsx
src/locales/en.json
src/styles/buttonclient.styl
src/styles/sidebar.styl
yarn.lock

Added the brand new button to invite users to download the Cozy desktop client.
Needs a new release of Cozy-UI https://github.com/cozy/cozy-ui/pull/114 and waiting for Cozy's website to deploy a page so I can update the url of the link.

New button to download desktop client

---

mobile/src/actions/settings.js
mobile/src/lib/init.js
mobile/src/lib/registration.js
mobile/src/styles/onboarding.styl
src/index.ejs

Quelques améliorations

---

package.json
src/components/ButtonClient.jsx
src/components/ButtonClientMobile.jsx
src/components/Main.jsx
src/locales/en.json
src/styles/buttonclient.styl

On mobile view, there's now a button just below the cozy-bar to invite you to download some Cozy apps :)
Please review with care, I'm not 100% sure i took the best path. ;)
⚠️ Needs a new release of Cozy-UI

Add download app button for mobile

---

src/styles/buttonclient.styl

fix: oops, breakpoints are different between drive and photo

---

src/components/File.jsx
src/locales/en.json
src/styles/table.styl

Makes sure we can format the dates according to the language.

fix: i18n date format

---

mobile/src/containers/onboarding/Welcome.jsx

because Apple's rules are apple's rules

---

mobile/config.xml
package.json

[changelog]
- remove external link on iOS platform

release: v0.3.1 :rocket:

---

src/actions/index.js

`window.open` on device open InAppBrowser window. So use [InAppBrowser.executeScript](https://github.com/apache/cordova-plugin-inappbrowser#inappbrowserexecutescript).

fix: Open picture on device :rice_scene:

---

config/webpack.config.base.js
config/webpack.target.browser.js
manifest.webapp
src/actions/index.js
src/components/FileList.jsx
src/components/FolderContent.jsx
src/components/FolderView.jsx
src/components/LightFolderView.jsx
src/components/PublicLayout.jsx
src/ducks/files/Container.jsx
src/ducks/files/rename.js
src/ducks/sharing/index.js
src/styles/actionmenu.styl
src/targets/public/index.ejs
src/targets/public/main.jsx

I tried to reuse existing components.
I faced two things:
1. I don't know how `<LightFolderView />` is getting its props
1. I don't know how to let the user download files
So, I guess I'll update this very PR when I'll get some answers.
I want to believe

feat: a public page listing shared folder's files

---

src/actions/index.js
src/ducks/files/Container.jsx
src/ducks/files/Toolbar.jsx
src/locales/en.json
src/styles/toolbar.styl

Added download button for displayed folder.

feat: download folder button

---

src/components/File.jsx
src/components/FileList.jsx
src/components/LightFolderView.jsx
src/targets/public/main.jsx

I added a `props` to hide the selection checkbox.
2 commits in this PR if you want:
Now it could be released.

feat: hide selection box for public page

---

config/webpack.config.vendors.js
manifest.webapp
src/components/ButtonClient.jsx
src/components/PublicLayout.jsx
src/components/Sidebar.jsx
src/locales/en.json

fix: ui in sharing public page

---

src/components/FolderContent.jsx

Regression added with https://github.com/cozy/cozy-drive/pull/328
Oops!

fix: selection checbox were missing

---

src/locales/en.json

fix: typo in i18n file

---

src/components/LightFolderView.jsx

It is hard to know if a link is revoked or not. But this code works for our purpose.

feat: display error when link is revoked

---

src/components/DownloadButton.jsx
src/components/LightFolderView.jsx

Add a button to download the public folder
or any of its subfolder.

feat: download folder in public view

---

config/webpack.target.mobile.js

It fixes the build for mobile.

fix: webpack mobile config

---

config/webpack.config.base.js
mobile/config.xml
mobile/src/actions/contactsBackup.js
mobile/src/actions/settings.js
mobile/src/components/Settings.jsx
mobile/src/containers/settings/Contacts.jsx
mobile/src/lib/cozy-helper.js
mobile/src/main.jsx
mobile/src/reducers/settings.js
package.json
src/locales/en.json
yarn.lock

Demo: https://thumbs.gfycat.com/PepperyAltruisticBluebird-mobile.mp4
The code here is ready for a review, but before merging we'll need a new version of cozy client js that includes [this PR](https://github.com/cozy/cozy-client-js/pull/192)

feat: sync device contacts to cozy

---

src/components/LightFolderView.jsx
src/styles/toolbar.styl

feat: display a menu more in mobile view

---

mobile/src/actions/contactsBackup.js

Existing contacts with a wrong format were messing up the import.

fix: defensive code guarding against ill-formatted contacts

---

mobile/config.xml
src/components/FolderView.jsx
src/locales/en.json
src/targets/mobile/containers/RatingModal.jsx
src/targets/mobile/lib/cozy-helper.js
src/targets/mobile/lib/withPersistentState.js
src/targets/mobile/styles/rating.styl

The user gets prompted after starting the apps a few times to give his/her feedback.
I suggest starting the review with `mobile/src/containers/RatingModal.jsx`, it's the component that holds the main logic.

feat: rating dialog

---

src/targets/mobile/containers/RatingModal.jsx

That way it'll end up directly in our feedback processing tools.

Change feedback email

---

src/components/ButtonClient.jsx

I guess this was some kind of typo.

fix: button Client didn't have a href anymore

---

package.json
src/drive/mobile/lib/cozy-helper.js

- a small fix to re-enable mobile builds
- a new command for cordova

fix: ios builds

---

src/photos/ducks/sharing/colorhash.js
src/photos/ducks/sharing/components/Recipient.jsx
src/photos/ducks/sharing/components/ShareAutocomplete.jsx
src/photos/ducks/sharing/components/autosuggest.styl
src/photos/ducks/sharing/components/recipient.styl
src/photos/lib/colorhash.js

Added default avatar on recipient with initial of the name and a stable color using [ColorHash](https://github.com/gweax/ColorHash)
Used Recipient component in 'who has access' & 'autocomplete' components.

Recipient default avatar

---

package.json
yarn.lock

chore: update UI deps to beta42

---

src/drive/components/File.jsx

Resolves https://github.com/cozy/cozy-drive/issues/369

Fixed erroneous images fetches

---

package.json
src/sharing/index.js

Made sure that sharing won't break if Piwik is blocked

---

src/photos/styles/layout.styl

Small bugfix for a small bug. Photos' layout was using UI's layout but overwrote some stuff it shouldn't.

fix: fix Photos layout

---

src/drive/styles/breadcrumb.styl
src/drive/styles/empty.styl
src/drive/styles/menu.styl
src/drive/styles/sidebar.styl
src/drive/styles/table.styl
src/photos/ducks/upload/styles.styl
src/photos/styles/addToAlbum.styl
src/photos/styles/albumsList.styl
src/photos/styles/createAlbumForm.styl
src/photos/styles/emptyAndError.styl
src/photos/styles/loading.styl
src/photos/styles/menu.styl
src/photos/styles/newAlbum.styl
src/photos/styles/photoList.styl
src/photos/styles/viewer.styl
src/photos/styles/viewerToolbar.styl
src/sharing/share.styl

Just using the good grey vars of UI, the depreciated ones will be removed in the next release of UI.

chore: use new grey vars

---

targets/drive/mobile/fastlane/metadata/android/en-US/full_description.txt
targets/drive/mobile/fastlane/metadata/android/fr-FR/full_description.txt
targets/drive/mobile/fastlane/metadata/ios/en-US/description.txt
targets/drive/mobile/fastlane/metadata/ios/en-US/privacy_url.txt
targets/drive/mobile/fastlane/metadata/ios/en-US/support_url.txt
targets/drive/mobile/fastlane/metadata/ios/fr-FR/description.txt

Updated the description of the app for each store in FR and EN.
Also updated the url of the privacy page for the App Store.

Update description of the app on iOS and Android + privacy page.

---

src/lib/redux-cozy-client/CozyAPI.js
src/lib/redux-cozy-client/CozyClient.js
src/lib/redux-cozy-client/__tests__/store.spec.js
src/lib/redux-cozy-client/connect.jsx
src/lib/redux-cozy-client/helpers.js
src/lib/redux-cozy-client/reducer.js
src/lib/redux-cozy-client/slices/sharings.js

@goldoraf what do you think? Isn't it cleaner?

refactor: cozy-redux-client

---

config/webpack.config.base.js
config/webpack.config.cozy-ui.js
config/webpack.config.dev.js
config/webpack.config.disable-contexts.js
config/webpack.config.manifest.js
config/webpack.config.pictures.js
config/webpack.config.preact.js
config/webpack.config.vendors.js
config/webpack.target.browser.js
config/webpack.target.mobile.js
src/drive/ducks/upload/styles.styl
src/drive/styles/confirms.styl
src/drive/styles/main.styl
src/drive/styles/table.styl
src/photos/ducks/upload/styles.styl
src/photos/styles/addToAlbum.styl
src/photos/styles/alerter.styl
src/photos/styles/confirms.styl
src/photos/styles/createAlbumForm.styl
src/photos/styles/layout.styl
src/photos/styles/main.styl
src/photos/styles/newAlbum.styl
src/sharing/components/autosuggest.styl
src/sharing/components/recipient.styl
src/sharing/share.styl
targets/photos/web/public/index.styl
webpack.config.js

see https://github.com/cozy/cozy-ui/pull/201

fix: import file only once

---

targets/drive/mobile/config.xml

https://github.com/cozy/cordova-plugin-list-library-items/releases/tag/v1.0.4

chore: upgrade list library items

---

src/drive/mobile/components/Settings.jsx
src/drive/mobile/containers/settings/About.jsx

Use Hammer to handle tap gesture instead of basic onClick

 🚑  Fix the complicated triple tap to show the support button on iOS

---

src/lib/cozy-client/slices/synchronization.js

Micro-fix to the sync code

---

config/webpack.target.mobile.js
package.json
src/drive/mobile/lib/cozy-helper.js
targets/drive/mobile/config.xml

This PR is dependent on https://github.com/cozy/cozy-client-js/pull/224, I will need to upgrade cozy-client-js once it's merged.

feat: use sqlite db for pouch on iOS

---

src/drive/mobile/styles/uploadprogression.styl

Resize, crop & fit image previews while uploading them.

🚑 Fix upload previews on mobile

---

src/drive/ducks/upload/styles.styl
src/drive/mobile/styles/onboarding.styl
src/drive/mobile/styles/settings.styl
src/drive/mobile/styles/uploadprogression.styl
src/drive/styles/actionmenu.styl
src/drive/styles/confirms.styl
src/drive/styles/filenameinput.styl
src/drive/styles/main.styl
src/drive/styles/sidebar.styl
src/drive/styles/table.styl
src/drive/styles/toolbar.styl
src/drive/styles/topbar.styl

From https://gitlab.cozycloud.cc/labs/cozy-bank/merge_requests/126
Comme vu avec Yannick, il reste quelques em() avec des bases différentes ;)

chore: remove em()

---

src/drive/mobile/ducks/mediaBackup/index.js

Most of the changes are just renaming variables for clarity, but the behavior should be identical. I'll highlight the one part that really changed below.

fix: respect network condition setting

---

src/drive/components/FolderView.jsx
src/drive/locales/en.json
src/drive/mobile/containers/MediaBackupProgression.jsx

- rename the component
- manage plural/single form

fix: media backup upload

---

src/drive/containers/File.jsx
src/drive/styles/table.styl

And I merged shared status and offline status into one column actually to avoid potential layout issues.

fix: Share status column is now hidden on mobile

---

package.json
yarn.lock

Upgrade to 4.5.0 which mostly fixes the app drawer icon problem on mobile.

chore: upgrade cozy bar

---

publish_registry.sh

There were a typo in the registry url : https://travis-ci.org/cozy/cozy-drive/builds/306209820
I'll merge it no matter what ;-)

fix: url registry

---

src/drive/mobile/containers/FirstUploadModal.jsx
src/drive/mobile/styles/uploadstatus.styl

Someone (hum,hum) fails to refactor without breaking things:
https://github.com/enguerran/cozy-drive/commit/71bb2027ee5f848e00d3eb9d73bc83d373d3166c#diff-bd80e7e0ab38cd29c6eb328468cd6b57

fix: firstuploadmodal styled button

---

src/drive/locales/en.json
src/photos/locales/en.json
src/sharing/ShareModal.jsx

feat: coming soon in sharebyemail

---

src/drive/containers/File.jsx
src/drive/ducks/services/components/SuggestionProvider.jsx

I refactor code from `File.jsx` to be able to get icon for `SuggestonProvider.jsx`.

feat: searchbar uses icons from File.jsx

---

src/sharing/ShareModal.jsx

with `width` it outreaches on mobile view.
with `max-width` it is good.

fix: maxwidth allows thin mobile screen

---

src/drive/containers/File.jsx

- application/vnd.oasis.opendocument.spreadsheet
- application/vnd.openxmlformats-officedocument.wordprocessingml.document
- application/octet-stream
- application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
- application/vnd.openxmlformats-officedocument.presentationml.presentation

fix: some mimetypes are superset of existing mimetype

---

src/drive/styles/nav.styl

Temporary fix was still here even though it wasn't needed anymore and actually it was messing with app list in the cozy-bar.

fix: cozy bar's apps on drive

---

src/components/Error/ErrorShare.jsx
src/components/Error/empty.styl

Some trailing typos from the previous refactoring of empty/erro views.

fix: Unshared error view

---

config/webpack.config.prod.js
package.json
targets/drive/web/index.ejs
targets/drive/web/public/index.ejs
targets/photos/web/index.ejs
yarn.lock

Related to https://github.com/cozy/cozy-client-js/pull/233

fix `can't convert undefined to object`

---

src/drive/locales/en.json
src/drive/mobile/assets/icons/icon-paperplane-blue.svg
src/drive/mobile/assets/icons/icon-paperplane-white.svg
src/drive/mobile/containers/MediaBackupProgression.jsx
src/drive/mobile/containers/RatingModal.jsx
src/drive/mobile/ducks/mediaBackup/UploadAbortedWifi.jsx
src/drive/mobile/ducks/mediaBackup/UploadProgression.jsx
src/drive/mobile/ducks/mediaBackup/UploadQuotaError.jsx
src/drive/mobile/ducks/mediaBackup/UploadUptodate.jsx
src/drive/mobile/ducks/mediaBackup/index.js
src/drive/mobile/ducks/mediaBackup/styles.styl
src/drive/mobile/styles/feedback.styl

Most changes are just because I split [one file into multiples](https://github.com/cozy/cozy-drive/pull/546/files#diff-d5df49947f20daea222c0c595047f1dbL1). 
The actual changes are :
- [a new component](https://github.com/cozy/cozy-drive/pull/546/files#diff-c5adba55890ddbfa6b6fb8bf48dd7538R1)
- [detecting the quota error](https://github.com/cozy/cozy-drive/pull/546/files#diff-d173561dcc55260e5a4050bb22efe48eR11)
- [minor css additions](https://github.com/cozy/cozy-drive/pull/546/files#diff-8c4e81d6be3ab034b04dfe94f956b64cR1)

feat: display message when quota is reached

---

src/drive/actions/index.js
src/drive/components/FilesViewer.jsx
src/drive/containers/FileExplorer.jsx
src/drive/reducers/view.js
src/lib/cozy-client/CozyClient.js
src/lib/cozy-client/adapters/CozyStackAdapter.js
src/lib/cozy-client/index.js
src/lib/cozy-client/withClient.jsx
src/viewer/AudioViewer.jsx
src/viewer/ImageViewer.jsx
src/viewer/NoViewer.jsx
src/viewer/VideoViewer.jsx
src/viewer/ViewerControls.jsx
src/viewer/styles.styl

See https://trello.com/c/1QG5e74x/592-5-ajouter-la-visionneuse-dimages-dans-drive for details

Viewer fixes take #2

---

src/components/Image/ImageLoader.jsx
src/drive/mobile/lib/filesystem.js
src/viewer/NoViewer.jsx
src/viewer/PdfViewer.jsx
src/viewer/Viewer.jsx
src/viewer/ViewerControls.jsx
src/viewer/styles.styl

This PR adds an embedded PDF viewer on desktop and fixes 1 bug and an usability issue (next/prev controls interfered with audio/video controls).
In agreement with our PO, I modified the CSS so that action buttons get aligned to the right and hide their labels. As the CSS is extending `$selectionbar`, this makes the CSS a bit messy but I can't find a better way without spending a lot of time on it...

Added PDF viewer

---

src/lib/cozy-client/collections/SharingsCollection.js

with minified source it is
r.byMe is undefined

fix: perms.byMe is undefined

---

src/drive/mobile/actions/unlink.js
src/drive/mobile/containers/DriveMobileRouter.jsx
src/drive/mobile/containers/RevokableWrapper.jsx
src/drive/mobile/containers/settings/Unlink.jsx
src/drive/mobile/lib/cozy-helper.js
src/drive/store/configureStore.js
src/lib/cozy-client/CozyClient.js
src/lib/cozy-client/reducer.js

Nearly the same thing as #525 — just fixed the conflicts.

Reset store

---

src/drive/mobile/containers/DebugTools.jsx
src/drive/mobile/styles/debugtools.styl
src/drive/mobile/styles/feedback.styl
src/photos/styles/photoList.styl

fix: forsaken buttons on mobile

---

src/viewer/NativePdfViewer.jsx

Regression introduced in cc60508aa182ecf9aae1866169e9275fe84c408e

fix: translations for native pdf viewer

---

package.json

Use an unique pattern : `task:app:target`
Je me trompe tout le temps dés que j'ai des tâches mobile à exécuter, donc je propose d'uniformiser tout ça.
En attendant bien sûr de migrer vers `create-cozy-app` dés que c'est prêt.

chore: proper package.json

---

src/lib/cozy-client/reducer.js

#581 is going to update our linting rules and these changes are needed (no camel case variables).

fix: linting

---

package.json

Clean `plugins/` and `platform/` before `cordova prepare`.

chore: clean plugins and platform before prepare

---

package.json

After #635, I had to update our `webpack-dev-server` command.

fix: update webpack server args

---

src/lib/cozy-client/package.json

Upgrade cozy-client version to 0.4.0 to release it.

chore: update cozy-client version

---

targets/drive/mobile/config.xml

see https://github.com/cozy/cordova-plugin-list-library-items/pull/7 for more details.

fix: update cordova plugin listlibraryitems

---

package.json
targets/drive/mobile/README.md

Fix documentation with current yarn commands.
Fix missing url-polyfill npm package.

Doc and config fixes on mobile developper onboarding.

---

src/drive/locales/en.json
src/drive/mobile/containers/MediaBackupProgression.jsx
src/drive/mobile/ducks/mediaBackup/UploadQuotaError.jsx

When the storage space is full, the button redirects the user to the storage page in settings, where he or she will be able to order extra space.

feat: redirect to the settings quota page

---

README.md

Pointing to the newest twitter, the other is no more used

Update Twitter account

---

src/drive/locales/en.json
src/drive/mobile/components/Settings.jsx
src/drive/mobile/containers/FeedbackForm.jsx
src/drive/mobile/containers/RatingModal.jsx
src/drive/mobile/containers/settings/Support.jsx
src/drive/mobile/lib/withPersistentState.js
yarn.lock

- 2b009667 (Enguerran, 23 seconds ago)
feat: :iphone: send feedback from settings
- 61b92abe (Enguerran, 4 hours ago)
refactor: ratingmodal components - remove binds - use class properties -
update syntax
- e0446255 (Enguerran, 28 hours ago)
chore: change scheme for pouchdb-adapter-cordova-sqlite dependence
git+https:// to https://

feat: :iphone: send feedback from settings

---

src/drive/mobile/containers/FeedbackForm.jsx

feat: send feedback to sentry

---

src/lib/cozy-client/__mocks__/cozy-client-js.js
src/lib/cozy-client/__tests__/stackAdapter.spec.js
src/lib/cozy-client/adapters/CozyStackAdapter.js
src/lib/cozy-client/helpers.js

- Renormalized data in update docs so that docs have a _type
- Added tests

fix: renormalize after update data

---

src/lib/cozy-client/package.json

Bump cozy-client version to 0.4.2

[cozy-client] chore: bump cozy-client version

---

package.json
src/lib/cozy-client/collections/SharingsCollection.js
src/lib/cozy-client/slices/sharings.js
src/sharing/components/ShareByLink.jsx
yarn.lock

~~Waiting for https://github.com/cozy/cozy-ui/pull/365 to be merged and a new `cozy-ui` release.~~

Revoke all sharing links for a given item

---

config/webpack.target.mobile.js
src/drive/mobile/lib/reporter.js

As discussed, we don't need 2 sentry projects, we can do everything we want with the `environment` tag.

chore: switch to single sentry project

---

targets/drive/mobile/fastlane/metadata/ios/en-US/description.txt

Update description with Cozy description

---

targets/drive/mobile/fastlane/metadata/android/en-US/full_description.txt

Update description with a Cozy description

---

config/webpack.config.dev.js
config/webpack.config.prod.js
package.json
targets/drive/mobile/README.md
yarn.lock

cc the banksters team since it might be of interest to you as well @kosssi @ptbrowne @drazik @doubleface

feat: add task to upload sourcemaps to sentry

---

package.json
yarn.lock

related to https://github.com/cozy/cozy-drive/pull/803 and https://github.com/cozy/cozy-bar/pull/179 and https://github.com/cozy/cozy-bar/pull/178 and https://github.com/cozy/cozy-bar/pull/177

feat: enable search bar from cozy-bar

---

package.json
src/photos/ducks/albums/components/AlbumsToolbar.jsx

- Fix album creation button
- Correction du bouton de création d'un album

fix: album creation link

---

src/components/Button/CozyHome.jsx
src/components/Button/CozyHomeLink.jsx
src/components/Button/index.jsx
src/drive/components/DownloadButton.jsx
src/drive/components/LightFolderView.jsx
src/drive/locales/en.json
targets/photos/web/public/App.jsx

Adds a button on the public pages that invites the user to create a cozy. Easy.

feat: added create cozy button

---

package.json
yarn.lock

So that modal on Safari gets its fix.

chore: update UI v7.9.2

---

package.json
src/drive/mobile/lib/__snapshots__/reporter.spec.js.snap
src/drive/mobile/lib/reporter.js
src/drive/mobile/lib/reporter.spec.js

I've copy-pasted some code from the internets.

Sentry sourcemaps upload — now with better pathes

---

README.md

doc: update link to mobile doc

---

targets/drive/mobile/main.jsx

fix: default value for persisted state

---

src/authentication/package.json
src/authentication/steps/Welcome.jsx

After having copied the function from `mobile/lib/device`, I skipped the function `isCordova` used by the helper :/

fix: undefined function when copied function

---

src/drive/actions/async.js
src/drive/components/FileList.jsx
src/drive/components/FilesViewer.jsx
src/drive/components/LightFolderView.jsx
src/drive/constants/config.js

We could take more time to understand what are all those `limit`, but it is a little bit overengineered if our purpose is to inscrease this limit on fetching files.

feat: files fetch limit to 100

---

src/viewer/Viewer.jsx

On desktop computer, the escape key is generally used to close the image preview.

Add escape key shortcut to close the Viewer.

---

src/drive/mobile/lib/cozy-helper.js
targets/drive/mobile/config.xml
targets/drive/mobile/main.jsx

this is used on cozy-stack to enhance statistics
https://trello.com/c/mg9hDsFD/935-fiabiliser-les-stats-des-apps-mobile

chore: change user-agent of fetch headers

---

src/drive/containers/File.jsx

Screenshot on mobile
Screenshot on desktop

feat: remove date display on folders

---

src/drive/mobile/lib/intents.js

Files shared through iOS don't have a proper mime type, so we have to forcefully set it.

fix: proper ios shared fle mime detection

---

.gitignore
package.json
src/authentication/package.json
src/authentication/yarn.lock
src/drive/actions/index.jsx
src/drive/components/FolderView.jsx
src/drive/containers/FileExplorer.jsx
src/drive/ducks/files/Container.jsx
src/drive/ducks/files/FileOpenerExternal.jsx
src/drive/ducks/files/Toolbar.jsx
src/drive/ducks/files/rename.js
src/drive/ducks/services/components/SuggestionProvider.jsx
src/drive/ducks/trash/actions.js
src/drive/ducks/upload/UploadQueue.jsx
src/drive/ducks/upload/index.js
src/drive/ducks/upload/styles.styl
src/drive/locales/en.json
src/drive/mobile/components/Settings.jsx
src/drive/mobile/containers/RatingModal.jsx
src/drive/mobile/containers/settings/Support.jsx
src/drive/mobile/lib/intents.js
src/drive/reducers/view.js
targets/drive/manifest.webapp
targets/drive/mobile/config.xml
targets/drive/mobile/fastlane/metadata/android/en-US/changelogs/151.txt
targets/drive/mobile/fastlane/metadata/android/fr-FR/changelogs/151.txt
targets/drive/web/services.jsx
yarn.lock

- Fixes icons in search results
- Fixes the inter-app file viewer and file download for some files
- updates the list of files after a new upload
- specific error message when offline while uploading a file

Release new version

---

package.json
src/drive/mobile/lib/cozy-helper.js
targets/drive/mobile/config.xml
targets/drive/mobile/main.jsx

The plugin didn't really work with iOS, but the `AppendUserAgent` preference seems to be doing the job!

fix: update user agent

---

src/lib/cozy-client/adapters/PouchdbAdapter.js
src/lib/cozy-client/reducer.js

When we use pouchdb we want to replicate pouch/couch every 30 seconds but for now only two replicate is launch.

fix: schedule replication 🐛

---

src/authentication/Revoked.jsx
src/drive/mobile/containers/DriveMobileRouter.jsx
src/drive/mobile/containers/RevokableWrapper.jsx
targets/drive/mobile/main.jsx

I've done a few things in this PR to stabilize the connexion process, i'll comment them below.

Transition from previous cozy-client on mobile

---

src/photos/ducks/albums/components/AlbumToolbar.jsx
src/photos/ducks/albums/index.js
targets/photos/web/public/App.jsx
targets/photos/web/public/index.ejs

This PR fixes various issues, mainly related to the sharing public page. I think the commit messages are sufficiently explicit.

Various Photos fixes

---

package.json
yarn.lock

Updated cozy-bar

---

package.json
src/drive/actions/async.js
src/drive/actions/index.jsx
src/drive/ducks/upload/index.js
src/drive/locales/en.json
src/drive/mobile/lib/background.js
src/drive/reducers/view.js
src/drive/store/configureStore.js
targets/drive/manifest.webapp
targets/drive/mobile/config.xml
targets/drive/mobile/main.jsx
targets/drive/web/main.jsx
targets/drive/web/public/main.jsx
targets/photos/manifest.webapp
yarn.lock

As the condition for determining if the displayed folder should show recent files first depends on localized paths, I had to bring the `t` function into the redux context. I again used the `withExtraArgument` method of `react-redux` thus the changes related to the store configuration.

Show recents files first when displaying an Administrative folder or backuped photos

---

package.json
src/drive/styles/layout.styl
targets/drive/mobile/config.xml
targets/drive/web/index.ejs

Corrects the layout problems on the iPhone X.

fix: iphonex UI

---

package.json
src/drive/actions/async.js
src/drive/actions/index.jsx
src/drive/components/FolderView.jsx
src/drive/components/Layout.jsx
src/drive/ducks/files/Container.jsx
src/drive/ducks/upload/index.js
src/drive/locales/en.json
src/drive/mobile/containers/RatingModal.jsx
src/drive/mobile/lib/background.js
src/drive/mobile/lib/constants.js
src/drive/reducers/view.js
src/drive/store/configureStore.js
src/drive/styles/layout.styl
src/sharing/SharingDetailsModal.jsx
src/sharing/__tests__/state.spec.js
src/sharing/components/Recipient.jsx
src/sharing/index.js
src/sharing/state.js
src/viewer/NoViewer.jsx
targets/drive/manifest.webapp
targets/drive/mobile/config.xml
targets/drive/mobile/main.jsx
targets/drive/web/index.ejs
targets/drive/web/main.jsx
targets/drive/web/public/main.jsx
targets/photos/manifest.webapp
yarn.lock

- Fix download file
- Add again the possibility to share one selected item
- Multiple fixes of sharing
- (mobile) Fix iPhone X layout
- (mobile) Fix iPhone rating 
- Files in "Administrative" and "Backuped from my mobile" are sorted "most recent first"
- Fix folder drag & drop on macOS
- Correction du bouton télécharger
- Réajout de la possibilité de partager un seul élément sélectionné
- Plusieurs corerctifs pour le partage
- (mobile) Correction de l'affichage sur iPhone X
- (mobile) Correction du module de notation sur iPhone
- Les fichiers dans "Administratif" et "Sauvegardées depuis mon mobile" sont triés du plus récent au plus ancien
- Correction du drag & drop de dossier sur macOS

Publish new version

---

src/lib/cozy-client/authentication/mobile.js

Cette PR permet d'utiliser le nouveau standard chez Apple pour ouvrir des pages avec Safari.
Cozy Banks a été bloqué pour le motif suivant:
> We noticed that the user is taken to Safari to sign in or register for an account, which provides a poor user experience.
>
> # Next Steps
>
> To resolve this issue, please revise your app to enable users to sign in or register for an account in the app.
>
> We recommend implementing the Safari View Controller API to display web content within your app. The Safari View Controller allows the display of a URL and inspection of the certificate from an embedded browser in an app so that customers can verify the webpage URL and SSL certificate to confirm they are entering their sign in credentials into a legitimate page.
Nous avons utilisé le plugin …

refactor: Use SafariViewController on registry 😇

---

src/drive/components/FileActionMenu.jsx
src/drive/containers/File.jsx
src/drive/styles/actionmenu.styl

Ellipsis on long filenames in the action menu

---

renovate.json

Ce n'est pas une heure pour bloquer le build de l'équipe ;)

Update schedule for renovate

---

package.json
src/drive/containers/File.jsx
src/drive/ducks/services/components/SuggestionProvider.jsx
src/drive/ducks/upload/UploadQueue.jsx
src/drive/ducks/upload/index.js
src/drive/ducks/upload/styles.styl
src/drive/lib/getFileMimetype.js
yarn.lock

In this PR, I also purged the queue when more files are added, and handled better the mimetypes' display in the queue.

Fixed upload queue's FOUC and other issues

---

src/drive/ducks/upload/UploadQueue.jsx
src/drive/ducks/upload/styles.styl

This reverts commit 640db78995874e0bbbd5171ade04afb0e60f701e.

Reverted tentative fix for the upload queue FOUC

---

package.json
targets/drive/manifest.webapp
targets/drive/mobile/config.xml
targets/drive/mobile/fastlane/metadata/android/en-US/changelogs/160.txt
targets/drive/mobile/fastlane/metadata/android/fr-FR/changelogs/160.txt
targets/photos/manifest.webapp

Updates version numbers and changelogs

Release prep

---

targets/drive/mobile/config.xml

Adds the safariviewcontroller plugin.

feat: enable cozy creation on iOS

---

src/sharing/ShareModal.jsx
src/sharing/components/ShareByEmail.jsx
src/sharing/index.jsx

- the tooltip was displayed all the time
- the sharing type was locked on link sharings

Fix tooltip

---

src/sharing/components/SharedStatus.jsx

Fixed shared-by-link indicator

---

src/sharing/ShareModal.jsx

The share modal didn't scroll when the content got bigger, now it does!

fix: Scrolling in share modal

---

src/sharing/components/Avatar.jsx
src/sharing/components/Recipient.jsx
src/sharing/components/recipient.styl
src/sharing/share.styl

If some contents were really long, the overflowing was off.

Share recipients style

---

src/drive/components/FileActionMenu.jsx
src/drive/ducks/files/Container.jsx
src/drive/styles/actionmenu.styl
src/sharing/components/Avatar.jsx
src/sharing/components/Recipient.jsx
src/sharing/components/recipient.styl
src/sharing/index.jsx

Not much to add, it's a rather straightforward change

Added sharing recipients to the action menu

---

package.json
src/drive/containers/RealtimeFiles.jsx
targets/drive/manifest.webapp
targets/drive/mobile/config.xml
targets/drive/mobile/fastlane/metadata/android/en-US/changelogs/180.txt
targets/drive/mobile/fastlane/metadata/android/fr-FR/changelogs/180.txt

- There's now a new view dedicated to shared files
- The existing UI around sharings has been improved
- Fixed a bug with contact details autocompletes not being available
- Changes made to files and folders elsewhere are now reflected in real time

Release next version

---

src/sharing/components/Recipient.jsx
src/sharing/components/ShareByEmail.jsx
src/sharing/components/autosuggest.styl
src/sharing/components/recipient.styl
src/sharing/share.styl

See individual commits for descriptions.

Sharing ui fixes

---

src/sharing/components/recipient.styl
src/sharing/index.jsx

Various UI fixes

---

src/drive/components/AppRoute.jsx
src/drive/containers/FileExplorer.jsx
src/drive/containers/Nav.jsx

Switching back to regular routing instead of preloading the content on the previous view.

feat: Instantly switch views when navigating

---

src/sharing/ShareModal.jsx
src/sharing/share.styl

Make the zone with share by link + recipients list scrollable.

fix: Adjust scrolling in sharing modal

---

src/components/Menu/index.jsx
src/components/Menu/index.styl
src/drive/locales/en.json
src/sharing/share.styl

A few fixes, commits are describing what goes on.

Various fixes

---

package.json
src/drive/mobile/containers/MediaBackupProgression.jsx
src/drive/mobile/ducks/mediaBackup/UploadProgression.jsx
src/drive/mobile/ducks/mediaBackup/index.js
src/drive/mobile/ducks/mediaBackup/reducer.js
src/drive/mobile/ducks/mediaBackup/styles.styl
src/drive/mobile/lib/media.js
targets/drive/mobile/config.xml

Uses th newest version of the syncing plugin.

Show sync progress

---

src/photos/locales/en.json
src/sharing/ShareModal.jsx
src/sharing/state.js

The album sharing by link failed because of a typo (and there were missing locale keys). I also disabled cozy-to-cozy sharing because it's insufficiently tested.

Yet another fix to album sharing by link

---

package.json
src/photos/locales/en.json
src/sharing/ShareModal.jsx
src/sharing/state.js
targets/drive/manifest.webapp
targets/drive/mobile/config.xml
targets/drive/mobile/fastlane/metadata/android/en-US/changelogs/190.txt
targets/drive/mobile/fastlane/metadata/android/fr-FR/changelogs/190.txt
targets/photos/manifest.webapp

Release version 1.9.0

---

src/drive/store/persistedState.js

Just a small possible bug I found later on.

fix: Prev state didn't always have authorization prop

---

package.json
src/photos/ducks/albums/index.js
src/photos/ducks/timeline/index.js
yarn.lock

A few fixes for stuff I broke while updating cozy-client.

Cozy client fixes

---

src/photos/components/LoadMoreButton.jsx
src/photos/components/PhotoBoard.jsx
src/photos/ducks/albums/components/AlbumsList.jsx
src/photos/ducks/albums/components/AlbumsView.jsx

Added fetchMore on albums view

---

src/photos/components/Topbar.jsx
src/photos/ducks/albums/components/AlbumToolbar.jsx
src/photos/ducks/albums/index.js
src/photos/styles/topbar.styl

The commits are explicit about what they do. 
The last one is a bit strange, there's more context [here](https://github.com/cozy/cozy-client/issues/144).

Multiple fixes on photos

---

src/photos/components/Topbar.jsx

Messed up with the return button on desktop.

fix: Album back button on desktop

---

src/drive/web/modules/navigation/duck/actions.jsx
src/drive/web/modules/navigation/duck/reducer.js

Remove reducer updates, seems that RealTime is already doing the work

fix: Drive file upload. 

---

src/drive/mobile/lib/cozy-helper.js
src/drive/mobile/modules/authorization/UserActionRequired.jsx
src/drive/mobile/modules/authorization/duck/reducer.js
src/drive/store/persistedState.js
src/drive/web/modules/navigation/RealtimeFiles.jsx
targets/drive/mobile/config.xml
targets/drive/mobile/main.jsx

A few standalone fixes — the commits are explicit.

Multiple bugfixes

---

package.json
src/drive/mobile/lib/cozy-helper.js
src/drive/mobile/modules/authorization/UserActionRequired.jsx
src/drive/mobile/modules/authorization/duck/reducer.js
src/drive/store/persistedState.js
src/drive/web/modules/navigation/RealtimeFiles.jsx
targets/drive/manifest.webapp
targets/drive/mobile/config.xml
targets/drive/mobile/fastlane/metadata/android/en-US/changelogs/1100.txt
targets/drive/mobile/fastlane/metadata/android/fr-FR/changelogs/1100.txt
targets/drive/mobile/main.jsx
targets/photos/manifest.webapp

Release version 1.10.0

---

package.json

feat: Add debug build to android command

---

src/drive/locales/en.json
src/drive/web/modules/drive/Toolbar.jsx

We don't want this button anymore!

fix: Removed get my bills button

---

package.json
targets/drive/mobile/config.xml

Adds a number for android builds so that wen can upload several builds for the same version code, if needed.

Android build number

---

package.json
src/drive/lib/upgradePouchDatabase.js
src/drive/mobile/lib/cozy-helper.js
src/drive/mobile/lib/replication.js
targets/drive/web/services.jsx
yarn.lock

Migrates our databases from websql to idb !

Websql migration

---

targets/drive/manifest.webapp
targets/drive/web/index.ejs
targets/drive/web/public/index.ejs
targets/drive/web/services.ejs
targets/photos/manifest.webapp
targets/photos/web/index.ejs
targets/photos/web/public/index.ejs

* Changes in manifest
* Changes in all .ejs files

Use name_prefix Cozy

---

src/drive/web/modules/drive/Toolbar/components/UploadItem.jsx
src/drive/web/modules/drive/Toolbar/toolbar.jsx
targets/drive/mobile/config.xml
targets/drive/mobile/translations/app/en.json
targets/drive/mobile/translations/app/fr.json

With dispatching an action, it works much better

fix: Upload file manually 

---

targets/drive/web/services.jsx
targets/photos/web/public/App.jsx

Release hotfixes

---

src/drive/lib/upgradePouchDatabase.js
src/drive/mobile/lib/replication.js

All indexes were not properly migrated from websql to idb, this PR fixe the problem.

Force Index migration on mobile

---

package.json
src/drive/mobile/lib/cozy-helper.js
src/photos/ducks/albums/index.js
src/viewer/ViewerControls.jsx
targets/drive/doctypes.js
targets/drive/web/main.jsx
targets/drive/web/public/main.jsx
targets/drive/web/services.jsx
targets/photos/web/doctypes.js
yarn.lock

chore: Upgrade to CozyClient 2.22.4

---

src/photos/ducks/albums/index.js

Repeat after me, do not use Constructor's name to test thing

fix: Test if validate is a function to get the right client

---

package.json
src/drive/locales/en.json
src/drive/styles/actionmenu.styl
src/drive/styles/confirms.styl
src/drive/web/modules/drive/Toolbar/share/SharedRecipients.jsx
src/drive/web/modules/navigation/breadcrumb.styl
src/photos/locales/en.json
src/sharing/ShareModal.jsx
src/sharing/assets/icons/icon-cross-bold.svg
src/sharing/components/Recipient.jsx
src/sharing/components/ShareAutosuggest.jsx
src/sharing/components/ShareByEmail.jsx
src/sharing/components/ShareByLink.jsx
src/sharing/components/autosuggest.styl
src/sharing/components/button.styl
src/sharing/components/recipient.styl
src/sharing/index.jsx
yarn.lock

Probably easiest to review commit by commit, they are very atomic.
We should wait a bit before merging this, as the recently introduced `body-scroll-lock` in the modals seem to be faulty on some browser (chrome responsive, but still investigating).

Lots of UI fixes

---

targets/drive/web/index.ejs
targets/drive/web/public/index.ejs
targets/drive/web/services.ejs
targets/photos/web/index.ejs

See https://www.w3.org/TR/appmanifest/#obtaining

fix: Send cookies when fetching manifest.json

---

package.json
src/drive/locales/en.json
src/drive/web/modules/drive/Container.jsx
src/drive/web/modules/move/MoveFooter.jsx
src/drive/web/modules/move/MoveHeader.jsx
src/drive/web/modules/move/MoveModal.jsx
yarn.lock

Still requires a new version of cozy-ui before we can merge it, but the rest should be good to go!

Move multiple files and folders

---

src/sharing/components/Recipient.jsx

Seems that having an object for key is not a good idea ...

fix: Sharing Recipients list

---

targets/photos/web/public/App.jsx
targets/photos/web/public/index.styl

After fixing the mobile view I accidentally made the desktop view slightly worse :/

fix(PublicAlbum): Better desktop view

---

config/expose-react.js
config/webpack.target.browser.js
package.json
targets/drive/web/main.jsx
targets/drive/web/public/main.jsx
targets/drive/web/services.jsx
targets/photos/web/main.jsx
yarn.lock

The cozy-bar is now using react by default, but we want it to use preact — for that we have to expose preact under the "react" name in the global scope.

feat: Expose preact as react

---

package.json
src/drive/lib/doctypes.js
src/drive/mobile/modules/authorization/UserActionRequired.jsx
src/drive/mobile/modules/mediaBackup/duck/index.js
src/drive/web/modules/navigation/RealtimeFiles.jsx
src/folder-references/index.js
src/photos/ducks/timeline/components/Timeline.jsx
src/photos/ducks/timeline/index.js
src/photos/locales/en.json
targets/drive/mobile/main.jsx
yarn.lock

Needs this [PR](https://github.com/cozy/cozy-client/pull/241) from cozy-client, and the doctypes/references will need to be declared in only one place for drive and photos before we merge this. But the rest should be ok!

Uploading photos to the correct folder

---

src/drive/styles/filelist.styl

Tested on Android & iOS seems to work as expected.

fix: Selection scroll mobile

---

package.json
src/drive/lib/doctypes.js
src/photos/ducks/clustering/consts.js
src/photos/ducks/clustering/settings.js
targets/photos/manifest.webapp
targets/photos/services/onPhotoUpload.js
yarn.lock

Note that nothing will be active, as I haven't defined the trigger in the manifest yet

Initialize clustering

---

jest.config.json
src/authentication/.babelrc
src/authentication/.gitignore
src/authentication/examples/index.html
src/authentication/examples/index.js
src/authentication/package.json
src/authentication/src/Authentication.jsx
src/authentication/src/Authentication.spec.jsx
src/authentication/src/Revoked.jsx
src/authentication/src/steps/SelectServer.jsx
src/authentication/src/steps/Welcome.jsx
src/authentication/webpack.config.js
src/authentication/yarn.lock

- Use latest cozy-ui (transpiled). Fixed a bug where cozy-ui leaked the [aria-hidden] { display: none} style.
- Supports the new cozy-client (along with the old)

feat: Improve cozy-authentication

---

src/photos/ducks/clustering/consts.js
src/photos/ducks/clustering/gradient.js
src/photos/ducks/clustering/service.js
src/photos/ducks/clustering/service.spec.js
targets/photos/services/onPhotoUpload.js

This is the actual clustering method. It works by finding inflection angle between reachabilities, that represent a significant variation in the photos, and therefore interpreted as a new cluster.
We also use a `maxBound` parameter as a noise detector in case a reachability is really high, e.g. 2 photos with several days and several km apart.

Add clustering by gradient method

---

src/photos/ducks/clustering/albums.js
src/photos/ducks/clustering/metrics.js
src/photos/ducks/clustering/service.js
src/photos/ducks/clustering/service.spec.js
targets/photos/services/onPhotoUpload.js

Note there is no test yet as we discovered some bugs impacting jest that need to be fixed first through their own PR.

Save clustering results

---

jest.config.json
jestHelpers/mocks/fileMock.js
jestHelpers/mocks/iconMock.js
src/components/pushClient/Banner.jsx
src/components/pushClient/Button.jsx
src/drive/web/modules/navigation/duck/actions.jsx
src/drive/web/modules/trash/Toolbar.jsx
src/sharing/components/ShareButton.jsx
src/sharing/components/SharedBadge.jsx
src/sharing/components/SharedStatus.jsx

Creating this PR so we don't forgot about this. Adding tests is currently a pain in the ass, because importing almost any component imports a lot of things and jest can't handle everything. This PR reworks the config until it works, but it's not finished yet.

Updated test config

---

src/drive/styles/filelist.styl
src/drive/web/modules/navigation/breadcrumb.styl
src/drive/web/modules/upload/styles.styl
src/photos/ducks/upload/styles.styl

Replaces some of our hard-coded color codes by variables. The simpler ones.

fix: Use more color variables

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/photos/targets/manifest.webapp

because we just published 1.14.1 on the AppStore & PlayStore

chore: Version 1.14.2

---

jest.config.json
package.json
src/drive/web/modules/drive/FolderContainer.jsx
src/drive/web/modules/drive/FolderContainer.spec.jsx
src/drive/web/modules/drive/RecentContainer.jsx
src/drive/web/modules/drive/RecentContainer.spec.jsx
src/drive/web/modules/drive/__snapshots__/FolderContainer.spec.jsx.snap
src/drive/web/modules/drive/__snapshots__/RecentContainer.spec.jsx.snap
src/drive/web/modules/drive/index.jsx
src/drive/web/modules/filelist/File.jsx
src/drive/web/modules/filelist/File.spec.jsx
src/drive/web/modules/navigation/duck/reducer.js
src/drive/web/modules/navigation/duck/reducer.spec.js
src/sharing/components/WhoHasAccessLight.jsx
yarn.lock

- display path of the parent folder under the filename
- click on the path redirects to parent folder
https://trello.com/c/J9GzS2Ao

fix: path in Recent view

---

package.json
src/photos/ducks/albums/index.jsx
src/photos/targets/public/App.jsx
yarn.lock

This PR reverts some of the previous changes we made, where we load photos as part of their parent album. We still keep the spinners we added last time though!
Needs https://github.com/cozy/cozy-client/pull/306 or the photo pagination will be broken.

feat: Fetch photos through relationships

---

src/photos/ducks/albums/index.jsx
src/photos/targets/public/App.jsx

Minor stuff I forgot to revert in my previous PR.

fix: Public album loading

---

src/drive/web/modules/navigation/duck/actions.jsx
src/drive/web/modules/navigation/duck/async.js
src/drive/web/modules/navigation/duck/reducer.js

Always sort by name by default

fix: Never sort by update date by default

---

package.json
yarn.lock

Bug Fixes: https://github.com/CPatchane/create-cozy-app/pull/1042

feat(deps): Upgrade Cozy-Scripts

---

src/photos/targets/browser/index.jsx

feat: Require DevTools

---

src/drive/lib/reporter.js
src/drive/mobile/modules/authorization/DriveMobileRouter.jsx
src/drive/targets/browser/index.jsx
src/drive/targets/manifest.webapp
src/drive/targets/public/index.jsx
src/photos/targets/browser/index.jsx
src/photos/targets/manifest.webapp
src/photos/targets/public/index.jsx

- Add instance tag with the cozy url 
- Add Sentry to Photos

feat(Drive/Photos): Add Instance Tag to Senty

---

package.json
src/photos/ducks/albums/index.jsx
src/photos/targets/browser/doctypes.js
yarn.lock

Follow-up of https://github.com/cozy/cozy-drive/pull/1355/files#diff-b99860e2348055cdd5e05388380200ddR49

fix: Better adding and removing photos from albums

---

src/photos/components/Loading.jsx
src/photos/components/PhotoList.jsx
src/photos/components/UploadButton.jsx
src/photos/ducks/upload/UploadQueue.jsx

To use new selector in testcafe, I must add 'data-test-id' to some components

refactor: Add data-test-id to some components

---

src/sharing/components/ShareAutosuggest.jsx

fix(ShareAutosuggest): Unique key is the key

---

src/drive/targets/browser/index.ejs
src/drive/targets/intents/index.ejs
src/drive/targets/public/index.ejs
src/photos/targets/browser/index.ejs
src/photos/targets/public/index.ejs

feat: Add CSS theme

---

.travis.yml
scripts/deploy-tests.sh

all instances are in the script for now, should we put them in travis encypted env vars ?

chore(travis): Add script to choose testing instance

---

scripts/downcloud.js

Left over typo after rebasing things :)

chore: Fix downcloud upload script

---

src/viewer/CallToAction.jsx
src/viewer/NoViewer.jsx

I know this is not the best solution to this problem but let's create a new card for that. 
Here, we just want to catch the exception if the call is made on a public page.

fix: Catch exception on public page

---

.travis.yml
scripts/deploy-on-instance.sh

Deploying drive and photos on instances using rundeck
This PR is deploy only (I don't check for Execution State yet, as it's another card..)

chore(travis): Deploy on instance using rundeck

---

package.json
src/authentication/examples/index.js
src/authentication/src/steps/Welcome.jsx
src/authentication/src/styles.styl
yarn.lock

No breaking changes for us because:
- We still use a custom avatar component, so the size changes don't affect us yet
- We don't use the stylesheet from cozy-ui (because I don't think we need it? We import the stuff we really want.)

fix: Upgrade cozy-ui

---

scripts/downcloud.js

We need different version number in order to use the rundeck jobs

chore(travis): Modify dev version in Manifest

---

package.json
src/drive/web/modules/navigation/RealtimeFiles.jsx
yarn.lock

Lot of bugfixes and improvements in this new version

Update v2 realtime

---

src/drive/mobile/lib/constants.js
src/drive/mobile/modules/settings/RatingModal.jsx

See https://docs.cozy.io/en/cozy-stack/auth/#linked-applications

feat: Link the mobile and web Drive applications

---

src/drive/targets/browser/index.ejs
src/drive/targets/intents/index.ejs
src/drive/targets/public/index.ejs
src/photos/targets/browser/index.ejs
src/photos/targets/public/index.ejs

This reverts commit 167b8bb75d4456b5126f57984ce6ec0f8038378e.

Revert "chore: Use the favicon from the stack"

---

src/photos/ducks/clustering/consts.js
src/photos/ducks/clustering/files.js
src/photos/targets/manifest.webapp
src/photos/targets/services/onPhotoUpload.js

This is the first PR of an incoming serie about the clustering execution by batch.

 feat: Add a limit to the clustering 

---

testcafe/runner-photos.js
testcafe/tests/pages/photos-album-model.js
testcafe/tests/photos/create_empty_album_scenario.js

this PR will need rebase after https://github.com/cozy/cozy-drive/pull/1453 is merge
[ feat(testcafe): Create empty album scenario](/cozy/cozy-drive/pull/1460/commits/1856cbeee24bdbc146e307a44db2f333820eeece) is the 'real' commit for this PR.
[feat(testcafe) : Photo album full #1453](/cozy/cozy-drive/pull/1460/commits/f13c5b8a3c51a767416873f6b0feb4980da14499)  is just getting the changes from [PR1453](https://github.com/cozy/cozy-drive/pull/1453) as the changes are needed to run this PR

Testcafe : Create empty album scenario

---

.travis.yml

I don't know why we don't build on tag since the regex is right :/

chore(Travis): Remove only for now

---

scripts/deploy-and-test-on-instance.sh

This PR is for investigation : 
add echo on curl to investigate when rundeck is not running

fix(travis): sometimes rundeck doesn't launch

---

package.json
yarn.lock

cc @cedricmessiant FYI, but it's just an upgrade so i'll merge it once the CI is happy.

fix: Upgrade cozy-bar

---

src/drive/locales/en.json
src/drive/mobile/modules/settings/components/SettingCategory.jsx
src/drive/mobile/modules/settings/components/Unlink.jsx
src/drive/mobile/modules/settings/components/Unlink.spec.jsx
src/drive/mobile/modules/settings/components/__snapshots__/Unlink.spec.jsx.snap

Updated the wording and removed the confirmation modal.

feat: Update unlink process

---

.travis.yml

This was actually working as expected.

Revert "chore(Travis): Remove only for now"

---

src/drive/web/modules/services/components/Embeder.jsx
src/viewer/PdfJsViewer.jsx
src/viewer/PdfJsViewer.spec.jsx
src/viewer/styles.styl

Commit messages speak for themselves!

Pdf updates

---

src/drive/mobile/lib/cozy-helper.js
src/drive/targets/browser/index.jsx
src/drive/targets/public/index.jsx
src/photos/targets/browser/index.jsx
src/photos/targets/public/index.jsx

Used by custom versions of cozy-bar

Inject CozyClient

---

src/drive/web/modules/drive/FileOpenerExternal.jsx
src/drive/web/modules/public/LightFolderView.jsx
src/drive/web/modules/services/components/Embeder.jsx
src/drive/web/modules/viewer/FilesViewer.jsx
src/photos/components/PhotosViewer.jsx
src/viewer/PdfJsViewer.jsx
src/viewer/controls.styl
src/viewer/styles.styl

Needs #1523 + rebase to be merged, but can already be reviewed.
- Enable horizontal and vertical scrolling inside a zoomed pdf
- Makes sure the viewer is correctly displayed in all situations

Viewer improvements

---

src/drive/targets/manifest.webapp
src/photos/targets/manifest.webapp

* Explicit default to [ALL]
* Fix methods prop and use verbs instead. This
change could imply regressions ⚠️

chore(manifest): Fix permissions 📝

---

src/drive/web/modules/filelist/FilePlaceholder.jsx

Missed the new column on the placeholder view.

fix: Add loading-placeholder for icon

---

src/components/Error/ErrorShare.jsx
src/photos/components/ErrorUnshared.jsx
src/photos/components/Photo.jsx
src/photos/components/__snapshots__/ErrorUnshared.spec.js.snap
src/photos/targets/public/App.jsx
src/photos/targets/public/__snapshots__/App.spec.jsx.snap
testcafe/runner-photos.js
testcafe/tests/pages/drive-viewer/drive-viewer-model.js
testcafe/tests/pages/photos-album/album-model.js
testcafe/tests/pages/photos-viewer/photos-viewer-model.js
testcafe/tests/pages/photos/photos-model-public.js
testcafe/tests/pages/viewer/viewer-model.js
testcafe/tests/photos/album_sharing_scenario.js
testcafe/tests/photos/photos_start_upload_photos.js

Testcafé : Album link sharing Scenario 

---

src/drive/web/modules/actionmenu/ActionMenu.jsx
src/drive/web/modules/move/Explorer.jsx
src/drive/web/modules/trash/Toolbar.jsx
testcafe/runner-drive.js
testcafe/tests/drive/classification_scenario.js
testcafe/tests/drive/public-viewer-feature.js
testcafe/tests/helpers/data.js
testcafe/tests/helpers/visualreview-utils.js
testcafe/tests/pages/drive-viewer/drive-viewer-model-public.js
testcafe/tests/pages/drive-viewer/drive-viewer-model.js
testcafe/tests/pages/drive/drive-modal-model.js
testcafe/tests/pages/drive/drive-model-private.js
testcafe/tests/pages/drive/drive-model.js
testcafe/tests/pages/photos-album/album-model.js
testcafe/tests/pages/photos-viewer/photos-viewer-model.js
testcafe/tests/pages/photos/photos-model.js
testcafe/tests/pages/photos/photos-timeline-model.js

OK for Review
(CI might still be running as a 2nd run is needed to validate new screenshots)

Drive classification scenario

---

package.json
yarn.lock

fix Screenshots size problem on Mac

chore: upgrade testcafe to 1.1.2

---

src/photos/locales/en.json

fix(Photo): Upload string

---

package.json
src/drive/mobile/modules/settings/Settings.jsx
src/drive/web/modules/navigation/ScrollToTop.jsx
yarn.lock

- Upgrade cozy-ui to fix bug scroll after creating a new folder 
- Add ScrollToTop component in order to scrollTo when we mount <Settings />

Fix: some bugs

---

testcafe/runner-drive.js
testcafe/runner-photos.js
testcafe/tests/drive/file_sharing_scenario.js
testcafe/tests/drive/folder_sharing_scenario.js
testcafe/tests/drive/public-viewer-feature.js
testcafe/tests/helpers/data.js
testcafe/tests/helpers/utils.js
testcafe/tests/helpers/visualreview-utils.js
testcafe/tests/photos/album_sharing_scenario.js

Fix several problem on travis 
All fixes in on PR to really check Travis status (and easier for everyone to rebase after merge)
See trello links below for more info on thoses problems
OLD PR : 
- https://github.com/cozy/cozy-drive/pull/1594
- https://github.com/cozy/cozy-drive/pull/1590
- https://github.com/cozy/cozy-drive/pull/1595

Fix: Travis troubles

---

testcafe/tests/drive/classification_scenario.js
testcafe/tests/drive/file_sharing_scenario.js
testcafe/tests/drive/folder_sharing_scenario.js
testcafe/tests/drive/public-viewer-feature.js
testcafe/tests/drive/viewer-feature.js
testcafe/tests/helpers/data.js
testcafe/tests/helpers/visualreview-utils.js
testcafe/tests/pages/drive-viewer/drive-viewer-model-public.js
testcafe/tests/pages/drive-viewer/drive-viewer-model.js
testcafe/tests/pages/drive/drive-model-private.js
testcafe/tests/pages/photos-viewer/photos-viewer-model.js
testcafe/tests/pages/photos/photos-timeline-model.js
testcafe/tests/pages/viewer/viewer-model.js
testcafe/tests/photos/album_sharing_scenario.js
testcafe/tests/photos/photos_end_delete_all_data.js
testcafe/tests/photos/photos_start_upload_photos.js

New/Modified screenshots listed on trello card
We need to remove baseline screenshots to see the new masks

fix: add/modify mask for visual review screenshots

---

src/drive/targets/intents/index.jsx

fix: Import transpiled css on interapp view

---

package.json
src/drive/targets/browser/index.jsx
src/drive/targets/intents/index.jsx
src/drive/targets/mobile/index.jsx
src/drive/targets/public/index.jsx
src/lib/react-cozy-helpers/importTranspiledCozyUi.js
src/photos/targets/browser/index.jsx
src/photos/targets/public/index.jsx
yarn.lock

Fix transpiled imports

---

package.json
src/drive/targets/browser/index.jsx
src/drive/targets/intents/index.jsx
src/drive/targets/mobile/index.jsx
src/drive/targets/public/index.jsx
src/lib/react-cozy-helpers/importTranspiledCozyUi.js
src/photos/targets/browser/index.jsx
src/photos/targets/public/index.jsx
yarn.lock

These 2 commits were part of the 1.18.1 release, I'm applying them to master as well.

Cherry pick 1.18.1 fixes

---

src/photos/components/AppRoute.jsx
src/photos/components/Loading.jsx
src/photos/components/PhotoBoard.jsx
src/photos/targets/public/App.jsx
src/photos/targets/public/index.jsx

- Sets the color of spinners on the `Loading` component — the prop was never used as far as I can tell
- The spinner on the public album wasn't showing up because the `<IconSprite />` was included only on a specific code path, but we need it all the time

Photos spinners

---

src/drive/mobile/lib/handleDeepLink.js
src/drive/mobile/lib/handleDeepLink.spec.js

To implement univerlink we need to add redirect params.

feat(deeplink): Remove fallback params is present

---

src/drive/styles/actionmenu.styl
src/drive/styles/toolbar.styl
src/drive/web/modules/upload/UploadButton.jsx

- The upload button in the main toolbar did not take the whole width
- The "toggle offline" menu item was mis-aligned

Menu display issues

---

package.json
src/drive/targets/browser/index.jsx
src/drive/targets/intents/index.jsx
src/drive/targets/mobile/index.jsx
src/drive/targets/public/index.jsx
src/lib/react-cozy-helpers/importTranspiledCozyUi.js
src/photos/targets/browser/index.jsx
src/photos/targets/public/index.jsx
yarn.lock

- UI upgrade 
- UI has a side effect for css, we can remove our internal hack (https://github.com/cozy/cozy-ui/commit/e41eac8c5533b17b7f2e2b81ffe7e9fad114d8bf)

fix: Upgrade UI

---

jest.config.json
package.json
src/drive/lib/doctypes.js
src/models/Contact.js
src/models/Contact.spec.js
src/models/index.js
src/sharing/components/ContactSuggestion.jsx
src/sharing/components/ContactSuggestion.spec.jsx
src/sharing/components/EditableSharingModal.jsx
src/sharing/components/Recipient.jsx
src/sharing/components/ShareAutosuggest.jsx
src/sharing/components/ShareByEmail.jsx
src/sharing/components/ShareModal.jsx
src/sharing/components/SharedStatus.jsx
src/sharing/components/__snapshots__/ContactSuggestion.spec.jsx.snap
src/sharing/index.jsx
yarn.lock

Use fullname if we have it. Else, use primary email.

Display fullname in suggestions if possible

---

src/models/Contact.js
src/models/Contact.spec.js
src/sharing/components/EditableSharingModal.jsx
src/sharing/components/Recipient.jsx
src/sharing/components/ShareByEmail.jsx
src/sharing/components/ShareModal.jsx
src/sharing/components/ShareRecipientsInput.jsx
src/sharing/propTypes.js

- Fixes a few regressions in sharing modal
- Use constants for contacts and groups propTypes and use them everywhere, add propTypes for `EditableSharingModal` component

Fixes to sharing

---

package.json
src/components/pushClient/Banner.jsx
src/components/pushClient/Button.jsx
yarn.lock

To go along with the Cozy-UI PR https://github.com/cozy/cozy-ui/pull/904
~~📌 Waiting for a Cozy-UI release…~~

feat: update button client icon method

---

package.json
testcafe/tests/drive/classification_scenario.js
testcafe/tests/drive/file_sharing_scenario.js
testcafe/tests/drive/folder_sharing_scenario.js
testcafe/tests/drive/public-viewer-feature.js
testcafe/tests/drive/viewer-feature.js
testcafe/tests/helpers/comment-on-github.js
testcafe/tests/helpers/logger.js
testcafe/tests/helpers/utils.js
testcafe/tests/helpers/visualreview-utils.js
testcafe/tests/pages/drive-viewer/drive-viewer-model-public.js
testcafe/tests/pages/drive-viewer/drive-viewer-model.js
testcafe/tests/pages/drive/drive-model-private.js
testcafe/tests/pages/drive/drive-model.js
testcafe/tests/pages/photos-album/album-model.js
testcafe/tests/pages/photos-viewer/photos-viewer-model.js
testcafe/tests/pages/photos/photos-model.js
testcafe/tests/pages/photos/photos-timeline-model.js
testcafe/tests/pages/viewer/viewer-model.js
testcafe/tests/photos/album_sharing_scenario.js
testcafe/tests/photos/photos_start_upload_photos.js
yarn.lock

Change console.log to use minilog

chore(testcafe): better logs in tests

---

src/drive/styles/layout.styl
src/drive/web/modules/layout/Layout.jsx

We can do without this stylefile now.

refactor: Removed unused code

---

testcafe/tests/drive/classification_scenario.js

./reports/ClassicationScenario/2-1 Rename file-1-rename1.png
./reports/ClassicationScenario/2-1 Rename file-2-rename1.png

fix: Add mask

---

scripts/rundeck.sh

Fixing the following error : 
```
↳ ℹ️  Creating instance...
EXECUTION_ID (or Error Output) : 57144
↳ Job running
↳ Job running
↳ Job succeeded
↳ ✅ Execution 57144 succeeded
↳ ℹ️  Instance testautophotos1634.cozy.rocks
↳ ℹ️  Password 1a8594520cbc8a9555f8
↳ ℹ️  Creating archive build/photos/photos.tar.gz
↳ ℹ️  Updating manifest version to 1.18.3-dev.209993a9aaaafd8c531088fa7beb4b4d90fb428c-525857500
↳ ℹ️  Sending artifact to downcloud
↳ ℹ️  Upload to downcloud complete.
↳ ✅ Upload complete, artifact available at https://downcloud.cozycloud.cc/upload/photos/mobile/1.18.3-209993a9aaaafd8c531088fa7beb4b4d90fb428c/photos.tar.gz
↳ ℹ️  Deploying photos (https://downcloud.cozycloud.cc/upload/photos/mobile/1.18.3-209993a9aaaafd8c531088fa7beb4b4d90fb428c/photos.tar.gz) on …
```

fix: Retry 3 times instead of one for rundeck conflicts

---

src/drive/web/modules/filelist/FileListBody.jsx
src/sharing/components/SharedDocuments.jsx

Remove 2 props related warnings in js console

Fix warnings in js console

---

package.json
yarn.lock

- filter on message sent by react-dev-tools 
- unique key on intent search

fix: Remove lot of messages in the console

---

package.json
yarn.lock

Fixes upload conflict (adds `uploadFile` method)

chore: Upgrade cozy-client to 6.33.0

---

src/drive/targets/manifest.webapp

fix: Email permission for web app

---

testcafe/tests/drive/search.js
testcafe/tests/helpers/data.js
testcafe/tests/pages/drive/drive-model-private.js
testcafe/tests/pages/selectors.js

remove Wait, and add condition on selector :  
`Selector('.coz-searchbar-autosuggest-suggestion-content').nth(value)` or `Selector(  '.coz-searchbar-autosuggest-status-container')`
for taking screenshots on search scenario

fix: Use selector instead of wait on search

---

package.json
src/drive/targets/browser/index.jsx
src/drive/targets/mobile/InitAppMobile.jsx
src/drive/web/modules/upload/index.js
src/drive/web/modules/upload/index.spec.js
src/models/index.js
yarn.lock

Depends on https://github.com/cozy/cozy-libs/pull/454

fix: Path in root directory (use CozyFile model)

---

package.json
yarn.lock

https://github.com/DevExpress/testcafe/releases/tag/v1.2.0

chore: Update to testcafe 1.2.0

---

package.json
src/drive/styles/toolbar.styl
src/drive/web/modules/upload/UploadButton.jsx
src/photos/components/UploadButton.jsx
src/photos/styles/toolbar.styl
testcafe/tests/pages/drive/drive-model-private.js
testcafe/tests/pages/photos/photos-timeline-model.js
yarn.lock

See https://github.com/cozy/cozy-ui/pull/1021
Except the aria-label change, I think it's OK. I tried to fix the fact that we display the icon via MenuItem in photos but styles are not easy to fix. Also, I removed translate() in UploadButton in photos because it seems we don't need it.

Use FileInput from cozy-ui

---

testcafe/runner-drive.js
testcafe/tests/drive/upload-conflicts.js

In `InitData`, add a test to upload a file already uploaded

feature: Add upload conflict test

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/photos/targets/manifest.webapp

Cherry pick a commit to release from the last stable version.

Prep' release

---

src/drive/web/modules/actionmenu/MobileActionMenu.jsx
src/drive/web/modules/filelist/File.jsx
src/drive/web/modules/upload/UploadQueue.jsx
src/photos/ducks/upload/UploadQueue.jsx

Need to wait https://github.com/cozy/cozy-libs/pull/531/files#diff-2fcc2368cf903f66a7df40a3d0c06848R81 
But the idea is to use our new split function from the models ;)

refactor: Use splitName from Models

---

.travis.yml

I don't like it, but we have no time ATM to debug the issue. I tried to, but in my local env, it seems to work.

test: Disable end to end

---

src/photos/ducks/clustering/albums.js

In some situations, we need to rewrite an existing cluster and therefore remove the existing files references, which was broken.

fix: Remove refs in clustering

---

src/photos/targets/services/onPhotoUpload.js

A service might be executed in parallel for the same instance, if several jobs are consecutively run in a short time. This could lead to conflicts and/or inconsistent results for the photos clustering.
Therefore, we use a database lock: when the service starts, it checks if the lock is set to true, if yes, it stops. If no, it runs normally and release the lock (set to false) at the end.

feat: Use lock during service execution

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/photos/targets/manifest.webapp

Since we have started a beta process to test the clustering

chore: bump version

---

src/drive/assets/icons/icon-list-min.svg
src/drive/assets/icons/icon-list.svg
src/drive/locales/en.json
src/drive/styles/filelist.styl
src/drive/web/modules/filelist/File.jsx
src/drive/web/modules/filelist/FileIcon.jsx
src/drive/web/modules/filelist/FileListHeader.jsx
src/drive/web/modules/filelist/FileThumbnail.jsx
src/drive/web/modules/navigation/duck/actions.jsx
src/drive/web/modules/navigation/duck/reducer.js

This fixes #1782 
I did not add tests because this part of the software does not look covered.
Tell me if I need to add anything ;)

feat: Thumbnail size

---

package.json
src/drive/targets/mobile/README.md

We now have access to HMR even when developing on mobile device ! Here is the how to ;)

docs: Add doc for HMR on mobile

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/photos/targets/manifest.webapp

Note this was made manually because of #1846

chore: Bump to version 1.18.12

---

src/drive/locales/en.json
src/drive/web/modules/upload/QuotaAlert.jsx
src/drive/web/modules/upload/withInstance.jsx

Add a new button when we're out of quota to upgrade our current plan

feat: Increase your quota

---

src/components/pushClient/Supportus.jsx

fix: Use get

---

src/components/pushClient/Button.jsx
src/components/pushClient/SupportUs.jsx
src/components/pushClient/pushClient.styl
src/components/pushClient/supportUs.styl
src/drive/locales/en.json
src/drive/web/modules/layout/Layout.jsx

Add support us description and change buttons order
Add a todo to use Cozy-UI pushClient component

feat: New version of support us... 

---

package.json
yarn.lock

Since cozy-bar will need it in the next version

feat: Upgrade cozy-client's version

---

src/drive/web/modules/navigation/AppRoute.jsx

forgot to merge on master this fix already deployed on Drive web :/

fix: Fix route for root file's revision

---

package.json
yarn.lock

isNote was failing on a few cases, specially when `version:0`

fix: Upgrade cozyclient to fix isNote helper

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/photos/targets/manifest.webapp

Upgrade version
Upgrade list-item cordova plugin to use latest version for iOS sync

chore: upgrade

---

package.json
src/components/App/App.jsx
src/drive/mobile/modules/mediaBackup/MediaBackupProgression.jsx
src/drive/mobile/modules/mediaBackup/MediaBackupProgression.spec.jsx
src/drive/targets/browser/index.jsx
src/drive/targets/mobile/InitAppMobile.jsx
src/drive/targets/public/index.jsx
yarn.lock

- Refactor: Create an App component 
- Upgrade react-redux

fix: Upgrade react-redux

---

src/drive/web/modules/public/PublicToolbar.jsx

Fix the public view when displayed in mobile format

fix: Pass the right context

---

src/drive/web/modules/filelist/FileOpener.jsx
src/drive/web/modules/filelist/fileopener.styl

The file list display was totally broken on edge 18.

fix: File list on  edge 18

---

src/drive/web/modules/filelist/FileOpener.jsx

Rebasing a change from release 1.22.0.

Rebasing 1.22.0

---

package.json
yarn.lock

- Downgrade mui to v3 to match UI dep
- With this downgrade the zIndex for the
modales are now right applied
- With UI upgrade we fixed the popover
menu
- Scanner upgrade is done because
of mui downgrade. We needed to fix
the Grid's margin

fix: Mostly zIndex related stuff

---

package.json
yarn.lock

Update cozy-ui fixes the problem

fix: Transparent mobile upload queue

---

CODEOWNERS
package.json
src/drive/web/modules/upload/index.js
src/drive/web/modules/upload/index.spec.js
yarn.lock

Since UploadQueue from UI now supports the display of the remaining time,
it was just a matter of computing the speed in the upload redux slice.

Add remaining time to upload queue

---

.github/auto-merge.yml

Add auto-merge config for cozy-drive ;)

chore: Add automerge feature

---

src/drive/targets/mobile/InitAppMobile.spec.jsx
src/drive/targets/public/index.jsx

We have a small linting error on master after #2019
edit: There was also a broken test because of a module that wasn't sufficiently mocked.

fix: Linting error

---

src/drive/mobile/modules/settings/components/FeedbackForm.jsx
src/drive/mobile/modules/settings/components/FeedbackForm.spec.jsx

Use jobCollection and a client from the context.

refactor: Use cozy client in feedback form

---

src/components/pushClient/index.js
src/components/pushClient/index.spec.js

Add a test for the isClientAlreadyInstalled

test: Add test for PushClient

---

src/drive/web/modules/drive/Toolbar/components/MoreMenu.spec.jsx
src/drive/web/modules/selectors.spec.jsx
src/drive/web/modules/upload/Dropzone.jsx
src/drive/web/modules/upload/Dropzone.spec.jsx
test/setup.jsx

~~Dropzone get displayedFolder from the state~~
Dropzone gets displayed folder as prop.
~~I don't know where is sharing state supposed to come from, I don't see it specified in FolderView's Dropzone :thinking:~~
EDIT: It seems to be coming from withSharingState HOC.

test: Dropzone test

---

src/drive/web/modules/drive/Toolbar/index.jsx
src/drive/web/modules/navigation/AppRoute.jsx
src/drive/web/modules/queries.js
src/drive/web/modules/views/Folder/FolderViewBody.jsx
src/drive/web/modules/views/Sharings/FilesViewerSharings.jsx
src/drive/web/modules/views/Sharings/SharingsFolderView.jsx
src/drive/web/modules/views/Sharings/index.jsx
src/drive/web/modules/views/Sharings/withSharedDocumentIds.jsx

This PR migrates the Sharings View. Only the last 2 commits are relevant, the other ones are from #2044 .

Share view

---

src/drive/web/modules/trash/Toolbar.jsx
src/drive/web/modules/views/Trash/TrashFolderView.jsx
src/drive/web/modules/views/Trash/TrashFolderView.spec.jsx
src/drive/web/modules/views/testUtils.jsx

On the trash view, we were showing the empty drive view.

Fix empty trash view

---

src/drive/mobile/modules/mediaBackup/duck/files.js
src/drive/mobile/modules/mediaBackup/duck/index.js
src/drive/mobile/modules/mediaBackup/duck/index.spec.js
src/drive/mobile/modules/settings/RatingModal.jsx
src/drive/web/modules/views/Drive/index.jsx

Add MediaBackupProgression / FirstUpload & RatingModal on the new Drive View 
Added few tests for the startMediaBackup 
Use CozyClient to update the last Sync date

fix: Display SyncStatus on mobile

---

package.json
src/components/pushClient/__mocks__/index.js
src/components/pushClient/index.js
src/components/pushClient/index.spec.js
src/drive/lib/RealTimeQueries.jsx
src/drive/lib/RealTimeQueries.spec.jsx
src/drive/lib/registerClientPlugins.js
src/drive/mobile/lib/cozy-helper.js
src/drive/targets/browser/index.jsx
src/drive/targets/intents/index.jsx
src/drive/targets/mobile/InitAppMobile.jsx
src/drive/targets/mobile/InitAppMobile.spec.jsx
src/drive/targets/public/index.jsx
src/drive/web/modules/actions/index.jsx
src/drive/web/modules/actions/useActions.spec.jsx
src/drive/web/modules/drive/DeleteConfirm.jsx
src/drive/web/modules/drive/DeleteConfirm.spec.jsx
src/drive/web/modules/drive/Toolbar/delete/delete.jsx
src/drive/web/modules/drive/Toolbar/delete/delete.spec.jsx
src/drive/web/modules/navigation/AppRoute.jsx
src/drive/web/modules/views/Public/index.jsx
src/drive/web/modules/views/Public/index.spec.jsx
src/drive/web/modules/views/Recent/index.spec.jsx
src/drive/web/modules/views/Trash/TrashFolderView.spec.jsx
yarn.lock

Several fixes for issues that have popped up after completing the migration. Individual commits should give a good idea of what's going on.
Still needs https://github.com/cozy/cozy-client/pull/740 but ready to review.

Variety of fixes

---

package.json
yarn.lock

fix: Update sharing

---

package.json
yarn.lock

interested by this PR https://github.com/cozy/cozy-bar/pull/687

feat: Upgrade cozy-bar to fix app img issue on mobile

---

package.json
yarn.lock

in particular https://github.com/cozy/cozy-libs/pull/1122

feat: Fix SelectBox issue in SharingModal

---

src/components/pushClient/Banner.jsx
src/components/pushClient/pushClient.styl

This is the "get desktop client" banner

feat: Replace pushClientBanner by cozy-ui Banner

---

src/components/sharing/PublicBanner.jsx
src/drive/locales/en.json

I will merge it as soon as the CI is green

fix: Translation

---

src/drive/targets/public/index.ejs
webpack/appicon.config.js

Next step is to use cozy-script to do it automatically, and for every apps

fix: Add favicon for Public pages

---

src/drive/web/modules/drive/ShareMenuItem.jsx

We only want to display actions in this Menu. So we use only infinitive verbs.

feat: Only display Share for the ShareMenuItem

---

src/components/pushClient/Button.jsx
src/components/pushClient/pushClient.styl

- Use the component from UI 
- One $extend removed

refactor: Use PushClientButton from UI

---

package.json
yarn.lock

Use new cozy-scanner version, including the new qualification

chore: Upgrade cozy-scanner

---

package.json
yarn.lock

- Fix "mail not sent" issue
- Fix avatars display
- Fix tooltip

feat: Upgrade cozy-sharings

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/photos/targets/manifest.webapp

chore: Upgrade 1.29.0

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/photos/targets/manifest.webapp

We're release 1.29, so let's create a new dev version 
I'll merge as soon as it green

chore: Upgrade to 1.30.0

---

package.json
src/drive/lib/migration/qualification.js
yarn.lock

This supports the receipt set from impots.gouv and improve logs in case of missing qualification case

Add new case for qualification migration

---

package.json
src/drive/lib/migration/qualification.js
src/drive/targets/services/qualificationMigration.js
src/photos/ducks/timeline/index.jsx
yarn.lock

Based on the 1.29.0 release branch already deployed

Merge with 1.29.0

---

src/drive/locales/en.json
src/drive/web/modules/filelist/cells/CarbonCopy.jsx
src/drive/web/modules/filelist/cells/ElectronicSafe.jsx
src/drive/web/modules/filelist/headers/CarbonCopy.jsx
src/drive/web/modules/filelist/headers/ElectronicSafe.jsx

Certification tooltip are now the same for the header and the row

Don't use connector slug in tooltip anymore

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/photos/targets/manifest.webapp

chore: Bump version to 1.31.0

---

package.json
src/components/FileHistory/HistoryModal.jsx
src/components/pushClient/SupportUs.jsx
src/drive/mobile/modules/authorization/UserActionRequired.jsx
src/drive/web/modules/actionmenu/ActionMenuWithHeader.jsx
src/drive/web/modules/certifications/CertificationTooltip.jsx
src/drive/web/modules/move/Footer.jsx
src/drive/web/modules/move/Header.jsx
src/drive/web/modules/move/MoveModal.jsx
src/photos/ducks/albums/components/__snapshots__/AlbumsView.spec.jsx.snap
yarn.lock

Update to cozy-ui 44.0.5 and fix breaking changes

Update cozy-ui to 44.0.5

---

package.json
yarn.lock

Bank qualifications are now available in the "Finance" theme.

feat: Upgrade cozy-scanner to get bank qualifications

---

package.json
yarn.lock

See https://github.com/cozy/cozy-libs/pull/1204

feat: Upgrade cozy-scanner for new bill icon

---

package.json
yarn.lock

Update cozy-ui/client/stack-client and add harvest-lib

---

src/drive/targets/manifest.webapp
src/drive/web/modules/filelist/cells/CarbonCopy.jsx
src/drive/web/modules/filelist/cells/ElectronicSafe.jsx
src/drive/web/modules/viewer/FilesViewer.jsx
src/drive/web/modules/viewer/Panel/Certifications.jsx
src/drive/web/modules/viewer/Panel/PanelContent.jsx
src/drive/web/modules/viewer/Panel/getPanelBlocks.jsx
src/drive/web/modules/viewer/helpers.js

**based on** https://github.com/cozy/cozy-drive/pull/2235
Ajout du bloc "connecteur" dans le panneau d'information du Viewer.

Add KonnectorBlock to Panel Viewer

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/photos/targets/manifest.webapp

chore: Bump to 1.32.0

---

package.json
src/drive/targets/manifest.webapp
yarn.lock

And add get permission on accounts and triggers
needed for the konnectorBlock in the FileViewer
@poupotte approved the "duplicate" descriptions

feat: Upgrade cozy-harvest-lib to 3.13.0

---

package.json
yarn.lock

Update cozy-harvest-lib to 3.14.0 https://github.com/cozy/cozy-libs/releases/tag/cozy-harvest-lib%403.14.0

feat: Update cozy-harvest-lib to 3.14.0

---

src/drive/web/modules/queries.js

and with buildOnlyFolderQuery too

fix: Use fetchPolicy correctly with specific metadata query

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/photos/targets/manifest.webapp

Bump to 1.34.0

---

src/drive/targets/intents/index.ejs
src/drive/web/modules/services/components/Embeder.jsx
src/drive/web/modules/viewer/FileOpenerExternal.jsx

On souhaite avoir un intent de visualisation de fichier plus proche du Viewer de Drive, et qu'il affiche également le panneau d'informations supplémentaires

Intents viewer Panel management

---

package.json
yarn.lock

to get Viewer's modification on mobile

feat: Upgrade cozy-ui to 44.10.0

---

src/drive/targets/mobile/README.md

Update Mobile documentation

---

package.json
yarn.lock

to get this fix https://github.com/cozy/cozy-libs/pull/1247

feat: Upgrade cozy-sharing to 2.11.7

---

src/drive/web/modules/services/components/Embeder.jsx
src/drive/web/modules/services/components/IntentHandler.jsx
src/drive/web/modules/viewer/FileOpenerExternal.jsx

To be more consistent with the Viewer

feat: Intent file opener is now white on charcoalBrey background

---

package.json
src/drive/mobile/modules/upload/index.jsx
src/photos/ducks/albums/components/__snapshots__/AlbumsView.spec.jsx.snap
yarn.lock

drive : `git://github.com/cozy/cozy-drive.git#build-jf-drive-muiv4`
photos : `git://github.com/cozy/cozy-drive.git#build-jf-photos-muiv4`
La migration des Modal vers les Dialog est l'objet d'une autre PR

Update to Mui v4

---

package.json
yarn.lock

to get https://github.com/cozy/cozy-ui/pull/1740

feat: Upgrade cozy-ui to 45.0.0-beta.5

---

src/drive/targets/mobile/README.md

docs: Update mobile doc

---

src/components/App/App.jsx
src/drive/targets/intents/index.jsx

Il est nécessaire d'ajouter le breakpoints provider pour pouvoir utiliser useBreakpoints notamment dans le Viewer. Et ce Viewer peut être utilisé dans un intent.

feat: Add breakpoints provider for intents

---

package.json
yarn.lock

to get https://github.com/cozy/cozy-ui/pull/1754

feat: Update cozy-ui to 45.3.0

---

src/drive/targets/mobile/README.md

Ajout d'info pour l'installation des outils de build pour Android

docs: Add some info for Android in mobile documentation

---

src/drive/targets/mobile/README.md

Update mobile doc

---

src/drive/targets/mobile/README.md

To warn if there is multiple ShareExt as targets

docs: Add mobile docs

---

package.json
yarn.lock

ShareAutosuggest can now handle with contact fullname

feat: Upgrade cozy-sharing to 3.2.0

---

src/drive/targets/mobile/InitAppMobile.jsx
src/drive/targets/mobile/InitAppMobile.spec.jsx
src/drive/web/modules/navigation/duck/actions.jsx
src/drive/web/modules/upload/index.js
src/drive/web/modules/upload/index.spec.js

On souhaite avoir un peu plus de visibilité dans Sentry lors d'erreur/plantage dans le process d'envoi de fichier sur mobile

feat: Add some logs in Upload module

---

package.json
yarn.lock

Pour avoir le correctif https://github.com/cozy/cozy-libs/pull/1285
Sera mergé dès la CI verte

feat: Upgrade cozy-harvest-lib to 5.1.0

---

package.json
src/drive/targets/public/index.jsx
src/drive/web/modules/public/LightFileViewer.jsx
src/drive/web/modules/public/LightFileViewer.spec.jsx
src/drive/web/modules/public/PublicToolbar.jsx
src/drive/web/modules/public/SharingBanner.jsx
yarn.lock

Must have the Viewer toolbar on desktop
and the cozy-bar "toolbar" (it's the '...' menu) on mobile

fix: Add correct toolbar on public file viewer

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/photos/targets/manifest.webapp

chore: Bump version to 1.35.0

---

.gitignore
src/drive/targets/public/index.jsx
src/drive/web/modules/viewer/FilesViewer.jsx

It'll fix requests on /doctypes/undefined

fix: Pass doctype + documentType to SharingProvider

---

src/components/App/App.jsx
src/drive/lib/DriveProvider.jsx
src/drive/targets/intents/index.jsx
src/drive/targets/public/index.jsx

Needed to use sharing in Viewer. We forgot to add this when we added the Footer on ExternalViewer.

Add SharingContext for intents

---

src/drive/web/modules/public/PublicLayout.jsx

We forgot to add it here https://github.com/cozy/cozy-drive/commit/a86eda10a9991e6b1583f18c0db2ffffa44c4653

fix: FlagSwitcher in PublicLayout

---

package.json
yarn.lock

It solves some translation problems
give me an APK / apk plz

feat: Upgrade authenticate

---

package.json
src/drive/locales/en.json
src/drive/targets/public/index.jsx
src/drive/web/modules/actions/index.jsx
src/drive/web/modules/navigation/AppRoute.jsx
src/drive/web/modules/public/LightFileViewer.jsx
src/drive/web/modules/public/PublicToolbar.jsx
src/drive/web/modules/services/components/Embeder.jsx
src/drive/web/modules/viewer/FileOpenerExternal.jsx
src/drive/web/modules/viewer/FilesViewer.jsx
src/drive/web/modules/viewer/barviewer.styl
src/drive/web/modules/views/Public/index.jsx
src/photos/ducks/upload/UploadQueue.jsx
yarn.lock

After https://github.com/cozy/cozy-ui/pull/1799, add only office support in viewers (public, private and intent)

OnlyOffice in Viewers

---

src/drive/locales/en.json

feat: Change wording for noapp error

---

src/drive/web/modules/move/Header.jsx

no ellipsis prop on Typography component, use noWrap instead

fix: Use ellipsis again on Typography

---

src/drive/web/modules/drive/RenameInput.jsx
src/drive/web/modules/filelist/FilenameInput.jsx
src/drive/web/modules/move/MoveModal.spec.jsx
src/drive/web/modules/upload/index.spec.js
src/drive/web/modules/views/OnlyOffice/Title.jsx
src/drive/web/modules/views/OnlyOffice/Toolbar/FileName.jsx
src/drive/web/modules/views/OnlyOffice/Toolbar/styles.styl

Add possibility to rename onyloffice file when consulting it.
Not active on mobile

OnlyOffice file renamer

---

src/drive/web/modules/views/OnlyOffice/Editor.spec.jsx
src/drive/web/modules/views/OnlyOffice/Error.jsx

Add CozyUi Viewer as error fallback for Only Office editor

---

package.json
src/drive/targets/browser/index.jsx
src/drive/targets/browser/wdyr.js
src/drive/web/modules/views/OnlyOffice/Toolbar/FileIcon.jsx
src/drive/web/modules/views/OnlyOffice/Toolbar/Sharing.jsx
src/drive/web/modules/views/OnlyOffice/Toolbar/index.jsx
src/drive/web/modules/views/hooks.js
src/drive/web/modules/views/hooks.spec.js
yarn.lock

it now returns always something even when fetching
To prevent blink after adding someone in sharing for the fist time
because it triggers a new file fetch

fix hook useFileWithPath

---

src/drive/web/modules/filelist/FileOpener.jsx

When instantiating HammerJs at component assembly, the ref used was not always the right one, because in some cases the 'span' seems to be chosen instead of the 'a' while the isOnlyOfficeEditorSupported() condition is executed.

fix: FileOpener now re-render if a depency change

---

src/drive/web/modules/views/OnlyOffice/useCreateFile.js

fix: Typo in route to retrieve only office templates

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/photos/targets/manifest.webapp

feat: Bump version to 1.36.0

---

src/drive/targets/public/index.jsx
src/drive/web/modules/views/OnlyOffice/Title.jsx
src/drive/web/modules/views/OnlyOffice/helpers.js
src/drive/web/modules/views/OnlyOffice/helpers.spec.js
src/drive/web/modules/views/OnlyOffice/index.jsx

already merged on 1.35.0 https://github.com/cozy/cozy-drive/pull/2367
will be merged when CI is green

Fix conditions to show the sharing banner on Only Office files

---

src/drive/targets/manifest.webapp

chore: Remove duplicated sharings permission in manifest

---

CODEOWNERS

Since everyone is supposed to review all repo pull request

chore: Remove codeowners

---

src/drive/targets/public/index.jsx
src/drive/web/modules/views/OnlyOffice/helpers.js
src/drive/web/modules/views/OnlyOffice/helpers.spec.js
src/drive/web/modules/views/OnlyOffice/index.jsx
src/drive/web/modules/views/OnlyOffice/useConfig.js

to show the name of the user editing the document

feat: Add username in only office editor config

---

src/drive/targets/public/index.jsx
src/drive/web/modules/drive/Toolbar/components/CreateOnlyOfficeItem.jsx
src/drive/web/modules/views/OnlyOffice/Create.jsx
src/drive/web/modules/views/OnlyOffice/useCreateFile.js

used to create an only office file in a shared by link folder with write access

Add only office creation route for public page

---

src/drive/web/modules/move/MoveModal.jsx
src/drive/web/modules/move/MoveModal.spec.jsx

There is no spec for this modal, we simply used Dialog instead of Modal and use the old style

fix: Remove padding on MoveModal

---

src/drive/web/modules/drive/AddMenu/AddMenu.jsx
src/drive/web/modules/drive/AddMenu/AddMenuProvider.jsx

to be still present after closing the menu

fix: ScanWrapper should be outside of the AddMenu

---

src/drive/web/modules/views/Folder/createFileOpeningHandler.js
src/drive/web/modules/views/Folder/createFileOpeningHandler.spec.js

We added a destructuring on the props, which caused a typo problem for the prop availableOffline

fix: Typo in createFileOpeningHandler props

---

src/components/Error/ErrorComponent.jsx
src/drive/targets/browser/index.ejs
src/drive/targets/browser/setupAppContext.js
src/drive/targets/intents/index.ejs
src/drive/targets/intents/index.jsx
src/drive/targets/public/index.ejs
src/drive/targets/public/index.jsx
src/drive/web/modules/views/OnlyOffice/Toolbar/HomeLinker.jsx
src/photos/targets/browser/index.ejs
src/photos/targets/browser/index.jsx
src/photos/targets/public/index.ejs
src/photos/targets/public/index.jsx

Afin de ne plus avoir besoin de mettre l'app à jour suite à une modification des cozy-data côté stack

Replace cozy-data-* by cozy-data

---

package.json
src/drive/web/modules/upload/index.spec.js

Eslint is required to have editor support during development. :)

fix(deps): Add eslint in devDeps

---

src/drive/targets/public/index.jsx
src/photos/targets/browser/index.jsx

quelques oublis suite à https://github.com/cozy/cozy-drive/pull/2385

fix: Dataset from CozyData

---

src/lib/react-cozy-helpers/QueryParameter.js
src/lib/react-cozy-helpers/QueryParameter.spec.js

fix: Decode URI search param with QueryParameter

---

src/drive/web/modules/views/Sharings/index.jsx
src/drive/web/modules/views/Sharings/index.spec.jsx

Ajout d'un Spinner le temps que les fichiers/dossiers soient chargés.

fix: Adding a Spinner when loading files

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/photos/targets/manifest.webapp

bump to 1.36.0

---

yarn.lock

command: npx yarn-deduplicate yarn.lock
then rm -rf node_modules
then yarn install
before:
1,1G	node_modules
after:
808M	node_modules

refactor: Ran yarn deduplicate

---

src/components/FileHistory/HistoryModal.jsx

We previously tried to use native methods even
if the user was on browser...

fix: Download version works on mobile web

---

src/drive/mobile/lib/media.js
src/drive/targets/mobile/config.xml

Need https://github.com/cozy/cordova-plugin-list-library-items/pull/35 on the Android side. On iOS this new header will be used by default

feat: Set the UA for native upload

---

.github/workflows/codeql-analysis.yml
CHANGELOG.md
src/drive/web/modules/viewer/CallToAction.jsx

In order to test this functionality from github. (scan code to find all variants of a vulnerability)

feat: Add CodeQL to scan code

---

.gitignore

locales should be ignored by git when pulling them
This reverts commit e3a1555ab161d34b3265fb0843cb52d3f453687d.

Revert "feat: Remove locales from gitignore"

---

package.json
src/components/pushClient/Button.jsx
src/drive/web/modules/layout/Main.jsx
src/photos/components/Layout.jsx
yarn.lock

https://trello.com/c/UA4mUUko/148-e113-supprimer-lencart-proposant-dinstaller-drive-05-jh
Simply return null if flagship env is detected

feat: Do not display banner in flagship

---

.travis.yml

In order to run our services on our futur production env

chore: Node12 & Node16 on travis

---

yarn.lock

- renamed chore commit into fix

fix(deps): Dependabot update

---

package.json
yarn.lock

fix #1326 #1325
I didn't see anything that use node-uuid

chore(node-uuid): remove useless deps

---

src/drive/web/modules/services/components/SuggestionProvider.jsx
src/drive/web/modules/services/components/helpers.js
src/drive/web/modules/services/components/helpers.spec.js
src/drive/web/modules/services/components/iconContext.js

There used to be 4 commits in the release-1.38.0:
- first commit has been merged into master, then cherry pick in the release (so it's not appearing)
- second commit is here 🎉 
- third commit has been merged into master, then cherry pick in the release (so it's not appearing)
- fourth commit upgrade cozy-client only, but we upgraded cozy-client already in another PR already merged

fix(beta): Merge release/1.38.0-beta

---

src/drive/targets/manifest.webapp

This can be used by the DACC service

feat: Add eu.mycozy.dacc remote doctype permission

---

src/photos/styles/topbar.styl

https://github.com/cozy/cozy-drive/pull/2481 introduces a bug while building Photos :
https://app.travis-ci.com/github/cozy/cozy-drive/jobs/558010052

fix(photos): Build failed because of incorrect require

---

src/drive/web/modules/views/Folder/OldFolderViewBreadcrumb.jsx
src/drive/web/modules/views/Public/index.jsx
src/drive/web/modules/views/Public/index.spec.jsx

That is a revert with a feature flag.

feat(breadcrumb): add feature flag on Breadcrumb on public view

---

CHANGELOG.md
package.json
src/drive/web/modules/public/LightFileViewer.spec.jsx
src/drive/web/modules/views/Drive/index.spec.jsx
src/drive/web/modules/views/OnlyOffice/Editor.spec.jsx
src/drive/web/modules/views/Public/index.spec.jsx
src/drive/web/modules/views/Recent/index.spec.jsx
src/drive/web/modules/views/Sharings/index.spec.jsx
src/drive/web/modules/views/Trash/TrashFolderView.spec.jsx
yarn.lock

When remaining comes in French locale, it was not translated

fix(deps): Upgrade cozy-ui to fix UploadQueue i18n translation

---

CHANGELOG.md
package.json
yarn.lock

chore(deps): remove useless dependencies

---

src/drive/targets/services/dacc-run.js
src/drive/targets/services/dacc-run.spec.js
src/drive/targets/services/dacc.js

This will be useful to set up a custom date for the files query, so the
indicator can be more easily tested.

feat: Add date attribute to flag

---

package.json
yarn.lock

that prevents progress moving too much while upload

fix(upload): upgrade cozy-ui to make progress bar size fixed

---

.travis.yml

Useless, as we don't publish any thing through pipeline anymore

chore(ci): remove drive android job

---

.travis.yml
package.json
yarn.lock

Because [a guy asks for fixing Travis](https://github.com/LironEr/bundlemon/pull/87) setting  pr number as false, making bundlemon fail on master, and the force of opensource => it's already fixed https://github.com/LironEr/bundlemon/pull/88

chore(bundlemon): Upgrade bundlemon version containing the expected fix

---

CHANGELOG.md

docs: changelog about bundlemon

---

CHANGELOG.md

docs: changelog updates for 1.41.0

---

.bundlemonrc
CHANGELOG.md
package.json
src/drive/serviceWorker/service-worker.js
src/drive/targets/browser/index.jsx
src/drive/targets/browser/serviceWorkerRegistration.js
src/drive/targets/browser/serviceWorkerRegistration.spec.js
src/drive/web/modules/views/Public/index.spec.jsx
webpack/workbox.config.js
yarn.lock

feat(service-worker): Add service-worker

---

CHANGELOG.md
src/drive/web/modules/views/Public/index.spec.jsx

test(public): Node 16 tests were randomly broken when component slows to render

---

src/drive/locales/en.json

I also updated the french translation in Transifex, but don't know if it will be taken into account after updating the original label.

Update the label of the Upload button in a message

---

src/drive/targets/browser/index.jsx

that part was not removed apparently

chore(service-worker): remove service worker registration

---

renovate.json

For test purpose. Then I will revert and merge the PR in cozy-libs : https://github.com/cozy/cozy-libs/pull/1776

chore(renovate): group cozy-client subpackages together

---

renovate.json

chore(renovate): group cozy-client subpackages together -fix

---

src/drive/web/modules/services/components/SuggestionProvider.jsx
src/drive/web/modules/services/components/SuggestionProvider.spec.jsx

In local, benchmark:
with 11 432 files with 10000 in my trashes. (there are 1059 remaining files in my cozy)
Without optims: 120ms - 9.66Mo
With optimisation:  2s - 2.46Mo

feat(search): fetch only required params for search

---

src/drive/web/modules/drive/Toolbar/components/ShortcutCreationModal.jsx

fix: Remove proptypes warning

---

src/drive/web/modules/services/components/SuggestionProvider.jsx
src/drive/web/modules/services/components/SuggestionProvider.spec.jsx

fix(search): Remove ROOT DIR

---

package.json
yarn.lock

Linked to https://github.com/cozy/cozy-bar/pull/778

fix(search): Upgrade Cozy Bar to prevent Minified React Error

---

package.json
yarn.lock

We had issues with the viewer, this cozy ui's upgrade should fix them.

fix: Viewer issue

---

src/drive/lib/dacc/dacc.js
src/drive/targets/manifest.webapp

- Use new DACC remote-doctype
- Use new groups API

Use new DACC API

---

.bundlemonrc

My goal is to set the maxPercentIncrease according to what is needed. Maybe some PR will fail and need to update this.

chore(bundlemon): run Bundlemon everywhere + make it sensitive

---

CODEOWNERS

chore(codeowners): Remove codeowners

---

src/drive/targets/manifest.webapp

Since we had some delay for the prod release, we change the trigger scheduling

feat: Change monthly trigger

---

.github/pull_request_template.md
README.md
jsconfig.json

- Add changelog PR template
- Add jsconfig file for assist navigation in editor
- Add again mails in dev docs

Update docs and add jsconfig.json to assist navigation

---

src/photos/ducks/clustering/albums.js
src/photos/ducks/clustering/matching.js
src/photos/ducks/clustering/settings.js
src/photos/ducks/clustering/utils.js
src/photos/lib/onPhotoUpload.js

```
*
* Fix errors on photos clustering
*
```

Fix clustering errors

---

src/drive/styles/filelist.styl

```
* Align buttons when dezooming
```

fix: Align buttons when dezooming

---

.bundlemonrc
package.json
src/drive/web/modules/drive/Toolbar/components/CreateNoteItem.jsx
src/drive/web/modules/views/Trash/TrashFolderView.jsx
yarn.lock

Since fixes have been already reviewed, I'll merge them

fix: backport of 1.46.0 release

---

src/drive/web/modules/navigation/Breadcrumb/Breadcrumb.spec.jsx

```
* Update Breadcrumb tests
```

test: Update Breadcrumb tests

---

src/components/pushClient/Banner.jsx
src/components/pushClient/Button.jsx

```
* remove piwik track function
```
Leftovers from piwik removal. An error was present in the PushClient banner when closing

fix: remove piwik track function

---

package.json
yarn.lock

feat: Update cozy-sharing from 4.8.1 to 4.9.0

---

src/components/Bar.jsx

```
* Show bar in normal variant on mobile
```

fix(Bar): Show bar as normal on mobile

---

src/drive/web/modules/search/components/BarSearchAutosuggest.jsx
src/drive/web/modules/search/components/BarSearchInputGroup.jsx
src/drive/web/modules/search/components/styles.styl
src/drive/web/modules/views/Search/SearchView.jsx

```
* Add clean button on search
```
- https://github.com/cozy/cozy-drive/pull/2793

Feat: Add clean button on search

---

jsconfig.json
src/drive/web/modules/search/components/BarSearchAutosuggest.jsx
src/drive/web/modules/search/hooks/useSearch.jsx
src/drive/web/modules/views/Search/SearchView.jsx

```
* handle input focus into SearchView
* index files on search input focus
* update path into jsconfig
```

Fix: index files on search input focus

---

src/drive/web/modules/search/__snapshots__/AppBarSearch.spec.jsx.snap
src/drive/web/modules/search/components/BarSearchAutosuggest.jsx
src/drive/web/modules/search/components/BarSearchInputGroup.jsx
src/drive/web/modules/search/components/SuggestionItemSkeleton.jsx
src/drive/web/modules/search/components/SuggestionListSkeleton.jsx
src/drive/web/modules/search/components/styles.styl
src/drive/web/modules/search/hooks/useSearch.jsx
src/drive/web/modules/views/Search/SearchView.jsx

```
* Improve design on search input state
* Use Skeleton to wait search result
```

Fix: improve search design

---

src/drive/web/modules/search/__snapshots__/AppBarSearch.spec.jsx.snap
src/drive/web/modules/search/components/BarSearchAutosuggest.jsx
src/drive/web/modules/search/components/SuggestionItem.jsx
src/drive/web/modules/search/components/SuggestionItemTextHighlighted.jsx
src/drive/web/modules/search/components/SuggestionItemTextSecondary.jsx
src/drive/web/modules/search/components/helpers.js
src/drive/web/modules/search/components/helpers.spec.jsx
src/drive/web/modules/search/components/styles.styl
src/drive/web/modules/search/hooks/useSearch.jsx
src/drive/web/modules/views/Search/SearchView.jsx
yarn.lock

```
* Click on parent path into search bar suggestions 
```

Fix : click on suggestion path

---

package.json
yarn.lock

```
* Update cozy-sharing from 4.9.0 to 5.0.0
```

feat: Update cozy-sharing from 4.9.0 to 5.0.0

---

.bundlemonrc
package.json
yarn.lock

```
* Update cozy-client from 34.1.5 to 34.7.1
```

feat: Update cozy-client from 34.1.5 to 34.7.1

---

package.json
src/drive/web/modules/search/components/BarSearchInputGroup.jsx
yarn.lock

```
* Use cross circle outline icon
* Update cozy-ui from 77.9.2 to 79.4.0
```

Fix: Use cross circle outline icon

---

src/components/FileHistory/HistoryModal.jsx
src/components/useHead.jsx
src/drive/mobile/modules/authorization/UserActionRequired.jsx
src/drive/mobile/modules/onboarding/OnBoarding.jsx
src/drive/mobile/modules/upload/index.jsx
src/drive/web/modules/actions/index.jsx
src/drive/web/modules/filelist/cells/FileName.jsx
src/drive/web/modules/navigation/Index.jsx
src/drive/web/modules/navigation/Nav.jsx
src/drive/web/modules/viewer/FileOpenerExternal.jsx
src/drive/web/modules/views/Drive/index.jsx
src/drive/web/modules/views/OnlyOffice/Toolbar/FileName.jsx
src/drive/web/modules/views/OnlyOffice/index.jsx
src/drive/web/modules/views/Public/index.jsx
src/drive/web/modules/views/Recent/index.jsx
src/drive/web/modules/views/Sharings/SharingsFolderView.jsx
src/drive/web/modules/views/Sharings/index.jsx
src/drive/web/modules/views/Trash/TrashFolderView.jsx

Feat: use react router dom hooks

---

src/drive/hooks/index.js
src/drive/hooks/useCurrentFileId.jsx
src/drive/hooks/useCurrentFolderId.jsx
src/drive/hooks/useDisplayedFolder.jsx
src/drive/hooks/useParentFolder.jsx
src/drive/web/modules/drive/AddMenu/AddMenuProvider.jsx
src/drive/web/modules/drive/Toolbar/components/CreateNoteItem.jsx
src/drive/web/modules/drive/Toolbar/components/DownloadButtonItem.jsx
src/drive/web/modules/drive/Toolbar/components/InsideRegularFolder.jsx
src/drive/web/modules/drive/Toolbar/components/ScanWrapper.jsx
src/drive/web/modules/drive/Toolbar/components/ShortcutCreationModal.jsx
src/drive/web/modules/drive/Toolbar/components/UploadButtonItem.jsx
src/drive/web/modules/drive/Toolbar/components/UploadItem.jsx
src/drive/web/modules/drive/Toolbar/delete/DeleteItem.jsx
src/drive/web/modules/drive/Toolbar/index.jsx
src/drive/web/modules/drive/Toolbar/share/ShareButton.jsx
src/drive/web/modules/drive/Toolbar/share/ShareItem.jsx
src/drive/web/modules/drive/Toolbar/share/SharedRecipients.jsx
src/drive/web/modules/move/MoveModal.jsx
src/drive/web/modules/navigation/duck/actions.jsx
src/drive/web/modules/selectors.js
src/drive/web/modules/viewer/FilesViewer.jsx
src/drive/web/modules/views/Drive/FilesViewerDrive.jsx
src/drive/web/modules/views/Drive/index.jsx
src/drive/web/modules/views/Public/index.jsx
src/drive/web/modules/views/Sharings/FilesViewerSharings.jsx
src/drive/web/modules/views/Sharings/SharingsFolderView.jsx
src/drive/web/modules/views/Trash/FilesViewerTrash.jsx
src/drive/web/modules/views/Trash/TrashFolderView.jsx

```
* Selector after router v6
```

Fix : selector after router v6

---

src/drive/web/modules/search/components/helpers.js
src/drive/web/modules/search/hooks/useSearch.jsx

```
* Clean button works with load more on search view
* On suggestionItem, show icon for file with mime
* Open Onlyoffice with router on search
```

Fix: Feedback search

---

src/photos/ducks/clustering/matching.js
src/photos/ducks/clustering/reclusterize.js
src/photos/ducks/clustering/utils.js
src/photos/lib/onPhotoUpload.js

Clustering service regularly fails for obscure reason: let's add logs to better understand when this happens
```
*
* Add clustering logs
```

feat: Add clustering logs

---

package.json
yarn.lock

```
* Update cozy-bar from 8.12.0 to 8.13.0
```

feat: Update cozy-bar from 8.12.0 to 8.13.0

---

src/drive/web/modules/search/components/SuggestionItem.jsx
src/drive/web/modules/search/components/helpers.js
src/drive/web/modules/search/hooks/useSearch.jsx

```
*  Use shortcut icon instead IconFiles in search
```

fix(Search): Use shortcut icon instead IconFiles

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/drive/targets/mobile/package.json
src/photos/targets/manifest.webapp

```
* Bump version from 1.48.0 to 1.49.0
```

chore: Bump version from 1.48.0 to 1.49.0

---

package.json
yarn.lock

```
* Increase support modal height to handle adding consent checkbox
```

feat: Update cozy-bar from 8.13.0 to 8.13.1

---

package.json
src/drive/web/modules/drive/Toolbar/share/ShareItem.jsx
src/photos/ducks/albums/components/AlbumToolbar.jsx
yarn.lock

```
* Update cozy-sharing to 6.0.1 to get new sharing-modal
```

feat: Update cozy-sharing to 6.0.1 to get new sharing-modal

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/drive/targets/mobile/package.json
src/photos/targets/manifest.webapp

chore: Bump version to 1.48.1

---

.transifexrc.tpl
.travis.yml
.tx/config
CONTRIBUTING.md
README.md
package.json
yarn.lock

```
* Migrate transifex config from v2 to v3
```
- https://github.com/cozy/cozy-libs/pull/2014
- https://github.com/cozy/cozy-libs/pull/2019

chore: Migrate transifex config from v2 to v3

---

src/drive/web/modules/views/OnlyOffice/ReadOnlyFab.jsx

```
*  Fab is now the same color on mobile & desktop
```

feat: Harmonize OnlyOffice FAB to primary color

---

package.json
yarn.lock

Needed for react-router v6 release
```
* Update cozy-ui to 81.2.1 to get fixed ImageViewer
```

feat: Update cozy-ui to 81.2.1

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/drive/targets/mobile/package.json
src/photos/targets/manifest.webapp

```
*  Bump version to 1.53.0
```

chore: Bump version to 1.53.0

---

package.json
yarn.lock

This update fix the display of owner recipient
```
* Update cozy-sharing from 6.0.3 to 6.0.5
```

feat: Update cozy-sharing from 6.0.3 to 6.0.5

---

src/drive/web/modules/views/OnlyOffice/useConfig.jsx

```
* Refresh page after onlyoffice idle session
```

feat: Refresh page after onlyoffice idle session

---

src/drive/targets/public/components/AppRouter.jsx
src/drive/targets/public/index.jsx
src/drive/web/modules/public/LightFileViewer.jsx
src/drive/web/modules/services/components/Embeder.jsx
src/drive/web/modules/viewer/FileOpenerExternal.jsx
src/drive/web/modules/viewer/FileOpenerExternal.spec.jsx
src/drive/web/modules/viewer/FilesViewer.jsx
src/drive/web/modules/views/Folder/FolderViewBody.jsx
src/drive/web/modules/views/OnlyOffice/helpers.js
src/drive/web/modules/views/OnlyOffice/useConfig.jsx

```
* Disable office on touch screen (mobile and tablet) with `drive.office.touchScreen.enabled` flag
```

Feat: Disable office on touch screen (mobile and tablet)

---

package.json
yarn.lock

```
* Update cozy-ui to 82.5.0 to get the new OnlyOffice paywall wording
```

feat: Update cozy-ui from 82.2.0 to 82.5.0

---

package.json
yarn.lock

```
* Update cozy-ui to 82.6.1 corrects the display in paywall on mobile applications
```

feat: Update cozy-ui from 82.5.0 to 82.6.1

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/drive/targets/mobile/package.json
src/photos/targets/manifest.webapp

```
* Bump version to 1.54.0
```

chore: Bump version to 1.54.0

---

package.json
yarn.lock

This update gets the new English translation for premium title in paywall
```
* Update cozy-ui from 82.6.1 to 82.10.0
```

feat: Update cozy-ui from 82.6.1 to 82.10.0

---

src/drive/styles/filelist.styl

```
* Add margin so Claudy no longer obstructs actions below him
```

fix: add margin so Claudy no longer obstructs actions below him

---

package.json
yarn.lock

```
* Update cozy-ui from 82.6.1 to 82.10.0
```

chore: Merge back fix from release 1.53.0

---

CODEOWNERS

chore(codeowners): Update codeowners

---

package.json
yarn.lock

```
* Update cozy-bar to get fixed cloud icon position
```

feat: Update cozy-bar to get fixed cloud icon position

---

.bundlemonrc
app.config.js
jest.config.js
package.json
src/drive/web/modules/viewer/PublicViewer.jsx
yarn.lock

This update provides a newer version of react-pdf to fix some issues with PDF rendering
```
* Fix some issues with PDF rendering
* Update cozy-ui from 82.13.0 to 83.1.0
```

feat: Update cozy-ui from 82.13.0 to 83.1.0

---

src/components/pushClient/index.js

Since we use queryFromState we need to
use the singleDocData: true.

fix: SingleDoc for queryFromState

---

package.json
yarn.lock

This update gets fixes for space issues on the SelectionBar and the ExtendableFab
```
*  Update cozy-ui from 83.1.0 to 83.3.0
```

feat: Update cozy-ui from 83.1.0 to 83.3.0

---

.bundlemonrc
package.json
src/drive/web/modules/viewer/FilesViewer.spec.jsx
yarn.lock

```
* Update cozy-realtime from 4.3.0 to 4.4.1
```

feat: Update cozy-realtime from 4.3.0 to 4.4.1

---

package.json
yarn.lock

```
* Upgrade cozy-scanner from 2.4.6 to 3.0.0
```

feat: Upgrade cozy-scanner from 2.4.6 to 3.0.0

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/drive/targets/mobile/package.json
src/photos/targets/manifest.webapp

```
* Bump version to 1.55.0
```

chore: Bump version to 1.55.0

---

src/drive/web/modules/views/OnlyOffice/useConfig.jsx

```
* OnlyOffice:  Reviews markup are now displayed even on read mode
```

feat: Display the review markup even on read mode

---

package.json
yarn.lock

This update brings new wording for paywall
```
* Update cozy-ui from 34.2.0 to 35.8.1
```

feat: Update cozy-ui from 34.2.0 to 35.8.1

---

package.json
src/drive/web/modules/layout/Layout.jsx
src/photos/components/Layout.jsx
yarn.lock

```
* Add CozyDevTools from cozy-client in development mode
```

feat: Add CozyDevTools from cozy-client

---

src/drive/targets/manifest.webapp

```
* Remove native link and icon from manifest
```

feat: Remove native link and icon from manifest

---

src/drive/web/modules/layout/Layout.jsx
src/photos/components/Layout.jsx

```
* Allow debug with CozyDevTools in production
```

feat: Allow debug with CozyDevTools in production

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/drive/targets/mobile/package.json
src/photos/targets/manifest.webapp

```
* Bump version to 1.56.0
```

feat: Bump version to 1.56.0

---

src/drive/web/modules/viewer/FilesViewer.spec.jsx

```
* Skip flaky test on FilesViewer
```

test(FilesViewer): Skip flaky test

---

src/photos/ducks/backup/components/BackupDescription.jsx
src/photos/ducks/backup/components/BackupError.jsx
src/photos/ducks/backup/helpers/error.js
src/photos/ducks/backup/hooks/useBackupActions.jsx
src/photos/ducks/backup/index.jsx
src/photos/locales/en.json

Display quota paywall when quota exceeded during backup

Manage quota exceeded during backup

---

package.json
yarn.lock

```
* Display alerts above the Cozy bar 
* Update cozy-ui from 88.6.0 to 90.0.0
```

feat: Update cozy-ui from 88.6.0 to 90.0.0

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/drive/targets/mobile/package.json
src/photos/targets/manifest.webapp

```
* Bump version to 1.57.0
```

feat: Bump version to 1.57.0

---

src/photos/components/AppRouter.jsx

We use flags directly in AppRouter to determine default router. It was too late when they were loaded before.

fix(backup): Flags were initialized too late

---

jest.config.js
package.json
src/drive/locales/en.json
src/drive/web/modules/move/FileList.jsx
src/drive/web/modules/move/Footer.jsx
src/drive/web/modules/move/MoveModal.jsx
src/drive/web/modules/move/MoveModal.spec.jsx
src/drive/web/modules/move/MoveOutsideSharedFolderModal.jsx
src/drive/web/modules/move/helpers.js
src/drive/web/modules/move/helpers.spec.js
src/drive/web/modules/queries.js
yarn.lock

```
* Alert user before moving out folder from sharing folder
```
**Remaining:**
- ~~Make working the test after converting `MoveModal` to functional component~~
- ~~Adapt test to my modification~~
- https://github.com/cozy/cozy-libs/pull/2249
- https://github.com/cozy/cozy-libs/pull/2251

feat: Alert user before moving out folder from sharing folder

---

src/photos/components/AppRouter.jsx
src/photos/components/WaitFlags.jsx
src/photos/targets/browser/index.jsx

refactor(backup): Create a component that wait flags

---

src/drive/locales/en.json
src/drive/web/modules/move/LoaderModal.jsx
src/drive/web/modules/move/MoveModal.jsx
src/drive/web/modules/move/MoveModal.spec.jsx
src/drive/web/modules/move/MoveOutsideSharedFolderModal.jsx
src/drive/web/modules/move/MoveSharedFolderInsideAnotherModal.jsx
src/drive/web/modules/move/helpers.js

```
* Alert user when moving shared folder inside another
```

feat: Alert user when moving shared folder inside another

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/drive/targets/mobile/package.json
src/photos/targets/manifest.webapp

```
* Bump version to 1.58.0
```

feat: Bump version to 1.58.0

---

src/components/PushBanner/QuotaBanner.jsx
src/components/PushBanner/QuotaBanner.spec.jsx

```
*  Show premium button of QuotaBanner on flagship with flag `flagship.iap.enabled`
```

feat: Quota banner iap enabled

---

src/photos/ducks/backup/components/LastBackupStatus.jsx
src/photos/ducks/backup/index.jsx
src/photos/locales/en.json

```
* Display last backup status
```

feat(backup): Display last backup status

---

package.json
yarn.lock

```
* Update cozy-ui from 92.0.0 to 92.0.1
```

feat: Update cozy-ui from 92.0.0 to 92.0.1

---

src/photos/ducks/backup/components/BackupActions.jsx

feat(backup): Add number of medias loaded during backup initialization

---

src/drive/web/modules/filelist/File.spec.jsx
src/drive/web/modules/filelist/cells/ShareContent.jsx
src/drive/web/modules/views/Public/index.spec.jsx
src/drive/web/modules/views/Recent/index.spec.jsx
src/drive/web/modules/views/Sharings/index.spec.jsx
src/drive/web/modules/views/Trash/TrashFolderView.spec.jsx

```
* Allow click on sharing status only when file is shared
```

fix: Improve sharing

---

package.json
yarn.lock

```
* Update cozy-sharing from 8.3.0 to 9.1.0
```

feat: Update cozy-sharing from 8.3.0 to 9.1.0

---

src/components/Error/Empty.jsx
src/drive/locales/en.json
src/drive/web/modules/drive/Toolbar/components/UploadItem.jsx
src/drive/web/modules/navigation/duck/actions.jsx
src/drive/web/modules/upload/Dropzone.jsx
src/drive/web/modules/upload/UploadButton.jsx
src/drive/web/modules/upload/__snapshots__/Dropzone.spec.jsx.snap
src/photos/components/PhotoBoard.jsx
src/photos/ducks/albums/components/AlbumPhotos.jsx
src/photos/ducks/albums/components/AlbumsList.jsx
src/photos/ducks/albums/index.spec.js
src/photos/locales/en.json
src/photos/targets/public/App.jsx
src/photos/targets/public/__snapshots__/App.spec.jsx.snap

```
* Improve text by distinguishing type in upload messages
* Improve wording for empty state in photos
```

Fix: improve wording

---

src/photos/locales/en.json

Merged back from 1.58.0 release

fix(backup): Backup buttons wording

---

package.json
src/drive/web/modules/navigation/duck/actions.jsx
yarn.lock

```
* Add missing type into upload alert
* feat: Update cozy-sharing from 9.0.1 to 9.0.2
```

fix: Add missing type into upload alert

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/drive/targets/mobile/package.json
src/photos/targets/manifest.webapp

```
* Bump version to 1.60.0
```

feat: Bump version to 1.60.0

---

src/drive/web/modules/trash/components/DestroyConfirm.jsx
src/drive/web/modules/trash/components/EmptyTrashConfirm.jsx

```
* Set the button as busy after the user clicked on it to empty / delete perm the trash
```

feat: Set busy button after emptying a folder / trash

---

.bundlemonrc
src/drive/locales/en.json
src/drive/web/modules/views/OnlyOffice/components/FileDivergedModal.jsx

```
* Add version for view mode in file diverged modal
```

fix: Wording and view mode on file diverged modal

---

.travis.yml

```
* Update Travis configuration to track release tags
```

chore: Update Travis configuration to track release tags

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/drive/targets/mobile/package.json
src/photos/targets/manifest.webapp

```
* Bump version to 1.64.0
```

feat: Bump version to 1.64.0

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/drive/targets/mobile/package.json

```
* Bump version to 1.65.0
```

feat: Bump version to 1.65.0

---

src/drive/components/TrashedBanner.jsx
src/drive/lib/DriveProvider.jsx
src/drive/locales/en.json
src/drive/web/modules/actions/index.jsx
src/drive/web/modules/trash/components/DestroyConfirm.jsx
src/drive/web/modules/upload/__snapshots__/Dropzone.spec.jsx.snap
src/drive/web/modules/views/OnlyOffice/Editor.spec.jsx
src/drive/web/modules/views/OnlyOffice/OnlyOfficeProvider.jsx
src/drive/web/modules/views/OnlyOffice/Title.jsx
src/drive/web/modules/views/OnlyOffice/View.jsx
test/components/AppLike.jsx

```
* Add a banner to warn users that the file they are accessing is in the trash
```
**Remaining work:**
- ~~Add unit test~~
- ~~Test every edge case for shared file~~

feat: Add TrashedBanner

---

.gitignore
.travis.yml
.tx/config
src/drive/locales/ar.json
src/drive/locales/de.json
src/drive/locales/es.json
src/drive/locales/fr.json
src/drive/locales/it.json
src/drive/locales/ja.json
src/drive/locales/ko.json
src/drive/locales/nl.json
src/drive/locales/nl_NL.json
src/drive/locales/pl.json
src/drive/locales/ru.json
src/drive/locales/zh_CN.json
src/drive/locales/zh_TW.json
transifex.yml

```
* Use Transifex integration
```

chore: Use Transifex integration

---

src/drive/locales/en.json
src/drive/locales/fr.json
src/drive/web/modules/move/MoveInsideSharedFolderModal.jsx
src/drive/web/modules/move/MoveModal.jsx
src/drive/web/modules/move/MoveModal.spec.jsx

```
* Warn user when he moves files into shared folder
```

feat: Warn user when he moves files into shared folder

---

package.json
src/drive/targets/manifest.webapp
src/drive/targets/mobile/config.xml
src/drive/targets/mobile/package.json

```
* Bump version to 1.66.0
```

feat: Bump version to 1.66.0

---

.bundlemonrc
package.json
src/drive/web/modules/navigation/AppRoute.jsx
src/drive/web/modules/queries.js
src/drive/web/modules/views/Drive/HarvestBanner.jsx
src/drive/web/modules/views/Drive/HarvestRoutes.jsx
yarn.lock

[VO-14] Fix/harvest banner

---

src/drive/locales/en.json
src/drive/locales/fr.json
src/drive/web/modules/filelist/AddFolder.jsx
src/drive/web/modules/filelist/AddFolderRow.jsx
src/drive/web/modules/move/MoveModal.jsx
src/drive/web/modules/move/MoveModal.spec.jsx
src/drive/web/modules/move/MoveModalContent.jsx
src/drive/web/modules/move/Topbar.jsx
src/drive/web/modules/move/helpers.js

```
* Allow the user to create folder inside move modal
```
**Remaining work :**
- ~~Add a test to check whether the input folder display~~

[VO-10] feat: Allow the user to create folder inside move modal

---

package.json
src/modules/public/LightFileViewer.jsx
src/targets/public/components/AppRouter.jsx
yarn.lock

See https://github.com/cozy/cozy-ui/pull/2563
```
* Remove konnector block in the public Viewer view
```

feat: Add isPublic prop to the public Viewer

---

src/components/FilesRealTimeQueries.jsx

The cozy-client function fetchQueryAndGetFromState should get definition as an object instead of a function. This PR fixes a regression introduce since https://github.com/cozy/cozy-drive/pull/3071

[VO-372] fix(FilesRealTimeQueries): Cannot init query with no doctype

---

src/modules/views/Sharings/SharingsFolderView.jsx

* Allow users to drag & drop files into the sharings view inside a directory

feat: Add dropzone into SharingsFolderView (VO-323)

---

src/constants/config.js
src/locales/en.json
src/locales/fr.json
src/modules/navigation/duck/actions.jsx
src/modules/upload/index.js
src/modules/upload/index.spec.js

* Display an alert window when the user tries to upload a file that is larger than the max allowed size by the server

feat: Handle file that are too large (VO-417) (VO-445)

---

package.json
yarn.lock

* Fix a bug where you could share a sub directory of a shared directory

feat: Update cozy-sharing to 10.4.1 (VO-301)

---

src/constants/config.js
src/locales/en.json
src/locales/fr.json
src/modules/navigation/duck/actions.jsx
src/modules/upload/index.js
src/modules/upload/index.spec.js

* Display an alert window when the user tries to upload a file that is larger than the max allowed size by the server

Feat  handle file that are too large

---

package.json
src/modules/drive/Toolbar/share/ShareItem.jsx
yarn.lock

```
* Update cozy-sharing from 10.4.1 to 11.0.0
```

feat: Update cozy-sharing from 10.4.1 to 11.0.0

---

src/targets/browser/index.jsx
src/targets/public/index.jsx

```
* Public version crashes in development version due to missing theme
```

fix: Public version crashes in development version due to missing theme

---

package.json
yarn.lock

```
*  Update cozy-bar from 12.0.0 to 12.2.0
```

feat: Update cozy-bar from 12.0.0 to 12.2.0

---

package.json
src/modules/drive/Toolbar/components/MoreMenu.jsx
src/modules/filelist/AddFolderRow.jsx
src/modules/filelist/File.jsx
src/modules/filelist/FileList.jsx
src/modules/filelist/FileListBody.jsx
src/modules/filelist/FileListHeader.jsx
src/modules/filelist/FilePlaceholder.jsx
src/modules/filelist/HeaderCell.jsx
src/modules/filelist/LoadMore.jsx
src/modules/filelist/LoadMoreV2.jsx
src/modules/filelist/MobileFileListHeader.jsx
src/modules/filelist/cells/CarbonCopy.jsx
src/modules/filelist/cells/ElectronicSafe.jsx
src/modules/filelist/cells/Empty.jsx
src/modules/filelist/cells/FileAction.jsx
src/modules/filelist/cells/FileName.jsx
src/modules/filelist/cells/LastUpdate.jsx
src/modules/filelist/cells/SelectBox.jsx
src/modules/filelist/cells/SharingShortcutBadge.jsx
src/modules/filelist/cells/Size.jsx
src/modules/filelist/cells/Status.jsx
src/modules/filelist/headers/CarbonCopy.jsx
src/modules/filelist/headers/ElectronicSafe.jsx
src/modules/move/Explorer.jsx
src/modules/navigation/Breadcrumb/components/MobileBreadcrumb/MobileBreadcrumb.jsx
src/modules/public/PublicToolbarCozyToCozy.jsx
src/modules/search/AppBarSearch.jsx
yarn.lock

```
* Update cozy-ui from 104.3.0 to 105.2.0
```

feat: Update cozy-ui from 104.3.0 to 105.2.0

---

package.json
yarn.lock

```
* Update cozy-bar from 12.2.0 to 12.2.1
```

feat: Update cozy-bar from 12.2.0 to 12.2.1

---

package.json
yarn.lock

```
* Update cozy-sharing from 12.3.0 to 13.0.0
```

[VO-592] feat: Update cozy-sharing from 12.3.0 to 13.0.0

---

package.json
yarn.lock

* This will fix a cozy bar typo in settings menu

feat: update cozy bar to 12.2.2 (VO-386)

---

src/modules/views/Folder/ExtraDrive.tsx
src/modules/views/Folder/FolderTabs.tsx
src/modules/views/Folder/types.ts

Following refactors there were mismatches in data query
and UI; These were discovered on dev env before staging

fix: Update UI and data for navlimiter (VO-529

---

src/constants/config.js
src/modules/queries.js
src/modules/search/components/helpers.js

This dir will be hidden from view in the following:
* search
* drive view
* move view
* upload view (uses move query)
Using db filter when possible
Javascript if not

feat: Hide shared drives dir from view (VO-647)

---

package.json
yarn.lock

```
* Update cozy-sharing from 13.1.0 to 13.1.2
```

feat: Update cozy-sharing from 13.1.0 to 13.1.2

---

package.json
yarn.lock

```
* Update cozy-sharing from 13.1.2 to 13.2.0
```

feat: Update cozy-sharing from 13.1.2 to 13.2.0

---

src/declarations.d.ts
src/modules/filelist/File.jsx
src/modules/filelist/FileThumbnail.jsx
src/modules/filelist/cells/FileName.jsx
src/modules/navigation/NavContent.jsx
src/modules/navigation/NavItem.jsx
src/modules/navigation/NavLink.jsx
src/modules/views/Folder/SharedDrives.tsx
src/modules/views/Folder/types.ts

- Hide url extension in mobile
- Correctly display external icon

fix: check class instead of type for ext drive (VO-529) (VO-621)

---

.gitignore
src/locales/en.json
src/locales/fr.json
src/modules/move/MoveModal.jsx

remove old api use new api
add new button to go to folder

feat: update move success alert (VO-284)

---

package.json
yarn.lock

```
*  Update cozy-sharing from 13.2.0 to 13.3.0
```

[VO-691] feat: Update cozy-sharing from 13.2.0 to 13.3.0

---

src/components/Bar.jsx
src/modules/public/PublicToolbarByLink.jsx

```
* Display filename on public view (shared by link)
```
Example:

feat(Public): Should display filename on public view when shared by link

---

src/components/Button/MoreButton.jsx
src/components/pushClient/Banner.jsx
src/components/pushClient/SupportUs.jsx
src/components/pushClient/supportUs.styl
src/modules/actions/index.jsx
src/modules/confirm/Message.jsx
src/modules/drive/DeleteConfirm.jsx
src/modules/drive/Toolbar/share/ShareButton.jsx
src/modules/drive/Toolbar/share/styles.styl
src/modules/filelist/FileIconShortcut.jsx
src/modules/filelist/cells/FileAction.jsx
src/modules/filelist/fileopener.styl
src/modules/navigation/Breadcrumb/breadcrumb.styl
src/modules/nextcloud/components/actions/trash.jsx
src/modules/search/components/styles.styl
src/modules/trash/Toolbar.jsx
src/modules/upload/DropzoneTeaser.jsx
src/modules/viewer/CallToAction.jsx
src/modules/viewer/FilesViewer.jsx
src/modules/viewer/styles.styl
src/styles/actionmenu.styl
src/styles/dropzone.styl
src/styles/filelist.styl
src/styles/filenameinput.styl

```
* Adjust colors to be more dark mode compliant
```

Adjust colors to be more dark mode compliant

---

src/modules/nextcloud/components/actions/downloadNextcloudFile.jsx

```
* Show download action disabled on folder
```

[VO-821] fix(nextcloud): Show download action disabled on folder

---

package.json
src/modules/search/__snapshots__/AppBarSearch.spec.jsx.snap
src/modules/upload/__snapshots__/Dropzone.spec.jsx.snap
src/modules/views/Folder/FolderView.jsx
yarn.lock

To better support dark mode (flagship app and dark mode button in cozy-settings).
```
*
*
* Update cozy-ui to 110.1.0 (better dark mode support)
```

feat: Update cozy-ui to 110.1.0

---

src/modules/search/components/styles.styl
src/modules/views/Search/SearchView.jsx

```
* Color in search result wasn't good
* Search page on mobile is now full height
```

Fix color and height on search

---

docs/nextcloud.md
package.json
src/declarations.d.ts
src/modules/nextcloud/components/actions/restoreNextcloudFile.tsx
yarn.lock

- https://github.com/cozy/cozy-client/pull/1503

[VO-924] fix: Reset the query to update the view even if it doesn't exist

---

src/modules/move/components/MoveModalSuccessAction.tsx

```
* Adapt color of buttons inside showAlert
```

[VO-935] fix: Adapt color of buttons inside showAlert

---

src/modules/drive/Toolbar/components/AddButton.jsx
src/modules/drive/Toolbar/index.jsx
src/modules/drive/Toolbar/share/ShareButton.jsx
src/modules/public/DownloadButton.jsx
src/modules/public/PublicToolbarByLink.jsx

```
* Add space between button inside toolbar
```

[VO-927] fix: Add space between button inside toolbar

---

package.json
src/components/App/App.jsx
src/lib/DriveProvider.jsx
src/modules/upload/__snapshots__/Dropzone.spec.jsx.snap
src/targets/public/index.jsx
yarn.lock

```
* Ignore user settings to chose theme in public context
* Update cozy-ui from 111.1.1 to 111.2.0
```
**Related PRs :**
- https://github.com/cozy/cozy-bar/pull/848

[VO-1001] fix: Ignore user settings to chose theme in public context

---

package.json
src/modules/navigation/AppRoute.jsx
src/modules/views/Drive/KonnectorRoutes.jsx
yarn.lock

```
* Update cozy-harvest-lib from 30.6.4 to 31.0.0
```
- https://github.com/cozy/cozy-libs/pull/2627

[VO-1184] feat: Update cozy-harvest-lib from 30.6.4 to 31.0.0

---

package.json
yarn.lock

To change the text style in the banner.

feat: Upgrade Cozy-Sharing to 16.9.0

---

package.json
yarn.lock

See https://github.com/cozy/cozy-libs/releases/tag/cozy-dataproxy-lib%402.1.0

feat: Improve search by upgrading cozy-dataproxy-lib

---

package.json
yarn.lock

To display message when not enough char in search query.

feat: Bump dataproxy

---

package.json
src/declarations.d.ts
src/lib/DriveProvider.jsx
src/modules/views/Drive/DriveFolderView.jsx
src/modules/views/Favorites/FavoritesView.tsx
src/modules/views/Recent/index.jsx
src/modules/views/Sharings/index.jsx
test/components/AppLike.jsx
yarn.lock

```
* Add action to share on mobile device
*
*
```

Add action to share on mobile device

---

src/lib/doctypes.js
src/modules/filelist/icons/BadgeKonnector.jsx
src/modules/filelist/icons/FileThumbnail.tsx
src/queries/index.ts

feat: Add a Badge to the first konnector folder

---

package.json
src/components/PushBanner/QuotaBanner.jsx
src/components/pushClient/Banner.jsx
src/components/pushClient/pushClient.styl
src/modules/layout/Layout.jsx
src/modules/layout/Main.jsx
src/modules/upload/Dropzone.jsx
src/modules/upload/index.js
src/modules/views/Drive/DriveFolderView.jsx
src/modules/views/Drive/DriveFolderView.spec.jsx
src/modules/views/Public/PublicFolderView.jsx
src/modules/views/Recent/index.jsx
src/modules/views/Sharings/index.jsx
src/modules/views/Trash/TrashFolderView.jsx
src/styles/dropzone.styl
src/styles/main.styl
yarn.lock

Here, we add the Layout Content component to different views to create a more classic layout construction. We adjust some margin to feat this way.

Make layout adjustment

---

src/hooks/helpers.js
src/modules/drive/AddMenu/AddMenu.jsx
src/modules/drive/AddMenu/AddMenuContent.jsx
src/modules/drive/AddMenu/AddMenuContent.spec.jsx
src/modules/drive/Toolbar/components/AddFolderItem.jsx
src/modules/drive/Toolbar/components/CreateNoteItem.jsx
src/modules/drive/Toolbar/components/CreateOnlyOfficeItem.jsx
src/modules/drive/Toolbar/components/CreateShortcut.jsx
src/modules/drive/Toolbar/components/ShortcutCreationModal.jsx

We want to be able to create folder and file from anywhere
If we are in sharing/recent/trash, it will create file/folder in root folder

Create folder and file from trash/recent/sharings

---

package.json
yarn.lock

See https://github.com/cozy/cozy-libs/pull/2731

fix: Realtime disconnection on refresh token

---

src/modules/filelist/cells/CertificationsIcons.jsx

according to the fixed issue on cozy-ui

feat(CertificationsIcons): Remove useless fetch

---

src/hooks/useOnLongPress.js
src/modules/filelist/FileOpener.jsx

correct way compared to https://github.com/cozy/cozy-drive/pull/3403

fix: Clicking in renamed field doesn't open the file anymore

---

package.json
yarn.lock

See
https://github.com/cozy/cozy-libs/compare/cozy-search%400.8.0...cozy-search%400.8.3

fix: Get latest fixes on AI assistant

---

src/modules/filelist/AddFolder.jsx
src/modules/filelist/AddFolderCard.jsx
src/modules/views/Folder/FolderViewBody.jsx

https://github.com/user-attachments/assets/11555a50-0610-4887-bfe8-2ae04dd0306b
https://github.com/user-attachments/assets/80aca3e6-ad1a-4513-8dc6-1505977f7867

✨ feat: add create new folder UI in grid view

---

package.json
src/modules/filelist/virtualized/GridFile.jsx
src/modules/views/Folder/virtualized/FolderViewBody.jsx
src/modules/views/Folder/virtualized/Grid.jsx
src/modules/views/Folder/virtualized/GridWrapper.jsx
src/styles/filelist.styl
yarn.lock

requires: https://github.com/cozy/cozy-ui/pull/2822

feat: implement virtualized grid view :sparkles:

---

package.json
src/modules/views/Folder/virtualized/Table.jsx
yarn.lock

Change the order of params in `handleRowSelect` to adapt the new version of `cozy-ui`
[cozy/cozy-ui#2844](https://github.com/cozy/cozy-ui/pull/2844)

fix: Change order of params in select row function :bug:

---

package.json
src/modules/navigation/AppRoute.jsx
src/modules/navigation/PublicNoteRedirect.tsx
src/modules/navigation/hooks/helpers.spec.js
src/modules/navigation/hooks/helpers.ts
yarn.lock

Open shared drive note

---

src/modules/navigation/AppRoute.jsx
src/modules/views/Sharings/index.jsx

Now redirect to the list of sharings in the "Shared drives" tab

fix: Redirects to shared drives list

---

package.json
yarn.lock

[cozy/cozy-sharing#2817](https://github.com/cozy/cozy-libs/pull/2817)

chore: Upgrade cozy-sharing to 26.1.1 :arrow_up:

---

src/modules/drive/RenameInput.jsx
src/modules/drive/RenameInput.spec.jsx
src/modules/shareddrives/components/SharedDriveFolderBody.jsx

Implement renaming files or folders in recipient's shared drives.

feat: Implement renaming files or folders in shared drive :sparkles:

---

src/modules/drive/Toolbar/components/CreateOnlyOfficeItem.jsx
src/modules/navigation/AppRoute.jsx
src/modules/views/OnlyOffice/Create.jsx
src/modules/views/OnlyOffice/useCreateFile.jsx

Update to create OnlyOffice from shared drive.
[cozy/cozy-client#1631](https://github.com/cozy/cozy-client/pull/1631)
https://github.com/user-attachments/assets/f0c3a2f2-8812-49c3-848b-8728eb597126

feat: Implement creating onlyoffice in shared drive :sparkles:

---

src/modules/folder/components/FolderBody.jsx

Fix layout of grid view when creating a new folder in shared drive.
https://github.com/user-attachments/assets/0c8c32d3-3a85-4d14-a726-0708208d2399

fix: Layout when creating folder in grid view of share drive is incorrect :bug:

---

src/modules/selection/SelectionProvider.jsx

follows https://github.com/cozy/cozy-drive/pull/3514

fix(SelectionProvider): Now relies on file._id instead of file.id

---

.github/workflows/create-bump-pr.yml

Example in a test repository. I propose to test this in real usage in the next week to see if it is interesting and if we should automate more.
https://github.com/user-attachments/assets/c52d777a-3253-4d32-a926-80822a1e06f2

chore: Add GH Actions to create a bump PR

---

src/modules/folder/components/FolderBody.jsx

Add right click on shared drive item in recipient.

feat: Add right click on shared drive item in recipient :sparkles:
